### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by michaelbunney** [MicrosoftDocs/OfficeDocs-O365ITPro#101]
Nothing in step 4 of the procedure "Add a TXT record for verification" corresponds to the navigation and labels I'm seeing in Google Domains.  I eventually found the right place, but perhaps this article needs to be reviewed against the current Google Domains U.I. for changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab521261-ae0d-9fe5-eff2-14ae0a5e3f68
* Version Independent ID: 59147889-4b01-f27e-599b-970595a7fe85
* Content: [Create DNS records at Google Domains for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-google-domains?redirectSourcePath=%252fArticle%252f0db29490-2612-48bc-9b77-1862e7a41a8c&view=o365-worldwide#BKMK_verify)
* Content Source: [Office365-Admin/dns/create-dns-records-at-google-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-google-domains.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndreaBarr** [comment]
@lindspea Could you please investigate this issue?

**Comment by lindspea** [comment]
@michaelbunney Thank you for your valuable contribution in pointing this out and making the docs better. Much appreciated.

**Comment by lindspea** [comment]
@michaelbunney thank you for your valuable contribution in improving MS docs.  We will work together to resolve this issue soonest.

**Comment by lindspea** [comment]
Hi @michaelbunney.  I have done some research on the issue.  Do you think these instructions would make it clearer:    
1. On the Website, domain & email page, scroll down and click DNS, then click Web DNS. 
2. Open the instructions for the type of verification record you would like to add to your domain's DNS records. 
3. Add a TXT verification record (most common) Under Personal web DNS settings, from the Type list, select TXT.
Please let me know if this works, and I can have them inserted into the instructions.
Thanks again for helping to improve MS docs.

**Comment by michaelbunney** [comment]
Hi, @lindspea.  Unfortunately your proposed revision still doesn't correspond to anything I’m seeing in the U.I. of Google Domains.  When I sign in to Google Domains as directed in step 3, I do not see a “Website, domain & email” page.

In order for this procedure to correspond to what I see in Google Domains, you would need to replace step 4 with these steps:


4. On the **My domains** page, find the domain you want to use with Office 365, and click the **MANAGE** link next to it.

5. In the left navigation, click **DNS**.


By the way, another suggestion.  In step 1 of this procedure (“To get started, go to your domains page at Google Domains by using this link”), clicking the hyperlink causes Google Domains to load in the current window, replacing the procedure.  I would suggest configuring this link to open in a new window, so the user can continue following the directions in the first window.

**Comment by lindspea** [comment]
Hi @michaelbunney.  Thank you for your helpful suggestions in improving MS docs.  I will revise the instructions to resolve this issue.

**Comment by lindspea** [comment]
Hi @michaelbunney.  Thanks again for your valuable contribution.  I have fixed the steps and they are under review, however opening a new tab for the link is unfortunately not possible.

**Comment by lindspea** [comment]
@AndreaBarr @mypil this can be closed.
