### ISSUE TITLE
Unclear steps on how to become an admin

### ISSUE THREAD

**Issue by FlorentinStafie** [MicrosoftDocs/OfficeDocs-O365ITPro#102]
Step 3 is too vague. It is unclear what steps I need to follow to get to the "Become the admin" if I am a member of the unmanaged tenant. Additionally, when the takeover process is started from a managed tenant in the Admin portal Step1 is not useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24eaf551-7e49-ee4a-2979-8515f92d4d2a
* Version Independent ID: 67e53343-d996-ce5e-4742-0c0d819fbca1
* Content: [Do an admin takeover in Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/become-the-admin?redirectSourcePath=%252fen-US%252farticle%252fb9707ec8-2247-4e25-9bad-f11ddbc686e4&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/become-the-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/become-the-admin.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndreaBarr** [comment]
@lindspea Could you please investigate this one?

**Comment by lindspea** [comment]
Will do.
[image: Picture]

**Comment by lindspea** [comment]
Hi @FlorentinStafie. Thank you for valuable contribution in pointing this out.  We will work together to resolve this soonest.

**Comment by albso** [comment]
I'm trying to follow the steps here but when I clicked the link in the email, and when the portal opens up, it says that I don't have permission to access. And I did not receive any "Become the admin..." wizard window. Any option on how to take ownership of the domain?

**Comment by lindspea** [comment]
@dariomws306 Could you perhaps help answer this question?

**Comment by dariomws306** [comment]
Hi @albso , are you trying with a Global Admin account?
