### ISSUE TITLE
#3 Needs Fixed - Same issue as others

### ISSUE THREAD

**Issue by jkerie** [MicrosoftDocs/OfficeDocs-O365ITPro#108]
There must be other reasons why the option to convert the mailbox doesn't appear. As another poster, I am a Global Admin, and it didn't show. However, I could do as the other poster stated and do it in the Exchange mailboxes section. Either fix the problem so that it shows for global admins, or point out where else it can be done, because if it weren't for the prior poster's comments I would have had no idea how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@lindspea Could you please investigate this?

**Comment by lindspea** [comment]
Will do.
[image: Picture]

**Comment by lindspea** [comment]
@jkerie Thank you for info.  Will look into it.

**Comment by lindspea** [comment]
@AndreaBarr @mypil this issue can be closed.
