### ISSUE TITLE
Step numbers changed for the creation portion?

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-O365ITPro#109]
Step 6 says if you get an error like the image below, no need to do step 6, to skip to step 7.  Guessing they should be incremented by 1 now (no need for step 7, skip to 8)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@kellipav Could you please investigate this?

**Comment by kellipav** [comment]
Yes!

**Comment by mypil** [comment]
@J-Fedor - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
