### ISSUE TITLE
How to revoke the access?

### ISSUE THREAD

**Issue by ThePangy** [MicrosoftDocs/OfficeDocs-O365ITPro#115]
This is great info on gaining access to a user's OneDrive for whatever the reason may be. However, supposing this is an existing user still, how do I now revoke the access that I gave myself as an admin? I am still able to see her files after our investigation was completed and I no longer want/need access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by AndreaBarr** [comment]
@sonika24 Could you please investigate this issue?

**Comment by mypil** [comment]
@ThePangy  - thank you for engaging with the community here for the docs. 

Can you please share what specific issue you have with this article? 
I would really appreciate if you are able to help me by providing more details as to what should be edited and/or included.

**Comment by ThePangy** [comment]
There was no information listed on how to revoke the access you give
yourself. By following the steps you outlined, you are permanently giving
yourself access to the user's OneDrive. This can be done for a user no
longer with the company or for a user who is still working at the company.
If the user still works at the company it would be a bad security practice
to give yourself permanent access to their OneDrive files. I mentioned in
my subsequent comment how to revoke your access to the user's OneDrive
files by removing yourself as a Site Collection Admin on their OneDrive
"my" site. These steps to revoke access should be included in the article.

Thanks!

**Comment by mypil** [comment]
@ThePangy - Thank you for pointing this out.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by theonlyrick** [comment]
@ThePangy - I had exactly the same thought.  Can you help me out with the right page that will remove my perms from a user's OneDrive?  Thanks,  R.

**Comment by theonlyrick** [comment]
@ThePangy - Got it, it's work-out-able from here: https://sharepointmaven.com/how-to-access-someone-elses-onedrive-account/

**Comment by ThePangy** [comment]
@theonlyrick - Yep, that link should definitely help figure it out. The TL/DR version is go to the URL for the user's OneDrive with /_layouts/15/settings.aspx at the end. Click Site Collection Administrators and remove the name of the user who no longer needs access.

(e.g. https://tenantname-my.sharepoint.com/personal/username_tenantname_com/_layouts/15/settings.aspx)
