### ISSUE TITLE
cannot edit the content pack report

### ISSUE THREAD

**Issue by PallaviPandey30** [MicrosoftDocs/OfficeDocs-O365ITPro#116]
We Cannot edit the content pack report. We will need a pbit file if we need any customizations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@PallaviPandey30 The article does mention the pbit file in the FAQ section. This is a generic overview. Is there a specific part of the article you would suggest us edit or add in?

**Comment by mypil** [comment]
@PallaviPandey30 - we would like to follow up and get more information from you. Is there a specific part of the article you would suggest us edit or add in?

**Comment by mypil** [comment]
@PallaviPandey30 - We appreciate any feedback you can provide to make the content in the Microsoft docs better. Since we did not get any response from you, we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
