### ISSUE TITLE
Manage MFA user settings - ambiquous location of step 2

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-O365ITPro#117]
There isn't a clear indication of where one can find the MFA settings in this section. There needs to be an assumption that users are coming here after already setting it up months ago, and telling them to go to a page which isn't clearly marked isn't very useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by gandoge** [comment]
Please fix this. I have no way of getting to the manage MFA portal in this new UI.

**Comment by StuBeck32** [comment]
Under Manage MFA Features, step 2 has "On the multi-factor authentication page, select the check box next to the people you want to manage." What is the multi-factor authentication page and how do you get to it?

**Comment by tseward** [comment]
@StuBeck32 can you explain exactly what isn't clear? The page has a link to your Active users in the O365 Admin Center and a pictorial about how to set a user up with MFA.

**Comment by StuBeck32** [comment]
Can you please explain what part of my comment you’re misunderstanding? I copied the step and the part that I’m not understanding, so I’m not sure how to be more clear.

**Comment by Sirkkuw** [comment]
@StuBeck32 - in the preview mode it is difficult to find - the topic has been updated. Does it seem more clear now?

**Comment by StuBeck32** [comment]
Yes, this is much more clear @Sirkkuw . I'm still confused as to what @tseward needed more details on.
