### ISSUE TITLE
Categories Attribute

### ISSUE THREAD

**Issue by CaitlinKnox** [MicrosoftDocs/OfficeDocs-O365ITPro#118]
I'm really interested in seeing the count by Category. I know there's VBA code that exists, but I'd like to leverage existing reports that are connected to this model in my organization. Does anyone know if this will ever be an available attribute available as a column selection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c35522-704a-a490-97a1-8389c0c6261c
* Version Independent ID: 1ed63bad-90bc-7716-3c2a-f9389946aa97
* Content: [Office 365 Reports in the Admin Center - Mailbox usage](https://docs.microsoft.com/en-us/office365/admin/activity-reports/mailbox-usage?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/mailbox-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@CaitlinKnox  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the Office 365 better. They keep a close tab on User Voice https://office365.uservoice.com/ and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!
