### ISSUE TITLE
StaffHub teams still allowed after implementing this solution

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/OfficeDocs-O365ITPro#119]
"StaffHub: Both admins and managers won't be able to create teams."
After restricting group creation, people can still create StaffHub teams. However, those created Teams do not create O365 Groups. Is this expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@ferrety2006 Thank you for this feedback

I want to make sure your issue gets the appropriate attention. I want to get you to Support who has more resources available to find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by ferrety2006** [comment]
I've submitted a ticket - thank you! I'll come back with an outcome.

**Comment by ferrety2006** [comment]
Ticket confirmed that we have an inconsistent experience to what is documented here. Documentation should include the information that StaffHub team creation from a Groups only perspective is impacted by this method. Staffhub Teams, independent of groups, can still be created by anyone at this time.

**Comment by tseward** [comment]
Like SharePoint, it is possible to create non-groupified sites. This article only covers Group-based restrictions.
