### ISSUE TITLE
Connecting new Yammer Group to O365 Group

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#12]
Can a new yammer group be connected to an existing O365 Group so that another SPO Site is not created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7a47d0-7e67-1890-8a1e-192871c99b55
* Version Independent ID: ff75ce98-2235-8c92-b6a2-9b034061adef
* Content: [Yammer and Office 365 Groups](https://docs.microsoft.com/en-us/yammer/manage-yammer-groups/yammer-and-office-365-groups?redirectSourcePath=%252fen-us%252farticle%252fyammer-and-office-365-groups-d8c239dc-a48b-47ab-b85e-6b4b8191a869)
* Content Source: [yammer/manage-yammer-groups/yammer-and-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-groups/yammer-and-office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by IrenePasternack** [comment]
No, this is not possible. If this is a feature that is important to you, please let the Yammer team know by adding it at [ https://yammer.uservoice.com/]( https://yammer.uservoice.com/).

**Comment by SolespireMarcus** [comment]
I definitely am not happy that additional SharePoint Sites are being created. I rather have previously created SharePoint Sites via Office 365 Groups be attached to a Yammer Group, the same way everything else is tied together in OWA and the greater working environment of Office 365.
