### ISSUE TITLE
Remove a user from an external network (done by user)

### ISSUE THREAD

**Issue by fkaleck** [MicrosoftDocs/OfficeDocs-O365ITPro#123]
There is no "Delete Account" in Settings-&gt;Networks. instead the link is named "Leave Network". Should be updated because it is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be3cea98-2b32-6f9f-8a22-4bc82613b6ac
* Version Independent ID: 9bcbd2d7-c954-1ddb-95eb-472c68f6e637
* Content: [Manage GDPR data subject requests in Yammer Enterprise](https://docs.microsoft.com/en-us/yammer/manage-security-and-compliance/gdpr-requests-in-yammer-enterprise)
* Content Source: [yammer/manage-security-and-compliance/gdpr-requests-in-yammer-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-security-and-compliance/gdpr-requests-in-yammer-enterprise.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by IrenePasternack** [comment]
Frank,

Thank you. I removed this whole section based on your other comment.

Irene

**Comment by AndreaBarr** [comment]
@fkaleck It looks like Irene has resolved this issue. I am closing this as this time. If this issue is not resolved pleaser re-open this issue.
