### ISSUE TITLE
Remove a user from an external network (done by user)

### ISSUE THREAD

**Issue by fkaleck** [MicrosoftDocs/OfficeDocs-O365ITPro#124]
The content is misleading that a user can "remove" himself from the External Network. Even the user is unable to logon to the External Network after selecting "Leave Network" the user identity is still there (Visible to the Network Administrator and others (eMail address, photo, first name, last name). 

The term "remove" is used in the same article describing a hard deletion of a user's identity. Quote: "After a user's account transitions from deactivated to removed, you can no longer associate user data with the user, which means you can no longer export and review their data."  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be3cea98-2b32-6f9f-8a22-4bc82613b6ac
* Version Independent ID: 9bcbd2d7-c954-1ddb-95eb-472c68f6e637
* Content: [Manage GDPR data subject requests in Yammer Enterprise](https://docs.microsoft.com/en-us/yammer/manage-security-and-compliance/gdpr-requests-in-yammer-enterprise)
* Content Source: [yammer/manage-security-and-compliance/gdpr-requests-in-yammer-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-security-and-compliance/gdpr-requests-in-yammer-enterprise.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by IrenePasternack** [comment]
Frank,

Thank you for the feedback. I removed the section on users removing themselves from external network, as you’re right, it does not erase the user’s personal data.

Irene

**Comment by AndreaBarr** [comment]
@fkaleck It looks like Irene has resolved this issue. I am going to close this at this time. If this is not resolved please re-open this issue.
