### ISSUE TITLE
Group Alias not removed

### ISSUE THREAD

**Issue by sravenscroft** [MicrosoftDocs/OfficeDocs-O365ITPro#125]
I ran the command to remove the alias, and received no error.

When I run Get-UnifiedGroup -Identity "Group Name" it still shows the alias.

When I run the command to remove the alias again, it returns "WARNING: The command completed successfully, but no settings of 'Group Name' have been modified."  I, therefore, assume that the alias was removed, but I am still unable to add it to another exchange mailbox.

How long does it take for the settings to propagate to the rest of Office 365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8792555-ecc1-9c9e-1d7a-e0b3b1b0b2b7
* Version Independent ID: 442f4470-d54b-b4c0-f0f1-9f35b7017dc1
* Content: [Troubleshoot Remove an alias from a group](https://docs.microsoft.com/en-za/office365/admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group?redirectSourcePath=%252fen-ie%252farticle%252ftroubleshoot-remove-an-alias-from-a-group-d96989c4-6efc-4523-9c89-44ce06e601bf&view=o365-worldwide)
* Content Source: [Office365-Admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group.md)
* Service: **o365-administration**
* GitHub Login: @anfowler
* Microsoft Alias: **anfowler**

**Comment by sravenscroft** [comment]
It seems that the correct command to use is:

Set-UnifiedGroup -Identity "Group name" -EmailAddresses @{remove="alias@contoso.com"}

**Comment by lindspea** [comment]
@sravenscroft Thank you for reaching out and helping improve MS Docs.  Please confirm if you have found the solution to your issue in the above comment and I will have the necessary changes made to the document.

**Comment by lindspea** [comment]
@AndreaBarr @mypil This can be closed thank you.
