### ISSUE TITLE
Availability in BELIZE

### ISSUE THREAD

**Issue by maragon-belize** [MicrosoftDocs/OfficeDocs-O365ITPro#126]
when will the O365 integration be available in Belize ?

**Comment by kenwith** [comment]
@maragon-belize - can you provide more information and we can work on seeing if there is already content related to this or if this is an area that needs new content. We did find this page that shows Belize already has availability for Office 365: https://products.office.com/en-us/business/international-availability

Is there something specific that is not available yet that you were looking for?

**Comment by maragon-belize** [comment]
Hello , yes office 365 is provided in Belize, what I am referring to is the new app Kaizala. It has not appeared on my admin page for me to administer the users.

Regards,
Maragon

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kenwith** [comment]
@maragon-belize - OK I got you now. I see on this page: https://products.office.com/en/business/microsoft-kaizala it shows where it is available but it does not show Belize.

Let me loop in @chuckedmonson who has written content for Kaizala and see if he knows if there is a release schedule available for other countries on a roadmap. It might be information that is not yet available yet but we can track it down if it is and put in the request for it if it isn't.

**Comment by kenwith** [comment]
@maragon-belize - I have an email out to @chuckedmonson to check if there is a roadmap. @nenonix did find this: https://docs.microsoft.com/en-us/office365/kaizala/regional-availability though Belize is not listed so I am looking to see if there is a published roadmap or not.

**Comment by mypil** [comment]
@kenwith @chuckedmonson - I would like to follow up on this. Do you have any updates? 

Thanks.

**Comment by chuckedmonson** [comment]
For Belize and other organizations currently outside the 28 launched markets, the Account Team can request the business desk team to get Kaizala Provisioned. We are working towards general availability for all markets in near future, without requiring special provision by the Account Team.

**Comment by mvanders** [comment]
Can I then request the Account Team to get Kaizala provisioned for Belgium, so that we can enable the option: 'Data retention for all organization groups' which is now impossible because of the warning: 
'Please make sure your organization has Kaizala Pro, Microsoft Exchange and Microsoft SharePoint licenses'.![2019-03-11 17_44_26-Settings - Kaizala Management Portal - Internet Explorer](https://user-images.githubusercontent.com/758617/54141445-f9fb8580-4425-11e9-8b44-aa80125c8798.png)
