### ISSUE TITLE
Comment on content

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/OfficeDocs-O365ITPro#127]
&lt;&lt;&lt;Users will not be able to modify domains when they create Office 365 groups. Only admins can specify the domain that the group can be created in.&gt;&gt;

I found that admin do not follow email address policy; they will still use the default accepted domain as default unless they change the domain during creation. 
I am not sure it is a product limitation but this should call out clearer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96002890-7e35-a0ab-a849-d94fef254fa8
* Version Independent ID: 2c4105db-b713-4829-393e-de355c5c60d4
* Content: [Choose the domain to use when creating Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/choose-domain-to-create-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/choose-domain-to-create-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/choose-domain-to-create-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by limjianan** [comment]
This is additional things i found.
the email address policy works when GroupCreatedinAdminCenter (admin.microsoft.com)
when it is created from ECP or AAD, it will not follow the email address policy.

**Comment by nenonix** [comment]
@limjianan Thank you for your feedback on the content.  I am going to research this issue and then try to work with you to improve  the text.  While  I do that, can you tell me more about what we would need to add or change to make this clearer?

**Comment by limjianan** [comment]
@nenonix  I have researched it further as well by creating groups in multiple places

GroupCreatedinECP
 GroupCreatedinAdminCenter
 GroupCreatedinAAD
 GroupCreatedinTeams
 GroupCreatedinTeamsPowerShell
 GroupCreatedinUnifiedGroupPowerShell

I found the only one who don't observe the email address policy when you create the group in ECP which is strange. do you want to test and confirm is it the same?

**Comment by joinimran** [comment]
@limjianan Can you please confirm that when you tried to create a group where it doesn't observe the policy was that in normal user mode or admin mode.

**Comment by mypil** [comment]
@limjianan - Thank you for your contribution to make the docs better! Much appreciated!

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@limjianan - Thank you for your contribution to make the docs better! Much appreciated!

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by limjianan** [comment]
sorry, I was away for a few days. The specific use case is 
When an admin person creates an office 365 group in ECP. By default, it will use the onmicrosoft.com 
Although the admin can manually change the email domain. 
If it save as onmicrosoft.com, it will not observe email address policy. 

When ad admin person create an office 365 group in adminportal. By default, admin cannot change the email domain. But email address policy will kick in. 

I repeat this and it happen again.
