### ISSUE TITLE
International

### ISSUE THREAD

**Issue by markburland** [MicrosoftDocs/OfficeDocs-O365ITPro#128]
Worth pointing out this only works for certain domains (cough US only cough).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1019f3-2e3e-8ac9-d18e-a89ffd1f9591
* Version Independent ID: aea85027-3a77-554b-fb0d-5b908edfd035
* Content: [Find your domain registrar for Office 365](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/find-your-domain-registrar?view=o365-worldwide)
* Content Source: [Office365-Admin/get-help-with-domains/find-your-domain-registrar.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/find-your-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by nenonix** [comment]
@markburland  Thank you for contributing feedback to improve the content. I will be working with you to incorporate your suggestion if possible. Can you tell me what aspect in the docs you are referring to specifically?

**Comment by LieslJordaan** [comment]
I totally agree, am a first time user of Domains and live in  South Africa and registered with registerdomain.co.za

**Comment by nenonix** [comment]
@LieslJordaan  Thank you for the feedback. I will try to reflect this in the document

**Comment by tseward** [comment]
@LieslJordaan Can you provide an example domain name that uses that registrar?

**Comment by LieslJordaan** [comment]
Hi there

I am not sure I am understanding you correct. Here is another example of a co.za domain "http://www.joburgsdarling.co.za/" this is the link for a South African registrar "https://www.registerdomain.co.za/" that I used. "https://www.domains.co.za/index.php" is another registrar.

The South African domains that I am aware of are www.name.co.za<http://www.name.co.za> or -.gov.za or -ac.za and many more.

Kind regards,
Liesl Jordaan
________________________________

**Comment by tseward** [comment]
@LieslJordaan thank you. I've updated it with a note that InterNIC only supports COM/NET/EDU TLDs. Unfortunately there is no single database from a non-commercial entity that I'm aware of which supports all forms of TLDs/gTLDs.
