### ISSUE TITLE
Listing of available reports

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#130]
small editorial suggestion, most of the items in the listing of available reports have bullets, but some do not. This should be made consistent.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2900ade-43fe-5f21-fc18-d1db33762787
* Version Independent ID: 574a1284-ace4-68ba-8811-4e305386c7de
* Content: [Activity Reports in the Office 365 admin center](https://docs.microsoft.com/en-au/office365/admin/activity-reports/activity-reports?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/activity-reports.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
Hi @AndreaBarr - This issue can be closed. Thank you.
