### ISSUE TITLE
Typo in the documentation page title.

### ISSUE THREAD

**Issue by YannickRondeau** [MicrosoftDocs/OfficeDocs-O365ITPro#133]
There is a typo in the page title, we should read "Welcome" instead of "Wlecome".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd50ed2-f843-2daf-fd8f-80ad9b3d5029
* Version Independent ID: 35571d2f-e4bf-c65b-450f-f57b1ecd6967
* Content: [Wlecome to Kaizala](https://docs.microsoft.com/en-us/office365/kaizala/kaizala-overview)
* Content Source: [Office365-Kaizala/kaizala-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/kaizala-overview.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
Hi @AndreaBarr - This issue can be closed. Thank you.
