### ISSUE TITLE
access to endusers onedrives should be off by default and aduit logged once admins get access

### ISSUE THREAD

**Issue by stche** [MicrosoftDocs/OfficeDocs-O365ITPro#138]
eventhough the ability to have access to content from an employee that left the company might be a valid ask, this article here simply just shows how and Admin can get access with no borders other than clicking a link. This is actually in most cases for the customers I work with a violation of their data privacy or internal IT-policies and I hope we do audit logging this event out of box without having additional licenses or even config steps in the sec & Compl. center.  Otherwise this would be a "carte blanche" for each company and/or its admins to "spy out" what a certain user has stored within her/his onedrive which is "sold as a private storage". And on top of it, endusers would not even notice it if the admin removes themselves right after.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@stche - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the OneDrive better. They keep a close tab on User Voice https://onedrive.uservoice.com/ and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!
