### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by msbemba** [MicrosoftDocs/OfficeDocs-O365ITPro#145]
![exchadmin](https://user-images.githubusercontent.com/45987684/50208592-923e1d00-0397-11e9-8089-974fe1028b97.PNG)
![covnerttoshared](https://user-images.githubusercontent.com/45987684/50208599-966a3a80-0397-11e9-8148-8d2595343709.PNG)

**Comment by jamesrhea** [comment]
Hi @msbemba. It appears that your issue submission only includes screenshots. Is there a specific article that you're looking at where images aren't showing up?

**Comment by msbemba** [comment]
Hello James,

Yes, I was trying to update the article
https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide
with different screenshots and changes in step 2-4 . This is the first time
I'm trying to do this and I have created a pull request after making the
desired changes in the code. Not sure if I'm doing something wrong here.

**Comment by jamesrhea** [comment]
@msbemba, thanks. That clarifies things. Looks like your pull request is here: https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/146

I've added a comment to identify that PR as a fix to this issue. Thanks for helping keep Microsoft Docs current and accurate!
