### ISSUE TITLE
Verificacion indentidad

### ISSUE THREAD

**Issue by jlopezgarcia19** [MicrosoftDocs/OfficeDocs-O365ITPro#150]
no puedo verificar mi cuenta porque, me envian el codigo a un numero telefonico que no estoy utilizando en el momento

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 95ccea09-c43c-352d-03d2-62e3f2c88024
* Version Independent ID: 928cfeb9-04f7-ee66-3086-b319ea1739f0
* Content: [Información de soporte técnico para Colombia](https://docs.microsoft.com/es-es/office365/admin/support/colombia?view=o365-worldwide)
* Content Source: [Office365-Admin/support/colombia.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/colombia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@samanthaw

**Comment by samanthaw** [comment]
@MollyMalone

**Comment by AndreaBarr** [comment]
I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
