### ISSUE TITLE
tool laat zich om veiligheidsredenen niet installeren. (ook niet met administrator-rechten.)

### ISSUE THREAD

**Issue by Marc26** [MicrosoftDocs/OfficeDocs-O365ITPro#152]
Office-outlook 365 loopt vast na start programma, met namen na bekijken inbox andere account dan standaard ingesteld.
De herstel-assistent loopt vast tijdens de installatie. (tool laat zich om veiligheidsredenen niet installeren. (ook niet met administrator-rechten.)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8b64ea8b-5422-812f-420d-6500e9e9eaee
* Version Independent ID: 7dc87b3e-f347-266f-0bbd-3d6b8217c22f
* Content: [Outlook en Office 365 problemen kunt oplossen met ondersteuning en herstel-assistent](https://docs.microsoft.com/nl-nl/office365/admin/troubleshoot-issues-for-admins/fix-outlook-and-office-365-issues?redirectSourcePath=%252fen-us%252farticle%252ffix-outlook-and-office-365-issues-with-support-and-recovery-assistant-for-office-365-12cd632c-d672-4782-b0ce-beb82b511525&view=o365-worldwide)
* Content Source: [Office365-Admin/troubleshoot-issues-for-admins/fix-outlook-and-office-365-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/troubleshoot-issues-for-admins/fix-outlook-and-office-365-issues.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by Marc26** [comment]
![afbeelding](https://user-images.githubusercontent.com/32365478/50342021-79fa0980-0521-11e9-8027-45f22a12f345.png)

**Comment by mypil** [comment]
@samanthaw

**Comment by samanthaw** [comment]
@MollyMalone

**Comment by AndreaBarr** [comment]
I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
