### ISSUE TITLE
which Office 365 editions

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/OfficeDocs-O365ITPro#156]
Document doesn't say if this applies to Office 365 Home as well as Business

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8536a8-9f8e-11be-09bd-1b5b55dce588
* Version Independent ID: 985d25d7-b37e-a256-468d-fe23bd6f84cf
* Content: [Buy a domain name in Office 365](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/buy-a-domain-name?view=o365-worldwide)
* Content Source: [Office365-Admin/get-help-with-domains/buy-a-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/buy-a-domain-name.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by khorne3** [comment]
@AndreaBarr I'll take a look at this one.

**Comment by mypil** [comment]
@marypcbuk - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by marypcbuk** [comment]
no, I can't see a list of which Office 365 subscriptions this applies to - so Office 365 Home uses are still asking me if they can have a custom domain because they don't know if this applies to them; a lit of what subscriptions support custom domains would avoid confusion

**Comment by marypcbuk** [comment]
the change suggested has NOT been merged, so this issue is still open

**Comment by mypil** [comment]
@marypcbuk - - Thank you for submitting this feedback.

I will get this over to @pebaum  for investigation. 

Thank you for reporting and making the docs better. Much appreciated.

**Comment by pebaum** [comment]
added "To Add, modify or remove domains you must be a Global Administrator of a business or enterprise plan. These changes affect the whole tenant, Customized administrators or regular users won't be able to make these changes." to the top of the article. text links to products.office.com business and enterprise plans. this standardized text that appears on a few other pages may be changed soon to reflect new M365 offerings.
