### ISSUE TITLE
Instruction is not universally applicable

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/OfficeDocs-O365ITPro#159]
"On the Dashboard page, in the All resources area, choose the domain that you want to update."
...this only works if you happened to have been using that domain recently and have your Dashboard configured to show it.
The more objective procedure that should be used would be something like "type DNS zone in the search bar, then select the zone from that menu" or "go to All Services &gt; Networking &gt; DNS Zones &gt; choose the zone".
Ideally the screenshot would be replaced as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 352180ef-af0b-c390-91fd-32bbc81a6a9f
* Version Independent ID: 68256656-ee0d-9d29-46cd-402ae70206b7
* Content: [Create DNS records for Azure DNS zones](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-for-azure-dns-zones?view=o365-worldwide#add-a-txt-record-for-spf-to-help-prevent-email-spam)
* Content Source: [Office365-Admin/dns/create-dns-records-for-azure-dns-zones.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-for-azure-dns-zones.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by dcbrown16** [comment]
Also, this page doesn't seem to show in the ToC, is that intentional?

**Comment by khorne3** [comment]
@AndreaBarr I'll take a look at this one.

**Comment by mypil** [comment]
@dcbrown16 - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better. Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
