### ISSUE TITLE
Policy Scope

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/OfficeDocs-O365ITPro#162]
Please clarify. Using "-IncludeUnifiedGroupRecipients" and "-ManagedByFilter" will only target Office 365 Groups, correct? So if we already have an EAP for User Mailboxes we would create an additional one for Office 365 Groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96002890-7e35-a0ab-a849-d94fef254fa8
* Version Independent ID: 2c4105db-b713-4829-393e-de355c5c60d4
* Content: [Choose the domain to use when creating Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/choose-domain-to-create-groups?redirectSourcePath=%252fen-us%252farticle%252fMulti-domain-support-for-Office-365-Groups-Admin-help-7cf5655d-e523-4bc3-a93b-3ccebf44a01a&view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/choose-domain-to-create-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/choose-domain-to-create-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@toddjohnson39 - Thank you for pointing this inquiry.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @toddjohnson39 This is only applicable on Office 365 groups and if you want to create EAP for Office 365 group, then this doc can help you set this up.

**Comment by mypil** [comment]
@toddjohnson39 - Did @joinimran resolve your issue?

**Comment by mypil** [comment]
@toddjohnson39 - We appreciate any feedback you can provide to make the content in the Microsoft docs better. Since we did not get any response from you, we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
