### ISSUE TITLE
add Copy to / Move to options and limits

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/OfficeDocs-O365ITPro#163]
Hi, 
please elaborate on the copy to / move to options. 
Seems that there is a limit of 500 GB and no support for versions (see here: https://support.office.com/en-us/article/move-files-and-folders-between-onedrive-and-sharepoint-5916f90d-f58a-4bf9-b135-10853f516d0b

You can move up to 500 MB of files and folders at a time.)

What are the option for large OD of former employees without download it all. 

I just add voice ticket for the 500 MB limit: 
https://onedrive.uservoice.com/forums/913528-onedrive-on-the-web/suggestions/36432421-remove-move-to-limit-of-500-mb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?redirectSourcePath=%252fen-us%252farticle%252fGet-access-to-and-back-up-a-former-user-s-data-a6f7f9ad-e3f5-43de-ade5-e5a0d7531604&view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
Created PR to add a note about he limitations.
 https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/247

**Comment by mypil** [comment]
@TiloGit - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
