### ISSUE TITLE
Add-In Details of the 'Enable Protected Mode' requirement

### ISSUE THREAD

**Issue by mhouston100** [MicrosoftDocs/OfficeDocs-O365ITPro#164]
Using an Office Add-Ins deployed using Centralized Deployment requires that 'Enable Protected Mode' be enabled in Internet Explorer Settings.

Is there more information regarding this? We don't want to 'Enable Protected Mode' across the board, is there a certain list of URL's that I can add to a certain zone (restricted for instance) that has protected mode enabled?

Is there any way for these to operate WITHOUT protected mode?

At minimum this information should be included in the 'Requirements' section of the implementation documentation as it is literally required to get add-in's to work.

**Comment by mypil** [comment]
@mhouston100 - Thank you for your valuable contribution in helping improve MS docs. Can you please share the document link or content source link for this particular issue?

**Comment by mypil** [comment]
@mhouston100 - we would like to follow up on this. May we know which Microsoft document link you used in reference to this issue? Please share it with us so we can make the necessary changes to improve the MS document for accuracy.

**Comment by mhouston100** [comment]
Hi Sorry, I'm getting back to this ASAP, I've just had the craziest week
with some SCCM/certificate issues!

I believe it was a couple of technet forum posts that discovered it I will
dig back through to find it.

Ive also done extensive testing on it, but the only way I can get Office
Store based add-in's to work is through enabling protected mode.

What originally led me to testing was this article here:

https://support.microsoft.com/en-ca/help/2761180/apps-for-office-don-t-start-if-you-disable-protected-mode-for-the-rest

That specifically says 'Restricted Zone' however I didn't find that was the
case.

When I get to work tomorrow I'll try and dig back through.

-Matt

**Comment by mypil** [comment]
@mhouston100 - we would like to follow up on this. Can you please provide more details as to what should be edited and/or included?

**Comment by mypil** [comment]
@mhouston100 - we would like to follow up on this. Do you have any updates?

**Comment by mypil** [comment]
@mhouston100 - We appreciate any feedback you can provide to make the content in the Microsoft docs better. Since we did not get any response from you, we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!
