### ISSUE TITLE
Problem solving not included

### ISSUE THREAD

**Issue by EnriqueLechuga** [MicrosoftDocs/OfficeDocs-O365ITPro#166]
The documentation lacks a  section for problem solving to activate Kaizala app. As an example, I cannot activate the app. I have downloaded it to my device (iPhone XS), entered my name, chosen my country (Mexico), entered my phone number, received a code and get a message that there is no connection and to try later). Oddly enough, if I change the code, the message states that the code is incorrect. 
I have tried several times to the point of being blocked for 24 hours for having tried too many times. 
I have uninstalled and reinstalled the app several times to the same result. All my colleagues at my company, but me, have the app.

A "Frequently asked questions" or "Problem solving" section would be most helpful. 

I would really appreciate if you could let me know how to solve my problem or whom I should contact to get help.       

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915b1428-b989-629d-2fe9-e3870100df73
* Version Independent ID: 17613672-bc40-dc95-b494-9d8111e78b98
* Content: [Kaizala app](https://docs.microsoft.com/en-us/office365/kaizala/kaizala-app)
* Content Source: [Office365-Kaizala/kaizala-app.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/kaizala-app.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@nitinjms2 and @n-r-s -- Can you please help Enrique with his activation inquiry? Thank you.

**Comment by n-r-s** [comment]
Thanks @EnriqueLechuga for bringing this up. 

1. You make a valid suggestion on having documentation for problem solving. This is something we're already working and will hopefully have up & running soon.
2. For the issue on signup: I am sorry to hear this happening. It will help us greatly if you could tell us the last 4 digits of your number & any approximate time interval when you were trying to sign up.

**Comment by EnriqueLechuga** [comment]
Dear Neeraja,

Thank you for your prompt response. It is really nice to know you will have problem solving documentation soon.

As to my phone number, the country code is +52, the area code is 55 and the last four digits are 5484.
The last time I attempted to activate the app was yesterday at 12:44 pm Mexico City time, which is the same as Central time in the USA.

Please let me know if any additional information is needed.

Warmest regards,

[20FESEN_02]

[cid:image003.png@01D4A41E.5BBC7AC0]

Enrique Lechuga Ballesteros
Marketing and Customer Care Director
Tel. +52 (55) 5148 5696 ext. 110 | Fax +52 (55) 5148 5697 | Mobile: +52 (55) 4524 5484
Lada sin costo 01 800 022 2024 | Twitter: EnriqueLB | Skype: enrique.lechuga| www.fesworld.com<http://www.fesworld.com>



De: Neeraja <notifications@github.com>
Enviado el: viernes, 4 de enero de 2019 07:45 a. m.
Para: MicrosoftDocs/OfficeDocs-O365ITPro <OfficeDocs-O365ITPro@noreply.github.com>
CC: Enrique Lechuga Ballesteros <elechuga@fesworld.com>; Mention <mention@noreply.github.com>
Asunto: Re: [MicrosoftDocs/OfficeDocs-O365ITPro] Problem solving not included (#166)


Thanks @EnriqueLechuga<https://github.com/EnriqueLechuga> for bringing this up.

  1.  You make a valid suggestion on having documentation for problem solving. This is something we're already working and will hopefully have up & running soon.
  2.  For the issue on signup: I am sorry to hear this happening. It will help us greatly if you could tell us the last 4 digits of your number & any approximate time interval when you were trying to sign up.

**Comment by EnriqueLechuga** [comment]
Dear Neeraja,

I attempted today, January 7th, and got the same result (“No connection” message). I got the code from +52 (418) 132 5656 at 5:52 pm Mexico City time (US Central time), and used it tight away.
Is there anything at all I can do to activate Kaizala?

I will certainly appreciate your help.

Warmest regards,

[20FESEN_02]

[cid:image003.png@01D4A6B7.9A99E570]

Enrique Lechuga Ballesteros
Marketing and Customer Care Director
Tel. +52 (55) 5148 5696 ext. 110 | Fax +52 (55) 5148 5697 | Mobile: +52 (55) 4524 5484
Lada sin costo 01 800 022 2024 | Twitter: EnriqueLB | Skype: enrique.lechuga| www.fesworld.com<http://www.fesworld.com>



De: Enrique Lechuga Ballesteros
Enviado el: viernes, 4 de enero de 2019 11:13 a. m.
Para: 'MicrosoftDocs/OfficeDocs-O365ITPro' <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-O365ITPro <OfficeDocs-O365ITPro@noreply.github.com>
CC: Mention <mention@noreply.github.com>
Asunto: RE: [MicrosoftDocs/OfficeDocs-O365ITPro] Problem solving not included (#166)

Dear Neeraja,

Thank you for your prompt response. It is really nice to know you will have problem solving documentation soon.

As to my phone number, the country code is +52, the area code is 55 and the last four digits are 5484.
The last time I attempted to activate the app was yesterday at 12:44 pm Mexico City time, which is the same as Central time in the USA.

Please let me know if any additional information is needed.

Warmest regards,

[20FESEN_02]

[cid:image008.png@01D4A6B7.9A99E570]

Enrique Lechuga Ballesteros
Marketing and Customer Care Director
Tel. +52 (55) 5148 5696 ext. 110 | Fax +52 (55) 5148 5697 | Mobile: +52 (55) 4524 5484
Lada sin costo 01 800 022 2024 | Twitter: EnriqueLB | Skype: enrique.lechuga| www.fesworld.com<http://www.fesworld.com>



De: Neeraja <notifications@github.com<mailto:notifications@github.com>>
Enviado el: viernes, 4 de enero de 2019 07:45 a. m.
Para: MicrosoftDocs/OfficeDocs-O365ITPro <OfficeDocs-O365ITPro@noreply.github.com<mailto:OfficeDocs-O365ITPro@noreply.github.com>>
CC: Enrique Lechuga Ballesteros <elechuga@fesworld.com<mailto:elechuga@fesworld.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Asunto: Re: [MicrosoftDocs/OfficeDocs-O365ITPro] Problem solving not included (#166)


Thanks @EnriqueLechuga<https://github.com/EnriqueLechuga> for bringing this up.

  1.  You make a valid suggestion on having documentation for problem solving. This is something we're already working and will hopefully have up & running soon.
  2.  For the issue on signup: I am sorry to hear this happening. It will help us greatly if you could tell us the last 4 digits of your number & any approximate time interval when you were trying to sign up.

**Comment by n-r-s** [comment]
@EnriqueLechuga : Thanks a ton for the details! We found the issue with the details you gave us. It was a problem at our end, which is expected to be fixed in 2 days. You could try signing up post that and it should go through. Apologies again for the inconvenience caused & the ensuing delay.

**Comment by EnriqueLechuga** [comment]
Dear Neeraja,

Thank you very much for your help. I was finally able to activate the app.

Have a great weekend!

Warmest regards,

[20FESEN_02]

[cid:image004.png@01D4A9E9.902ADFB0]

Enrique Lechuga Ballesteros
Marketing and Customer Care Director
Tel. +52 (55) 5148 5696 ext. 110 | Fax +52 (55) 5148 5697 | Mobile: +52 (55) 4524 5484
Lada sin costo 01 800 022 2024 | Twitter: EnriqueLB | Skype: enrique.lechuga| www.fesworld.com<http://www.fesworld.com>



De: Neeraja <notifications@github.com>
Enviado el: martes, 8 de enero de 2019 11:42 a. m.
Para: MicrosoftDocs/OfficeDocs-O365ITPro <OfficeDocs-O365ITPro@noreply.github.com>
CC: Enrique Lechuga Ballesteros <elechuga@fesworld.com>; Mention <mention@noreply.github.com>
Asunto: Re: [MicrosoftDocs/OfficeDocs-O365ITPro] Problem solving not included (#166)


@EnriqueLechuga<https://github.com/EnriqueLechuga> : Thanks a ton for the details! We found the issue with the details you gave us. It was a problem at our end, which is expected to be fixed in 2 days. You could try signing up post that and it should go through. Apologies again for the inconvenience caused & the ensuing delay.
