### ISSUE TITLE
Unable to Contact Support Team

### ISSUE THREAD

**Issue by cepmgsy** [MicrosoftDocs/OfficeDocs-O365ITPro#168]
unable to contact skype for business support through the numbers mentioned above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2b385a-9cb4-9110-94bb-7d63f7e591f0
* Version Independent ID: 07d6eed9-0f79-5c7e-6c7b-0391d0190c57
* Content: [Support information for India](https://docs.microsoft.com/en-us/office365/admin/support/india?view=o365-worldwide)
* Content Source: [Office365-Admin/support/india.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/india.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by j0rt3g4** [comment]
This is the way you can get help if that channel doesn't work:
https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by mypil** [comment]
@cmcatee-MSFT - this issue is similar to #81

**Comment by mypil** [comment]
@cepmgsy - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by mypil** [comment]
@cepmgsy - We have confirmed that the phone numbers stated in the MS Article are correct. However, there is a technical issue in the backend that is being resolved. Rest assured that this is being worked on.

Thank you for submitting this feedback. We appreciate your contribution to make the docs better.

**Comment by Gautami007** [comment]
Hello Team,

I am trying to connect to technical team for microsoft skype for business tool issue. But not able to reach out with given phone number. Please help me to resolve my issue.

**Comment by cmcatee-MSFT** [comment]
Hi @Gautami007 We're still working on the situation with the phone numbers, but don't have a solution yet. In the meantime, please use the online support in the admin center to request a call back from a support representative. The instructions to do so are [here](https://docs.microsoft.com/en-us/Office365/Admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
