### ISSUE TITLE
Article is stale, here are the current commands of relevance.

### ISSUE THREAD

**Issue by jonblackburn** [MicrosoftDocs/OfficeDocs-O365ITPro#169]
```
Connect-AzureAD  
Set-AzureADUser -ObjectID EMAIL@COMPANY.COM -PasswordPolicies DisablePasswordExpiration
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8299b0d8-25e4-af45-a9f8-724f61ed4f4a
* Version Independent ID: 4ab5dc30-7f11-758b-9b58-e5254e25774e
* Content: [Set an individual user's password to never expire](https://docs.microsoft.com/en-us/office365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by nenonix** [comment]
@jonblackburn Thank you for your feedback and for providing clarity. I will look into this and post here when this has been resolved.

**Comment by BEAULONEA** [comment]
Is there an upadated command to find out whether a user's password is set to never expire?

**Comment by j0rt3g4** [comment]
Hi guys @BEAULONEA and @jonblackburn  I've added 2 reports where the outputs are: 
*CSV 
*HTTP
Solved on PR #282

**Comment by mypil** [comment]
@j0rt3g4 - We are still waiting for the doc owner to merge the content. Follow up has been done already. Thanks.

**Comment by j0rt3g4** [comment]
@mypil  Yes Not sure if it has been already merged...

**Comment by mypil** [comment]
@jonblackburn - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
