### ISSUE TITLE
Retiring Staffhub App - OpenSource code ?

### ISSUE THREAD

**Issue by IoTFier** [MicrosoftDocs/OfficeDocs-O365ITPro#172]
Hi @AndreaBarr and others, is there any thought on Open sourcing the retiring StaffHub App code ?

Is there a link / doc that explain how can I merge (invoke) some of the Staffhub functionalities in a mobile App/Site giving access to integrate with O365 APIs but allowing me to use StaffHub App functionality while providing my own color themes etc to the merged Staffhub App module(s).

Your thoughts will be appreciated.

Thanks,

**Comment by mypil** [comment]
@IoTFier - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the Office 365 better. They keep a close tab on User Voice- **[](https://office365.uservoice.com/)** and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!
