### ISSUE TITLE
Office 365 administration

### ISSUE THREAD

**Issue by jmlahammer** [MicrosoftDocs/OfficeDocs-O365ITPro#173]
I would like to be able to run a report that gives me all the aliases and who they point to for my organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f73b082-eed3-e2a8-50a3-ba1b85f2915d
* Version Independent ID: 05dbb561-a215-1cf8-de66-6ea901617719
* Content: [Quick help Types of users](https://docs.microsoft.com/en-us/office365/admin/misc/types-of-users?redirectSourcePath=%252fen-US%252farticle%252f0dc55430-98d6-4cbe-ba69-1a4ad29a967d&view=o365-worldwide)
* Content Source: [Office365-Admin/misc/types-of-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/types-of-users.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@jmlahammer - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
