### ISSUE TITLE
API access permissions

### ISSUE THREAD

**Issue by danno77** [MicrosoftDocs/OfficeDocs-O365ITPro#174]
Hi, Can you please confirm the required level of permissions for accessing the Reporting API?  Is it the same as the report permissions?  thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by lindspea** [comment]
Hi @danno77 Thank you for reaching out.  The same permissions apply for viewing and for the reporting API. Please let me know if you need any further assistance.

**Comment by lindspea** [comment]
@AndreaBarr @mypil this can be closed thank you.
