### ISSUE TITLE
"Manage inactive mailboxes in Exchange Online" link incorrect

### ISSUE THREAD

**Issue by DenisMitchell** [MicrosoftDocs/OfficeDocs-O365ITPro#176]
As stated in title, "Manage inactive mailboxes in Exchange Online" link is incorrect and goes to:
https://docs.microsoft.com/en-us/office365/securitycompliance/eop/exchange-online-protection-overview

The link should go either to:
https://docs.microsoft.com/en-us/office365/securitycompliance/inactive-mailboxes-in-office-365
or
https://docs.microsoft.com/en-us/office365/securitycompliance/create-and-manage-inactive-mailboxes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d96d7b-d9da-9c6b-0f74-65bb006ec9ee
* Version Independent ID: f0aa71c1-3fc1-f7fb-77cc-a048b726330e
* Content: [Remove licenses from users in Office 365 for business](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/remove-licenses-from-users?view=o365-worldwide&tabs=One)
* Content Source: [Office365-Admin/subscriptions-and-billing/remove-licenses-from-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/remove-licenses-from-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by AndreaBarr** [comment]
@DenisMitchell  It appears that this link has been updated/corrected already. 

I have verified that the link now goes to https://docs.microsoft.com/en-us/office365/securitycompliance/create-and-manage-inactive-mailboxes. 

I am going to close this issue at this time. If the link is not updated when you follow it please let us know.
