### ISSUE TITLE
Correction to the docs on 'Enabling the content pack'

### ISSUE THREAD

**Issue by veronicageek** [MicrosoftDocs/OfficeDocs-O365ITPro#177]
The documentation says:
* In the admin center, expand the left nav, and go to **_Reports_** > **_Usage_**.
* On the _Usage- page, locate the _Microsoft 365 usage analytics_ card, and choose Get started.
* On the Reports panel that opens, set `Make data available the Microsoft 365 usage analytics for Power BI` to On > Save.

That doesn't seem correct as `Make data available the Microsoft 365 usage analytics for Power BI` is currently available under **_Settings_** > **_Services & add-ins_** >> **_Reports_**.

Regardless of if the Admin preview is on or off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec8961e-4fc1-eb46-1e71-3147b55ac90e
* Version Independent ID: 2c66ebfb-53b5-18ab-e560-702d4cae057f
* Content: [Enable Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by nenonix** [comment]
Thank you for pointing this out. I will reflect your changes in the document. While I research the issue,  can you help me by suggesting how we edit the content for clarity?

**Comment by veronicageek** [comment]
Hi,

The documentation should says:

* In the admin center, expand the left navigation, and go to **_Services & add-ins_**
* On the _Services & add-ins_ page, scoll down and click on **_Reports_**.
* When the _Reports_ blade opens, check the box `Make data available the Microsoft 365 usage analytics for Power BI` and click on **_Save changes_**.

**Comment by nenonix** [comment]
@veronicageek  Thank you, We really appreciate your efforts to improve the documentation.

**Comment by Sirkkuw** [comment]
@veronicageek  and @AndreaBarr - the steps in the topic are actually correct. The green field experience has the "Get Started" button there if you never set this up before.
In the **Service&add-ins** `>` **reports** you can uncheck to turn it off, I believe.
I am going to close the associated PR.
