### ISSUE TITLE
Screen shots and work around out dated 

### ISSUE THREAD

**Issue by cuzito** [MicrosoftDocs/OfficeDocs-O365ITPro#185]
Hi 
The screenshots for Ionos are outdated and they have changed the layout of their DNS records. Also clicking on the loop for the video continually reloads this page rather than showing the video. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60ec04cf-93af-b216-4290-c2d0ff79878d
* Version Independent ID: e7fd186e-7efd-711e-3f29-e318b2100083
* Content: [Create DNS records at 1&1 IONOS for Office 365](https://docs.microsoft.com/en-gb/office365/admin/dns/create-dns-records-at-1-1-internet?redirectSourcePath=%252fen-us%252farticle%252fVideo-Create-DNS-records-at-1-1-Internet-for-Office-365-543fb112-ecf5-47ae-b096-07f3f942a089&view=o365-worldwide)
* Content Source: [Office365-Admin/dns/create-dns-records-at-1-1-internet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-1-1-internet.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by jamesrhea** [comment]
@pebaum, is this the video referred to in this article? https://www.youtube.com/watch?v=H7KLpm50kv8

**Comment by mypil** [comment]
@pebaum - we would like to follow up and get your insights on the query from @jamesrhea. Thank you.

**Comment by pebaum** [comment]
removed the video link - working on removing outdated screenshots across this set.
