### ISSUE TITLE
Workarround is available for converting to shared mailbox in Hybrid

### ISSUE THREAD

**Issue by yatsymbal** [MicrosoftDocs/OfficeDocs-O365ITPro#188]
Hello,

Is there any reason why we can't use the workaround posted in the support article as a recommended guidance?
https://support.microsoft.com/en-us/help/2710029/shared-mailboxes-are-unexpectedly-converted-to-user-mailboxes-after-di

With the workaround the process of converting mailbox to a shared in Hybrid would as easy as this:

    1. Convert a mailbox to shared in Exchange Online Admin Center
    2. Change the recipient type in AD on-prem by running the cmdlet:
    Set-ADUser -Identity ((Get-Recipient PrimarySmtpAddress).samaccountname) -Replace @{msExchRemoteRecipientType=100;msExchRecipientTypeDetails=34359738368}

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#convert-a-users-mailbox-in-a-hybrid-environment)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@yatsymbal - Thank you for submitting this Feedback.

From my understanding the issue of has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by NeighborGeek** [comment]
@neonix and @mypil - I may be missing something, but I don't see where @yatsymbal's question was answered.  They asked if it could be supported/recommended to convert a mailbox to shared in the cloud, without ever moving it back to on-prem, and updating the msExchRemoteRecipientType attribute of the AD account.  

If that workaround does actually get a hybrid user mailbox converted to a shared mailbox with the proper configuration, it seems like it would be a much better option than migrating the mailbox back to on-prem, converting, and migrating back to cloud.
