### ISSUE TITLE
gestion de tickets 

### ISSUE THREAD

**Issue by TeyssierF** [MicrosoftDocs/OfficeDocs-O365ITPro#189]
Bonjour je suis Technicien informatique dans une petite structure (-22 pers).
J 'ai besoin d'un service de ticket qui passe par la boite mail outlook.
Cela est il possible?
Cordialement
Florian Teyssier

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f6eb21db-f7a1-2f51-068a-ee3b939a560f
* Version Independent ID: 15980f1a-120a-5a2d-0df0-c54ba099410e
* Content: [Informations de prise en charge pour la France](https://docs.microsoft.com/fr-fr/office365/admin/support/france?view=o365-worldwide)
* Content Source: [Office365-Admin/support/france.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/france.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@samanthaw

**Comment by dplotnikov** [comment]
Bonjour, juste pour confirmer, allez-vous adresser une demande d'assistance par courrier électronique à Microsoft? Si tel est le cas, ouvrez votre panneau d’administration Office 365, puis recherchez un élément de menu Support dans le menu. Cet élément de menu devrait vous permettre de créer une nouvelle demande d'assistance par courrier électronique.

**Comment by dplotnikov** [comment]
@TeyssierF bonjour attend toujours votre entrée

**Comment by dplotnikov** [comment]
@TeyssierF s'il vous plaît laissez-moi savoir si vous avez encore des questions

**Comment by kenwith** [comment]
@TeyssierF - I do not speak French but looking at Bing Translator it seems you are asking to open a service ticket or have a question about support. Please open a service ticket in your tenant. Here is a link on how to do that: https://www.youtube.com/watch?v=puuOy0sEg1Y

Thank you for your feedback and please feel free to re-open this issue if I am misunderstanding and there is a specific area of the docs that we can improve or make better. Thanks!
