### ISSUE TITLE
Soft delete gives 404 now, instead of a 403. 

### ISSUE THREAD

**Issue by petey121175** [MicrosoftDocs/OfficeDocs-O365ITPro#190]
The 403 error no longer represents a group that's been soft deleted. We throw a 404 error instead. It was 403 some time ago, but engineering has decided to change to a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22c9b1f8-635e-cbc2-6927-9f2d7767bbc6
* Version Independent ID: c2abc72f-0007-1ed1-803e-ce85f7e87d4f
* Content: [Restore a deleted Office 365 Group](https://docs.microsoft.com/en-us/office365/admin/create-groups/restore-deleted-group?redirectSourcePath=%2Fen-us%2Farticle%2FRestore-a-deleted-Office-365-Group-b7c66b59-657a-4e1a-8aa0-8163b1f4eb54&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/restore-deleted-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/restore-deleted-group.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed.
