### ISSUE TITLE
Microsoft 365 Roadmap not Office 365 Roadmap

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-O365ITPro#193]
Hi Team. Microsoft has bundled the Office 365 Roadmap into the wider Microsoft 365 Roadmap. I suggest changing the couple of times above that "Office 365 Roadmap" is used, and also put in the correct link. The one you have above doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7a47d0-7e67-1890-8a1e-192871c99b55
* Version Independent ID: ff75ce98-2235-8c92-b6a2-9b034061adef
* Content: [Yammer and Office 365 Groups](https://docs.microsoft.com/en-us/yammer/manage-yammer-groups/yammer-and-office-365-groups)
* Content Source: [yammer/manage-yammer-groups/yammer-and-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-groups/yammer-and-office-365-groups.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by IrenePasternack** [comment]
Thank you. In the Yammer docs, I’ve changed the name of the link to Microsoft 365 Roadmap. The destination fwlink has been redirected so it goes to the correct location.

Irene

**Comment by nenonix** [comment]
@Michael-Sampson and @IrenePasternack  I apologise for flooding your issue with PR references .  I am a freelancer working on a number of repos with @kenwith and @AndreaBarr  and I went through the docs and found a number of instances where we could reflect this change as well. To explain why I simply used this issue. I did change some 365itPro docs and would like to know more about the fwlink.
I used https://www.microsoft.com/microsoft-365/roadmap. Please let me know if that is not in order. Thanks for pointing this out. Nicole

**Comment by kenwith** [comment]
@LolaJacobsen - FYI
