### ISSUE TITLE
You can't send as a distribution list just by being a member?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-O365ITPro#194]
I think these instructions are missing a critical step of granting Send As rights or this is talking about something totally different?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2913af07-8c4d-e496-0fa5-1983d9397d92
* Version Independent ID: b43f9698-a736-86de-a0f6-f5e516ea3f6b
* Content: [Send email as a distribution list in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/send-email-as-distribution-list?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/send-email-as-distribution-list.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/send-email-as-distribution-list.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by dariomws306** [comment]
Hi @hoyty76 , thanks for your feedback. You're rigth, I am updating the article so it let you know that you need the send as permissions too, it's not enough with just add the user as member.

Thank you again.

**Comment by mypil** [comment]
@hoyty76 - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
