### ISSUE TITLE
My ID

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/OfficeDocs-O365ITPro#197]
Как активировать бизнес аккаунт?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: eb46296b-72d7-ea4a-84d2-2f868f38e3cf
* Version Independent ID: 070d474b-9171-cb91-772e-4e71173b9f71
* Content: [Сведения о поддержке для Казахстан](https://docs.microsoft.com/ru-ru/office365/admin/support/kazakhstan?view=o365-worldwide)
* Content Source: [Office365-Admin/support/kazakhstan.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/kazakhstan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by lindspea** [comment]
@samanthaw  @AndreaBarr

**Comment by lindspea** [comment]
Привет. Пожалуйста, смотрите ссылки ниже.
Hi @matuhinal . Please see the links below.
https://docs.microsoft.com/en-us/office365/admin/setup/setup?view=o365-worldwide&tabs=BusPremium
https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/buy-licenses?view=o365-worldwide.

**Comment by lindspea** [comment]
@samanthaw @MollyMalone please review

**Comment by MollyMalone** [comment]
Вот ссылки на российские статьи:
Here are links to the Russian articles:
https://docs.microsoft.com/ru-ru/office365/admin/setup/setup?view=o365-worldwide&tabs=BusPremium 
https://docs.microsoft.com/ru-ru/office365/admin/subscriptions-and-billing/buy-licenses?view=o365-worldwide.
@lindspea once you add the correct link to the English article we will automatically update the Russian article (как только вы добавите правильную ссылку на английскую статью, мы будем автоматически обновлять российскую статью)

**Comment by lindspea** [comment]
Hi Molly, this might be a stupid question but where is the English
article?  The content from this issue only brings up the page for contact
support for Kazakhstan.?

[image: Picture]

**Comment by lindspea** [comment]
@MollyMalone Hi Tina, I'm aware of the links but where is the content document that needs to be updated with the links? This issue was opened under the document - contact support for Kazakhstan.

**Comment by matuhinal** [comment]
Thanks for the tip!We started working with the Azure team yesterday! 06.02.2009, 01: 06, "AndreaBarr" <notifications@github.com>:Closed #197.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.  -- With respect,MatuhinaL+77078086126
