### ISSUE TITLE
Simpler instructions please?

### ISSUE THREAD

**Issue by jesspent** [MicrosoftDocs/OfficeDocs-O365ITPro#2]
This really very clear to me on how to create a Dynamic group in Yammer. - E.G. add a Group / Distribution list called finance. And anyone in this group/dl/ or  attribute of finance automatically get added. Could you make this simpler please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d80456-b900-8982-0077-bdd6c0626d3b
* Version Independent ID: c549c24d-b75b-f8c3-a2a6-05b8775be38f
* Content: [Create a dynamic group in Yammer](https://docs.microsoft.com/en-us/yammer/manage-yammer-groups/create-a-dynamic-group)
* Content Source: [yammer/manage-yammer-groups/create-a-dynamic-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-groups/create-a-dynamic-group.md)
* Service: **o365-administration**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by AndreaBarr** [comment]
@jesspent Thank you for this feedback

I will get this over to the O365ITPro Team for investigation and update.

I was able to get this into the backlog for the O365ITPro team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
