### ISSUE TITLE
CNAME

### ISSUE THREAD

**Issue by apriltale** [MicrosoftDocs/OfficeDocs-O365ITPro#205]
"In the New Resource Record dialog box, make sure that the fields are set to precisely the following values:
Host Name: sip
Type: CNAME
Address: sip
dir.online.lync.com"

The Address should be in one sentence "sipdir.online.lync.com" instead of separately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0937468-6fd2-c83a-ed60-81129a4b766a
* Version Independent ID: 010a32f0-45a3-81da-1a6c-864996a86597
* Content: [Create DNS records for Office 365 using Windows-based DNS](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-using-windows-based-dns?view=o365-worldwide)
* Content Source: [Office365-Admin/dns/create-dns-records-using-windows-based-dns.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-using-windows-based-dns.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by lindspea** [comment]
@apriltale thank you for pointing this out and your valuable contribution in improving MS docs.  We will work together to have it changed as soon as possible.

**Comment by lindspea** [comment]
This can be closed thanks @AndreaBarr @mypil
