### ISSUE TITLE
Deleted Date values missing from Mailbox Usage Report

### ISSUE THREAD

**Issue by junecastillote** [MicrosoftDocs/OfficeDocs-O365ITPro#210]
Pulling the <i>getMailboxUsageDetail</i> using Graph API or exporting the report from Office 365 portal, the <b>Deleted Date</b> value is always blank - even when the <b>Is Deleted</b> value is <b>True</b>.
This produces an inaccurate report regarding deleted mailboxes.

Also, some mailboxes that actually are not deleted are showing as deleted (Is Deleted = true) in the report.

**Comment by mypil** [comment]
@junecastillote - Thank you for your valuable contribution in helping improve MS docs. Can you please share the document link or content source link for this particular issue?

**Comment by mypil** [comment]
@junecastillote - we would like to follow up on this. May we know which Microsoft document link you used in reference to this issue? Please share it with us so we can make the necessary changes to improve the MS document for accuracy.

**Comment by mypil** [comment]
@junecastillote - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
