### ISSUE TITLE
What is other activity???

### ISSUE THREAD

**Issue by raymondhahs** [MicrosoftDocs/OfficeDocs-O365ITPro#211]
hi, what is other activity in the teams report???  my channel message, chat messge, calls and meetings are only 200, but other activity are up to 800... how do i know what are the other activity about?  TQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a013cc2d-f495-9c68-002a-be7e861bfcdc
* Version Independent ID: 7b153b00-b9e4-f251-8391-0ba4d392af35
* Content: [Office 365 Reports in the Admin Center - Microsoft Teams user activity](https://docs.microsoft.com/en-us/office365/admin/activity-reports/microsoft-teams-user-activity?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Reports-in-the-Admin-Center-Microsoft-Teams-user-activity-07f67fc4-c0a4-4d3f-ad20-f40c7f6db524&view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/microsoft-teams-user-activity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/microsoft-teams-user-activity.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@raymondhahs - Thank you for engaging with the community here for the docs.

The **Other activity** is the number of other team activities by the user some of which include, and not limited to: liking messages, apps, working on files, searching, following teams and channel and favoriting them.

Please check on this MS article link for more details - https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports#other-information-on-the-reports-dashboard

**Comment by mypil** [comment]
@raymondhahs - Have we answered your query about the "Other Activity"?

**Comment by mypil** [comment]
@raymondhahs - We hope that your query has been answered.  If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
