### ISSUE TITLE
Contact Number for Philippines Mobile Phones

### ISSUE THREAD

**Issue by bensonrlee** [MicrosoftDocs/OfficeDocs-O365ITPro#213]
Is there a contact number that can be called from mobile phones in the Philippines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f68f42-3e1e-f119-c15b-83e788997eae
* Version Independent ID: 0bf16d91-f0a3-96e4-8ddf-4ef00e613c7a
* Content: [Support information for Philippines](https://docs.microsoft.com/en-us/office365/admin/support/philippines?view=o365-worldwide)
* Content Source: [Office365-Admin/support/philippines.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/philippines.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by lindspea** [comment]
@AndreaBarr @scanum please assign to me

**Comment by lindspea** [comment]
@bensonrlee I have found a number for the Philippines. Please let me know if it works and I will have it added to the document. Phone: (63 2) 860 8989. Thank you for your valuable contribution in helping improve MS docs.

**Comment by bensonrlee** [comment]
Hi @lindspea, I called the number to try it and it does not sound like from Office 365 at all.  

The greeting simply said: "Welcome to Microsoft Philippines, please stay on the line and an operator will be right with you".

After a brief hold on queue, the call gets terminated without being connected to an operator at all.

**Comment by lindspea** [comment]
Thanks @bensonrlee. I will investigate further and let you know.  Thanks again for your contribution.

**Comment by cmcatee-MSFT** [comment]
Hi @bensonrlee. The #s published above are the only support #s we have for the Philippines. If you're unable to call either of those #s, please use the Need help? button in the admin center to open a support request, and one of our agents can either email or call you back.
