### ISSUE TITLE
Learn more section issues

### ISSUE THREAD

**Issue by Jimnar** [MicrosoftDocs/OfficeDocs-O365ITPro#214]
The Office 365 public roadmap was renamed the Microsoft 365 public roadmap. Also, I think the message center link might be wrong, or it might require permissions to access the center within Office 365. You might want to note that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046ce912-1f0f-81b9-1126-5558e93df52a
* Version Independent ID: 755e811c-2aa0-9dc5-6846-93a6c401b01e
* Content: [Set up the Standard or Targeted release options in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/release-options-in-office-365?redirectSourcePath=%252fen-us%252farticle%252fset-up-the-standard-or-targeted-release-options-in-office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47&view=o365-worldwide)
* Content Source: [Office365-Admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by nenonix** [comment]
@Jimnar Thank you for pointing this out. We will post back here when the issue has been addressed.

**Comment by Sirkkuw** [comment]
@mypil yes - the roadmap has been renamed to Microsoft 365 public roadmap and the message center link is incorrect - it is now:
https://admin.microsoft.com/Adminportal/Home?source=applauncher#/MessageCenter

**Comment by mypil** [comment]
@Jimnar - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
