### ISSUE TITLE
There are two contrary statements

### ISSUE THREAD

**Issue by AndreasZinic** [MicrosoftDocs/OfficeDocs-O365ITPro#215]
First One here:
"If you only remove a user's license but don't delete the account, the content in the user's OneDrive will remain accessible to you even after 30 days."
 
Second One:
"When you remove the license, all that user's data is held for 30 days. You can access the data, or restore the account if the user comes back. After 30 days, all the user's data (except for documents stored on SharePoint Online) is deleted permanently from Office 365 and can't be recovered."
 
Link to first one:
https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide  10/26/2018
 
Link to second One:
https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide#remove-and-delete-the-office-365-license-from-a-former-employee  12/03/2018

Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by lindspea** [comment]
@AndreasZinic Thank you for reaching out and helping improve MS docs.  I will investigate further and revert soonest.

**Comment by lindspea** [comment]
@AndreasZinic Just to clarify, if you already deleted the account, you have 30 days to restore it. At that point, the data will be available to you even after 30 days. ("At that point" refers to the day that you restored it) So, if an account has been deleted, if you restore it, the data will be available to you even after 30 days. If you remove the user's license only, not the account, the content will still be available to you after 30 days as well. Hope this answers your question.  Please let me know if you have any further questions.
​
​
​

**Comment by AndreasZinic** [comment]
@lindspea We need to be very specific here. Which kind of data is removed when by what action.
We have the following data:
1. Exchange
2. OneDrive
3, SharePoint
4. Flow
5. PowerApps

Are you really sure about removing license, as I know from last year that removing a License will delete the mailbox of a user and his OneDrive after 30 Days permanently. Removing a license triggers a delete period.

What about Flow Flows and PowerApps? Will they continue to run? Will they be deleted when a) a license is removed b) b) account is deleted?

I am still confused what data you are referring to, as the only thing that really will prevail is data on SharePoint Online, according to my knowledge, despite having a license removed or account deleted.

**Comment by lindspea** [comment]
@get-itips can you please assist here?

**Comment by mypil** [comment]
@AndreasZinic - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

 
**NOTE:**  We used to use this link to a video explaining how to open a support ticket. 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
