### ISSUE TITLE
Applicable Services

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#220]
Which services and applications are accessible through Lockbox? which ones are not? Please add this to the documentation

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39baa10f-a0eb-7a34-ccab-2c5fa86d0c3a
* Version Independent ID: e5358a65-c3cf-36b3-0e09-71f569f1e5bc
* Content: [Office 365 Customer Lockbox Requests](https://docs.microsoft.com/en-au/office365/admin/manage/customer-lockbox-requests?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
The only services that  Customer Lockbox works with are Exchange Online, SharePoint Online, and OneDrive for Business. I can now see it updated in the document.

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
