### ISSUE TITLE
Missing steps

### ISSUE THREAD

**Issue by piersrr** [MicrosoftDocs/OfficeDocs-O365ITPro#222]
"You can take steps while you add the domain to keep its website hosted where the site is hosted"

What steps where??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 922a82b5-470a-553b-2bc0-292140ec82b7
* Version Independent ID: e27c707b-0693-86fc-fa2a-b417b0633c05
* Content: [Change nameservers to set up Office 365 with any domain registrar](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide)
* Content Source: [Office365-Admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
Created PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/245

**Comment by mypil** [comment]
@piersrr - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
