### ISSUE TITLE
This Documentation is incorrect - Can you please update!

### ISSUE THREAD

**Issue by DerekGreen** [MicrosoftDocs/OfficeDocs-O365ITPro#224]
*** This Documentation is incorrect - Can you please update ***

I have been trying and failing to change the EmailAddress Alias on an O365 group using the following command (as in this webpage from 26/10/2018)
   Set-UnifiedGroup -Identity "Group name" -Alias @{remove="alias@contoso.com"}

I then spent a couple of hours with MS Support over the last few days, trying to resolve this issue... they've just got back to me saying that the correct command to use is:
   Set-UnifiedGroup -Identity "Group name" -EmailAddresses @{remove="alias@domain.com"}

Now that I come back to this article I see that there are some comments in the Feedback section, which talk about this exact problem, with SRavenscroft giving the solution.

If only I'd see this comment, I could have saved myself a lot of time stuck on the phone trying commands that didn't work.

** As a matter of urgency, can someone with the ability to edit this webpage, please update it with the correct command. **

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8792555-ecc1-9c9e-1d7a-e0b3b1b0b2b7
* Version Independent ID: 442f4470-d54b-b4c0-f0f1-9f35b7017dc1
* Content: [Troubleshoot Remove an alias from a group](https://docs.microsoft.com/en-us/office365/admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group?view=o365-worldwide)
* Content Source: [Office365-Admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group.md)
* Service: **o365-administration**
* GitHub Login: @anfowler
* Microsoft Alias: **anfowler**

**Comment by lindspea** [comment]
@AndreaBarr @scanum please assign to me.

**Comment by lindspea** [comment]
Hi @DerekGreen. Thank you for pointing this out and for your valuable contribution in helping to improve MS docs.  I will have this updated as soon as possible.

**Comment by lindspea** [comment]
@AndreaBarr  @mypil  This issue can be closed.
