### ISSUE TITLE
Spelling TYPO

### ISSUE THREAD

**Issue by Rkendall75** [MicrosoftDocs/OfficeDocs-O365ITPro#226]
The Versions view shows you the number of unique users for each version of Outlook in Wondows.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 535888ea-6011-1467-bf9a-1de66cb8c402
* Version Independent ID: d72f6ddc-15a0-5398-251e-92496afdf309
* Content: [Office 365 Reports in the Admin Center - Email apps usage](https://docs.microsoft.com/en-us/office365/admin/activity-reports/email-apps-usage?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/email-apps-usage.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/email-apps-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by scanum** [comment]
A PR has been made https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/230

**Comment by kenwith** [comment]
Merged!
