### ISSUE TITLE
Where's the English support? 

### ISSUE THREAD

**Issue by Barbara232** [MicrosoftDocs/OfficeDocs-O365ITPro#228]
I called 0120 628 860 for help with short-term account deactivations. The recorded message is only in Japanese and when I was able to speak with a person, she acted like English support was not available.  I've been on hold now for 5 minutes, while she scrambles (I'm presuming here) to find someone who speaks English.  Oh dear, now I see where I've gone wrong.  You only have English language support for Office 365 Enterprise accounts, for which you have a separate number. Jeez, I guess my company is not big enough for you to help . . .  Well, you can help yourselves on this page by separating all the O365Enterprise info from the rest of it.  Why make me go back and forth and try to figure it out? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f24de2f-6764-d9ec-fca5-34e63fe509e5
* Version Independent ID: ee4f842d-8783-11b7-56df-03635a131123
* Content: [Support information for Japan](https://docs.microsoft.com/en-us/office365/admin/support/japan?view=o365-worldwide)
* Content Source: [Office365-Admin/support/japan.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/japan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@Barbara232 - thank you for submitting feedback.

Please check on this [link](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?redirectSourcePath=%252fen-us%252farticle%252fContact-support-for-business-products-Admin-Help-32a17ca7-6fa0-4870-8a8d-e25ba4ccfd4b&view=o365-worldwide&tabs=phone) for the support phone number based on the country you select (English support is also found here).

However, if you will still encounter issues while calling for support, I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
