### ISSUE TITLE
Characters are visible instead of .png

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#229]
Characters are visible instead of .png(../media/455b84df-defb-4da6-92f7-0ca21cc8d930.png)

https://docs.microsoft.com/ja-jp/yammer/troubleshoot-problems/limited-functionality-in-explorer-10-document-mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 772c688b-607c-8812-a8d8-13026750156b
* Version Independent ID: 0a85eaa3-bd33-2deb-ccb3-cba9934e5aee
* Content: [Limited functionality in Yammer in Internet Explorer 10 document mode](https://docs.microsoft.com/en-us/yammer/troubleshoot-problems/limited-functionality-in-explorer-10-document-mode)
* Content Source: [yammer/troubleshoot-problems/limited-functionality-in-explorer-10-document-mode.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/troubleshoot-problems/limited-functionality-in-explorer-10-document-mode.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@samanthaw

**Comment by samanthaw** [comment]
@MollyMalone

**Comment by MollyMalone** [comment]
@hyoshioka0128 the image is now displaying ok in the Japanese topic.  Thanks again for reporting it.

**Comment by mypil** [comment]
@AndreaBarr - I believe this issue can be closed. Thank you.
