### ISSUE TITLE
Emails sent to distribution list not being received by all recipients

### ISSUE THREAD

**Issue by carlosmiguelsns** [MicrosoftDocs/OfficeDocs-O365ITPro#232]
We are having a problem where when emails are sent to a distribution list (e.g. distList@company.com), not all members of that distribution list are receiving the emails. It occurring on one particular dist list. I confirmed that certain users didn't receive certain emails. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45747a24-bff0-b8ab-23e7-9c6c7ae49446
* Version Independent ID: 52adc2ce-30ca-f5b2-d58d-bcd40732cc6b
* Content: [Troubleshooting distribution list issues](https://docs.microsoft.com/en-us/office365/admin/troubleshoot-issues-for-admins/distribution-list-issues?view=o365-worldwide)
* Content Source: [Office365-Admin/troubleshoot-issues-for-admins/distribution-list-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/troubleshoot-issues-for-admins/distribution-list-issues.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by D1872375545** [comment]
Is it dynamic distribution group? if so ,you can refer to the link:
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking

O365's DBEB features prevent external users from sending mail to dynamic distribution group within an organization

**Comment by mypil** [comment]
@carlosmiguelsns - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
