### ISSUE TITLE
Showing &#39; HTML code of single quote character

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#239]
What& #39; s の新しい → 新着情報

https://docs.microsoft.com/ja-jp/yammer/yammer-landing-page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701c4134-00e1-34c7-e7d0-75f521733c9a
* Version Independent ID: 8233cbcd-59ee-a3e1-f3c1-07ae522bef21
* Content: [Yammer admin key concepts](https://docs.microsoft.com/en-us/yammer/get-started-with-yammer/admin-key-concepts)
* Content Source: [yammer/get-started-with-yammer/admin-key-concepts.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/get-started-with-yammer/admin-key-concepts.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
@hyoshioka0128 Great bug, thanks for reporting.  I see the same issue for all languages, not just Japanese.   I shared with the localization vendors and they will fix it soon.

**Comment by OfficeGSX** [comment]
The article was previously MachineTranslated, we changed it to HumanTranslation to fix the issue. Topic was updated and published live.

Best Regards,
Michal
