### ISSUE TITLE
MFA in combination with Conditional Access

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/OfficeDocs-O365ITPro#243]
Please provide some more information about what to configure at the MFA side when using MFA from Conditional Access policies. Which settings must be set/or not be set in order to get this working properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by j0rt3g4** [comment]
Solved at pull [#242](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/242)

**Comment by mypil** [comment]
@kennethvs - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
