### ISSUE TITLE
Correction to 'Customer Lockbox Requests' location

### ISSUE THREAD

**Issue by veronicageek** [MicrosoftDocs/OfficeDocs-O365ITPro#244]
Hi,

The ```Customer LockBox Requests``` are located under _**Support >> Customer LockBox Requests**_.
Not anymore under _Settings > Support > Service requests_.

![image](https://user-images.githubusercontent.com/25181757/52288552-56b9db00-2964-11e9-9db4-f72db1315ebe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39baa10f-a0eb-7a34-ccab-2c5fa86d0c3a
* Version Independent ID: e5358a65-c3cf-36b3-0e09-71f569f1e5bc
* Content: [Office 365 Customer Lockbox Requests](https://docs.microsoft.com/en-us/office365/admin/manage/customer-lockbox-requests?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by j0rt3g4** [comment]
Solving in pull [#242](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/242)

**Comment by mypil** [comment]
@veronicageek - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
