### ISSUE TITLE
Step 2 8b incorrect

### ISSUE THREAD

**Issue by allenmock** [MicrosoftDocs/OfficeDocs-O365ITPro#248]
Step 2 8b says "red rectangles above".

the image is below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32446a8e-a16c-8017-290e-d414e6d9a242
* Version Independent ID: e4f45a16-0deb-2eb4-eca2-31bec804dc51
* Content: [Create a knowledge-based commnity in Yammer by using QnA Maker and Flow](https://docs.microsoft.com/en-us/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker#step-7-replace-the-sample-content-with-your-own)
* Content Source: [yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@allenmock - Thank you for pointing this out.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@allenmock - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
