### ISSUE TITLE
No support for Modern Auth

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/OfficeDocs-O365ITPro#249]
All of our Global Admins have MFA turned on. This script is useless for us without MFA support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0659185-aece-2fa7-0e9d-fe56c771d8f9
* Version Independent ID: b5f0658e-d859-ad4d-7d1f-33a753fbd6c9
* Content: [Determine if Centralized Deployment of add-ins works for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@cmcapellan - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the Office 365 better. They keep a close tab on User Voice **https://office365.uservoice.com** and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
