### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by nplima** [MicrosoftDocs/OfficeDocs-O365ITPro#25]
well... why the limited regional availability? Why so many chat applications int he Office 365 world?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2033900c-d18a-cdd3-313c-7efed2ceb4ec
* Version Independent ID: 87b1f4a4-abb8-f3f6-241e-ca8b9b3d5015
* Content: [Kaizala regional availability](https://docs.microsoft.com/en-gb/office365/kaizala/regional-availability)
* Content Source: [Office365-Kaizala/regional-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/regional-availability.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by AndreaBarr** [comment]
@nplima Thank you for this feedback. 

I am not sure how to answers these questions but Support will be able to answer them. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
