### ISSUE TITLE
Azure AD Organizational Unit as User Criteria for Microsoft 365 Usage Analytics with Power BI

### ISSUE THREAD

**Issue by natebd** [MicrosoftDocs/OfficeDocs-O365ITPro#258]
It would be amazing if Azure AD had an Organizational Unit as User State Table Data for Microsoft 365 Usage Analytics with Power BI.
We are large company and generally manage a lot of non Office 365 reporting Data against our On-Prem AD OU Structure.  So far the Microsoft 365 analytics only let me filter reports with state, country, office.  Being able to somehow link our OnPrem OU properties to Azure AD Users would be tremendous for our reporting needs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fdd664-c2d2-7712-fd41-3745c52d1442
* Version Independent ID: 0dfdadc8-15f0-dd7e-0efc-9a2565f7b519
* Content: [Customize the reports in Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/customize-reports?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/customize-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/customize-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@natebd - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the Office 365 better. They keep a close tab on User Voice **https://office365.uservoice.com** and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!
