### ISSUE TITLE
"電源 BI","電源双" needs to be replaced with "Power BI" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#260]
https://docs.microsoft.com/ja-jp/office365/kaizala/content-pack
Same as #254

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec87f28-ba9a-63b8-3543-d82ff6b44a51
* Version Independent ID: 0e7558d4-ac8a-be96-f6c2-5b8b7ea4316d
* Content: [Kaizala content pack](https://docs.microsoft.com/en-us/office365/kaizala/content-pack)
* Content Source: [Office365-Kaizala/content-pack.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/content-pack.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting this feedback.

I will get this over to @samanthaw @MollyMalone   for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by MollyMalone** [comment]
@hyoshioka0128 Thank you for reporting this issue.   However we will not fix the over-translation of Power BI at this time.   It is a known issue that some of our Product names (including Power BI) are being unnecessarily translated by the machine translation tool.   We are investigating a tool solution to fix these issues.   At this time we can not fix each issue individually.
