### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by hpfaff88** [MicrosoftDocs/OfficeDocs-O365ITPro#266]
I have my flow and qna maker set up correctly and it was working. It has since stopped responding. You ask a question in Yammer and it doesn't give an answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32446a8e-a16c-8017-290e-d414e6d9a242
* Version Independent ID: e4f45a16-0deb-2eb4-eca2-31bec804dc51
* Content: [Create a knowledge-based commnity in Yammer by using QnA Maker and Flow](https://docs.microsoft.com/en-us/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker)
* Content Source: [yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@hpfaff88  - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**NOTE:**  We used to use this link to a video explaining how to open a support ticket. 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
