### ISSUE TITLE
out-of-date?

### ISSUE THREAD

**Issue by iwillneverjoin** [MicrosoftDocs/OfficeDocs-O365ITPro#267]
The link to "domains page" https://go.microsoft.com/fwlink/p/?linkid=834818 tells me that This feature is provided by your partner. and gives a link to godaddy -- which goes to email alias page and has nothing to do with adding a domain.  I've done this before in the past but something has changed, can't find where to do this in godaddy now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf4bb58c-d6e6-2cd8-2e0a-13b7eabfebc7
* Version Independent ID: fa15ca5c-66f9-62ec-1d2b-0f8020b0827a
* Content: [Add a domain to Office 365](https://docs.microsoft.com/en-us/office365/admin/setup/add-domain?view=o365-worldwide)
* Content Source: [Office365-Admin/setup/add-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/add-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@iwillneverjoin - Thank you for submitting this feedback.

Here is the link on how you can Create DNS records at GoDaddy for Office 365 - **https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-godaddy?view=o365-worldwide**

Kindly try this and let me know if it works.

**Comment by smartwombat** [comment]
The instructions at step 6 for 123REG say to set the MX priority to 0.
This is wrong.
On that page the "step-by-step instructions" link goes to a page that has the correct value of 1 for priority.

**Comment by mypil** [comment]
@smartwombat - Thank you for submitting feedback. 

Can you share which specific article you are referring to? Can you please share the MS article link so we can check?

Thank you.

**Comment by mypil** [comment]
@iwillneverjoin & @smartwombat - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
