### ISSUE TITLE
enterpriseenrollment.manage.microsoft.com

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-O365ITPro#268]
Is now (note the "-s"):
enterpriseenrollment-s.manage.microsoft.com

As shown here:
https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-using-windows-based-dns?view=o365-worldwide#add-cname-records

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaff890-3858-eacb-ed21-a7c0dc4d3d36
* Version Independent ID: 087f92d5-6ace-4a32-4252-c94b843de607
* Content: [Create DNS records at Cloudflare for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-cloudflare?redirectSourcePath=%252fen-US%252farticle%252fCreate-DNS-records-at-Cloudflare-for-Office-365-84acd4fc-6eec-4d00-8bed-568f036ae2af&view=o365-worldwide#add-the-six-cname-records-that-are-required-for-office-365)
* Content Source: [Office365-Admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@rpodric - Thank you for pointing this out.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@rpodric - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
