### ISSUE TITLE
This solution is not working for me.

### ISSUE THREAD

**Issue by Artocol** [MicrosoftDocs/OfficeDocs-O365ITPro#269]
I tried creating a new Planner with a user that was not added to the security group, and there was nothing stopping him at all from doing that.
I checked the "GroupCreationAllowedGroupId" that the script outputs, and it's the correct group.
Also the "EnableGroupCreation" flag was correctly set to "False".

How long could it take for these changes to take effect?

Thanks in advance for the help.

**Comment by mypil** [comment]
@Artocol - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

 
**NOTE:**  We used to use this link to a video explaining how to open a support ticket. 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
