### ISSUE TITLE
Convert to shared does not get rid of password - account can still be logged in to

### ISSUE THREAD

**Issue by Toasty66** [MicrosoftDocs/OfficeDocs-O365ITPro#270]
We've discovered that mailboxes converted to a shared mailbox still allow the original user/pass to gain access to the account, at a minimum, for SMTP relay. This is even when the license has been removed after being converted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by j0rt3g4** [comment]
I've checked this on the field, and actually it works.
the old user can log in using the regular credentials and is even being used to avoid to get licenses for some customers.

**Comment by mypil** [comment]
@Toasty66 - Thank you for submitting feedback. It seems you are asking to open a service ticket or have a question about support. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

 
**NOTE:**  We used to use this link to a video explaining how to open a support ticket. 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
