### ISSUE TITLE
Microsoft Office 365 hotline

### ISSUE THREAD

**Issue by makoicriador** [MicrosoftDocs/OfficeDocs-O365ITPro#277]
i have been calling for weeks, no one is answering the hotline. i need support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f68f42-3e1e-f119-c15b-83e788997eae
* Version Independent ID: 0bf16d91-f0a3-96e4-8ddf-4ef00e613c7a
* Content: [Support information for Philippines](https://docs.microsoft.com/en-us/office365/admin/support/philippines?view=o365-worldwide)
* Content Source: [Office365-Admin/support/philippines.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/philippines.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@makoicriador - Thank you for submitting feedback.  

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

 
**NOTE**:  We used to use this link to a video explaining how to open a support ticket. 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by mypil** [comment]
@cmcatee-MSFT @kenwith @AndreaBarr - FYI.

**Comment by makoicriador** [comment]
Thank you for your response.

I appreciate the links and instructions you have given, unfortunately, my
issue is a bit different.

The Office365 account is from a previous partner, and said account is being
billed monthly on my personal credit card. Right now, i am unable to
contact her in any way possible for her to cancel her subscription, and I
have been paying for it for almost a year now.

What I need right now is for my credit card to be unbound from her
Office365 account, nevermind the balance, I will pay for it, as long as it
doesn't bill anymore on the next cycle.

Ultimately, I need my credit card to be cut, and I cannot do that unless
all monthly subscriptions being billed there will be removed.

I hope you can help me with this, I have been struggling to contact
Microsoft hotline for more than three months now.

Thank you.

**Comment by mypil** [comment]
@makoicriador - thank you for providing this additional feedback. We have already informed the relevant team to investigate on the Philippines phone support hotline issue and they are still working on it. With regards to your other issue, I am checking with some people that could help to address your concern.

@cmcatee-MSFT @kenwith

**Comment by makoicriador** [comment]
It was recently brought up in a call with an agent that since I am unable
to unbound the Microsoft subscription, I can just call again and have it
blocked, given that I settle the remaining balance.

Can you confirm this? If so, please elaborate the process so I may
immediately act on this.

Thank you.

**Comment by RussellReadMSFT** [comment]
Hi @makoicriador,

My name is Russell and I'm part of the Microsoft support organization. While I can't answer your question from the information here, I'll try to get the right folks engaged to get this resolved for you. Additionally, I'd like to understand more about the challenge you've had with our phone number.

Can you send an e-mail to russell.read@microsoft.com and I'll respond to get the information we need to move forward.

-thanks, Russell.

**Comment by mypil** [comment]
@makoicriador - Kindly work with Russell to help resolve your concern. We will proceed to close this issue.  

Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
