### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ulflunqvist** [MicrosoftDocs/OfficeDocs-O365ITPro#28]
The Office 365 Roadmap link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fb833c2-bcef-be1a-30da-b69070db3aa3
* Version Independent ID: 78609177-69be-486e-b3c0-0325cdca2d3f
* Content: [Compare options for a free trial of Yammer](https://docs.microsoft.com/en-us/yammer/get-started-with-yammer/compare-options-for-a-free-trial)
* Content Source: [yammer/get-started-with-yammer/compare-options-for-a-free-trial.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/get-started-with-yammer/compare-options-for-a-free-trial.md)
* Service: **o365-administration**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by IrenePasternack** [comment]
I tested the link in the last line of the file, and it goes to the roadmap. Could you try again and let me know if it works?

Thanks,
Irene
