### ISSUE TITLE
Step 2 

### ISSUE THREAD

**Issue by irean** [MicrosoftDocs/OfficeDocs-O365ITPro#284]
Is this  example valid now? I was thinking about the GDPR and this feels like a violation against that law

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6024c6e-1373-58de-ca8b-819a11693968
* Version Independent ID: 5d02bdc8-6e20-8b9b-942e-cca0e312cc5e
* Content: [Remove a former employee from Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@irean - Thank you for submitting this feedback.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@kwekuako - We need your insights on this issue. Thank you.

**Comment by mypil** [comment]
@irean - Is it just Step 2 on this article that you want clarification on? Or is there another section that you want more information on?

**Comment by mypil** [comment]
@irean - I would like to follow up and get more details from you. Is it just Step 2 on this article that you want clarification on? Or is there another section that you want more information on?

Thank you.

**Comment by kenwith** [comment]
@irean - thank you for the feedback and surfacing this so we can investigate. Sorry for the long delay. We brought the documentation to the legal team at Microsoft and received the following:

"Our documentation accurately describes technical steps for administrators to disable access to organizational accounts when an employee leaves the organization. You should consult your own legal or privacy team to help ensure your processes comply with GDPR, as Microsoft cannot offer this sort of advice."

There was a lot more info received back from legal but that is the quote they gave publicly. My take on it is that every organization is different and how they comply with GDPR can be unique for each organization. Meaning that some organizations might not allow company email addresses to be used for personal use, etc...   I am not a lawyer and just giving my take on the above quote and the issue you raised. :)  Going to close this out as the documentation is correct.
