### ISSUE TITLE
Typo in text

### ISSUE THREAD

**Issue by gustav87** [MicrosoftDocs/OfficeDocs-O365ITPro#285]
Under the topic "How do I check which DLs are eligible for upgrade?", there's a typo.

It says the following:

"If you want to check which DLs are eligible for upgrade just run the following command:

Get-EligibleDistributionGroup"

However, this input produces an error. The complete command is Get-EligibleDistributionGroupForMigration.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 10dbb56e-1c52-8fa0-0d3d-bab6d50519d0
* Version Independent ID: ff6585cd-9d68-ed1c-ee5f-1f451457dbef
* Content: [Uppgradera distributionslistor till Office 365-grupper i Outlook](https://docs.microsoft.com/sv-se/office365/admin/manage/upgrade-distribution-lists?redirectSourcePath=%252fen-us%252farticle%252fupgrade-distribution-lists-to-office-365-groups-in-outlook-787d7a75-e201-46f3-a242-f698162ff09f&view=o365-worldwide)
* Content Source: [Office365-Admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by lindspea** [comment]
@mypil @andrea please assign to me.

**Comment by lindspea** [comment]
@gustav87 Thank you for pointing this out and helping improve MS docs.  I'll have it corrected asap.  Thanks.

**Comment by nenonix** [comment]
@gustav87  Thank you for taking time to help us improve the content in Microsoft Docs,  The change you suggest will be made.

**Comment by nenonix** [comment]
@AndreaBarr please close

**Comment by gustav87** [comment]
There's an identical typo in the paragraph just above the one I reported. The text now says:

How do I check which DLs are eligible for upgrade?
If you want to check whether a DL is eligible or not, you can run the below command:

Get-DistributionGroup \<DL SMTP address\> | **Get-EligibleDistributionGroup**

If you want to check which DLs are eligible for upgrade just run the following command:

Get-EligibleDistributionGroupForMigration

**Comment by mypil** [comment]
@gustav87 - thanks for pointing this out. @nenonix - please assist to check and make the necessary changes on this. Thank you.

**Comment by nenonix** [comment]
@gustav87 thanks, us writers appreciate precise instructions (and we know not to mess with the code ;)

**Comment by mypil** [comment]
@gustav87 - the content has been updated to correct the identical typo that you pointed out. Kindly check and let us know if your issue has been resolved. Thanks.
