### ISSUE TITLE
Grammer in the Tip section.

### ISSUE THREAD

**Issue by AndyConlisk** [MicrosoftDocs/OfficeDocs-O365ITPro#286]
In the Tip section (green colored section titled Tip)

It starts "Check the out the steps in" I think there is an extra "the" and would make more sense if it was "Check out the steps in"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784a196f-3e0e-0c0a-0b2f-af2105a774d9
* Version Independent ID: 08300f82-3b1d-b96d-bf10-e401ac6ef2c0
* Content: [Allow members to send as or send on behalf of a Group](https://docs.microsoft.com/en-us/office365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by nenonix** [comment]
@AndyConlisk  Thank you for pointing this out. We appreciate you taking the time to help us improve the content.  The change will be made and once merged, this issue will be closed. Thanks again.

**Comment by nenonix** [comment]
@AndreaBarr  please close
