### ISSUE TITLE
Restrict Action items

### ISSUE THREAD

**Issue by toniHunter** [MicrosoftDocs/OfficeDocs-O365ITPro#289]
Hi 
I would like to be able to show only those actions which are applicable to those who are simply members of the group.  For example I have created an action which allows them to sign in and out of a client site, add notes and photos in the event of an issue and for their location to be recorded.  This is the only one I want them to use, also it would be great if I could create their schedule , i.e. 09:00 Attend Mary Smith for 30 minutes, 10:00 Attend Fred Jones for 45 minutes, 11:00 Attend Peter Smith for 60 minutes and send as a batch to a user, so they could respond accordingly.  Alternatively being able to do the same using the Job Action (although I would like to add location data to that default action).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c35b6c9-aef0-9190-3c70-f1f7d4638b6c
* Version Independent ID: 5405815c-220a-1c69-5552-60e3d71ebde4
* Content: [Kaizala management portal](https://docs.microsoft.com/en-gb/office365/kaizala/kaizala-management-portal?redirectSourcePath=%252farticle%252fAbout-Kaizala-Management-Portal-2046ddba-06fb-49c9-b6d6-a4777e8a556f#feedback)
* Content Source: [Office365-Kaizala/kaizala-management-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/kaizala-management-portal.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@toniHunter - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the Office 365 better. They keep a close tab on User Voice **https://office365.uservoice.com** and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
