### ISSUE TITLE
Cannot change the notification tone

### ISSUE THREAD

**Issue by CarikeBL** [MicrosoftDocs/OfficeDocs-O365ITPro#29]
It would be great to be able to change the notification tone for the app instead of using the default. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2033900c-d18a-cdd3-313c-7efed2ceb4ec
* Version Independent ID: 87b1f4a4-abb8-f3f6-241e-ca8b9b3d5015
* Content: [Kaizala regional availability](https://docs.microsoft.com/en-za/office365/kaizala/regional-availability?redirectSourcePath=%252farticle%252fkaizala-regional-availability-d0a029fa-5ba1-400e-be9f-909befdef2f4)
* Content Source: [Office365-Kaizala/regional-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/regional-availability.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by AndreaBarr** [comment]
@CarikeBL Thank you for this suggestion. 

I know the product teams are always looking for user feedback and how to make software  better. They keep a close tab on the Kaizala app [kaizalafeedback@microsoft.com](kaizalafeedback@microsoft.com).
 
Thank you for your contribution to make the docs better! Much appreciated!
