### ISSUE TITLE
Yammer connection error

### ISSUE THREAD

**Issue by Laskewitz** [MicrosoftDocs/OfficeDocs-O365ITPro#290]
Hi,

When I try to authenticate the Yammer connector I get the following error:
OAuth2 authorization flow failed for service 'Yammer'. OAuth 2 sign in failed to exchange code for access token. Client ID and secret sent in form body.. Response status code=Forbidden. Response body: Your network is not allowed to request an OAuth token for this Application Client ID and secret sent in Basic authorization header.. Response status code=NotFound. Response body: invalid client application

And yes, I have 3rd party apps allowed in the network settings...

Can you please help? I see multiple people having the same issue.

Thanks,
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32446a8e-a16c-8017-290e-d414e6d9a242
* Version Independent ID: e4f45a16-0deb-2eb4-eca2-31bec804dc51
* Content: [Create a knowledge-based commnity in Yammer by using QnA Maker and Flow](https://docs.microsoft.com/en-us/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker)
* Content Source: [yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by Larryngolog** [comment]
I have the same issue

**Comment by Larryngolog** [comment]
Hi mypil. I have created support ticket and will update you with the findings. Cheers!

**Comment by Larryngolog** [comment]
Hi! Looks like the issue was resolved on MS Backend and it's working again.
