### ISSUE TITLE
Inconsistancy with documenation

### ISSUE THREAD

**Issue by Insidii** [MicrosoftDocs/OfficeDocs-O365ITPro#291]
The documentation still shows the 1GB increase purchase blocks, in SPO the increase size was changed at some point last year see below link, not sure if this applies to all product groups.  
https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94e36d7b-9d38-d71f-e64e-938e7cdf860a
* Version Independent ID: 770a6dc2-7af2-3a66-f580-98ebff5bc5c4
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-au/office365/admin/subscriptions-and-billing/add-storage-space?redirectSourcePath=%252farticle%252f96EA3533-DE64-4B01-839A-C560875A662C&view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/add-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@Insidii - Thank you for pointing this out.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@Insidii Thank you for your feedback on documentation. As per the referred documents, all SPO have 1TB of storage available per company. Can you please confirm if you also have 1TB of storage with your tenant?

**Comment by mypil** [comment]
@Insidii - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
