### ISSUE TITLE
How to revert settings to original state?

### ISSUE THREAD

**Issue by urbi129** [MicrosoftDocs/OfficeDocs-O365ITPro#292]
Once above solution will be implemented - how to undo those changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by urbi129** [comment]
If you want to turn off the group creation restriction and again allow all users to create groups, set $GroupName to "" and $AllowGroupCreation to "True" and rerun the script.
Can be closed....

**Comment by mypil** [comment]
@urbi129 - Thank you for submitting feedback. From the last comment you provided, it appears that the issue has been resolved. Can you please share what specific issue you have with this article? 
I would really appreciate if you are able to help me by providing more details as to what should be edited and/or included. Thank you.

**Comment by mypil** [comment]
@urbi129 - I would like to follow up on this. From the last comment you provided, it appears that the issue has been resolved. Can you please share what specific issue you have with this article?
I would really appreciate if you are able to help me by providing more details as to what should be edited and/or included. Thank you.

**Comment by mypil** [comment]
@urbi129 - We appreciate any feedback you can provide to make the content in the Microsoft docs better. Since we did not get any response from you, we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
