### ISSUE TITLE
No explicit information regarding service changes

### ISSUE THREAD

**Issue by dbowling** [MicrosoftDocs/OfficeDocs-O365ITPro#298]
This document should explicitly state if all account information is maintained (including OneDrive data, Skype, OneNote, etc.) without disrupting users when taking over a shadow tenant. 

If there are disrupting events, it should include details on those or link out to another supporting article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24eaf551-7e49-ee4a-2979-8515f92d4d2a
* Version Independent ID: 67e53343-d996-ce5e-4742-0c0d819fbca1
* Content: [Do an admin takeover in Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/become-the-admin?view=o365-worldwide)
* Content Source: [Office365-Admin/misc/become-the-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/become-the-admin.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@dbowling - Thank you for pointing this out.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@dbowling All account information will be maintained and nothing will be deleted or modified.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by albso** [comment]
I'm trying to follow the steps here but when I clicked the link in the email, and when the portal opens up, it says that I don't have permission to access. And I did not receive any "Become the admin..." wizard window. Any option on how to take ownership of the domain?
