### ISSUE TITLE
When will be available for ios? 

### ISSUE THREAD

**Issue by alexiordan** [MicrosoftDocs/OfficeDocs-O365ITPro#3]
What is the road map for Kaizala Web app? When will it support ios? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6ac125-809c-25c8-520d-c899d7c0f5f4
* Version Independent ID: 328117c5-6159-589e-eca4-1bc3dc7ee0f5
* Content: [Use the Kaizala web app](https://docs.microsoft.com/en-us/office365/kaizala/use-the-web-app)
* Content Source: [Office365-Kaizala/use-the-web-app.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/use-the-web-app.md)
* Service: **kaizalams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by AndreaBarr** [comment]
@alexiordan Thank you for this feedback

I want to get this question answered for you quickly. Support will handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
