### ISSUE TITLE
Export does not appear

### ISSUE THREAD

**Issue by justjeff2018** [MicrosoftDocs/OfficeDocs-O365ITPro#300]
In Teams console, on report, Export button is not present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a013cc2d-f495-9c68-002a-be7e861bfcdc
* Version Independent ID: 7b153b00-b9e4-f251-8391-0ba4d392af35
* Content: [Office 365 Reports in the Admin Center - Microsoft Teams user activity](https://docs.microsoft.com/en-us/office365/admin/activity-reports/microsoft-teams-user-activity?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/microsoft-teams-user-activity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/microsoft-teams-user-activity.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@justjeff2018 - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
