### ISSUE TITLE
Showing "** AAD の条件付きアクセスします**" (Markdown notation)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#301]
https://docs.microsoft.com/ja-jp/yammer/troubleshoot-problems/phasing-out-temporary-mobile-passwords

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eccc79e7-399d-9701-d87b-812d2f06d772
* Version Independent ID: ddf603fe-dd24-97af-dacd-83aa90179a05
* Content: [Phasing out temporary mobile passwords in Yammer](https://docs.microsoft.com/en-us/yammer/troubleshoot-problems/phasing-out-temporary-mobile-passwords)
* Content Source: [yammer/troubleshoot-problems/phasing-out-temporary-mobile-passwords.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/troubleshoot-problems/phasing-out-temporary-mobile-passwords.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
@hyoshioka0128 Thanks, I passed it to the localization vendors to fix it.

**Comment by MollyMalone** [comment]
@hyoshioka0128 This has now been fixed by @OfficeGlobal Thanks again for reporting it.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
