### ISSUE TITLE
Showing "https & #58;//www & #46; yammer & #46; com"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#302]
https://docs.microsoft.com/ja-jp/yammer/work-with-external-users/create-and-manage-an-external-network

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25fe589-e3cf-115f-25a1-d120e801b90d
* Version Independent ID: 24b8ddb0-0222-7bf5-7e2b-799c70764671
* Content: [Create and manage an external network in Yammer](https://docs.microsoft.com/en-us/yammer/work-with-external-users/create-and-manage-an-external-network)
* Content Source: [yammer/work-with-external-users/create-and-manage-an-external-network.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/work-with-external-users/create-and-manage-an-external-network.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
Thank you @hyoshioka0128 - another great bug!  I passed it to the localization team to fix.

**Comment by OfficeGlobal** [comment]
The article has been HumanTranslated and published live. 
Reported issue is fixed

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
