### ISSUE TITLE
Affect of Group Classification

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#307]
Please provide a detailed listing of how a Groups Classification is displayed in the UI, e.g., list ALL of the different applications/services that show the value AND provide a listing of the various apps/service that can use this value to perform a function, e.g, DLP, AIP, CAS, etc may use it but I'm not that they do. Please clarify and provide links to documentation about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0753620c-8f40-dc10-8884-b7b23f416bea
* Version Independent ID: 661ddf49-aefc-7f17-4c65-f3b09a10b9ce
* Content: [Plan for Office 365 Groups governance](https://docs.microsoft.com/en-us/office365/admin/create-groups/plan-for-groups-governance?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/Plan-for-groups-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/Plan-for-groups-governance.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
Hi @DeanGross Thank you for you valuable contribution in helping improve MS Docs.  I will do some investigating and get back to you soonest.

**Comment by mypil** [comment]
@MikePlumleyMSFT - we need your insights on this issue. @lindspea did some research and found that the article doesn't have any information on how to use the classification of a group created. Please let us know whether this information already exists in another article (if yes, please assist to provide us the links) or if a PR needs to be created to add this information.  Kindly advise on how to proceed with this.

Thank you.

**Comment by MikePlumleyMSFT** [comment]
This is great feedback. There is [additional work going on in the labeling area](https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Announcing-the-availability-of-unified-labeling-management-in/ba-p/262492). We'll look at incorporating this information into the next revision of the article.

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting this feedback.

From our understanding the issue you raised has been answered. If you feel it hasn't been answered please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
