### ISSUE TITLE
Password length

### ISSUE THREAD

**Issue by the-epoch** [MicrosoftDocs/OfficeDocs-O365ITPro#309]
Whilst the article discusses keeping passwords to 8 characters minimum (Password guidelines for administrators), it doesn't discuss what the maximum length allowable is for Office 365.
Passwords longer than 16 characters are automatically shortened to 16 characters without any notification from Office365. This is poor behaviour and constraining. Many users now use , long, complex ad completely random passwords (stored in a password vault) or long strings of morable sentences or loosely associated words (e.g. myHorseWinnylovesto3@Thay). 
The 16 character limit significantly reduces this abilty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c354faae-625c-2b36-2a77-4ed2962feff3
* Version Independent ID: 1dd96166-8bae-fc8c-491f-99ca45f5b058
* Content: [Password policy recommendations for Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/password-policy-recommendations?view=o365-worldwide#password-guidelines-for-administrators)
* Content Source: [Office365-Admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@the-epoch - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://office365.uservoice.com**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
