### ISSUE TITLE
remove "t".「～ウイルス対策 t」→「～ウイルス対策」

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#310]
https://docs.microsoft.com/ja-jp/yammer/configure-your-yammer-network/configure-yammer
「 SharePoint Online のウイルス対策 t」→「SharePoint Online のウイルス対策」

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510cc7b0-d2ff-3fc1-b569-0e619e7cd04d
* Version Independent ID: 604d2362-b6fd-2343-ab8f-ffb0b4bacbbd
* Content: [Configure your Yammer network](https://docs.microsoft.com/en-us/yammer/configure-your-yammer-network/configure-yammer)
* Content Source: [yammer/configure-your-yammer-network/configure-yammer.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/configure-your-yammer-network/configure-yammer.md)
* Service: **yammer**
* Product: **office-online-server**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
@hyoshioka0128 thanks for reporting it, I passed it to the localization vendors to fix.

**Comment by MollyMalone** [comment]
@hyoshioka0128 This has now been fixed by @OfficeGlobal .  Thanks again for letting us know about it.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
