### ISSUE TITLE
Autopilot CSV file lists PKID field

### ISSUE THREAD

**Issue by dugatlin** [MicrosoftDocs/OfficeDocs-O365ITPro#311]
The later MS Autopilot PowerShell scripts and the MS OEM Autopilot documentation do not include the PKID.
There should be a note on this page that the PKID (Windows Product ID) is deprecated and is not recommended.
This is causing some customer confusion when they insist data is missing.
Please update the associated documentation.
We have previously asked and some web facing documents were updated, but apparently not this one.

Thank you,
duane.gatlin@hp.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26d3ae8-ca76-7931-4ed1-191c5f2c1bd2
* Version Independent ID: 0f149a35-4e08-ccfb-8281-7afc7cf1c170
* Content: [Device list CSV-file](https://docs.microsoft.com/en-us/office365/admin/misc/device-list?redirectSourcePath=%252farticle%252f932e3676-2491-49f0-9177-d893d2f5276e&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/device-list.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/device-list.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@dugatlin I have updated the topic.

**Comment by Sirkkuw** [comment]
@dugatlin  Thank you for this.
