### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nenonix** [MicrosoftDocs/OfficeDocs-O365ITPro#315]
there may be just a couple OF technical people who have admin permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed8d3b0-6dba-f001-2a0d-f77ef9460e28
* Version Independent ID: 8d1aa49b-5df0-0363-a61b-ebde6aa563e5
* Content: [Office 365 admin overview](https://docs.microsoft.com/en-us/office365/admin/admin-overview/admin-overview?view=o365-worldwide)
* Content Source: [Office365-Admin/admin-overview/admin-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/admin-overview/admin-overview.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
