### ISSUE TITLE
Showing "www & #46; contoso & #46; com"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#316]
https://docs.microsoft.com/ja-jp/yammer/manage-security-and-compliance/set-up-a-usage-policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cc8404f-3084-fb70-1a52-f29cd0b8b49b
* Version Independent ID: 2c910822-269a-bef9-1883-327f3211d5cf
* Content: [Set up a Yammer usage policy](https://docs.microsoft.com/en-us/yammer/manage-security-and-compliance/set-up-a-usage-policy)
* Content Source: [yammer/manage-security-and-compliance/set-up-a-usage-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-security-and-compliance/set-up-a-usage-policy.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
@hyoshioka0128 thanks for reporting it.   Passed on to @OfficeGlobal who will fix this issue.

**Comment by OfficeGlobal** [comment]
@MollyMalone Working on a fix (Bug 3186633)

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
