### ISSUE TITLE
OneDrive not syncing

### ISSUE THREAD

**Issue by bfike** [MicrosoftDocs/OfficeDocs-O365ITPro#317]
OneDrive (SharePoint) will not sync to my laptop. I click the "Sync" button and a dialogue box pops up saying "Getting ready to sync... if nothing happens, you may to get the latest version of OneDrive" (which I do) and nothing happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a55cc6-4e1f-b456-f59c-82e6f854f1ff
* Version Independent ID: ad66caa0-eed4-168c-650f-5e4b8bc1532a
* Content: [Support information for United States](https://docs.microsoft.com/en-us/office365/admin/support/united-states?view=o365-worldwide)
* Content Source: [Office365-Admin/support/united-states.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/united-states.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@bfike - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
