### ISSUE TITLE
How do we schedule MFV enabling for users

### ISSUE THREAD

**Issue by vdmamaril06** [MicrosoftDocs/OfficeDocs-O365ITPro#320]
Can a Global Administrator enable MFV for Office 365 users with a given date?
i.e. I want to bulk upload now via a csv file of users to enable each's Office 365 accounts' MFV 2 weeks from now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @dianef
* Microsoft Alias: **Dianef**

**Comment by mypil** [comment]
@vdmamaril06 - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by vdmamaril06** [comment]
Thanks @mypil !

Support replied that the functionality I am looking for is not available. :(

**Comment by mypil** [comment]
@vdmamaril06 - I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://office365.uservoice.com**

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
