### ISSUE TITLE
6.a.ii and 6.a.iii need improvement

### ISSUE THREAD

**Issue by mramnet** [MicrosoftDocs/OfficeDocs-O365ITPro#324]
6.a.ii and 6.a.iii are providing differing information for what SPF record to include - one is saying just "outlook.com" and the other is "protection.outlook.com". 
The bigger problem is that using "outlook.com" consumes 8 of the maximum 10 SPF records, while protection.outlook.com consumes 4.  Using "spf.protection.outlook.com" is the most efficient at only 3 lookups and should be the only include statement ever used. 
Cross reference to this:
https://docs.microsoft.com/en-us/office365/SecurityCompliance/set-up-spf-in-office-365-to-help-prevent-spoofing
It's possible this is just a typo or oversight as the line that specifically calls "outlook.com" has the full spf.protection.outlook.com reference listed later, but all in all this section should better clarify the limitations and definitely be consistent in the include statement.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc99803-4432-cd7c-4747-0953276298d9
* Version Independent ID: 1d7554f1-8b1c-dd3a-18e6-1106ad2b3bcb
* Content: [Domains FAQ](https://docs.microsoft.com/en-au/office365/admin/setup/domains-faq?view=o365-worldwide#can-i-pilot-office-365-with-just-a-few-email-addresses-from-my-custom-domain)
* Content Source: [Office365-Admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by nenonix** [comment]
@mramnet Thank you for taking time to give helpful feedback. I will research the issue and post back here when it is dealt with.

**Comment by mypil** [comment]
@mramnet - From our understanding the issue you raised has been <answered>. If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
