### ISSUE TITLE
missing word

### ISSUE THREAD

**Issue by ml4den** [MicrosoftDocs/OfficeDocs-O365ITPro#325]
How long does it take for a domain to be removed?
It can [[take]] as little as 5 minutes

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd73a9c7-f673-9dc0-da9b-9e0a22e27027
* Version Independent ID: c3820561-1dff-5672-db66-86b173ce0a5c
* Content: [Remove a domain from Office 365](https://docs.microsoft.com/en-gb/office365/admin/get-help-with-domains/remove-a-domain?redirectSourcePath=%252fen-GB%252farticle%252ff09696b2-8c29-4588-a08b-b333da19810c&view=o365-worldwide)
* Content Source: [Office365-Admin/get-help-with-domains/remove-a-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/remove-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@ml4den - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
