### ISSUE TITLE
Menu item misspelled

### ISSUE THREAD

**Issue by conradagramont** [MicrosoftDocs/OfficeDocs-O365ITPro#330]
Menu text for this page is misspelled.  It's missing an "s" in Customize. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae211d5-32c4-5286-ab27-898d3f68c373
* Version Independent ID: f1b4e12d-98c7-c7e8-5dca-d608618ec305
* Content: [Customize your team site for file storage and sharing](https://docs.microsoft.com/en-us/office365/admin/setup/cutomize-team-site?redirectSourcePath=%252fen-us%252farticle%252fcustomize-your-office-365-team-site-for-file-storage-and-sharing-70a62f09-45ea-4968-8482-43cddfb8cc01&view=o365-worldwide)
* Content Source: [Office365-Admin/setup/cutomize-team-site.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/cutomize-team-site.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@conradagramont - Thank you for pointing this out.

I will get this issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.
