### ISSUE TITLE
Perpanjangan uji coba microsoft 365

### ISSUE THREAD

**Issue by ilhammiftah** [MicrosoftDocs/OfficeDocs-O365ITPro#331]
[Masih bnyak fitur yg blum saya faham]

---
#### Detail Dokumen

⚠ *Jangan edit bagian ini. Diperlukan untuk masalah penautan docs.microsoft.com ➟ GitHub.*

* ID: 20755c6b-6eac-a037-e6be-be7110a11f32
* Version Independent ID: 65c63c2a-bc5b-0e32-412e-5bf72989c360
* Content: [Extend your trial for Office 365 for business](https://docs.microsoft.com/id-id/office365/admin/subscriptions-and-billing/extend-your-trial?redirectSourcePath=%252farticle%252f75533195-f1f6-4c2c-8ceb-0b5597790d7b&view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/extend-your-trial.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/extend-your-trial.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
@mypil , @MollyMalone This is not loc content issue so there is no action needed from loc team.

**Comment by mypil** [comment]
@ilhammiftah - terima kasih telah terlibat dengan komunitas di sini untuk dokumen.

Saya tahu tim produk selalu mencari umpan balik pengguna tentang cara membuat Office 365 lebih baik. Mereka memperhatikan umpan balik pengguna dan akan luar biasa jika Anda bisa menambahkan suara Anda di Suara Pengguna **https://office365.uservoice.com**
Anda mungkin menemukan orang lain telah membuat permintaan serupa yang dapat Anda tambahkan, atau Anda dapat membuka yang baru.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
