### ISSUE TITLE
It is not clear what to add to the SPF record, you have it shown 3 different ways, as shown:

### ISSUE THREAD

**Issue by RispIT** [MicrosoftDocs/OfficeDocs-O365ITPro#334]
... just add "include:outlook.com" to the current TXT record...
... include:spf.protection.outlook.com ...
... protection.outlook.com...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc99803-4432-cd7c-4747-0953276298d9
* Version Independent ID: 1d7554f1-8b1c-dd3a-18e6-1106ad2b3bcb
* Content: [Domains FAQ](https://docs.microsoft.com/en-us/office365/admin/setup/domains-faq?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@RispIT - From our understanding the issue you raised has been . If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
