### ISSUE TITLE
broken URL "[Office 365 グループを作成できるユーザーを管理する](https://docs.microsoft.com/office365/admin/create-groups/manage-creation-of-groups)"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#335]
https://docs.microsoft.com/ja-jp/yammer/manage-yammer-groups/yammer-and-office-365-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7a47d0-7e67-1890-8a1e-192871c99b55
* Version Independent ID: ff75ce98-2235-8c92-b6a2-9b034061adef
* Content: [Yammer and Office 365 Groups](https://docs.microsoft.com/en-us/yammer/manage-yammer-groups/yammer-and-office-365-groups)
* Content Source: [yammer/manage-yammer-groups/yammer-and-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-groups/yammer-and-office-365-groups.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
@mypil The link has been fixed, it's displayed properly at live site

**Comment by mypil** [comment]
@hyoshioka0128 - From our understanding the issue you raised has been answered. If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by hyoshioka0128** [comment]
@mypil Thank you.
