### ISSUE TITLE
Contact quote on chat

### ISSUE THREAD

**Issue by svjr** [MicrosoftDocs/OfficeDocs-O365ITPro#34]
How do you make a contact in the chat !? I tried to use the @ character but I could not!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef921d18-04ac-dc05-3a66-093903cf2ec5
* Version Independent ID: 0539f939-04fa-db4e-2c0f-acae96d49498
* Content: [Kaizala mobile app](https://docs.microsoft.com/en-us/office365/kaizala/kaizala-mobile-app)
* Content Source: [Office365-Kaizala/kaizala-mobile-app.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/kaizala-mobile-app.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by AndreaBarr** [comment]
@svjr Thank you for this inquiry

It looks like this app mostly goes off of your phones contact list for contacts inside the app. Most apps like this also has a search function but I'm not familiar with this one. I am going to get this over to the o365ITPro team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by nenonix** [comment]
@svjr Apologies for the delay in responding. On the mobile app you must click or tap the contact name to start a chat. Does that work for you?

**Comment by nenonix** [comment]
@svjr  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.   Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by nenonix** [comment]
@AndreaBarr @mypil please close
