### ISSUE TITLE
Characters are visible instead of .png(../media/kb/azure-cognitive-services.png)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#345]
https://docs.microsoft.com/ja-jp/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32446a8e-a16c-8017-290e-d414e6d9a242
* Version Independent ID: e4f45a16-0deb-2eb4-eca2-31bec804dc51
* Content: [Create a knowledge-based commnity in Yammer by using QnA Maker and Flow](https://docs.microsoft.com/en-us/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker)
* Content Source: [yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 The images are displayed properly, could you please close the issue as #346 ?

Thank you

**Comment by mypil** [comment]
@hyoshioka0128 - From our understanding the issue has been resolved based on issue #346. If you feel it hasn't been resolved please re-open this issue. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
