### ISSUE TITLE
Characters are visible instead of .png(../media/kb/azure-resource-group.png)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#346]
https://docs.microsoft.com/ja-jp/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32446a8e-a16c-8017-290e-d414e6d9a242
* Version Independent ID: e4f45a16-0deb-2eb4-eca2-31bec804dc51
* Content: [Create a knowledge-based commnity in Yammer by using QnA Maker and Flow](https://docs.microsoft.com/en-us/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker)
* Content Source: [yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
Same article for the image bug number: #345 | #343 | #342 | #340 | #339 | #338 | #337
___
Hello @hyoshioka0128, all the issues listed above are for the same article, you don't need to log an issue for every found occurrence, We always check the whole article

**Comment by OfficeGlobal** [comment]
Hello @hyoshioka0128 , the topic was recently updated and all images are visible live.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
