### ISSUE TITLE
broken URL "[Yammer グループを管理する](https://support.office.com/article/6e05c6d6-5548-4c88-89cd-e6757a514ef2)"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#347]
https://docs.microsoft.com/ja-jp/yammer/manage-yammer-users/manage-users-across-their-lifecycle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba22026-cfbc-68a8-4ffd-4b9111cebc81
* Version Independent ID: a3a0948e-ef2e-5d39-7f67-521ef81bb907
* Content: [Manage Yammer users across their lifecycle from Office 365](https://docs.microsoft.com/en-us/yammer/manage-yammer-users/manage-users-across-their-lifecycle)
* Content Source: [yammer/manage-yammer-users/manage-users-across-their-lifecycle.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-users/manage-users-across-their-lifecycle.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
@mypil , @hyoshioka0128 The link has been fixed, it's displayed and works properly

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
