### ISSUE TITLE
Connection lost. Please ensure that your computer is connected to internet. Reconnect

### ISSUE THREAD

**Issue by jthalies** [MicrosoftDocs/OfficeDocs-O365ITPro#348]
I'll try to use Kaizala Web Preview on my company device in Chrome browser. The company uses zScaler Proxy app for securing internet access. When I open the site webapp.kaiza.la/Account/Webapp the page is loading successfully, but an error is displayed:
![image](https://user-images.githubusercontent.com/48199304/53716015-dd72b280-3e53-11e9-8a7a-1ee28f07f4d7.png)
The client has a good internet connection, but I guess the Kaizala Web isn't supporting proxy connection yet.
If I enter my phone number. I cannot click on "generate code" due to that error message.

**Comment by mypil** [comment]
@jthalies - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
