### ISSUE TITLE
Is it correct that users without license can use Enterprise features

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ITPro#349]
Document states:  "These users can be made admins, create groups, and use all Yammer Enterprise features. " Is it correct from licensing perspective?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701c4134-00e1-34c7-e7d0-75f521733c9a
* Version Independent ID: 8233cbcd-59ee-a3e1-f3c1-07ae522bef21
* Content: [Yammer admin key concepts](https://docs.microsoft.com/en-us/yammer/get-started-with-yammer/admin-key-concepts)
* Content Source: [yammer/get-started-with-yammer/admin-key-concepts.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/get-started-with-yammer/admin-key-concepts.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Larryngolog  Thank you for submitting Feedback. You are right, In case you do not choose to enforce Office 365 identity, users who are on the same email domain as your Yammer network but do not have Office 365 licenses can join the network by creating a Yammer account at http://www.yammer.com. A user can be made admin, Create yammer groups and use all admin enterprise feature without a license being assigned. However, If you select the option to enforce Office 365 identity, all users must have a Yammer license through Office 365.

**Comment by mypil** [comment]
@Larryngolog - From our understanding the issue you raised has been answered. If you feel it hasn't been answered please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by Larryngolog** [comment]
Hi! Sorry for not replying earlier. My customers find this sentence "These users can be made admins, create groups, and use all Yammer Enterprise features. " misleading as they assume that users who do not have Office 365 license are the same as users who have Basic (free) license. So they read this paragraph as a statement that there can be both Basic and Enterprise users in one network and Basic users do not have to have an Enterprise license. As I understand all users of a network where there are enterprise licenses need to have an Enterprise license purchased, even if this license is not enforced. Is this correct? If so can you please add a sentence stating that users must be licensed with Enterprise license when using a network were Enterprise features were activated?
