### ISSUE TITLE
Extra File Storage and M365

### ISSUE THREAD

**Issue by Bahawki26** [MicrosoftDocs/OfficeDocs-O365ITPro#355]
In addition to the packages listed above (are E2 and E4 still valid?) can you also add Extra File Storage onto all of the Microsoft 365 packages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94e36d7b-9d38-d71f-e64e-938e7cdf860a
* Version Independent ID: 770a6dc2-7af2-3a66-f580-98ebff5bc5c4
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/add-storage-space?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/add-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Bahawki26 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@Bahawki26 packages E2 and E3 are no more available. And Microsoft has increased the storage limits for all of its packages and you don't need to buy any additional storage. Please see the following article. https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits

**Comment by Bahawki26** [comment]
Sorry, but that response is inadequate.  E3 is certainly available - E4 is not, at least in the Microsoft CSP world. In addition, an add-on for all of the CSP O365 packages is "Office 365 Extra File Storage." The responder put this in the context of SharePoint, but I'm talking about overall O365. My question was whether or not you could add Extra File Storage to the O365 component of M365.  The answer - which I was able to confirm through another channel - is yes, you can add it onto M365.

**Comment by joinimran** [comment]
@Bahawki26 Sorry for the typo on the above comment, E3 plan is available but E4 is not. You can add extra file storage mentioned in the above document for O365 plans which comes under M365 like E5, E3, and F1. 
Thanks.

**Comment by cmcatee-MSFT** [comment]
@Bahawki26, I've updated the list to include the new Microsoft 365 SKUs for E3, E5, and F1. Also, even though some of the SKUs in the list (such as E4) are no longer available to purchase, existing customers who have subscriptions for those SKUs are still able to purchase extra file storage. I hope that helps answer your questions. Thanks.

**Comment by mypil** [comment]
@Bahawki26 - From our understanding, the issue has been answered by cmcatee-MSFT. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
