### ISSUE TITLE
When will Belgium be added to the list?

### ISSUE THREAD

**Issue by mvanders** [MicrosoftDocs/OfficeDocs-O365ITPro#359]
Just started an important project here. When will Belgium be added to the list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2033900c-d18a-cdd3-313c-7efed2ceb4ec
* Version Independent ID: 87b1f4a4-abb8-f3f6-241e-ca8b9b3d5015
* Content: [Kaizala regional availability](https://docs.microsoft.com/en-us/office365/kaizala/regional-availability#feedback)
* Content Source: [Office365-Kaizala/regional-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/regional-availability.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@mvanders - Thank you for this inquiry. 

Please refer to the answer from @chuckedmonson  found in issue #126. According to him, "For Belize and other organizations currently outside the 28 launched markets, the Account Team can request the business desk team to get Kaizala Provisioned. We are working towards general availability for all markets in near future, without requiring special provision by the Account Team.

_Originally posted by @chuckedmonson in https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/126#issuecomment-466131373_

Hope this answers your query.

**Comment by mypil** [comment]
@officedocsbot close
