### ISSUE TITLE
Who ever changed this article; please reach out to me immediately.  Thanks

### ISSUE THREAD

**Issue by Melindawj** [MicrosoftDocs/OfficeDocs-O365ITPro#36]
Who ever changed this article please reach out to me.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fea1bd-47c1-ca3f-7a67-9b629a2e9d12
* Version Independent ID: 7b1aacb9-b57b-b4c7-bb64-0b7a7ebb249b
* Content: [Manage messages in Message center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-messages?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/manage-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-messages.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
I have reached out and added a section on how to leave feedback on a message center post.
