### ISSUE TITLE
Are there countries where Disabled state is bypassed?

### ISSUE THREAD

**Issue by elenanakhmanson** [MicrosoftDocs/OfficeDocs-O365ITPro#361]
The article states that subscription "moves into a disabled state, which lasts for 90 days for most subscriptions, in most countries and regions". Are there countries or regions where this doesn't happen and the disabled state is bypassed? Could you list which countries are excluded from this rule? We just experienced this situation with Office 365 tenant in China operated by 21Vianet and it would've helped if this article was clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0721ffec-3115-1479-a73f-e74706d41410
* Version Independent ID: d34d5bdf-4380-e2e0-fa47-10057f7ef0ea
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/what-if-my-subscription-expires?view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@elenanakhmanson - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@elenanakhmanson - We have notified the doc author @cmcatee-MSFT about this feedback you submitted. He is working on updates to that topic and will try to get it addressed before republishing the article.  Thank you.

**Comment by mypil** [comment]
@officedocsbot close
