### ISSUE TITLE
Kaizala account creation

### ISSUE THREAD

**Issue by bugsystems** [MicrosoftDocs/OfficeDocs-O365ITPro#362]
I have an issue in creating my Kaizala account. This came up after using it for a period of two months. Urgently, assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915b1428-b989-629d-2fe9-e3870100df73
* Version Independent ID: 17613672-bc40-dc95-b494-9d8111e78b98
* Content: [Kaizala app](https://docs.microsoft.com/en-us/office365/kaizala/kaizala-app#feedback)
* Content Source: [Office365-Kaizala/kaizala-app.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/kaizala-app.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bugsystems - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mypil** [comment]
@officedocsbot close
