### ISSUE TITLE
Centralized deployment compatibility checker not working

### ISSUE THREAD

**Issue by marianatuma** [MicrosoftDocs/OfficeDocs-O365ITPro#365]
I apologize if this is not the right place for this question, but I couldn't find a better place. I'm trying to run the [add-in centralized deployment compatibility checker](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide), but I keep getting this output:

```
> Invoke-CompatibilityCheck

cmdlet Invoke-CompatibilityCheck at command pipeline position 1
Supply values for the following parameters:
TenantDomain: <domain>.com
Microsoft Office Add-In Centralized Deployment Eligibility Checker.  This tool helps you assess whether your organization can use the Office 365 Centralized Deployment service.  It will identify which users have a compatible version of Exchange and a license to a compatible version of Office.  See https://aka.ms/centralized-deployment-guidance for more information.

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Getting all users from tenant
Gathering activations
WARNING: 03/12/2019 11:22:38 Error occured during retrieval of required data. Output file will not be produced.
Finished execution

```

I couldn't find documentation on this error. Does anyone know how to solve this? Thanks in advance.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@marianatuma - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
