### ISSUE TITLE
License requirements for mixed user scenarios.

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ITPro#367]
This is related to issue 349. My customers find this sentence "These users can be made admins, create groups, and use all Yammer Enterprise features. " misleading as they assume that users who do not have Office 365 license are the same as users who have Basic (free) license. So they read this paragraph as a statement that there can be both Basic and Enterprise users in one network and Basic users do not have to have an Enterprise license tu use Enterprise features. As I understand all users of a network where there are enterprise features need to have an Enterprise license purchased, even if this is not enforced. Is this correct? If so can you please add a sentence stating that users must be licensed with Enterprise license when using a network were Enterprise features were activated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701c4134-00e1-34c7-e7d0-75f521733c9a
* Version Independent ID: 8233cbcd-59ee-a3e1-f3c1-07ae522bef21
* Content: [Yammer admin key concepts](https://docs.microsoft.com/en-us/yammer/get-started-with-yammer/admin-key-concepts)
* Content Source: [yammer/get-started-with-yammer/admin-key-concepts.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/get-started-with-yammer/admin-key-concepts.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Larryngolog Thank you for the feedback. When you say Enterprise features, Are you referring to other apps like Exchange, SharePoint online etc?

**Comment by msbemba** [comment]
@Larryngolog Can you brief us about the enterprise features that you would like to add? Are you referring to apps like exchange online, Sharepoint online etc?

**Comment by Larryngolog** [comment]
Hello, no. I'm referring to Yammer Enterprise features vs Yammer basic features as outlined here https://docs.microsoft.com/en-us/office365/servicedescriptions/yammer-service-description/yammer-service-description. It's a bit strange question as I'm quoting this article, where enterprise features are mentioned, see this quote "These users can be made admins, create groups, and use all Yammer Enterprise features.". As I mentioned in my initial submission, article is understood by customers that they can use Enterprise features without appropriate license and I think it needs clarification. I'm not asking about adding any enterprise features. Just please add clarification, that although technically it is possible to add users who do not have Office 365 license, users still need to be licensed when they are using yammer network where enteprise features are enabled.

**Comment by msbemba** [comment]
Thank you @Larryngolog . I wasn't sure if you meant just the Yammer enterprise features. I have created a PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/373 to make the necessary changes in the document for clarity.

**Comment by Larryngolog** [comment]
Thank you.

Pozdrawiam
Paweł Wróbel
________________________________
Od: Sriraman M S <notifications@github.com>
Wysłane: Friday, March 15, 2019 6:41:44 PM
Do: MicrosoftDocs/OfficeDocs-O365ITPro
DW: Pawel Wróbel; Mention
Temat: Re: [MicrosoftDocs/OfficeDocs-O365ITPro] License requirements for mixed user scenarios. (#367)


Thank you @Larryngolog<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLarryngolog&data=02%7C01%7Cpwrobel%40microsoft.com%7C3b667eca10944ee0823b08d6a96d7de2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636882685062774461&sdata=0U8KnE%2Foo3q%2BygRnWILJW99dYRPrF8kq0eMf%2BXEZZ%2FI%3D&reserved=0> . I wasn't sure if you meant just the Yammer enterprise features. I have created a PR #373<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-O365ITPro%2Fpull%2F373&data=02%7C01%7Cpwrobel%40microsoft.com%7C3b667eca10944ee0823b08d6a96d7de2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636882685062784439&sdata=4uAIVVQLILuF58smv7CAhRGjpE9IOPPfa8UUz17HFGk%3D&reserved=0> to make the necessary changes in the document for clarity.

**Comment by mypil** [comment]
@Larryngolog - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
