### ISSUE TITLE
Delegation grant access to OneDrive and delegation options

### ISSUE THREAD

**Issue by MikeDembek** [MicrosoftDocs/OfficeDocs-O365ITPro#37]
Is it possible to delegate access to the access files function in a manner similar to Exchange RBAC (ie. targeted group)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?redirectSourcePath=%252fen-us%252farticle%252fget-access-to-and-back-up-a-former-user-s-data-a6f7f9ad-e3f5-43de-ade5-e5a0d7531604&view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by AndreaBarr** [comment]
@MikeDembek Thank you for this inquiry

I am not sure about delegating access for this. Let me get this over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @MikeDembek , please could you further elaborate on the comment?

Thank you!

**Comment by dariomws306** [comment]
Hi @MikeDembek , I think you are talking about this:
https://docs.microsoft.com/en-us/sharepoint/manage-user-profiles#add-and-remove-admins-on-a-onedrive-account

**Comment by MikeDembek** [comment]
Yes, that's a good option to accomplish what I was looking to do.  Could that get linked as an alternative option in part 1?

**Comment by dariomws306** [comment]
Ok, I am working on it.

**Comment by SCS-sysadmin** [comment]
+1 for adding a link in the article. It wasn't until I came to this thread that I figured out how to delegate access to another user (in my case the user's manager).
