### ISSUE TITLE
Update License requirement

### ISSUE THREAD

**Issue by JoshuaLowery** [MicrosoftDocs/OfficeDocs-O365ITPro#376]
Can the license requirement be updated to provide a more clear description?  

"To manage who creates Office 365 Groups, the following people need Azure AD Premium licenses or Azure AD Basic EDU licenses assigned to them:"  

This can be misunderstood and lead admins to believe they need additional licenses to make this process work.  Maybe remove "EDU" or add another clarifying statement?  It is clear at this point that additional licenses are not required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JoshuaLowery - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
Thank you for your feedback @JoshuaLowery .  I have created a PR#https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/377 to remove the word "EDU" from the licensing requirements to make this clear.

**Comment by mypil** [comment]
@JoshuaLowery - Please see the answer from the doc owner found [here](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/377#issuecomment-476210129). 

Hope this helps. We appeciate your contribution to make the docs better!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by JoshuaLowery** [comment]
@mypil This document is still incorrect, even after being told it is.

**Comment by mypil** [comment]
@JoshuaLowery - I believe the doc owner @MikePlumleyMSFT is still investigating to get confirmation on your additional feedback as shown on his [comment](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/377#issuecomment-500041376). Thanks.
