### ISSUE TITLE
Not detecting questions in malformed user posts

### ISSUE THREAD

**Issue by stuartridout** [MicrosoftDocs/OfficeDocs-O365ITPro#378]
When I exposed this to users I encountered two problems

1) Sometimes users don't end a question with a question mark
2) Sometimes the braintrust provides an answer with URL that contains a ? for a parameter

I edited the Flow that checks whether the post is a question to include additional checks.  It is a question if it starts with how, who, what, why, which, where, when, or if there is a question mark and the post does not contain "http".  

@or(
and(contains(triggerBody()?['body']?['parsed'], '?'),
not(contains(triggerBody()?['body']?['parsed'], 'http'))),
startsWith(triggerBody()?['body']?['parsed'], 'How'),
startsWith(triggerBody()?['body']?['parsed'], 'Who'),
startsWith(triggerBody()?['body']?['parsed'], 'What'),
startsWith(triggerBody()?['body']?['parsed'], 'Why'),
startsWith(triggerBody()?['body']?['parsed'], 'Which'),
startsWith(triggerBody()?['body']?['parsed'], 'Where'),
startsWith(triggerBody()?['body']?['parsed'], 'When')
)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32446a8e-a16c-8017-290e-d414e6d9a242
* Version Independent ID: e4f45a16-0deb-2eb4-eca2-31bec804dc51
* Content: [Create a knowledge-based commnity in Yammer by using QnA Maker and Flow](https://docs.microsoft.com/en-us/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker#feedback)
* Content Source: [yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/integrate-yammer-with-other-apps/knowledge-base-community-flow-qna-maker.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@stuartridout - Thank you for submitting feedback.

Is this a possible bug that you are reporting? If not, could you please assist me by suggesting how this content could be edited to incorporate your feedback?

**Comment by stuartridout** [comment]
@mypil It is not a bug.   It is an improvement suggestion for the original flow owner.   They would need to update the flow files available in Step 1 of this document.

It is a suggestion more for @irene_pasternack

**Comment by mypil** [comment]
@IrenePasternack - Can you please share your insights on this issue? Thank you.

**Comment by IrenePasternack** [comment]
This article is moving today to the tech community, and I’ll be removing it from docs.microsoft.com. The new link is:

https://techcommunity.microsoft.com/t5/Yammer-Resources/Identify-sentiment-of-comments-in-a-Yammer-group-by-using-Azure/ta-p/393398

I’ve passed Stuart’s comments to the new owner of the article, but it is probably worth posting them on the tech community.

Irene

**Comment by mypil** [comment]
@stuartridout - From our understanding, the issue you raised has been answered by IrenePasternack. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
