### ISSUE TITLE
Get-AzureADDirectorySettingTemplate cmlet invalid

### ISSUE THREAD

**Issue by D1872375545** [MicrosoftDocs/OfficeDocs-O365ITPro#38]
Get-AzureADDirectorySettingTemplate : The term 'Get-AzureADDirectorySettingTemplate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzureADDirectorySettingTemplate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureADDirectorySettingTemplate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?redirectSourcePath=%252fzh-cn%252farticle%252fManage-Office-365-Group-Creation-4c46c8cb-17d0-44b5-9776-005fced8e618&view=o365-21vianet)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by bally-singh** [comment]
Ensure that you are using the AzureADPreview cmdlet... try this first as admin in ISE:

Get-Module azuread -ListAvailable | uninstall-module
Install-Module -Name AzureADPreview

**Comment by D1872375545** [comment]
Hi,
       Thank you very much for your help.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: bally-singh <notifications@github.com>
发送时间: Wednesday, November 7, 2018 11:01:45 PM
收件人: MicrosoftDocs/OfficeDocs-O365ITPro
抄送: 代超群; Author
主题: Re: [MicrosoftDocs/OfficeDocs-O365ITPro] Get-AzureADDirectorySettingTemplate cmlet invalid (#38)


Ensure that you are using the AzureADPreview cmdlet... try this first as admin in ISE:

Get-Module azuread -ListAvailable | uninstall-module
Install-Module -Name AzureADPreview

―

**Comment by AndreaBarr** [comment]
@D1872375545 It looks like Bally-singh resolved the issue you were having. I am going to close this issue as resolved. If this is not resolved please re-open this issue.
