### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by Jason6311** [MicrosoftDocs/OfficeDocs-O365ITPro#380]
A few things are vague in this article. If you provided either better descriptions of fields with examples or an actual attached example of the report export you would completely clear this up for folks without easy access to run the report themselves from a tenant.
1. The screenshot of the view in Admin Center shows a character string, not a friendly username. Is that how the report should look?
2. The "version" field: does it include the exact Outlook version number (which is important for specific features) or is it just the general platform version (Mac, Windows, iOS, etc)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 535888ea-6011-1467-bf9a-1de66cb8c402
* Version Independent ID: d72f6ddc-15a0-5398-251e-92496afdf309
* Content: [Office 365 Reports in the Admin Center - Email apps usage](https://docs.microsoft.com/en-us/office365/admin/activity-reports/email-apps-usage?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/activity-reports/email-apps-usage.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/email-apps-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Jason6311 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by npsptechusa** [comment]
@Jason6311 
- Report will list the real username. Screenshot is showing the Guid to hide the real username.
- Version is just general platform version (Mac, Windows, iOS, etc) and its not outlook version number.

**Comment by mypil** [comment]
@Jason6311 - From our understanding, the issue has been answered by npsptechusa. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
