### ISSUE TITLE
Cortana and Outlook

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-O365ITPro#381]
"Support for using Cortana with Outlook on the desktop is planned for a later release" - this has been supported for some time. Please update the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e53cb7b-1559-f607-7027-44a1b6435dff
* Version Independent ID: 14eb4989-1955-cdb3-e716-4f221ab23c38
* Content: [Cortana integration with Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/cortana-integration?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/cortana-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/cortana-integration.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pyoungberg - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@pyoungberg - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
