### ISSUE TITLE
Confusing page

### ISSUE THREAD

**Issue by kerridv** [MicrosoftDocs/OfficeDocs-O365ITPro#382]
The U.S. is not listed in the regional availability but then it says the app is available worldwide. Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2033900c-d18a-cdd3-313c-7efed2ceb4ec
* Version Independent ID: 87b1f4a4-abb8-f3f6-241e-ca8b9b3d5015
* Content: [Kaizala regional availability](https://docs.microsoft.com/en-us/office365/kaizala/regional-availability#feedback)
* Content Source: [Office365-Kaizala/regional-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/regional-availability.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@kerridv - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
@kerridv I'll look into this and get back to you soonest.

**Comment by chuckedmonson** [comment]
Kaizala Pro will be commercially available in the U.S. shortly. The free version of Kaizala is available worldwide through the app stores. Thank you.

**Comment by kerridv** [comment]
Thank you for clarifying.

Kerri Davis  FIP, CIPP/US, CIPM
Privacy Manager – Sales & Marketing Privacy Program
Office:  425-707-4734
kerrid@microsoft.com<mailto:kerrid@microsoft.com>
