### ISSUE TITLE
The Title of this document says "... DNS with Cloudflare" when it should Removing DNS service from Cloudflare

### ISSUE THREAD

**Issue by RispIT** [MicrosoftDocs/OfficeDocs-O365ITPro#385]
This article does the exact opposite of what it says it will do..  Removing cloudflare DNS service and migrating it to MS Office (which limits what you can do with the DNS.)  We need to host off of Office to have more flexibility in modifying a basic SPF record.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fd88ec-5028-8c7e-1c48-fe3970385651
* Version Independent ID: 4373ebdd-84fe-540f-2f4d-b1906f98c5c5
* Content: [Change nameservers to set up Office 365 with Cloudflare](https://docs.microsoft.com/en-us/office365/admin/dns/change-nameservers-at-cloudflare?view=o365-worldwide)
* Content Source: [Office365-Admin/dns/change-nameservers-at-cloudflare.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/change-nameservers-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RispIT - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msjbja** [comment]
@RispIT I checked on the document but the actual title says "Change nameservers to set up Office 365 with Cloudflare" which is what the document reflects. May I have further clarification on the discrepancy? Maybe  a link if possible?

**Comment by mypil** [comment]
@RispIT - We would like to follow up. Can you please respond to the query from msjbja? 

Thank you.

**Comment by mypil** [comment]
@RispIT - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
