### ISSUE TITLE
Basic Grammar: Stop Mixing up Singular and Plural Pronouns and Subjects

### ISSUE THREAD

**Issue by jonathanpeopleai** [MicrosoftDocs/OfficeDocs-O365ITPro#387]
Don't use a plural pronoun to refer to a singular subject. 
Incorrect sentence: "If an admin registers an app for all users in their organization, he or she is asked for permission to let that app access information and resources in their organization."
Correct sentence: "If an admin registers an app for all users in their organization, he or she is asked for permission to let that app access information and resources in his or her organization."
The subject is, "admin", which is singular. The pronoun used is "'their' organization.", which is plural. Make the subject and it's pronoun match, or just use, "admin's organization" if you are concerned about gender issues.

Ex, incorrect: "...when someone uses a third-party app, that app might ask for permission to access their calendar and to edit files that are in a OneDrive folder."
Correct: "...when someone uses a third-party app, that app might ask for permission to access his or her calendar and to edit files that are in a OneDrive folder."
The subject is "someone", which is singular. You've used "their", which is plural. If you are worried about gender offense issues, just use the phrase, "the person's" instead of "his or her".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279bb5c8-222e-5ee9-dcd7-8c06bd4d3a3e
* Version Independent ID: 4b1d6664-91b3-8bd6-f26e-d46005891294
* Content: [Turning Integrated Apps on or off](https://docs.microsoft.com/en-us/office365/admin/misc/integrated-apps?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/integrated-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/integrated-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jonathanpeopleai - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by nenonix** [comment]
@jonathanpeopleai  Thank you for taking the time to provide detailed feedback. The points you raise are certainly valid but the grammar used in this document does not clearly contravene the Microsoft Style guidelines. Your suggested solution is on the same footing (both "their" and "his or her" are deemed to be OK to use now and then). See https://docs.microsoft.com/en-us/style-guide/grammar/nouns-pronouns#pronouns-and-gender Maybe this is a better place to raise and debate these issues? In this particular instance I will review the content to see if the pronoun discord can be addressed.
