### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-O365ITPro#389]
Double "the" in this sentence: "When a new Office 365 Group is created via Yammer or Teams, the the group isn't visible in Outlook or the address book because the primary communication between those users happens in their respective clients." - "the the group".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0753620c-8f40-dc10-8884-b7b23f416bea
* Version Independent ID: 661ddf49-aefc-7f17-4c65-f3b09a10b9ce
* Content: [Plan for Office 365 Groups governance](https://docs.microsoft.com/en-us/office365/admin/create-groups/plan-for-groups-governance?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/Plan-for-groups-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/Plan-for-groups-governance.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@MySkypeLab - Thank you for pointing this out.

PR #390 created to fix this typo error. 

Thank you for reporting and making the docs better. Much appreciated.
