### ISSUE TITLE
Do we need AD Premium licenses for each member of group creators security group. 

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/OfficeDocs-O365ITPro#39]
I am working with an org who have 1000 E1 or E3 license plans, all accompanied with the default Azure AD basic licenses. To regulate the creation of Office 365 groups, this org simply needs to ensure that all the members of the designated SG have Azure AD P1 licences; the remaining users can stay as they are? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@westerdaled Thank you for this inquiry

I am not sure on this licensing question. I will get this over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by riabovil** [comment]
@AndreaBarr, any news about it?
On my developer's Office 365 instance it works without Azure AD Premium license.

**Comment by westerdaled** [comment]
@riabovil  thanks for verifying.  I haven't  had an update on this yet from o365ITPro.  Off topic, we found the only members in this group could create Teams,  i.e. Global tenant & Exchange admins that were not members of this group could not, despite this fact being contradicted in the documentation.

**Comment by AndreaBarr** [comment]
@sonika24 Can you investigate this issue please?

**Comment by sonika24** [comment]
@westerdaled ,The best way to do this is to create a security group, and then only the people in that security group will be able to create Office 365 Groups and teams in apps like outlook, share point, Microsoft teams.
The administrator who configures the settings, and the members of the affected groups, must have Azure AD Premium licenses assigned to them.

**Comment by kenwith** [comment]
@westerdaled - thanks for your help identifying the gaps in the content and helping to make this more clear. @sonika24 - do you think you could update the article (referenced at the top of this thread) with the information in a PR and we can get it signed off and merged to live?

**Comment by kenwith** [comment]
@sonika24 - actually, I think this is similar to work that @tseward might be working on. Please coordinate with him and if what he is already working on solves this we can use his PR.

**Comment by westerdaled** [comment]
Thanks @sonika24, @AndreaBarr , @kenwith for progressing this . Just to reiterate, once we enable the SG that can create Office 365 groups, Is it just the admin who configured the group and the members that need  AAD P1 assigned to them? The reason I ask is because  this contradicts: 

> "The steps in this article doesn't prevent members of certain roles from creating Office 365 Groups. Office 365 Global admins may create Office 365 Groups via any means, such as the Office 365 Admin center, Planner, Teams, Exchange, and SharePoint Online".

Does this mean Global Admins can also create groups as mentioned but must have the additional license, once the SG is setup?

**Comment by tseward** [comment]
No, as they're not part of the restricted group. Only members of the group identified to create O365 Groups require P1 licenses.

**Comment by westerdaled** [comment]
Thanks @tseward. Not for the first time your insightful posts have saved me! #clientbudget

**Comment by JoshuaLowery** [comment]
I have verified this process works without any additional license requirements.  I have a case open with our Premier support to get clarification.
