### ISSUE TITLE
Thank You:  This should be automated

### ISSUE THREAD

**Issue by LMImani** [MicrosoftDocs/OfficeDocs-O365ITPro#392]
For my start-up company, I paid for both Bluehost to host my domain / website.  This came with the option to buy  Office 365 email.  As a user, I clicked all of the buttons to setup email and expected the email o work correctly.  In today's automated world, I think that it should not be necessary for me to cut and paste the correct DNS records in order to get my email to work properly (my problem was:  incoming mail was not working).    Nevertheless, I am grateful that by following these instructions, I now have working email.

Thank you to all who contributed to this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e339f0-e8f8-a30f-1b27-af58235f1b0d
* Version Independent ID: 6928fa1f-7f67-71ee-c839-9688b96da754
* Content: [Change nameservers to set up Office 365 with Bluehost](https://docs.microsoft.com/en-us/office365/admin/dns/change-nameservers-at-bluehost?redirectSourcePath=%2FArticle%2F7712b6af-329c-43a0-af7b-c4e4c1befb0e&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/change-nameservers-at-bluehost.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/change-nameservers-at-bluehost.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@LMImani - Thank you for submitting feedback.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://office365.uservoice.com**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by LMImani** [comment]
Hello.  I just want to let you know that I did a uservoice, per your suggestion, located at the following link:
https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/37187173-simple-way-to-just-tell-office-365-that-the-websi
