### ISSUE TITLE
Missing space in the TXT record for SPF

### ISSUE THREAD

**Issue by theseankelly** [MicrosoftDocs/OfficeDocs-O365ITPro#393]
There's a missing space before '-all' in the VALUE for the SPF TXT record.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cd535d-46b0-1ac9-e9c6-4d9d64a9ad1b
* Version Independent ID: 21c609a3-8f25-55fa-c2fc-0992e4cad573
* Content: [Create DNS records at Dreamhost for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-dreamhost?redirectSourcePath=%252fen-US%252farticle%252fCreate-DNS-records-at-Dreamhost-for-Office-365-9c0812e0-908b-4b41-a64b-77f0dbd3db7a&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-dreamhost.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-dreamhost.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@theseankelly - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@theseankelly - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
