### ISSUE TITLE
Unauthorized Person is Using our organization email and domain for Office 365

### ISSUE THREAD

**Issue by davidking2019** [MicrosoftDocs/OfficeDocs-O365ITPro#394]
Hi, I am trying to create Office 365 account, but it is showing that our school email has already been registered. I am an IT Administration  of our organization and I have not registered with our school email before. Please help to to delete the old account.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c67076-a5f6-a3c6-99f2-f90d0f304165
* Version Independent ID: 686ec1ba-6692-f167-4bf7-329a3b6668e1
* Content: [Support information for Nepal](https://docs.microsoft.com/en-us/office365/admin/support/nepal?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/support/nepal.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/nepal.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@davidking2019 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by davidking2019** [comment]
@mypil - The mentioned link only provides number for In the United States, Australia, Canada, and United Kingdom. My country does not have any contact no. Only feedback forum is available.

**Comment by mypil** [comment]
@davidking2019 - Have you tried using the online-support? Here is the link- **https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online**

Please let me know if this mode of contacting technical support works for you. Thank you.

**Comment by mypil** [comment]
@davidking2019 - We hope that the online-support path provided to you helped you in contacting technical support to resolve your issue. We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by cmcatee-MSFT** [comment]
@davidking2019 - What country or region are you in that's not listed in the drop-down list at the bottom of the **Phone** tab [here](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone)

**Comment by davidking2019** [comment]
@cmcatee-MSFT _ I can't find Nepal number in drop-down list

**Comment by cmcatee-MSFT** [comment]
@davidking2019 - Are you viewing the contact support page in an language other than English? I'm able to see Nepal in the drop-down list. The support info for Nepal is [here](https://docs.microsoft.com/en-us/Office365/Admin/support/nepal?view=o365-worldwide). Hope that helps!

**Comment by davidking2019** [comment]
There is Nepal in the drop-down  list, but Telephone, Technical, and Billing support not available. Only feedback option is available.

**Comment by mypil** [comment]
@cmcatee-MSFT - Do you have any updates on this? Thanks.

**Comment by cmcatee-MSFT** [comment]
@davidking2019, you're right - I apologize. I think your best option is to contact support online through the admin center. Steps to do that are [here](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online)

**Comment by cmcatee-MSFT** [comment]
I just responded & closed the issue. Thanks.
