### ISSUE TITLE
Caribbean Island

### ISSUE THREAD

**Issue by juliobrazil** [MicrosoftDocs/OfficeDocs-O365ITPro#399]
What is the process to make Kailaza available to Barbados and other islands? We plan to dissiminate the tool in the region with the governments, but is not yet available. thanks

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@juliobrazil - Thank you for this inquiry.

Please refer to the related answer from @chuckedmonson found in issue #126. According to him, "For Belize and other organizations currently outside the 28 launched markets, the Account Team can request the business desk team to get Kaizala Provisioned. We are working towards general availability for all markets in near future, without requiring special provision by the Account Team.

Originally posted by @chuckedmonson in #126 (comment)

Hope this answers your query.

**Comment by chuckedmonson** [comment]
@juliobrazil - As of today, this topic has been updated to show that the roll out of Kaizala Pro worldwide will begin in May 2019. Thank you for your interest.
