### ISSUE TITLE
[LOC] Bold characters are showing across multiple articles

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-O365ITPro#400]
The bold characters "**" are showing across multiple articles due to the extra space. See the examples in the articles below:

https://docs.microsoft.com/en-us/office365/admin/dns/change-nameservers-at-bluehost?view=o365-worldwide
https://docs.microsoft.com/en-us/office365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide
https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-hostgator?view=o365-worldwide

Search for "*" in these articles 

![image](https://user-images.githubusercontent.com/47977325/55538156-15bd1900-56be-11e9-817e-ce546a51fd20.png)

Could you please scan through the whole repository for this issue and fix it ? This affects the localized topics as well.

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGlobal - Thank you for pointing this out.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
Assigning this to @nenonix. Kindly take care this issue and do the needful. 

cc: @dianef77 - Hi Diane, looping you in on this issue as FYI.  

Thank you.

**Comment by dianef77** [comment]
Hi, is this an error I've been introducing into the articles?

**Comment by nenonix** [comment]
@dianef77  Not sure, but I have searched for instances and made a number of PRs. I think I found them all but will recheck after these changes are merged. 😄

**Comment by dianef77** [comment]
Thank you so much!

**Comment by mypil** [comment]
@dianef77 - I checked on the PRs that @nenonix created and found that the affected articles are from various doc owners. I would greatly appreciate your help by informing the other doc owners about this markdown issue so they would know that the bold characters "**" are showing  when putting an extra space. 

Thank you.
