### ISSUE TITLE
"Deploy Add-In" window doesn't show

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [MicrosoftDocs/OfficeDocs-O365ITPro#401]
"4. Choose Deploy Add-in at the top of the page. You will see the following introduction."
When I click on this button, nothing happens. I don't have any popup blocker.
Is there any issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d424b-6f62-e70c-9c2d-ad779ffa6c3b
* Version Independent ID: e4597136-bfe8-4230-da83-f806a1126005
* Content: [Manage deployment of Office 365 add-ins in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@FelipeCostaGualberto - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by FelipeCostaGualberto** [comment]
Thanks, I'll do that!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by FelipeCostaGualberto** [comment]
Just giving a feedback... the issue was caused by new Office 365 portal layout. As soon as I switched it off to the old layout, it worked.

**Comment by rahulraj40** [comment]
This is still an issue with new Office 365 portal layout, And I can not change back to old layout.
