### ISSUE TITLE
Multiple Acceptable Prefixes?

### ISSUE THREAD

**Issue by admintgal** [MicrosoftDocs/OfficeDocs-O365ITPro#411]
Is it possible to allow for multiple acceptable prefix policies?  For example if I want to require a business unit to prefix the group name with  "Division1 - " is it possible to allow for multiple accepted prefixes (i.e. "Division1 - " and "Division2 - ").  If so how would this be done?  Would it be multiple policies or a multi valued policy and would there be conflicts with multiple policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f70ad7b-5ba2-6167-1207-7496d57c6828
* Version Independent ID: 3df3ae33-83d3-e25f-3b41-070620030a08
* Content: [Office 365 Groups naming policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/groups-naming-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/groups-naming-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@admintgal - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@admintgal Thank you for submitting feedback. Unfortunately, there is only one groups naming Policy that can be active at a time.If you set up your naming policy In Azure AD and you have an existing Exchange group naming policy, the Azure AD naming policy is applied. If there is a requirement to create a group outside of the naming policy, The following are the list of administrator roles exempted from the group naming policy.

Global administrator
Partner Tier 1 Support
Partner Tier 2 Support
User administrator
Directory writers

Regards
Sriraman

**Comment by mypil** [comment]
@admintgal - From our understanding, the issue has been answered by msbemba. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
