### ISSUE TITLE
These instructions are awesome but not up to date

### ISSUE THREAD

**Issue by andygo2** [MicrosoftDocs/OfficeDocs-O365ITPro#413]
godddy changed the layout of the DNS setup page and it is a bit confusing if following these instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9ee5421-c232-e4d5-ce94-3aca93ac7722
* Version Independent ID: 7423c9cf-2fcf-42a7-5f85-94d83c881122
* Content: [Create DNS records at GoDaddy for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-godaddy?redirectSourcePath=%252fArticle%252ff40a9185-b6d5-4a80-bb31-aa3bb0cab48a&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-godaddy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-godaddy.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@andygo2 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by andygo2** [comment]
Awesome, thank you!

Sent from my iPhone

On Apr 8, 2019, at 2:20 AM, Joyce Y. <notifications@github.com<mailto:notifications@github.com>> wrote:


@andygo2<https://github.com/andygo2> - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@andygo2 Thank you for the feedback, I have submitted a PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/447 to make necessary changes to the document.

**Comment by mypil** [comment]
@andygo2 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
