### ISSUE TITLE
Formatting erro

### ISSUE THREAD

**Issue by andy2002a** [MicrosoftDocs/OfficeDocs-O365ITPro#415]
There is no line break between sip and Protocol of the SRV record paragraph. 

Service: _sipProtocol: _tls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0937468-6fd2-c83a-ed60-81129a4b766a
* Version Independent ID: 010a32f0-45a3-81da-1a6c-864996a86597
* Content: [Create DNS records for Office 365 using Windows-based DNS](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-using-windows-based-dns?view=o365-worldwide)
* Content Source: [Office365-Admin/dns/create-dns-records-using-windows-based-dns.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-using-windows-based-dns.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@andy2002a - Thank you for pointing this out.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
Created PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/421

**Comment by mypil** [comment]
@andy2002a - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
