### ISSUE TITLE
out of date requirements?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/OfficeDocs-O365ITPro#416]
"Download and Install PackageManagement PowerShell Modules Preview from here."
The PackageManagement module is available by default on most windows installations now.  It would only be required for a much older OS.  And there is no preview version of it any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67be3bb5-b150-e197-08fb-eaa3bf8f7a0b
* Version Independent ID: 5e2b6dc2-992c-5b76-955d-9cb57da9fbcc
* Content: [Improve Office 365 sign-in for Yammer with auto-acceleration policy](https://docs.microsoft.com/en-us/yammer/manage-yammer-users/auto-acceleration-policy-for-signing-in)
* Content Source: [yammer/manage-yammer-users/auto-acceleration-policy-for-signing-in.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-users/auto-acceleration-policy-for-signing-in.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jordanmills - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @jordanmills ,
**The PackageManagement module is available by default on most windows installations now. It would only be required for a much older OS.** - it is available by default only in PowerShell 5.0 and newer (not depending on OS), so those who are using PowerShell 3.0 or 4.0 still need PackageManagement PowerShell Module to be installed.

**And there is no preview version of it any more.** - yes, current version is 1.3.1, so the link should be updated, I am going to create PR

Thank you

**Comment by IrenePasternack** [comment]
I updated the topic.

**Comment by MaratMussabekov** [comment]
Dear @IrenePasternack ,
I think there is some kind of mistake in the updated version of the topic. Could you please take a look to the wrong link at the second prerequisite?
Thank you

**Comment by IrenePasternack** [comment]
Thank you Marat. I have updated the topic so the link appears properly.

**Comment by mypil** [comment]
@jordanmills - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
