### ISSUE TITLE
How to upgrade steps do not apply

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/OfficeDocs-O365ITPro#417]
"Under included services, click Yes, activate Yammer Enterprise for my network."

There is no "included services" in the office admin center, nor anything that seems to be like "Yes, activate Yammer Enterprise for my network."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac610948-8148-899a-935f-353487191198
* Version Independent ID: 33e0ccaf-cf1e-f7bc-2be6-ebb2b5b03959
* Content: [Upgrade your network to stand-alone Yammer Enterprise subscription](https://docs.microsoft.com/en-us/yammer/troubleshoot-problems/upgrade-your-network-to-stand-alone-yammer)
* Content Source: [yammer/troubleshoot-problems/upgrade-your-network-to-stand-alone-yammer.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/troubleshoot-problems/upgrade-your-network-to-stand-alone-yammer.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by IrenePasternack** [comment]
Jordan,

Is your tenant a US Government tenant? This topic only applies to specific tenants.

Irene

**Comment by jordanmills** [comment]
Yes it is.  Hctx.onmicrosoft.com (Harris County, Texas).

________________________________

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jordanmills - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by IrenePasternack. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by jordanmills** [comment]
I don't see any answer.  Am I missing something?

**Comment by mypil** [comment]
@jordanmills - According to @IrenePasternack, the article topic only applies to specific tenants.

@IrenePasternack - Can you please clarify what you meant by specific tenants?

Thank you.

**Comment by jordanmills** [comment]
Yes, and as I answered, we have one of those tenants.  Per the top line of the article: "NOTE: This topic applies to customers using Office 365 Government."  That's what we're using.

**Comment by mypil** [comment]
@IrenePasternack - Can you please share your insights on this issue? Please advise how to proceed. Thank you.

**Comment by IrenePasternack** [comment]
Jordan, thanks for your feedback. I'm researching this, but I don't have an answer yet. Is this blocking you from using Yammer? If so, please open a support case.

**Comment by jordanmills** [comment]
It may be, but I'm not sure if something is blocking it or if it's blocking something else.  I have opened a case about merging networks, which might change what I see once it gets done.  Thanks!
