### ISSUE TITLE
Outlook 365 mac

### ISSUE THREAD

**Issue by filipkcz** [MicrosoftDocs/OfficeDocs-O365ITPro#418]
Hi, 

when user with Outlook 365 business premium on Mac client using Office 365 business / Exchange Online account. He cannot sync contact list, distribution list with Office 365 Account. It is a bug. 

Any solution for this bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f1aa49-6d0f-8866-4744-6260ce13deb9
* Version Independent ID: 8b547e7e-1b0d-a298-c596-32aa33b449f5
* Content: [Add a user or contact to an Office 365 distribution list](https://docs.microsoft.com/en-us/office365/admin/email/add-user-or-contact-to-distribution-list?view=o365-worldwide)
* Content Source: [Office365-Admin/email/add-user-or-contact-to-distribution-list.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/add-user-or-contact-to-distribution-list.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@filipkcz - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
