### ISSUE TITLE
Vague

### ISSUE THREAD

**Issue by micfau1091** [MicrosoftDocs/OfficeDocs-O365ITPro#42]
"Enter your email address in the prompt so we can send you a link to join the Office 365 account where your domain is currently added."

What prompt? Where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24eaf551-7e49-ee4a-2979-8515f92d4d2a
* Version Independent ID: 67e53343-d996-ce5e-4742-0c0d819fbca1
* Content: [Do an admin takeover in Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/become-the-admin?view=o365-worldwide)
* Content Source: [Office365-Admin/misc/become-the-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/become-the-admin.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by j0rt3g4** [comment]
@micfau1091 I've added more clarifications on the documentation

**Comment by j0rt3g4** [comment]
Addressed at PR #264

**Comment by micfau1091** [comment]
Thank you guys!!!
-Michael

**Comment by mypil** [comment]
@micfau1091 - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
