### ISSUE TITLE
Please help update information of User management administrator in this article

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-O365ITPro#422]
User management administrator can no longer edit Skype for business user properties/settings in O365 admin portal since this April.
In the past this access is always ok to proceed. Raised a request to Product Group team, now the following role can access Teams/SFB portal
SfB Admin, Global Admin, Teams Service Admin, Teams Communication Admin, Teams Communication Support Engineer, Teams Communication Support Specialist.

In this article, User management administrator: 'Translates to this in Skype for Business Online' is Skype for Business admin, please update this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About Office 365 admin roles](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#what-can-the-office-365-admin-roles-do-in-exchange-online-sharepoint-online-and-skype-for-business-online)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@XixiHuang333 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@XixiHuang333 Thank you for the Feedback. I have created a PR#https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/426

**Comment by mypil** [comment]
@XixiHuang333 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
