### ISSUE TITLE
Is it OK for Yammer?

### ISSUE THREAD

**Issue by shrinika92** [MicrosoftDocs/OfficeDocs-O365ITPro#424]
I tried this few months ago but Yammer doesn't work it. How can I prevent the group creation of the Yammer group without admin?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?redirectSourcePath=%252fen-ie%252farticle%252fmanage-who-can-create-office-365-groups-4c46c8cb-17d0-44b5-9776-005fced8e618&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@shrinika92 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by ub-k** [comment]
@mypil this doesn't work for Yammer. For Planner it is working exactly the way you have described, but users who are not member of my 'AllowedToCreateGroups' group is still seeing the 'Create a Group' link in Yammer. I feel, this setting is just stopping the user from creating the associated Office365 group, since I don't see any Office365 resources with this dummy group that I have created. Could you please check? I don't think this is an one off issue which require Microsoft support team to look at, rather than functional issue/ behavior.

**Comment by ub-k** [comment]
I have just tested this one more time by enabling group creation. This time the Yammer group got created with Office 365 resources. So, it seems, disabling group creation is stopping Office 365 connected group creation from Yammer but it is creating Yammer groups anyway. I am wondering if there is a way to restrict creation of Yammer groups as well.

**Comment by shrinika92** [comment]
There is multiple Yammer network, so it's doesn't work well. And also Microsoft not recommended for Multiple Yammer networks configuration.
