### ISSUE TITLE
Kaizala vers 1.125.105091811 in IOS 12.2 (IPhone SE)

### ISSUE THREAD

**Issue by rsvmarques** [MicrosoftDocs/OfficeDocs-O365ITPro#425]
Hi, 
Microsoft Kaizala mobile App  (vers 1.125.105091811) when register it crashes in IOS new version 12.2 (IPhone SE)

Cheers!
Renato Marques

**Comment by mypil** [comment]
@rsvmarques - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
