### ISSUE TITLE
Global Admin Rights Needed to Approve Email in Dynamics 365?

### ISSUE THREAD

**Issue by tbogle** [MicrosoftDocs/OfficeDocs-O365ITPro#429]
I see that the documentation reflects needing to be a global Admin to approve the email, but there's no explanation about why?  As a Dynamics 365 service admin You can do every other feature, except this one and that functionality appears to have changed at some point. I'm curious what the reason for this change was. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About Office 365 admin roles](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?redirectSourcePath=%252farticle%252fAbout-Office-365-admin-roles-da585eea-f576-4f55-a1e0-87090b6aaa9d&view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@tbogle - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @tbogle ,
Dynamics 365 service admin role was designed to delegate dynamic 365 administration without providing access to private data.
According to [this article](https://docs.microsoft.com/dynamics365/customer-engagement/admin/use-service-admin-role-manage-tenant), the ability to Approve Customer Engagement emails was restricted "for privacy reasons".
Thank you

**Comment by mypil** [comment]
@tbogle - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
