### ISSUE TITLE
Please don't write to system32

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-O365ITPro#43]
Don't understand why your script writes to C:\windows\system32. Please either provide a hook where the output can be specified or write someone else like the desktop or the root of the system drive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0659185-aece-2fa7-0e9d-fe56c771d8f9
* Version Independent ID: b5f0658e-d859-ad4d-7d1f-33a753fbd6c9
* Content: [Determine if Centralized Deployment of add-ins works for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins?redirectSourcePath=%252fen-us%252farticle%252fDetermine-if-Centralized-Deployment-of-add-ins-works-for-your-Office-365-organization-b4527d49-4073-4b43-8274-31b7a3166f92&view=o365-worldwide)
* Content Source: [Office365-Admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by pyoungberg** [comment]
Excel can't open items from system32, it has to be copied to another directory before it will open

**Comment by AndreaBarr** [comment]
@pyoungberg Thank you for this suggestion

I know the product teams are always looking for user feedback and how to make o365 better. They keep a close tab on User Voice [https://office365.uservoice.com/](https://office365.uservoice.com/) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by marianatuma** [comment]
I get the following message when I try to run the compatibility checker: "WARNING: 03/12/2019 11:22:38 Error occured during retrieval of required data. Output file will not be produced." No relevant results appear in a google search. Can someone help me run this?
