### ISSUE TITLE
Cannot add more than a single alias from any domain

### ISSUE THREAD

**Issue by sprender** [MicrosoftDocs/OfficeDocs-O365ITPro#430]
I was able to add an alias from one of my domains using this process earlier (alias1@domain.com), but attempting to add another (alias2@domain.com) fails with an error message like: "Email addresses need to be unique.smtp:alias2@domain.com is being used by the user..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50963b73-8563-f99a-72f7-bf4037965cde
* Version Independent ID: 5daa29ed-8092-3a79-c011-8bcbe0225b2c
* Content: [Add another email alias for a user](https://docs.microsoft.com/en-us/office365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@sprender - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
