### ISSUE TITLE
Add Custom DNS 

### ISSUE THREAD

**Issue by webon077** [MicrosoftDocs/OfficeDocs-O365ITPro#431]
[There is no where mention about how can we add custom DNS records if the domain is not hosted by Microsoft. I have domain from GoDaddy and can not see this option in O365]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a782c64-5ec7-de5c-d57f-65b8f07a8678
* Version Independent ID: dbb00763-2bae-7843-2334-cc3d077beb1a
* Content: [Add or edit custom DNS records in Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/add-or-edit-custom-dns-records?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/add-or-edit-custom-dns-records.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/add-or-edit-custom-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@webon077 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@webon077 Thank you for your feedback. I have added a snip to the document which shows how to add a custom record . The changes are tracked under PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/445 

While the document gets updated, You Check to see if you see the below option to add custom record. 

https://user-images.githubusercontent.com/45987684/56503244-e5111800-64e2-11e9-8db8-1f1d13915b06.PNG

Regards
Sriraman

**Comment by mypil** [comment]
@webon077 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
-------------------------------------

**Comment by mypil** [comment]
@officedocsbot close
