### ISSUE TITLE
[LOC] Invalid link in an TOC

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-O365ITPro#434]
There is an invalid link in a toc file.

**Repro steps**:
1. Navigate to the yammer "TOC.md" file in the yammer folder
2. Open the file
3. Search for "Create a dynamic group"

**Actual results:**
Link redirect to an error page
**Expected results:**
Link should redirect to a valid page

**GH article:**
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/TOC.md

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGlobal - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
