### ISSUE TITLE
Not compatible with modern auth!!!

### ISSUE THREAD

**Issue by nathank1989** [MicrosoftDocs/OfficeDocs-O365ITPro#436]
I see someone else pointed this out, this checker is not compatible with modern auth making it entirely useless.

FIX THIS NOW!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0659185-aece-2fa7-0e9d-fe56c771d8f9
* Version Independent ID: b5f0658e-d859-ad4d-7d1f-33a753fbd6c9
* Content: [Determine if Centralized Deployment of add-ins works for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins?redirectSourcePath=%252fen-us%252farticle%252fDetermine-if-Centralized-Deployment-of-add-ins-works-for-your-Office-365-organization-b4527d49-4073-4b43-8274-31b7a3166f92&view=o365-worldwide)
* Content Source: [Office365-Admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@nathank1989 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@nathank1989 Thank you for the feedback. Could you please provide the error message that you are receiving ?

Regards
Sriraman

**Comment by mypil** [comment]
@nathank1989 - We would like to follow up. Can you please respond to the query of msbemba? 

Thank you.

**Comment by nathank1989** [comment]
WARNING: Failed to sign in with provided username and password

Now when I tried today, I got a little further, I saw this:
Getting all users from tenant
WARNING: The user or administrator has not consented to use the application

Which popped up a modern auth login window, however, when signing in with the same global admin account I get this error:
Request Id:  c73661e0-49be-4d97-9b71-51b4816a7200 
 
Correlation Id:  0f51af66-9904-48ed-a3df-41d5d18af852 

Timestamp:  2019-04-24T20:30:20Z 
 
Message:  AADSTS50197: Sorry, we could not find the user, please sign-in again.

**Comment by msbemba** [comment]
@nathank1989 I was getting the same error, Let me check if we can determine the cause and update the document.

**Comment by mypil** [comment]
@nathank1989 - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by kemper451** [comment]
tried to run on my tenant and it just fails with no helpful details:
Credential
Getting all users from tenant
Gathering activations
WARNING: 05/04/2019 23:34:04 Error occured during retrieval of required data. Output file will not be produced.
Finished execution

**Comment by mypil** [comment]
@kemper451 - Please contact technical support for this issue. You can either use Phone support or contact support online through the admin center. Please follow the instructions [here](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).

Hope this helps. Thank you!

**Comment by mypil** [comment]
@officedocsbot close
