### ISSUE TITLE
link goes to wrong article

### ISSUE THREAD

**Issue by bickell** [MicrosoftDocs/OfficeDocs-O365ITPro#438]
There is a link in the section   https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide#save-the-contents-of-a-former-employees-mailbox

entitled   "Manage inactive mailboxes in Exchange Online."   It goes to an article about EOP instead.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6024c6e-1373-58de-ca8b-819a11693968
* Version Independent ID: 5d02bdc8-6e20-8b9b-942e-cca0e312cc5e
* Content: [Remove a former employee from Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide#save-the-contents-of-a-former-employees-mailbox)
* Content Source: [Office365-Admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by bickell** [comment]
The link in question is has the following URL:   https://go.microsoft.com/fwlink/p/?LinkID=286939 which is an EOP overview. 

I did find two relevant docs that the link should go to and they have lots of overlap.  Seems like the overview ought to have a link to the "create and manage" doc in the body, but I do see that there os a link in the TOC in the left hand menu. 

https://docs.microsoft.com/en-us/office365/securitycompliance/inactive-mailboxes-in-office-365

https://docs.microsoft.com/en-us/office365/securitycompliance/create-and-manage-inactive-mailboxes

**Comment by mypil** [comment]
@bickell - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@bickell thank you for the feedback and making our documents better. I have raised a pull request https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/443 to make necessary changes on the URL.

**Comment by mypil** [comment]
@bickell - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated

**Comment by mypil** [comment]
@officedocsbot close
