### ISSUE TITLE
Does Sharepoint in the Office 365 Education A1 eligible for Office 365 Extra File Storage?

### ISSUE THREAD

**Issue by CheongCS** [MicrosoftDocs/OfficeDocs-O365ITPro#439]
As titled, can school purchase additional space for sharepoint in Office 365 A1? For example, the default storage for sharepoint is 1TB. School would like to have 16TB in total. Can school buy additional storage of 15TB?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94e36d7b-9d38-d71f-e64e-938e7cdf860a
* Version Independent ID: 770a6dc2-7af2-3a66-f580-98ebff5bc5c4
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/add-storage-space?view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/add-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by cmcatee-MSFT** [comment]
@CheongCS The best way to tell is to check to see if the add-on is available in the admin center on the [Purchases Services](https://go.microsoft.com/fwlink/p/?linkid=842054) page. If it's listed, then the answer is yes, they can buy additional storage.

**Comment by CheongCS** [comment]
Thanks, Cern McAtee.  My customer hasn't subscribed to Office 365 A1 yet. They are searching around any better solution to replace their current on prem file server.

**Comment by mypil** [comment]
@CheongCS - Thank you for submitting feedback.

From our understanding, the issue has been answered by cmcatee-MSFT. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
