### ISSUE TITLE
使用 microsoft office 365 商務版 開啟電郵中 的EXCEL 檔案, 經常發生 ( 檔案損毀,無法開啟) 

### ISSUE THREAD

**Issue by mickeytsui** [MicrosoftDocs/OfficeDocs-O365ITPro#44]
使用 microsoft office 365 商務版 開啟電郵中 的EXCEL 檔案, 經常發生 ( 檔案損毀,無法開啟) ,
但本機內的EXCEL 檔案是沒有問題, 
現只能移除 microsoft office 365 軟件後, 再安裝一次microsoft office 365 就可以開啟檔案 , 
( 現時電郵使用版本: windows live mail )

---
#### 文件的詳細資料

⚠ *請勿編輯此部分。 docs.microsoft.com 必要 ➟ 連結 GitHub 問題。*

* ID: 68d423ef-7d7a-0729-f239-8681b4752e19
* Version Independent ID: 67e30897-9816-b92b-dd6f-b7d3bfbfd751
* Content: [支援資訊 （香港特別行政區）](https://docs.microsoft.com/zh-hk/office365/admin/support/hong-kong-sar?view=o365-worldwide#phone-number)
* Content Source: [Office365-Admin/support/hong-kong-sar.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/hong-kong-sar.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by AndreaBarr** [comment]
@mickeytsui Thank you for this feedback

Can you verify if this is a translation issue or if the document needs update. 

https://docs.microsoft.com/en-us/office365/admin/support/hong-kong-sar?view=o365-worldwide#phone-number

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
@mickeytsui was this an issue that you needed support with?   If so, has the issue been resolved?
Or is there a problem with the help content?
這是你需要支援的問題嗎？  如果是, 問題是否得到解決？
或者説明內容是否存在問題？

**Comment by mypil** [comment]
@mickeytsui - We appreciate any feedback you can provide to make the content in the Microsoft docs better. Since we did not get any response from you, we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
