### ISSUE TITLE
CNAME records for Mobile Device Management (MDM) two possible values, which is the correct one? 

### ISSUE THREAD

**Issue by mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh** [MicrosoftDocs/OfficeDocs-O365ITPro#440]
At this page it's specified the CNAME for enterpriseenrollment should be enterpriseenrollment-s.manage.microsoft.com. At the admin.microsoft.com portal it states that the cname should be to enterpriseenrollment.manage.onmicrosoft.com. I receive them both as aliases for peproxyfeeu02.cloudapp.net. Are both to be continued in use? Is one preferred over the other? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1ab25e-c8aa-14fc-9724-6917a985e0e7
* Version Independent ID: 52b8dbba-a313-e012-b81c-cba78597dcf8
* Content: [Create DNS records at any DNS hosting provider for Office 365](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?redirectSourcePath=%252farticle%252f7b7b075d-79f9-4e37-8a9e-fb60c1d95166&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh Thank you for your feedback. You are right, There should be only one Value which is "enterpriseenrollment.manage.microsoft.com". I have created a PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/444 to reflect this change on the document.

**Comment by mypil** [comment]
@mMDG0Oowa-3TPkpg7JOmdx4ff4IfPvyCGSAHbnh - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
