### ISSUE TITLE
Microsoft Forms Data is restored too

### ISSUE THREAD

**Issue by sairao77** [MicrosoftDocs/OfficeDocs-O365ITPro#441]
When an office 365 group is restored, any microsoft form and its data associated with the group is also restored. It is nice to add Forms to the list of content that will get restored

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@sairao77 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by sairao77** [comment]
@mypil - I didn't use a particular Microsoft document link, during a testing process to retrieve Forms data that is deleted as part of Office 365 Group, I found that Forms data can be retrieved when an Office 365 group is restored. So I would like to suggest this to be added to docs for anybody in the future to reference it.

Below link should help you reference why I would like to suggest this change

https://techcommunity.microsoft.com/t5/Microsoft-Forms/Form-dissapeared/m-p/475110#M3108

**Comment by mypil** [comment]
@sairao77 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://office365.uservoice.com**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by sairao77** [comment]
@mypil - but isn't this more of a documentation addition rather than a feature addition, for which we might have to use uservoice

**Comment by mypil** [comment]
@sairao77 - Based on the link you provided, the only MS article indicated is this link - **https://docs.microsoft.com/en-us/office365/admin/create-groups/restore-deleted-group?view=o365-worldwide**

Is this the article where you want the information to be added to? Kindly confirm. Thank you.

**Comment by sairao77** [comment]
Yes @mypil , I would like the information to be added to this article :)

**Comment by mypil** [comment]
@sairao77 - a Pull Request (PR #454) has been created by @joinimran to incorporate your feedback in the article. We just have to wait until the doc owner merges the PR content for the changes to appear in the article. Thank you.

**Comment by mypil** [comment]
@sairao77 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
