### ISSUE TITLE
MOERA error

### ISSUE THREAD

**Issue by DavidSchrag** [MicrosoftDocs/OfficeDocs-O365ITPro#446]
After running the command described here, I get this error in PowerShell: "There should be at least one MOERA in Email Addresses." Get-UnifiedGroup shows a primary SMTP address as well as multiple smtp aliases. What does the MOERA error signify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8792555-ecc1-9c9e-1d7a-e0b3b1b0b2b7
* Version Independent ID: 442f4470-d54b-b4c0-f0f1-9f35b7017dc1
* Content: [Troubleshoot Remove an alias from a group](https://docs.microsoft.com/en-us/office365/admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/troubleshoot-issues-for-admins/remove-an-alias-from-a-group.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DavidSchrag - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@DavidSchrag Thank you for the feedback. Microsoft Online Email Routing Address (MOERA) is usually the UPN or the .onmicrosoft.com email address. So from the error it looks like you are trying to remove  the MOERA address from the group, which will not work unless there is another moera address added as an alias to the emailaddresses attribute.

**Comment by DavidSchrag** [comment]
How do you determine which values count as MOERA values? I have a group where the EmailAddresses attribute contains one SMTP value, two smtp values, and one SPO value. If I try to remove one of the two smtp values, I get the error, even though the smtp values are aliases that should never be used for this group. I would think that the SMTP value would count as the MOERA.

**Comment by msbemba** [comment]
@DavidSchrag  It is usually the .onmicrosoft.com addresses which counts as the MOERA, However if you get the error while removing normal aliases, I would recommend you to contact your O365 Tenant support to understand more on what could be causing this and request for a fix.

Feel free to Let us know if there is any changes required on the document.

Regards
Sriraman

**Comment by DavidSchrag** [comment]
Somehow there was no onmicrosoft.com address listed within the EmailAddresses field. When I added one, I was able to remove the unwanted alias. You might update the documentation to suggest using Get-UnifiedGroup -Identity <groupname> | Format-List to view the existing Email Addresses to ensure that an onmicrosoft.com address is present before trying to remove aliases. Thanks for your help.

**Comment by msbemba** [comment]
@DavidSchrag Thank you for the quick response. A .onmicrosoft.com address is usually added immediately as an alias after you create a Unified group, So we may not need an update as of now. Thank you again for submitting your feedback, I'm glad that your issue is resolved.

**Comment by mypil** [comment]
@DavidSchrag - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by MartyTh** [comment]
for those who arrive here after some our of work, the command that worked for me to add the onmicrosoft.com adresse to my office 365 group was: Set-UnifiedGroup -Identity "GroupName" -EmailAddresses @{add="GroupName@yourpersonaldomain.onmicrosoft.com"}

my office 365 group was created from a distribution list that have been upgraded to o365 group. Then I successfully removed an alias with the following command: Set-UnifiedGroup -Identity "GroupName" -EmailAddresses @{remove="EmailToDelete@domaine."}
