### ISSUE TITLE
Not able to open Skype for Business

### ISSUE THREAD

**Issue by Gautami007** [MicrosoftDocs/OfficeDocs-O365ITPro#448]
Hello Team,

I am trying to connect to technical team for microsoft skype for business tool issue. But not able to reach out with given phone number. Please help me to resolve my issue. 

Issue: When I click on skype it opens the tool; however it disappears in 5 seconds.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Gautami007 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Gautami007** [comment]
Hi, Unfortunately the online support numbers are not working and I am not sure how to logged service ticket.

**Comment by mypil** [comment]
@Gautami007 - One of the options you can follow is to contact support online through the admin center. Please follow the instructions [here](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online). 

Hope this helps. Thank you!

**Comment by mypil** [comment]
@officedocsbot close
