### ISSUE TITLE
Is the process described in the Workaround a valid/supported method for converting user mailboxes to shared in hybrid environments?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/OfficeDocs-O365ITPro#449]
In issue #188, yatsymbal pointed out a support article which describes a way to update the necessary attributes of a local AD account associated with a cloud mailbox that has been converted to shared.  A note was added to this article referencing the workaround, but yatsymbal's question was not answered.  
"Is there any reason why we can't use the workaround . . . as a recommended guidance?" 

The 'recommended' method, moving a mailbox from cloud to local exchange, converting it to shared, then moving it back to the cloud, requires a lot more time and effort than the workaround of converting the mailbox in place and updating the attributes of the local AD account.  Is there any reason that the 'workaround' method should not be used as the primary way to convert a cloud based user mailbox to shared? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#convert-a-users-mailbox-in-a-hybrid-environment)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by msbemba** [comment]
@NeighborGeek Thank you for the feedback. The primary reason for not recommending this approach is that the attribute "LicenseReconciliationNeeded" gets stuck on "True" most of times after making the AD changes and removing license on cloud. This means the mailbox in cloud could get deleted after 30 days This is an MSOL attribute and Cannot be changed using powershell, So It is always safe to off-board the mailbox convert it to shared and on-board to cloud. Hope this helps!

Regards
Sriraman

**Comment by NeighborGeek** [comment]
@msbemba Thank you, I really appreciate that you not only advised against using this workaround, but also explained why.  

I hope that the product team recognizes that the recommended process of moving a mailbox from cloud to on-prem, converting, and moving back to cloud is not ideal.  The workaround sounds like a much better way to do it, if only it worked correctly.  

Ideally, when using set-remotemailbox to change the mailbox type to shared, it should also update the appropriate attributes in AD, and possibly even remove the Office 365 license.  (I'm not sure if there are other reasons to have a license applied to a shared mailbox account.)

Thanks!
Steve
