### ISSUE TITLE
Send a message to everyone at a specific location

### ISSUE THREAD

**Issue by GeoffreyMcN** [MicrosoftDocs/OfficeDocs-O365ITPro#45]
It would be useful for my organisation to send announcements to all staff *currently* at a specific location or building.
eg: emergency warnings, staff duress alerts, 'have you seen &lt;whatever&gt;, tell us if you have', etc, etc.

email won't do that.
Skype for Business won't do that.
teams won't do that.
Kaizala? It looks like that won't do it either.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef921d18-04ac-dc05-3a66-093903cf2ec5
* Version Independent ID: 0539f939-04fa-db4e-2c0f-acae96d49498
* Content: [Kaizala mobile app](https://docs.microsoft.com/en-au/office365/kaizala/kaizala-mobile-app?redirectSourcePath=%252fen-us%252farticle%252fAbout-the-Kaizala-mobile-app-122fdf32-9f15-465d-a905-6fae72d38b42)
* Content Source: [Office365-Kaizala/kaizala-mobile-app.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/kaizala-mobile-app.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by AndreaBarr** [comment]
@GeoffreyMcN Thank you for this inquiry

I think there is a way to do that with utilizing Group Policy Objects from the Admin side of things but I'm not a 100% on that. Let me get this over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@GeoffreyMcN - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the Office 365 better. They keep a close tab on User Voice **https://office365.uservoice.com/** and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!
