### ISSUE TITLE
Copies of emails still not appearing in users inboxes.  Mail only appears in the actual group folder

### ISSUE THREAD

**Issue by kglick** [MicrosoftDocs/OfficeDocs-O365ITPro#450]
The instructions here have failed to function as described.  Users only receive the email in the group folder in the folder tree.  A copy of the email is not placed in the users actual inbox.  This causes users to often miss the communication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36ccf55-c8e6-e4a2-c99d-1feeb9e0b7ca
* Version Independent ID: 24e94600-1f0d-9d8b-abae-73690a4a633d
* Content: [Create an Office 365 group in the admin center](https://docs.microsoft.com/en-us/office365/admin/create-groups/create-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/create-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/create-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@kglick - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
