### ISSUE TITLE
Wipe email application as part of the offboarding process

### ISSUE THREAD

**Issue by JohnE2** [MicrosoftDocs/OfficeDocs-O365ITPro#451]
I'd like to add the step of wiping and end-users mailbox as part of my offboarding process. The command I would use is "clear-mobiledevice -accountonly"

Is it possible to include a remote wipe when I'm also: blocking sign-in, resetting the password, revoking AAD and SPO tokens, hiding from GAL, disabling all mail protocols, and soft deleting the O365 account. My uncertainty is if I do all of the above, how will the device connect and receive the remote wipe command?

 FYI my environment is cloud-only.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JohnE2 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by JohnE2** [comment]
hello @mypil and thanks for responding. I started in one article and then progressed to a few others as tried to understand the ps command to perform the mailbox only remote wipe of a mobile device. Here are the links. Thanks!

Article on how to remove a former employee form O365:
https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide#wipe-and-block-a-former-employees-mobile-device

Article regarding the remote wipe feature
https://docs.microsoft.com/en-us/exchange/clients/exchange-activesync/remote-wipe?view=exchserver-2019

Article on the command to issue a remote wipe
https://docs.microsoft.com/en-us/powershell/module/exchange/devices/Clear-MobileDevice?view=exchange-ps

**Comment by msbemba** [comment]
@JohnE2 Thank you for the question, The remote wipe command works as long as the Account is configured on the phone(regardless of password reset, sign in block, etc..)  So if a device is showing up as synced(under the exchange mailbox properties-->mobile devices synced) it is possible to perform a remote wipe. Hope this helps! 

Regards
Sriraman

**Comment by JohnE2** [comment]
@msbemba that's great news! To confirm, all mail protocols for the user's mailbox can be disabled and the command will still function? For example if this command was previously issued: `Set-CASMailbox -Identity $User -OWAEnabled $False -OWAforDevicesEnabled $False -OutlookMobileEnabled $False -POPEnabled $False -ImapEnabled $False -ActiveSyncEnabled $False`

**Comment by msbemba** [comment]
@JohnE2 That is correct.

**Comment by JohnE2** [comment]
Outstanding. Thank you very much.

**Comment by msbemba** [comment]
@JohnE2 One small correction. Only Mobile devices, when configured for your Office 365 account via Exchange/ActiveSync protocol, can be remotely wiped. So the active sync protocol cannot be disabled prior to a remote wipe, rest of the cmdlet looks fine.

**Comment by JohnE2** [comment]
Gotcha. Leave the activesync protocol enabled by removing the following from my command `-ActiveSyncEnabled $False`. Thanks again! @msbemba

**Comment by mypil** [comment]
@JohnE2 - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
