### ISSUE TITLE
Licenses for service accounts?

### ISSUE THREAD

**Issue by RadioActiveLamb** [MicrosoftDocs/OfficeDocs-O365ITPro#452]
I would like to see information regarding licensing service accounts, so that automated/on-prem services can manipulate data in O365 - such as depositing log files in SharePoint online. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f28ec79-1d61-21ae-a11e-b429d32a3346
* Version Independent ID: 2f068dd8-b9c9-7266-159a-09b90501c100
* Content: [Understand subscriptions and licenses in Office 365 for business](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/subscriptions-and-licenses?view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/subscriptions-and-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/subscriptions-and-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RadioActiveLamb - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@RadioActiveLamb Thank you for your feedback. Usually Service accounts  aren't linked to a person, they're used autonomously and only for specific tasks. In these cases you can create an service account without a product license (“Create user without product License” options when creating the account) and assign admin roles as per your requirement. If the Service account needs access to a specific mailbox or a SharePoint site you may need to assign the required licenses for it like you would assign a user. Hope this Helps! 

Regards
Sriraman

**Comment by mypil** [comment]
@RadioActiveLamb - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
