### ISSUE TITLE
Missing role: Security Operator + others

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/OfficeDocs-O365ITPro#453]
Hello, this page is missing "Security Operator"
There are actually multiple missing roles, like "Records Management"
Can this entire page be reviewed? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About Office 365 admin roles](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?redirectSourcePath=%252fen%252farticle%252fda585eea-f576-4f55-a1e0-87090b6aaa9d&view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SwiftOnSecurity - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@SwiftOnSecurity Thanks for the feedback. This document pertains to the admin roles available when you try to assign an admin role to the user via the Office365 admin center and doesn't imply to other security or compliance permissions available in Office 365. So this covers all the options that a global admin gets when he is trying to assign a user with admin role. Hope this Helps!

<img width="319" alt="admin" src="https://user-images.githubusercontent.com/45987684/56769239-997a9a80-677e-11e9-8fa4-ca60e2f68d3c.PNG">


Regards
Sriraman

**Comment by mypil** [comment]
@SwiftOnSecurity - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by SwiftOnSecurity** [comment]
Hello, thank you. Where is the right place to get information about this role? I looked and could not find it easily, which needs to be addressed.
Thanks for your time.

**Comment by msbemba** [comment]
@SwiftOnSecurity https://docs.microsoft.com/en-us/office365/securitycompliance/file-plan-manager is a good place to start, I wasnt able to get one which only talks about it though.

Regards
Sriraman

**Comment by mypil** [comment]
@SwiftOnSecurity - Kindly review the additional answer provide by msbemba. Please let us know if you have any other questions related to this issue or if we can proceed to close this. 

Thank you!

**Comment by mypil** [comment]
@officedocsbot close
