### ISSUE TITLE
Is ODfB accessible in China?

### ISSUE THREAD

**Issue by crshovrd41** [MicrosoftDocs/OfficeDocs-O365ITPro#456]
"Save to OneDrive for Business while signed in with a Microsoft account | To keep your data within your country, you cannot save a document to your organization site (OneDrive for Business) when you are signed in to Office with a Microsoft account."

What on earth does this mean? Does it mean ODfB is not available in China? Does it mean I cannot access my ODfB while using a live account, which you can't do any way?

Can I access ODfB if I'm logged in with my Office 365 account?

Bottom line, I cannot find any information on the internet if ODfB is accessible in China.

Can I access ODfB in China and share files with users outside of China?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35c839a1-9440-3e07-1cd9-99f8664d1a6e
* Version Independent ID: d87fa57b-b806-febd-7c0f-7a074dcbf7cc
* Content: [Office 365 operated by 21Vianet](https://docs.microsoft.com/en-us/office365/admin/services-in-china/services-in-china?view=o365-21vianet)
* Content Source: [Office365-Admin/services-in-china/services-in-china.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/services-in-china/services-in-china.md)
* Service: **o365-administration**
* GitHub Login: @LoreenLa
* Microsoft Alias: **LOREENL**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@crshovrd41 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@LoreenLa - Can you please share your insights on this issue? 

Thank you.

**Comment by mypil** [comment]
@LoreenLa - I would like to follow up on this. Can you please share your insights on this issue?

Thank you.

**Comment by SKjerland** [comment]
@crshovrd41 - Sorry for the confusion. I have confirmed that OneDrive for Business IS accessible in China. To keep data in China, you must sign in using your Office 365 account that is operated by 21Vianet. Do not sign in using Office 365 accounts operated by Microsoft outside of China. We will update the content so this is more clear. Thanks!

**Comment by crshovrd41** [comment]
@SKjerland Thanks! This makes it a little more clear! Just for my own knowledge, this means that if I have users in a US tenant that reside in China, they cannot access ODfB data in China. Would we then need to create a new tenant in China or simply set their geographic location in our single tenant to China?

**Comment by crshovrd41** [comment]
@SKjerland - Sorry, one last question. What if we share a link to someone that doesn't use Office 365 at all from a US tenant? For example, we create an "Anonymous" link to a file in a US based tenant and someone in China tries to open it, do you know what their experience will be?

**Comment by SKjerland** [comment]
@crshovrd41 - Here's what our product team had to say: By US tenant, you mean tenant subscribing to the public cloud or the global Office 365 not Office 365 operated by 21Vianet, correct? If so, then the users in China will be able to access OneDrive for Business. Regarding your question about sharing a link...if the link points to resources that reside inside of the data center, the user would need to have an Office 365 account and sign in. If the link points to something such as a website outside of the data center, then the user would not be able to access it.
