### ISSUE TITLE
Kaizala Training Action

### ISSUE THREAD

**Issue by Jascareer** [MicrosoftDocs/OfficeDocs-O365ITPro#457]
After training completion by a user, can the training content still be available for revision or to go through again? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7831e3d-8a07-342e-c756-d3ff3829251e
* Version Independent ID: da91c83d-e188-d1bc-64cb-d5fda2a48746
* Content: [Kaizala Actions](https://docs.microsoft.com/en-us/office365/kaizala/actions)
* Content Source: [Office365-Kaizala/actions.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/actions.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Jascareer - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@chuckedmonson - can you please assist with this query? 

Thank you.

**Comment by chuckedmonson** [comment]
@jascareer -- Yes, you can go through the training content as many times as needed. Thank you for your interest.
