### ISSUE TITLE
Delete email address policies

### ISSUE THREAD

**Issue by jonimattila** [MicrosoftDocs/OfficeDocs-O365ITPro#459]
This command does not follow -name, it should -identity
Correct command:
Remove-EmailAddressPolicy -Identinty StudentsGroups

Error output from -Name:
A parameter cannot be found that matches parameter name 'Name'.
    + CategoryInfo          : InvalidArgument: (:) [Remove-EmailAddressPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Remove-EmailAddressPolicy
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96002890-7e35-a0ab-a849-d94fef254fa8
* Version Independent ID: 2c4105db-b713-4829-393e-de355c5c60d4
* Content: [Choose the domain to use when creating Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/choose-domain-to-create-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/choose-domain-to-create-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/choose-domain-to-create-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jonimattila - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@jonimattila Thank you for submitting the feedback. We made the requested changes on PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/460.

Regards
Sriraman

**Comment by mypil** [comment]
@jonimattila - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
