### ISSUE TITLE
O365 Roadmap link broken

### ISSUE THREAD

**Issue by Gunner237** [MicrosoftDocs/OfficeDocs-O365ITPro#46]
The Office 365 Roadmap link to https://fasttrack.microsoft.com/roadmap leads to an error page, rather than the expected roadmap page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91eaa7f6-1a74-947f-80d0-8962b6df9b39
* Version Independent ID: 8b546fac-4393-7589-9c71-bd5860d0f0b2
* Content: [Stay on top of Office 365 changes](https://docs.microsoft.com/en-gb/office365/admin/manage/stay-on-top-of-updates?redirectSourcePath=%252fen-GB%252farticle%252f719f4904-cbdd-4889-a0cf-fbd7837dfecd&view=o365-worldwide)
* Content Source: [Office365-Admin/manage/stay-on-top-of-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/stay-on-top-of-updates.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@Gunner237 Thank you for pointing this out

I will get this link issue over to the o365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Referencing PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/129
