### ISSUE TITLE
the bottom note doesn't make sense it seems

### ISSUE THREAD

**Issue by HenrikBernhard** [MicrosoftDocs/OfficeDocs-O365ITPro#463]
Not sure if it should say "if you are only a member of" or similar - as you can't "be" the role itself
"If you are an Organization Management or Recipient Management"

and why does it say "on-premises" when also saying you have to use exchange online powershell to run the command?
Isn't this about changing the shared mailbox in the cloud, and the workaround listed in the tip, is for ensuring that the type is also updated onpremises after you have converted it in EXO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@HenrikBernhard - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@HenrikBernhard Thank you for submitting the feedback. The section of the document that you are pointing to relates to migrating mailbox to on-premise and then converting it to a shared mailbox, I have made the other changes that you rightly pointed out about the member and not the role itself on the Note section. The changes are tracked under PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/464 . Once again thank you for making our docs better.

Regards
Sriraman MS

**Comment by mypil** [comment]
@HenrikBernhard - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
