### ISSUE TITLE
What's New in Admin Center Notifications

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#466]
This is a nice start for letting us know what's new. However, the approach used by the Azure Portal with the pop-up message and the what's new page in each section of that portal is very good and it would be great if you could do something similar in the M365 admin center(s)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c772841-0d77-98e6-3e0e-af6f5c9d06a1
* Version Independent ID: 9e61ed55-3037-c7f2-4149-ca72ba789c9d
* Content: [What's new in the Microsoft 365 admin center?](https://docs.microsoft.com/en-us/office365/admin/whats-new-in-preview?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/whats-new-in-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/whats-new-in-preview.md)
* Service: **o365-administration**
* GitHub Login: @anfowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
