### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-O365ITPro#472]
How is this article last updated 20 March 2019 and it still references SkyDrive Pro and Lync? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43efaa70-69c2-01b1-e2d7-85f8b1f5e84e
* Version Independent ID: ce7bd43d-818d-d7d3-a66e-14b19e8d85fb
* Content: [Transfer data manually between two Office 365 accounts](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/transfer-data-manually?view=o365-worldwide)
* Content Source: [Office365-Admin/get-help-with-domains/transfer-data-manually.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/transfer-data-manually.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@michevnew - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@michevnew Thank you for your feedback. We have made the changes on PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/475 .

Regards
Sriraman MS

**Comment by mypil** [comment]
@officedocsbot close
