### ISSUE TITLE
Wrong translation to swedish.

### ISSUE THREAD

**Issue by michaelhenriksson** [MicrosoftDocs/OfficeDocs-O365ITPro#476]
Helpdesk admins can´t reset passwords for global admin,  should be = Helpdesk-administratörer kan INTE återställa lösenord för globala administratörer. Now its says they can in swedish..

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [Om Office 365-administratörsroller](https://docs.microsoft.com/sv-se/office365/admin/add-users/about-admin-roles?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @OfficeGlobal
@officedocsbot add label localization

**Comment by mypil** [comment]
@OfficeGlobal - Can you please assist with this Translation (Localization) issue?

**Comment by OfficeGlobal** [comment]
@MollyMalone , @mypil We're working on a fix (Bug 3352909)

**Comment by mypil** [comment]
@OfficeGlobal - Do you have any updates on this?

Thank you.

**Comment by OfficeGlobal** [comment]
@mypil , @michaelhenriksson the article has been HumanTranslated and published live - the reported text was updated

**Comment by mypil** [comment]
@michaelhenriksson - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
