### ISSUE TITLE
MFA turn features on or off

### ISSUE THREAD

**Issue by DBerrelez1** [MicrosoftDocs/OfficeDocs-O365ITPro#479]
Is there a way in  365 MFA to only require 2 step authentication(Passcode sent via text, phone verification) and disable the need for app password and code generator?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DBerrelez1 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@DBerrelez1 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
