### ISSUE TITLE
Imagens da documentação estão em inglês 

### ISSUE THREAD

**Issue by rubenssleme** [MicrosoftDocs/OfficeDocs-O365ITPro#48]
As imagens da documentação estão em inglês, aparentemente são mais antigas do que as ferramentas atuais.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 0176b533-4c38-8f7b-f4f8-2cd62d1e698c
* Version Independent ID: b9bdbc3a-e960-4d77-e556-d5ff6dcf0e69
* Content: [Caixas de correio de equipamentos e salas](https://docs.microsoft.com/pt-br/office365/admin/manage/room-and-equipment-mailboxes?redirectSourcePath=%252fpt-BR%252farticle%252f9f518a6d-1e2c-4d44-93f3-e19013a1552b&view=o365-worldwide)
* Content Source: [Office365-Admin/manage/room-and-equipment-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/room-and-equipment-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by AndreaBarr** [comment]
@rubenssleme Thank you for pointing this out 

I will get this images issues over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
@rubenssleme Thank you for reporting this.  Unfortunately we currently do not translate images that are included in machine translated articles. We hope to have a solution for this machine translating images later this year. 
Obrigado por relatar isso.  Infelizmente, atualmente não traduzimos imagens que estão incluídas em artigos traduzidos em máquina. Esperamos ter uma solução para esta máquina traduzir imagens ainda este ano.
