### ISSUE TITLE
Please update graphics

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/OfficeDocs-O365ITPro#482]
Please update the graphics in this article to reflect the new look. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1e37fbb-0bb1-7c14-fda3-376ed667834a
* Version Independent ID: 44237e1d-1792-2073-9d9a-0905a9e2c555
* Content: [Add your company branding to Office 365 Sign In page](https://docs.microsoft.com/en-us/office365/admin/setup/customize-sign-in-page?view=o365-worldwide)
* Content Source: [Office365-Admin/setup/customize-sign-in-page.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/customize-sign-in-page.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@cchambers-cap - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@cchambers-cap Thank you for your feedback. We have changed the graphics in the article to reflect our new sign-in page via PR  https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/487

**Comment by cchambers-cap** [comment]
Thanks!

Craig Chambers
(Sent from my phone)
________________________________

**Comment by mypil** [comment]
@cchambers-cap - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
