### ISSUE TITLE
Add FAQ: The Office 365 CDN does not support tenants with custom domains

### ISSUE THREAD

**Issue by kelleyvice-msft** [MicrosoftDocs/OfficeDocs-O365ITPro#483]
According to the CDN engineering team, tenants with custom domains cannot currently use the Office 365 CDN. I am updating the Office 365 CDN topics to reflect this with a note at the top of the article "Use the Office 365 Content Delivery Network (CDN) with SharePoint Online" (https://review.docs.microsoft.com/en-us/Office365/Enterprise/use-office-365-cdn-with-spo?branch=kvice-cdn). It probably makes sense to add a note about that here as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc99803-4432-cd7c-4747-0953276298d9
* Version Independent ID: 1d7554f1-8b1c-dd3a-18e6-1106ad2b3bcb
* Content: [Domains FAQ](https://docs.microsoft.com/en-us/office365/admin/setup/domains-faq?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@kelleyvice-msft - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@kelleyvice-msft We have added a note on top of the article via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/486

**Comment by kelleyvice-msft** [comment]
@msbemba - Thanks very much!

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@kelleyvice-msft - I'm reopening this issue since the PR content has not been merged yet. I will close this and notify you as soon as the doc owner approves and merges the content. Thank you.

**Comment by mypil** [comment]
@kelleyvice-msft - the PR created was closed by the doc owner @pebaum.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by ShawnTeng** [comment]
Hi Team, how can we receive another transferred domain from other registrar? We have got an Auth-info code, but we cannot find where to receive.
