### ISSUE TITLE
Kaizala regional availability 

### ISSUE THREAD

**Issue by Kwonsoonman** [MicrosoftDocs/OfficeDocs-O365ITPro#485]
add Sourth Korea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2033900c-d18a-cdd3-313c-7efed2ceb4ec
* Version Independent ID: 87b1f4a4-abb8-f3f6-241e-ca8b9b3d5015
* Content: [Kaizala regional availability](https://docs.microsoft.com/en-us/office365/kaizala/regional-availability#feedback)
* Content Source: [Office365-Kaizala/regional-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/regional-availability.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Kwonsoonman - Thank you for submitting feedback. 

Based on the article, it shows that Beginning in May 2019, Kaizala Pro will be commercially available internationally and this may already include South Korea. Looping in chuckedmonson to get confirmation.

@chuckedmonson - can you please confirm if South Korea will be part of this?

Thank you.

**Comment by chuckedmonson** [comment]
@Kwonsoonman - Yes, the release will include South Korea. A specific release date in May still hasn't been announced. Thank you.
