### ISSUE TITLE
List of roles not up to date

### ISSUE THREAD

**Issue by katrae** [MicrosoftDocs/OfficeDocs-O365ITPro#488]
The list of roles above do not match the current list of roles in the Portal:
 Billing administrator
Dynamics 365 service administrator
Customer Lockbox access approver
Exchange administrator
Helpdesk administrator
Kaizala administrator
License administrator
Skype for Business administrator
Message Center reader
Power BI service administrator
Reports reader
Service administrator
SharePoint administrator
Teams communications administrator
Teams communications support engineer
Teams communications support specialist
Teams Service Administrator
User management administrator 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f73b082-eed3-e2a8-50a3-ba1b85f2915d
* Version Independent ID: 05dbb561-a215-1cf8-de66-6ea901617719
* Content: [Quick help Types of users](https://docs.microsoft.com/en-us/office365/admin/misc/types-of-users?redirectSourcePath=%252fen-US%252farticle%252f0dc55430-98d6-4cbe-ba69-1a4ad29a967d&view=o365-worldwide)
* Content Source: [Office365-Admin/misc/types-of-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/types-of-users.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by katrae** [comment]
The above comment was made because this is the page the Admin Portal Active Users "Types of Users" links to. Perhaps the better fix is to change the link to this page: On the Active Users page, the link for "Types of users" would be better if it was linked to this page: 
https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide
as it matches the roles listed

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@katrae - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @katrae , Thank you for your feedback here. I can feel that you have redirected to the wrong page via Office365 admin panel active user whereas the correct information is available at https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide which you already have mentioned. For this correction, I would request to you send us a feedback using Feedback section in the bottom right corner of Office365 admin panel so that it can be routed to the correct team to make the necessary changes. 

Thanks.

**Comment by mypil** [comment]
@officedocsbot add label bug

**Comment by mypil** [comment]
@katrae - This issue you reported could be a bug within the O365 admin portal. 
I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

**Comment by mypil** [comment]
@officedocsbot close
