### ISSUE TITLE
Office365 MFA admins

### ISSUE THREAD

**Issue by Tuxhedoh** [MicrosoftDocs/OfficeDocs-O365ITPro#489]
Is there anyway for users who aren't Global Admins to enable users for MFA in the basic Office365 MFA feature?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Tuxhedoh - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Tuxhedoh** [comment]
https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide  first green Tip Box

**Comment by mypil** [comment]
@Tuxhedoh - Thank you for engaging with the community here for the docs.

I believe that only the Global Admins can enable users for MFA. 

@msbemba - Can you please confirm this? If yes, please do create a PR to put clarity on the article. 

Thank you.

**Comment by msbemba** [comment]
@Tuxhedoh Only Global Administrators have access to Enable/Disable MFA. I'll add a note or edit the Tip on the document  to make it clear. Hope this Helps!

**Comment by msbemba** [comment]
@Tuxhedoh Added more information to the TIP to explicitly mention that only GA's have access to Modify MFA setting, This is tracked Via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/495

**Comment by mypil** [comment]
@Tuxhedoh - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
