### ISSUE TITLE
Types of Public user no clarity

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/OfficeDocs-O365ITPro#49]
Public groups have 3 types of users - admins, members & subscribers. - as per the dialogue box. But the documentation url in the know more is not explaining the above 3 types. Kindly give clarification on types of users and the two radio buttons for managed and public in the same dialogue box.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b12ffd-4ecd-300c-8a7e-98993fec5126
* Version Independent ID: 2a8683a1-ba29-c368-8ac0-01e71de18459
* Content: [Kaizala public groups](https://docs.microsoft.com/en-gb/office365/kaizala/public-groups?redirectSourcePath=%252fen-us%252farticle%252fkaizala-public-groups-9bfde61a-6f8f-4aa8-aead-4ba0c10ed636)
* Content Source: [Office365-Kaizala/public-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/public-groups.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by AndreaBarr** [comment]
@sing-ideas Thank you for this feedback

I will get this information over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by sing-ideas** [comment]
This is not just a doc feed back. I am struggling to use the kaizala app. I created a Public Managed group and invited my B2C clients to install their app.

They opened the app and verified their mobile number tried to get into my company group but Kaizala is asking for Office 365 user ID and password for my end clients.

Confusion gets complicated when my clients are employed in MNCs where they use Office 365, unfortunately my clients are trying to use their employee login as if we are asking them to use their employer provided O365 login.

Now my household clients are to be treated like B2B clients via their O365 logins.

.
Singaravelu S, CFP

Get Outlook for Android

________________________________

**Comment by AndreaBarr** [comment]
@sing-ideas Thank you for the clarification. 

The document part has been sent over to the o365ITPro team. For the other part of this I want to get you to Support who have more resources than we do here to dig in and help find a solution to what your clients are seeing with Kaizala

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by j0rt3g4** [comment]
Hi, @sing-ideas  Did you try to do the live demo at
https://kaizalademo.office.com/ on steps 4, 5 and 6 gives you the permissions and if it's requested the O365 account checkbox checked it would be required to have that Sign-in access.

**Comment by j0rt3g4** [comment]
I've added the section with the related description of each role. Please check it out

**Comment by j0rt3g4** [comment]
@sing-ideas  I've added some more clarifications to #265

**Comment by mypil** [comment]
@sing-ideas - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
