### ISSUE TITLE
Asterisks instead of bold text

### ISSUE THREAD

**Issue by douglasac10** [MicrosoftDocs/OfficeDocs-O365ITPro#491]
Under Step 2 of the Software requirements section, there is a space between each set of asterisks surrounding the word File, so it's not bold and we can see the asterisks. Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc64ec1-ba7d-bcd3-51a6-a99a5d060e2c
* Version Independent ID: 2e6ca190-14c5-5ae5-780a-00ca99ccc9fd
* Content: [Plan for multi-factor authentication for Office 365 Deployments](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/multi-factor-authentication-plan?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/multi-factor-authentication-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/multi-factor-authentication-plan.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@douglasac10 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.
