### ISSUE TITLE
dns record removal

### ISSUE THREAD

**Issue by francescopoli** [MicrosoftDocs/OfficeDocs-O365ITPro#493]
it worth mention that after the domain has been validated in the portal, the record can be removed from the dns

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27249e0c-e601-b849-8404-ce0bb8155fce
* Version Independent ID: a308f156-998b-8ea9-5668-7a59e549cd10
* Content: [Gather the information you need to create Office 365 DNS records](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/information-for-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@francescopoli - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@francescopoli Thank you for your feedback. We have added a step to remove the DNS records after they are verified in o365. This can be tracked under PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/496

Regards
Sriraman MS

**Comment by mypil** [comment]
@francescopoli - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
