### ISSUE TITLE
Statement regarding shared mailbox support in Outlook mobile app incorrect

### ISSUE THREAD

**Issue by mdi-db** [MicrosoftDocs/OfficeDocs-O365ITPro#494]
The statement "The Outlook mobile app doesn't include the feature to access shared mailboxes, and it's not going to be added." is now incorrect as the feature is listed on the Office 365 roadmap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a258b08-9f84-d11d-a5c5-8c758dfd5d18
* Version Independent ID: 1b9620e1-c056-cb1d-72cd-623703365e79
* Content: [Create a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/create-a-shared-mailbox?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@mdi-db - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@mdi-db Thank you for your feedback. We have corrected the statement via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/497

**Comment by mypil** [comment]
@mdi-db - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
