### ISSUE TITLE
Link to Group Naming Policy feature, link please

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-O365ITPro#500]
Please insert link to the preview feature on Group naming  https://portal.azure.com/#blade/Microsoft_AAD_IAM/GroupsManagementMenuBlade/NamingPolicy 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0753620c-8f40-dc10-8884-b7b23f416bea
* Version Independent ID: 661ddf49-aefc-7f17-4c65-f3b09a10b9ce
* Content: [Plan for Office 365 Groups governance](https://docs.microsoft.com/en-us/office365/admin/create-groups/plan-for-groups-governance?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/Plan-for-groups-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/Plan-for-groups-governance.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@blouwagie - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@blouwagie - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by blouwagie** [comment]
Thank you Joyce

Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)
http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call <https://www.uberconference.com/bart40> is needed)

**Comment by mypil** [comment]
@officedocsbot close
