### ISSUE TITLE
Incorrect / Misleading information

### ISSUE THREAD

**Issue by celliott2012** [MicrosoftDocs/OfficeDocs-O365ITPro#507]
On Step 5 of this document, the wording needs to change. This is giving people the impression that no one is able to sign in at all. I’ve spoken to Microsoft reps in the past that have told me the same thing, however that’s clearly not the case. Step 5 is denoted with “direct sign-in is unnecessary”, however immediately before it states that they "won't be able to sign in".

So is signing in unnecessary, or is it not possible? That is not clear, and it should be for security reasons.
I found that sign in IS possible. The wording on this needs to change. Hopefully you can forward my concern to those able to modify this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@celliott2012 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@celliott2012 -  I believe the content has been updated to add the changes that you requested for. Kindly check and let us know if your issue has been resolved. Thanks.

**Comment by celliott2012** [comment]
Hi @mypil , I looked over this really quick and it looks really good. I do like the linking to the Remove A Former Employee document as well, I think that is a great addition.
Thank you for being attentive to this.
