### ISSUE TITLE
[LOC]Showing "![Kaizala 管理ポータルでの相互運用機能の設定] ページのスクリーン ショット](media/interop-settings-teams.png)"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#509]
https://docs.microsoft.com/ja-jp/office365/kaizala/teams-interop

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7da12ae2-58db-005f-215f-eb5275712a58
* Version Independent ID: 6d8c4a4b-7cae-962b-5029-4c62f8faa581
* Content: [Kaizala とマイクロソフトのチームとの間の相互運用機能](https://docs.microsoft.com/ja-jp/office365/kaizala/teams-interop)
* Content Source: [Office365-Kaizala/teams-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/teams-interop.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @OfficeGlobal
@officedocsbot add label localization

**Comment by mypil** [comment]
@OfficeGlobal - Can you please assist with this Translation (Localization) issue?

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @mypil article is updated. The image is displayed properly

**Comment by mypil** [comment]
hyoshioka0128 - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
