### ISSUE TITLE
[LOC]Showing "![Kaizala 管理ポータルで有効にするオプションを示すスクリーン ショットの設定] ページ](media/settings-showing-enable-option.png)"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ITPro#511]
https://docs.microsoft.com/ja-jp/office365/kaizala/backup-export-org-data

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b0928814-4438-0202-d809-4993eafefb52
* Version Independent ID: a6cdae3a-3ab3-92a3-573c-9146523f4caa
* Content: [バックアップし、Kaizala での組織データのエクスポート](https://docs.microsoft.com/ja-jp/office365/kaizala/backup-export-org-data)
* Content Source: [Office365-Kaizala/backup-export-org-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/backup-export-org-data.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @OfficeGlobal
@officedocsbot add label localization

**Comment by mypil** [comment]
@OfficeGlobal - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
hyoshioka0128 - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
