### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by dibbkd** [MicrosoftDocs/OfficeDocs-O365ITPro#514]
Last word in the "Office 365 groups..." paragraph says planer, should be "planner".

I came to this page trying to find how to change a Distribution lists to be an Office 365 group but didn't see how to do that on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbf6567-57c3-e359-8672-0c52cce6cc3b
* Version Independent ID: 2a0fbbad-b49d-7e6a-b5b8-3620d9fa9081
* Content: [Compare groups in Office 365](https://docs.microsoft.com/en-us/office365/admin/create-groups/compare-groups?redirectSourcePath=%252fen-US%252farticle%252f758759ad-63ee-4ea9-90a3-39f941897b7d&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dibbkd - Thank you for pointing this out.

PR #515 has been created to correct this typo error. 

We appreciate your contribution to make the docs better!
