### ISSUE TITLE
"It's not possible" to migrate is a bit overstated

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/OfficeDocs-O365ITPro#516]
It is possible, but there isn't any interface in the portal that does it.  #PowerShellFTW.  Something like this should work
o Delete the shared mailbox
o Create a group with the same name "new-unifiedgroup"
o Add any aliases set-unifiedgroup -identity id -EmailAddresses @{Add="newAddr"}
o Set each email address that one wants to be reachable externally to the primary, temporarily to sync DBEB set-unifiedgroup -identity id PrimaryEmailAddress "newAddr"
o Set the primary back to the original primary

Not pretty, but it should get the job done

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbf6567-57c3-e359-8672-0c52cce6cc3b
* Version Independent ID: 2a0fbbad-b49d-7e6a-b5b8-3620d9fa9081
* Content: [Compare groups in Office 365](https://docs.microsoft.com/en-us/office365/admin/create-groups/compare-groups?redirectSourcePath=%252fen-US%252farticle%252f758759ad-63ee-4ea9-90a3-39f941897b7d&view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ericleigh007 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@ericleigh007 Thank you for your feedback. The migration that the article refers to is to migrate content that is currently available in the  shared mailbox to an Office 365 group. You steps are correct and can be used if someone needs to have the same Email address for a Office 365 group that is currently linked with a shared mailbox.
Hope this Helps!

Regards
Sriraman

**Comment by mypil** [comment]
@ericleigh007 - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
