### ISSUE TITLE
Missing PowerShell instructions

### ISSUE THREAD

**Issue by greg2k** [MicrosoftDocs/OfficeDocs-O365ITPro#517]
Not sure if this is because it's not possible via PowerShell, but I'd like to know what cmdlet is needed for sending the new password email to a user. Having to do this through the UI is a chore when resetting passwords for multiple users at once. If I can add users, reset their passwords, force or not force a password change on next logon...why can't I trigger an email? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c77d35a7-8728-19e1-ada9-793ccfc08cd8
* Version Independent ID: 50ca3ae2-1a41-a66b-72df-e3b12c57e3bc
* Content: [Resend a user's password in Office 365 - Admin Help](https://docs.microsoft.com/en-us/office365/admin/add-users/resend-user-password?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/resend-user-password.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/resend-user-password.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@greg2k - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@greg2k Thank you for the feedback. If you need to change the password for an account, use the Set-MsolUserPassword cmdlet, However sending a notification email to the user or admin with the new password is not a possible option now via powershell. Below are the only switches that can be used against Set-msoluserpassword. Hope this helps!

Set-MsolUserPassword
   [-NewPassword <String>]
   [-ForceChangePassword <Boolean>]
   [-ForceChangePasswordOnly <Boolean>]
   -UserPrincipalName <String>
   [-TenantId <Guid>]


Sriraman MS

**Comment by greg2k** [comment]
Thanks Sriraman, I hope this is added to the cmdlet in future revisions. Regards,

Greg
