### ISSUE TITLE
Not able to login my outlook account in my app

### ISSUE THREAD

**Issue by vymallesh** [MicrosoftDocs/OfficeDocs-O365ITPro#519]
Hello,

I am developing an email client application in iOS.I am using "Mailcore2" library, to send/receive emails.I can be able to login with my company details , send/receive emails in my app which i developed using Mailcore2 library.My app supports all email clients, where any user can login their personal accounts too including Outlook.

Here comes my issue now, i had given my outlook credentials in my app.I can be able to login and send emails  (through SMTP) with outlook account which i logged in my app.But if i try to retrieve the emails (through IMAP) , i am not getting the list.

Here is the code which i am using to retrieve the emails,

    session = [[MCOIMAPSession alloc]init];
    session.hostname = @"imap-mail.outlook.com";
    session.username = @"dummy14@outlook.com";
    session.password  = @"Dummy14";
    session.port = 993;
    session.authType = MCOAuthTypeSASLLogin;
    session.connectionType = MCOConnectionTypeStartTLS;
    session.checkCertificateEnabled = false;

But i failed to fetch those emails using Mailcore library and it says an error , Below is that screen shot. 

![Screenshot 2019-05-27 at 8 03 52 PM](https://user-images.githubusercontent.com/19487513/58426620-a9a5d280-80ba-11e9-8cec-af9d4ad08ba3.png)

Do i need to implement OAuth2 as we do for Google, If yes to generate the access token do i need to undergo any payment subscription(any amount to paid ?).

Conclusion : Is it is possible to retrieve the emails without integrating Outlook login SDK or is it mandatory to integrate Login SDK in my app followed by Auth2 implementation.

Any help would be appreciated !!

Thanks,

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by vymallesh** [comment]
I didn't get you @mypil

**Comment by mypil** [comment]
@vymallesh - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
