### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ReQ6W7rFnaBxyfb** [MicrosoftDocs/OfficeDocs-O365ITPro#52]
This link is dead: If you're a user looking to reset or change your password, see I forgot the username or password for the account I use with Office. 
https://support.office.com/article/https://support.office.com/en-US/article/I-forgot-the-username-or-password-for-the-account-I-use-with-Office-eba0b4a2-c0ae-472c-99f6-bc63ee2425a8.aspx#bkmk_buschangepw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90059adc-9f5f-bc6c-caab-695e7ca1933a
* Version Independent ID: d71bf1c7-ee9d-4c7c-5b65-a8765366b064
* Content: [Let users reset their own passwords in Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/let-users-reset-passwords?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/let-users-reset-passwords.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/let-users-reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@ReQ6W7rFnaBxyfb Thank you for pointing this out

I will get this link information over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jamesrhea** [comment]
@AndreaBarr, the dead link is no longer present. This issue can be closed.
