### ISSUE TITLE
No Mention Of Mapping Network Drive

### ISSUE THREAD

**Issue by brandonkirsch** [MicrosoftDocs/OfficeDocs-O365ITPro#520]
The internet is filled with guides on how to map a Sharepoint O365 Documents Library as a local Network Drive, but I can't find any of this information in the official documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c454f78-7336-f872-c945-23c2997856af
* Version Independent ID: 4d7e4a09-122e-d291-769b-93a4dffb0942
* Content: [Set up Office 365 file storage and sharing](https://docs.microsoft.com/en-us/office365/admin/setup/set-up-file-storage-and-sharing?view=o365-worldwide)
* Content Source: [Office365-Admin/setup/set-up-file-storage-and-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/set-up-file-storage-and-sharing.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@brandonkirsch - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@brandonkirsch Thank you for reaching out to improve MS Doc, I will have sorted out soonest.

**Comment by mypil** [comment]
@brandonkirsch - From our understanding, the issue has been answered by Reeced40.  If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
