### ISSUE TITLE
[LOC] Invalid link in the article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-O365ITPro#521]
**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/office365/admin/manage/manage?view=o365-worldwide
2. Check "_Fix OneDrive sync problems_" link text (https://support.office.com/article/e12c6a8b-4bbe-4391-9c23-1a52b55a1967)
3. Click the link --> 404 error page

**Expected:** link should redirect to a valid page or be removed from the article

![image](https://user-images.githubusercontent.com/47977325/58561859-68cbcc00-8228-11e9-8441-78b44713f453.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGlobal - Thank you for submitting feedback.

I will get this issue over to the O365ITPro  writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@OfficeGlobal Thank you for reaching out, I'm looking into it.

**Comment by mypil** [comment]
@OfficeGlobal - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
