### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGSX** [MicrosoftDocs/OfficeDocs-O365ITPro#525]
There is an invalid link in an article

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/office365/admin/misc/self-service-sign-up?view=o365-worldwide
2. Search for "Quick Start: Register for the Microsoft Business Center "
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link should either redirect correctly or be removed

**GH article**:
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/self-service-sign-up.md

![image](https://user-images.githubusercontent.com/16706698/58637879-cc6efb80-82f3-11e9-9441-b90b68be0388.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGSX - Thank you for pointing this out.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by Reeced40** [comment]
@OfficeGSX Thank you for your feedback, I will investigate further.

**Comment by mypil** [comment]
@OfficeGSX - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
