### ISSUE TITLE
Why isn't there instructions on converting to a shared mailbox from the main Admin Center's Active Users page?

### ISSUE THREAD

**Issue by Shlibidi** [MicrosoftDocs/OfficeDocs-O365ITPro#528]
Directing admins to the Exchange admin center seems unnecessary as, it's much easier and faster to convert a user account's mailbox to a shared mailbox from the main Admin Center's Active Users page, no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Shlibidi - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
Raised a PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/532 to merge the media content

**Comment by msbemba** [comment]
Thank you for your feedback. We have made changes to the Doc via PR  https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/546

**Comment by mypil** [comment]
@Shlibidi - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
