### ISSUE TITLE
Microsoft 365 usage analytics template

### ISSUE THREAD

**Issue by hfulks** [MicrosoftDocs/OfficeDocs-O365ITPro#53]
I downloaded the template and entered my organization's tenant ID but the template generated 2 pages of errors. Completely unusable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fdd664-c2d2-7712-fd41-3745c52d1442
* Version Independent ID: 0dfdadc8-15f0-dd7e-0efc-9a2565f7b519
* Content: [Customize the reports in Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/customize-reports?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/customize-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/customize-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@hfulks THank you for this feedback

I am not sure why you received the error. Let get you over to Support who has more resources to dig in and find resolutions.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
