### ISSUE TITLE
Step 1.6 isn't possible with Power BI as the example

### ISSUE THREAD

**Issue by yellowbrickcode** [MicrosoftDocs/OfficeDocs-O365ITPro#530]
I tried to follow the instructions but get stuck at 1.6: "Follow the email link that shows your email address and a Yes, that's me button.". The email that I receive from Power BI with the confirmation code in it doesn't have the "Yes, that's me" button. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24eaf551-7e49-ee4a-2979-8515f92d4d2a
* Version Independent ID: 67e53343-d996-ce5e-4742-0c0d819fbca1
* Content: [Do an admin takeover in Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/become-the-admin?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/become-the-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/become-the-admin.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@yellowbrickcode - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@yellowbrickcode - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
