### ISSUE TITLE
License removal and data loss

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/OfficeDocs-O365ITPro#531]
Assignment of an Exchange Online license means the provisioning of a mailbox. With the removal of an Exchange Online license for a shared mailbox, is there a risk of data loss due to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 869d9464-bef4-95df-24c2-ad8c2f676cb4
* Version Independent ID: 87399719-c92a-a8ee-e64f-bf66940469e2
* Content: [Remove license from shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/remove-license-from-shared-mailbox?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/remove-license-from-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/remove-license-from-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@FMCUSystemAdmins - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by adefowler** [comment]
@mypil - I'm already working on this with engineering. I"ll update the topic when I get the information.

**Comment by mypil** [comment]
@adefowler - We would like to follow up. Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@adefowler - Any updates on this?

**Comment by mypil** [comment]
@adefowler - We would like to follow up. Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@adefowler - We would like to follow up. Any updates on this?

Thank you.

cc: @scotvidican

**Comment by mypil** [comment]
@adefowler - We would like to follow up. Do you have any updates from the engineering team?

cc: @scotvidican @AndreaBarr @kenwith

**Comment by mypil** [comment]
@msbemba - As discussed, kindly assist with this issue. Thank you.

**Comment by msbemba** [comment]
@FMCUSystemAdmins Thank you for the question. When the exchange online license is unassigned, there is no risk of data loss if the mailbox is less than 50 GB. In short Shared mailboxes don't need a license unless the mailbox has over 50GB of data.. The same has been updated on the Document for reference.

Hope this Helps!

Thanks
Sri

**Comment by FMCUSystemAdmins** [comment]
Great, thank you so much for looking into this and updating the documentation!
Thanks,
Craig Jones
Sr. System Administrator
Firstmark Credit Union | Information Technology
2023 Gold Canyon Dr. | San Antonio, TX 78232
210.341.9602 x10514
craigj@firstmarkcu.org<mailto:mcraigj@firstmarkcu.org> | www.firstmarkcu.org<http://www.firstmarkcu.org/>
CONFIDENTIAL NOTIFICATION: This electronic mail message and any files or documents transmitted with it contain information belonging to the sender that is confidential and may be legally privileged.  This information is intended for the use of the individual or entity to which it is addressed.  If you are not the intended recipient, be advised that you may have received this electronic mail in error and that any use, including but not limited to, disclosure, copying, distribution, forwarding, printing, dissemination of any kind, or action taken in reaction to or reliance on the contents of the information is strictly prohibited.  If you have received this electronic mail message in error, please immediately delete it as permanently as possible and notify the sender.

**Comment by mypil** [comment]
@FMCUSystemAdmins - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
