### ISSUE TITLE
Requirement for target release

### ISSUE THREAD

**Issue by MeenakshiDeepika** [MicrosoftDocs/OfficeDocs-O365ITPro#533]
I could like to understand if there is any license requirement when we set target release for respective users.

Also how long is the feedback period open for target release , when does the first release go live for all users ?

**Comment by mypil** [comment]
@MeenakshiDeepika - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
