### ISSUE TITLE
Direct debit availability

### ISSUE THREAD

**Issue by jkinma39** [MicrosoftDocs/OfficeDocs-O365ITPro#536]
The comment in this document that "Paying by using a bank account is not available in Japan" while technically correct is not the whole story.  Paying by bank account is only available in the United States and the EU where the currency is the Euro.  The document, "Add, update, or remove a credit card or bank account in Office 365 for business", has a better note that can be used here as well, "Paying by using a bank account is not available in some countries or regions".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d660a70-e4c7-8f70-bd5c-32ee23c9eeec
* Version Independent ID: d1166c15-d29c-9a28-e8ca-8c11f5b45ade
* Content: [Change your payment method for Office 365 for business](https://docs.microsoft.com/en-au/office365/admin/subscriptions-and-billing/change-payment-method?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/change-payment-method.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/change-payment-method.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jkinma39 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by cmcatee-MSFT** [comment]
@mypil @jkinma39 I've already fixed the topic. Thanks!
