### ISSUE TITLE
Please turn off automatic translation.

### ISSUE THREAD

**Issue by Pikaloko** [MicrosoftDocs/OfficeDocs-O365ITPro#538]
Text is unreadable!

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 6dc99803-4432-cd7c-4747-0953276298d9
* Version Independent ID: 1d7554f1-8b1c-dd3a-18e6-1106ad2b3bcb
* Content: [Często zadawane pytania dotyczące domen](https://docs.microsoft.com/pl-pl/office365/admin/setup/domains-faq?redirectSourcePath=%252farticle%252f5980474a-097f-4f21-a864-21245314957f.aspx&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @OfficeGlobal
@officedocsbot add label localization

**Comment by mypil** [comment]
@OfficeGlobal - Can you please assist with this Translation (Localization) issue?

**Comment by OfficeGlobal** [comment]
Working on a fix (Bug 3406239)

**Comment by OfficeGlobal** [comment]
@Pikaloko , @mypil the article has been HumanTranslated and published live

**Comment by mypil** [comment]
@Pikaloko - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
