### ISSUE TITLE
Docs refer to incorrect UI

### ISSUE THREAD

**Issue by tylerbutler** [MicrosoftDocs/OfficeDocs-O365ITPro#541]
The documentation for the section explaining how "To turn off add-in acquisition" has a fourth step that reads:

&gt; Click the toggle next to **Allow people to use third-party hosted storage services** so that it's in the **Off** position

That setting (Allow people to use third-party hosted storage services) has nothing to do with addins. I assume the text is meant to refer to a different UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d424b-6f62-e70c-9c2d-ad779ffa6c3b
* Version Independent ID: e4597136-bfe8-4230-da83-f806a1126005
* Content: [Manage deployment of Office 365 add-ins in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by tylerbutler** [comment]
Looks like it was introduced in af334c2a8e7ad54f108e2586768ad0f314b62f7a.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@tylerbutler - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@tylerbutler  Thank you for the feedback. We have made changes to the document via PR  https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/545

**Comment by mypil** [comment]
@tylerbutler - From our understanding, the issue has been resolved. For more details, please check on this [comment](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/545#issuecomment-500381822). If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
