### ISSUE TITLE
Forwading not showing in Exchange Admin Center

### ISSUE THREAD

**Issue by rico-neuendorf** [MicrosoftDocs/OfficeDocs-O365ITPro#543]
Hi there,
if I forward addresses like this, the forwarding is not showing in our Exchange admin center.
However if someone tries to set it up there an error message occours saying that a forwading is already configured.
We tested that with normal, licenced users and with shared mailboxes.

Why is it so?

Best regards
Rico

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8183c4-8fef-2e30-b84d-ad48d7a5278b
* Version Independent ID: f29c45cf-0d0c-a30b-c8c7-58abd4e7e3d4
* Content: [Configure email forwarding in Office 365](https://docs.microsoft.com/en-us/office365/admin/email/configure-email-forwarding?view=o365-worldwide)
* Content Source: [Office365-Admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rico-neuendorf - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@rico-neuendorf - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by rico-neuendorf** [comment]
@mypil - I got an answer by the support but I am quite happy with it.

There is a difference between setting up the forwarding via the MS 365 Admin Center and the Exchange Online Center.

While  Admin Center sets up a "FORWARDING SMTP ADDRESS", the Exchange Center sets up a "FORWADING ADDRESS" - so no SMTP address..

Stated by the support the main difference between these attributes is that forwarding to a SMTP address simply provides you the feature to forward to external addresses while the normal forwarding is for internal mailboxes.

Firstly I am unhappy that there are two attributes provided for the "same action" I like to achieve and secondly I am confused that the Admin Center provides the more flexible option.

But hey, mystery solved. We just have to get used to, to configure it via either one or the other center.

Thanks
Rico

**Comment by mypil** [comment]
@rico-neuendorf - Glad to know that your issue has been answered by technical support. I will proceed to close this issue now. 

Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
