### ISSUE TITLE
Missing Products

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#547]
It would be great if this included data about PowerBI usage, as well as all of the other products in O365. It it ironic that this Usage Analytics template does not include data about the product that is used to create it :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fdd664-c2d2-7712-fd41-3745c52d1442
* Version Independent ID: 0dfdadc8-15f0-dd7e-0efc-9a2565f7b519
* Content: [Customize the reports in Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/customize-reports?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/customize-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/customize-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@Sirkkuw - We would like to follow up. Can you please share your insights on this issue?

Thank you.

**Comment by Sirkkuw** [comment]
@mypil The topic is focused on how to modify the reports that are generated for Office 365 for business usage, not so much PowerBI documentation. PowerBI has their own help docs here: https://docs.microsoft.com/en-us/power-bi/

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue you raised has been answered by Sirkkuw. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
