### ISSUE TITLE
RESET and CHANGE password with AAD

### ISSUE THREAD

**Issue by pieroramos** [MicrosoftDocs/OfficeDocs-O365ITPro#548]
Hi. In the description page of AAD FREE and BASIC is wrong 
https://azure.microsoft.com/en-us/pricing/details/active-directory/,  because it says that AAD Free can perform only  "Self-Service Password Change for cloud users " and AAD Basic  "Self-Service Password Reset for cloud users ". I have clients with AAD FREE that comes included in Office 365 Business Premium and they can do both (RESET and CHANGE). 
I have tried it personally and it works correctly RESET and CHANGE password with AAD Free with cloud users. 
Regards
Piero

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90059adc-9f5f-bc6c-caab-695e7ca1933a
* Version Independent ID: d71bf1c7-ee9d-4c7c-5b65-a8765366b064
* Content: [Let users reset their own passwords in Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/let-users-reset-passwords?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/let-users-reset-passwords.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/let-users-reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pieroramos - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@pieroramos Thank you for your feedback. The document in reference does say that the self-service password reset is available in all versions of AAD. Let me know if you have any questions.

**Comment by mypil** [comment]
@pieroramos - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by pieroramos** [comment]
Hi @msbemba 
Sorry, maybe I wasn't clear. I'm just trying to say that according to the documentation (https://azure.microsoft.com/en-us/pricing/details/active-directory/) it says: AAD Free can only "Self-Service Password Change for cloud user", but performing a test I see that AAD Free can perform the same characteristic that AAD Basic (Self-Service Password Change for cloud user + Self-Service Password Reset for cloud user) .

![image](https://user-images.githubusercontent.com/40305441/59819589-86a3c280-92f6-11e9-80ce-784154100477.png)

regards
Piero

**Comment by msbemba** [comment]
@pieroramos  Thank you. I see the changes that is required now on https://azure.microsoft.com/en-us/pricing/details/active-directory/ . We'll work with the concerned team to get this changed.

**Comment by vinayshekhar-github** [comment]
@msbemba - 
1. Just to clarify the query from @pieroramos. So Self Service Password Reset is available for Cloud users in Azure AD FREE as well, is my understanding Correct???
2. Could you also please include the Smart Lockout feature included in the Azure AD Pricing table, so it clearly calls out which license it is available with ???

Appreciate your help.

**Comment by msbemba** [comment]
@vinayshekhar-github  @pieroramos  Thank you For your feedback. The suggested feedback is not for the current document but for the Azure pricing page.  We are trying to reach out to the respective team who may be in position to  address your feedback.

Thanks
Sri

**Comment by mypil** [comment]
@cmcatee-MSFT - looping you in as FYI.

**Comment by ckssaas** [comment]
@pieroramos @msbemba My team can confirm the same experience in multiple tenants. Either the pricing document is wrong or the functional differences between SSPC/SSPR are not being implemented correctly by Azure. I attempted to open this topic of conversation on a different page but received unsatisfactory responses. I would  appreciate a resolution. Here is a link to git, thanks: https://github.com/MicrosoftDocs/azure-docs/issues/34423#issuecomment-512028370

**Comment by cmcatee-MSFT** [comment]
@pieroramos The AAD pricing page is correct as written. Password change is included with Free. Password reset is included starting with Basic. The fact that you can do both likely indicates a licensing compliance issue with your tenant.

**Comment by curtand** [comment]
License compliance is not always enforced in Azure AD resource management actions. A person without the required license can still perform those actions, but it puts the organization out of compliance.
