### ISSUE TITLE
May 2019 - Modern authentication setting

### ISSUE THREAD

**Issue by 0acff4be45** [MicrosoftDocs/OfficeDocs-O365ITPro#549]
"Modern authentication. Yes, there is a new setting to turn on Modern authentication! To check it out, go to Settings &gt; Services & add-ins &gt; Modern authentication."

I am unable to find this setting while logged in with a global admin account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c772841-0d77-98e6-3e0e-af6f5c9d06a1
* Version Independent ID: 9e61ed55-3037-c7f2-4149-ca72ba789c9d
* Content: [What's new in the Microsoft 365 admin center?](https://docs.microsoft.com/en-us/office365/admin/whats-new-in-preview?view=o365-worldwide)
* Content Source: [Office365-Admin/whats-new-in-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/whats-new-in-preview.md)
* Service: **o365-administration**
* GitHub Login: @anfowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@0acff4be45 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@0acff4be45 Thank you for your feedback. We have made changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/553

**Comment by adefowler** [comment]
Some new features are rolled out slowly. If you're not seeing the change yet, just be patient, it will show up!

**Comment by mypil** [comment]
@0acff4be45 - From our understanding, the issue you raised has been answered by adefowler. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
