### ISSUE TITLE
Moving to Yearly Prepaid

### ISSUE THREAD

**Issue by davihar** [MicrosoftDocs/OfficeDocs-O365ITPro#551]
I had month to month Essential.  I purchased a prepaid Business yearly that I added to my account.  It was confusing that I could not reduce the Essential license count to zero.  It said I had to cancel the subscription.  Then I got an email about when my data will be deleted pointing to this page.  First, it is alarming to get such an email.  Second, this documentation should be clearer about if my data will be deleted in my situation.  Third, the email should not be sent if my data is going to be retained due to the prepaid license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0721ffec-3115-1479-a73f-e74706d41410
* Version Independent ID: d34d5bdf-4380-e2e0-fa47-10057f7ef0ea
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/what-if-my-subscription-expires?redirectSourcePath=%252farticle%252f4436582f-211a-45ec-b72e-33647f97d8a3&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@davihar - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by davihar** [comment]
OK, I opened a ticket and my data is safe because I have licenses.  The support person said I received automated emails and I should ignore the one that said my data was going to be deleted.  Obviously this is not an optimal user experience.  Are you going to update the documentation to say to ignore automated emails?  😉

**Comment by mypil** [comment]
@davihar - Thank you for the additional feedback but the issue you encountered might just be an isolated case. Hence, the current documentation remains valid. We will proceed to close this issue now.

**Comment by mypil** [comment]
@officedocsbot close
