### ISSUE TITLE
Outdated - No "type" field available

### ISSUE THREAD

**Issue by ScottBeeson** [MicrosoftDocs/OfficeDocs-O365ITPro#552]
I do not see a "type" field. Is this document outdated or is there something else I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c8e89a-d001-eb11-d1e4-e2525561307a
* Version Independent ID: 42c5f231-7a58-4e92-2a43-eb35bcf8c410
* Content: [Create distribution lists in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/setup/create-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/create-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/create-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by ScottBeeson** [comment]
Nevermind, I was accessing this from the Exchange admin interface and creating a group from there.  You have to do this from the main admin center to see the "type" field.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ScottBeeson - Thank you for submitting feedback.

I would like to clarify with you. Is there anything within the document that you suggest to be edited/updated? If there's none, then feel free to close this issue.

**Comment by mypil** [comment]
@ScottBeeson - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
