### ISSUE TITLE
Confusing headings

### ISSUE THREAD

**Issue by SuperTekBoy** [MicrosoftDocs/OfficeDocs-O365ITPro#554]
The heading titled "Which distribution lists can be upgraded?" is for a table of groups that can't actually be upgraded. While the following text mentions the table below cannot be upgraded the title causes confusion and is not representative of the majority of the section. Propose a change of the title to "Which distribution lists cannot be upgraded". Or split CAN and CANNOT into two sections to avoid confusion. I have seen a few people get confused reading this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10dbb56e-1c52-8fa0-0d3d-bab6d50519d0
* Version Independent ID: ff6585cd-9d68-ed1c-ee5f-1f451457dbef
* Content: [Upgrade distribution lists to Office 365 Groups in Outlook](https://docs.microsoft.com/en-us/office365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SuperTekBoy - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Solving with PR #560

**Comment by mypil** [comment]
@SuperTekBoy - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
