### ISSUE TITLE
Navigation bar has wrong title

### ISSUE THREAD

**Issue by douglasac10** [MicrosoftDocs/OfficeDocs-O365ITPro#555]
This page is listed in the navigation bar as "Stay on topc of changes", I imagine it's meant to be "Stay on top of changes".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91eaa7f6-1a74-947f-80d0-8962b6df9b39
* Version Independent ID: 8b546fac-4393-7589-9c71-bd5860d0f0b2
* Content: [Stay on top of Office 365 changes](https://docs.microsoft.com/en-us/office365/admin/manage/stay-on-top-of-updates?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/stay-on-top-of-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/stay-on-top-of-updates.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@douglasac10 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Solving Issue with PR #559

**Comment by mypil** [comment]
@douglasac10 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
