### ISSUE TITLE
Update bank inforamtion for India 

### ISSUE THREAD

**Issue by LydiaDong** [MicrosoftDocs/OfficeDocs-O365ITPro#562]
Dear Team,

Could you please help to update the public article for : https://support.office.com/en-us/article/Pay-for-your-Office-365-for-business-subscription-734f4aab-df2d-4e9b-8cb1-691910bde216?ui=en-US&rs=en-US&ad=US  

When we select India as the country, there is no payment bank info displayed. Please help to update bank info for India customer for better customer service experience. Thanks very much. 

---
#### Document [[Details]()](url)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 682c512f-ad8a-2513-d7cd-87db2c0bd9fb
* Version Independent ID: 72eacd6a-5b78-1802-3941-8d6419e907fa
* Content: [Payment information for India](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/pay/india?view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/pay/india.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/pay/india.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@LydiaDong - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@LydiaDong - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by LydiaDong** [comment]
Dear Joyce and Team,

Thanks for your support.

This link https://docs.microsoft.com/office365/admin/contact-support-for-business-products<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Foffice365%2Fadmin%2Fcontact-support-for-business-products&data=02%7C01%7Cv-lyddo%40microsoft.com%7Ce6316dd7e175455a738e08d6f0e301a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636961255107088948&sdata=djGt6GAa5WjE1ZMCvdvL3DYPx%2FAQsm7%2B03h1R0fGoWU%3D&reserved=0> redirected to Office<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Foffice365%2Fadmin%2Fcontact-support-for-business-products&data=02%7C01%7Cv-lyddo%40microsoft.com%7Ce6316dd7e175455a738e08d6f0e301a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636961255107088948&sdata=djGt6GAa5WjE1ZMCvdvL3DYPx%2FAQsm7%2B03h1R0fGoWU%3D&reserved=0> 365 support. Actually here we are Office 365 billing support. We escalate the request for our customer to get better experience for our public article. Could you please help on this request or help to involve related team? Really appreciate.

Best Regards
Lydia Dong

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@LydiaDong - Thank you for this additional feedback. I reopened this issue and will get help from the doc owner.

@cmcatee-MSFT - Can you please advise on how to proceed to resolve this issue? 

Thank you.

**Comment by cmcatee-MSFT** [comment]
@mypil I am investigating.

**Comment by cmcatee-MSFT** [comment]
@LydiaDong As I understand it, there are 2 types of invoices issued to customers in India, depending on what products they have. We don't want customers accidentally submitting payment to the wrong account, so we therefore do not include the addresses on this page, and instead instruct customers to send payment to the address listed on their invoice.
