### ISSUE TITLE
Pay Now feature

### ISSUE THREAD

**Issue by DanielManta** [MicrosoftDocs/OfficeDocs-O365ITPro#564]
Hello, 

Pay now feature is available to the Admin that added the credit card used for subscription. Other Global Administrator will not see this option. 

Thank you, 
Daniel

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DanielManta - We would like to get some details from you. Can you please share what specific issue you have and for which article? Kindly provide the article link as well so we can investigate.

Thank you.

**Comment by DanielManta** [comment]
Hi Joyce,

Issue is with Pay Now option presented in this article https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/pay-for-your-subscription?view=o365-worldwide .
From testing I found that only the Global/Billing Administrator that added the credit card on a specific subscription will see the Pay Now feature. Other Global Administrators will not see it and they can only add a new cc.

Thank you,
Daniel

**Comment by mypil** [comment]
@DanielManta - Thank you for submitting feedback and sharing more details.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@DanielManta - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
