### ISSUE TITLE
Affected services in Office 365

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#565]
The note above states that targeted release applies to Office 365, SharePoint Online and Exchange Online. The reference to Office 365 is rather vague, please make this more specific, e.g., does it apply the admin centers, which services/apps within O365 will get updated through the targeted release process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046ce912-1f0f-81b9-1126-5558e93df52a
* Version Independent ID: 755e811c-2aa0-9dc5-6846-93a6c401b01e
* Content: [Set up the Standard or Targeted release options in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/release-options-in-office-365?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@DeanGross  Thank you for your feedback. You are right, I have Made a change to the note to explicitly mention o365 Suite so that it is not vague. The same can be tracked on PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/574

**Comment by msbemba** [comment]
@DeanGross We checked with the author and seems like this document is correctly written. Once again, thank you for your feedback.

Thanks
Sri

**Comment by mypil** [comment]
@officedocsbot close

**Comment by hrfmjp** [comment]
After all, what does "Office 365" include?
