### ISSUE TITLE
High Contrast Theme 

### ISSUE THREAD

**Issue by rudyvalentino** [MicrosoftDocs/OfficeDocs-O365ITPro#567]
After setting the Prevent users from overriding theme toggle to On end user selection of the High Contrast theme is not preserved.  The setting was modified using steps 1 through 6 in the
Customize the Office 365 theme for your organization article at https://docs.microsoft.com/en-us/office365/admin/setup/customize-your-organization-theme?view=o365-worldwide

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rudyvalentino - We appreciate your efforts to clarify the docs. 

Can we get more details from you? Could you please assist us by suggesting how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by rudyvalentino** [comment]
The verbiage for Prevent users from overriding theme setting states, “Flip this toggle to prevent users from choosing their own theme from our theme selection. This does not prevent users from being able to set a high contrast theme”.   The behavior that is being experienced is once the setting is toggled to On an end user selects the High Contrast (blue) theme after a page refresh or signing in/out of Office 365 the theme reverts back to Default (black).  When the Prevent users from overriding theme value is set Off the selection of a High Contrast theme is preserved on page refreshes and signing in/out of Office 365.  While an end user can set a High Contrast theme when the Prevent users from overriding theme value is set On the selection is not preserved, which results in an end user having to continuously modify the theme selection.  Is the before mentioned user experience the desired behavior of the setting or are other configurations required to preserve the High Contrast theme selection?

**Comment by mypil** [comment]
@rudyvalentino - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
