### ISSUE TITLE
GCC Tennant Licensing?

### ISSUE THREAD

**Issue by PSJeffH** [MicrosoftDocs/OfficeDocs-O365ITPro#569]
This article doesn't advise if it applies to users in the Office 365 GCC environment as our licensing options are G1, G3, and G5. Can you update the article to include this environment and the required licensing or advise if this isn't supported.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PSJeffH - We would like to get some details from you. Can you please share what specific issue you have and for which article? Kindly provide the article link as well so we can investigate.

Thank you.

**Comment by PSJeffH** [comment]
Oh, my apologies I thought it included the link already. 

Link in Question which I'd like updated: https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy?view=o365-worldwide

My Tennant for Office 365 is Government and it becomes difficult to determine what features we have, and can do when there are different Tenants of Office 365.

GCC Link on GCC Details https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc 

Licensing requirements as it doesn't mention GCC environments. 

To use the Groups naming policy feature, the following people need an Azure Active Directory Premium P1 license or Azure AD Basic EDU license:

**Comment by msbemba** [comment]
@PSJeffH Thank you for the feedback. The license requirement in the article refers to the Plan that is needed to use group naming policy feature. 

In your case the Azure Active Directory Premium P1 license  is an add on SKU for Office 365 SKU's(GCC or enterprise editions ). In short, If your license(G1 , G3 or G5  includes Azure AD Premium Plan 1 then you will be able to access the group naming policy feature, Else you will have to purchase this as add-on.  Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@PSJeffH - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
