### ISSUE TITLE
Documentation needs updated

### ISSUE THREAD

**Issue by RustyNailz77** [MicrosoftDocs/OfficeDocs-O365ITPro#57]
This article states that "Power BI is a free service for users in your organization to connect to, analyze, and securely share data with others. "  This is not quite correct.  You cannot share content without a Pro license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27380ae-e2d6-7d32-b573-5c9a08592164
* Version Independent ID: b17e2ed4-9b79-0fd3-efa9-e62f73dc5cb4
* Content: [Using self-service sign up in your organization](https://docs.microsoft.com/en-us/office365/admin/misc/self-service-sign-up?redirectSourcePath=%2Farticle%2F4f8712ff-9346-4c6c-bb63-a21ad7a62cbd&view=o365-worldwide)
* Content Source: [Office365-Admin/misc/self-service-sign-up.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/self-service-sign-up.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by AndreaBarr** [comment]
@RustyNailz77 Thank you for pointing this out

I will get this update information over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
