### ISSUE TITLE
Please add DLL version for the feature

### ISSUE THREAD

**Issue by FullStackEngN** [MicrosoftDocs/OfficeDocs-O365ITPro#579]
I did test, if I only enable registry, it won't work.
I found this web article(https://blog.kloud.com.au/2015/11/07/modern-authentication-updates-for-office-2013-msi-based/), and it mentioned 5 DLLs version requirement, I did test, install Office 2013RTM, and just install the 5 KBs, then enable registry key, then MFA works for my Office 2013.
So I think it's better that MS releases the DLLs version requirement to avoid confusion.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db5aea7-bb2e-f349-7518-fc4fd396b3da
* Version Independent ID: b4112301-d38e-4a77-847b-f41bd7bca0f1
* Content: [Enable Modern Authentication for Office 2013 on Windows devices](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@FullStackEngN - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@FullStackEngN Thank you for your feedback. We have a note on this documnet which directs you to https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/multi-factor-authentication-plan?view=o365-worldwide#software-requirements and that has the information you are looking for.

Hope this helps!

Thanks
Sri

**Comment by FullStackEngN** [comment]
Thanks Sriraman, that’s what I’m looking for.

Regards
FullStackEngN
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mypil** [comment]
@FullStackEngN - From our understanding, the issue you raised has been answered by Sriraman. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
