### ISSUE TITLE
Require approval for some users

### ISSUE THREAD

**Issue by thomasdewulf** [MicrosoftDocs/OfficeDocs-O365ITPro#580]
Is it possible to require approval for a certain subgroup of users? For example: All users not in group 'X', all users with a domain that ends with 'volunteer.company.com'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0176b533-4c38-8f7b-f4f8-2cd62d1e698c
* Version Independent ID: b9bdbc3a-e960-4d77-e556-d5ff6dcf0e69
* Content: [Room and equipment mailboxes](https://docs.microsoft.com/en-us/office365/admin/manage/room-and-equipment-mailboxes?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/room-and-equipment-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/room-and-equipment-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@thomasdewulf - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
