### ISSUE TITLE
Multiple user computers

### ISSUE THREAD

**Issue by NetMage** [MicrosoftDocs/OfficeDocs-O365ITPro#581]
For computers shared by multiple users with multiple logons, having an HKCU key is horribly painful. It should also have an HKLM equivalent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db5aea7-bb2e-f349-7518-fc4fd396b3da
* Version Independent ID: b4112301-d38e-4a77-847b-f41bd7bca0f1
* Content: [Enable Modern Authentication for Office 2013 on Windows devices](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@NetMage -  Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://office365.uservoice.com**

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
