### ISSUE TITLE
Admin via PowerShell?

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-O365ITPro#583]
Where's the information regarding adding admins to groups via powershell? If I have a large number of groups in a large organisation I want to be able to add a user as admin to many groups in bulk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa3130f-f429-4305-5114-915d1ebb9762
* Version Independent ID: 5902f898-f078-6025-8dbc-35d121d80ec9
* Content: [Add, block, or remove Yammer users](https://docs.microsoft.com/en-us/yammer/manage-yammer-users/add-block-or-remove-users#feedback)
* Content Source: [yammer/manage-yammer-users/add-block-or-remove-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-users/add-block-or-remove-users.md)
* Product: **office-online-server**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@angoo-atea - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by angoo-atea** [comment]
Hi @mypil, many thanks. I've now opened a support request: [Ticket #:15065739] "add specific users as admin to specific Yammer groups in bulk via the Yammer REST API and PowerShell"
I've asked the engineer to determine whether this functionality is available, and if not when it will be added.

**Comment by mypil** [comment]
@angoo-atea - Thank you for this additional information. Let me also tag the doc owner on this issue to get some insights to your query. 

@IrenePasternack - Can you please share your insights on this issue?

Thank you.

**Comment by IrenePasternack** [comment]
The REST API documentation can be found at developer.yammer.com/docs.  There are some sample PowerShell scripts for working with Yammer at TechNet at https://gallery.technet.microsoft.com/office/Create-a-Yammer-Group-56b0a4a0.

**Comment by IrenePasternack** [comment]
We don't support setting admins for Yammer groups using PowerShell.

Our  long-term direction is to make all groups connected in Yammer, and then the standard Office 365 Groups APIs will work. Until then there are some holes in the capabilities and these need to be raised via Design Change Requests (DCRs) through support cases, so you’re on the right track by opening a support request.

Irene

**Comment by mypil** [comment]
@angoo-atea - From our understanding, the issue you raised has been answered by IrenePasternack. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
