### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#587]
We are seeing Teams Owner get group expiration notification in their Activity Feed in Teams and they are not getting an email, which is not consistent with the documentation above. Please review the expected behavior and update the documentation as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4773fc-df89-4d7c-6819-9ed94c66e1a3
* Version Independent ID: 9a0ce458-fd6b-5f12-0b6e-98f9b38ad13c
* Content: [Office 365 Group Expiration Policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/office-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/office-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/office-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I was able to test this behavior and made recommendations to change the content in doc via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/637 

Thanks
Sri

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by DeanGross** [comment]
Ok, thanks for updating the documentation to describe the behavior. While this is helpful, the implementation is not as good as it could be. All  group owners should be notified via email, regardless of how the group was created. This is going to make it much more difficult to let group owners know what to expect.

**Comment by mypil** [comment]
@DeanGross - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
[User Voice](https://office365.uservoice.com) 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by DeanGross** [comment]
I have added it to uservoice, https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/38229319-group-expiration-notifications-should-be-consisten
