### ISSUE TITLE
Manage group admins via PowerShell

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-O365ITPro#588]
Where's the information regarding adding admins to groups via powershell? If I have a large number of groups in a large organisation I want to be able to add a user as admin to many groups in bulk.
See also issue #583: https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/583

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2651c11-4d40-f6e7-5f80-6a5416e90477
* Version Independent ID: a04898e8-34ab-ad61-4066-ddcf73a1c543
* Content: [Manage Yammer admins](https://docs.microsoft.com/en-us/yammer/manage-yammer-users/manage-yammer-admins#bmk_group)
* Content Source: [yammer/manage-yammer-users/manage-yammer-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-users/manage-yammer-admins.md)
* Service: **yammer**
* Product: **office-online-server**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot add label duplicate

**Comment by mypil** [comment]
This issue is a duplicate to #583

**Comment by mypil** [comment]
@officedocsbot close
