### ISSUE TITLE
Only groups owned by users with group creation privileges will be connected to Office 365

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-O365ITPro#589]
Q4 under FAQ - Network eligibility "Q: I don't want my existing groups to get connected to Office 365. Can I turn this off?"

Apart from the fact that this is a really poor implementation, the answer needs clarification regarding "groups owned by users".

Scenario: I create a Yammer group using a service account with no privileges to create O365 groups, to ensure that it is a "classic" Yammer group with no O365 group. 
I then add another user as co-owner of the group who does have permissions to create O365 groups - will the group then be subject to the auto enablement of an O365 group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7a47d0-7e67-1890-8a1e-192871c99b55
* Version Independent ID: ff75ce98-2235-8c92-b6a2-9b034061adef
* Content: [Yammer and Office 365 Groups](https://docs.microsoft.com/en-us/yammer/manage-yammer-groups/yammer-and-office-365-groups)
* Content Source: [yammer/manage-yammer-groups/yammer-and-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-groups/yammer-and-office-365-groups.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by IrenePasternack** [comment]
Thanks for the feedback. I’ve updated the topic with a clarification:

Only groups with at least one admin with group creation privileges can be connected to Office 365.

Irene

**Comment by angoo-atea** [comment]
Hi Irene;, 
So basically you're confirming that in the scenario above, as soon as a user who has privileges to create O365 Groups is added as owner to the Yammer group, it then becomes O365 Group enabled?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@IrenePasternack - Do you have any updates on this? Thank you.

**Comment by mypil** [comment]
@angoo-atea - According to Irene, it is definitely not automatic. The group becomes eligible to become an Office 365 group, but there currently is no way to guarantee that it actually is converted. The team is working on coming up with an official process that we can document for how to request that a sweep is done to identify eligible groups and convert them. 

We hope this answers your query. Thank you for taking the time to submit feedback that helps us improve the content.

**Comment by mypil** [comment]
@officedocsbot close
