### ISSUE TITLE
Link to download center for most recent PBIT file

### ISSUE THREAD

**Issue by bartbilliet** [MicrosoftDocs/OfficeDocs-O365ITPro#590]
Is it possible to link to the exact download center location to find the most recent PBIT file? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bartbilliet - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@bartbilliet - Is this related to issue #591? Can we proceed to close this issue as well?

**Comment by bartbilliet** [comment]
It is related, although here the link is missing. I've created pull request [#613](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/613) which would fix this.
