### ISSUE TITLE
Link to download center (PBIT file) seems broken

### ISSUE THREAD

**Issue by bartbilliet** [MicrosoftDocs/OfficeDocs-O365ITPro#591]
The download returns a ZIP-file containing different information than the expected PBIT file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fdd664-c2d2-7712-fd41-3745c52d1442
* Version Independent ID: 0dfdadc8-15f0-dd7e-0efc-9a2565f7b519
* Content: [Customize the reports in Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/customize-reports?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/customize-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/customize-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bartbilliet - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by bartbilliet** [comment]
Seems the download link is working now, thanks :)

**Comment by mypil** [comment]
@bartbilliet - Glad to know that the issue has been fixed. We will close this issue now.

Thank you for your contribution to make the docs better!

**Comment by mypil** [comment]
@officedocsbot close
