### ISSUE TITLE
What Admin Center

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-O365ITPro#600]
In the beginning you say : In the admin center, go to the Users &gt; Active users page.

WHICH admin center are you referring to: Exchange, Sharepoint, Azure, Security,..? Please tell exactly what the steps are to get to the correct place

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@blouwagie - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by cmcatee-MSFT** [comment]
@blouwagie We have removed the "Office 365" and "Microsoft 365" designation due to branding changes. When we say "admin center" we mean the main Microsoft 365 admin center. If we mean a different admin center, such as Exchange, SharePoint, etc., we will state that explicitly. Also, both procedures have links into the admin center in the very first step. If you click the link, you will be taken directly to the place you need to go.

**Comment by blouwagie** [comment]
That may be clear to you authors, but is clear as mud to the reader IMHO.
Thank you for responding!
Bart

Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)
http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call <https://www.uberconference.com/bart40> is needed)
