### ISSUE TITLE
Reporting on Client

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-O365ITPro#604]
Is there any existing reporting confirming whether OneDrive Clients are working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59b9dada-0658-e34b-fba2-568d1322b947
* Version Independent ID: 4561d278-79c0-517f-fb7e-de94474cc3f3
* Content: [Office 365 Reports in the Admin Center - OneDrive for Business usage](https://docs.microsoft.com/en-us/office365/admin/activity-reports/onedrive-for-business-usage?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/onedrive-for-business-usage.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/onedrive-for-business-usage.md)
* Service: **o365-administration**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@StPhil -  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@StPhil - That feature is currently not available. That report feature request is probably better suited to be raised in [User Voice for OneDrive](https://onedrive.uservoice.com). 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
