### ISSUE TITLE
Role requirements missing

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/OfficeDocs-O365ITPro#605]
You need to advise what role a person must have assigned in order to access information or perform actions.  For example, my role doesn't allow me to configure (or see settings for) Targeted release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91eaa7f6-1a74-947f-80d0-8962b6df9b39
* Version Independent ID: 8b546fac-4393-7589-9c71-bd5860d0f0b2
* Content: [Stay on top of Office 365 changes](https://docs.microsoft.com/en-us/office365/admin/manage/stay-on-top-of-updates?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/stay-on-top-of-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/stay-on-top-of-updates.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@giterdn - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@giterdn Thank you for your feedback. You need to be a Global Administrator in order to make changes or signup for Targeted release. I have created a PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/610 to reflect a note in the doc to avoid confusion.


Thanks
Sri

**Comment by mypil** [comment]
@giterdn - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
