### ISSUE TITLE
Requires Preview Version of Admin Center

### ISSUE THREAD

**Issue by rprechel** [MicrosoftDocs/OfficeDocs-O365ITPro#606]
Based on my experience, the **Modern authentication** setting is only available on the preview version of the admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rprechel - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Rahat-3858** [comment]
I will get this issue over to the O365ITPro writing team for investigation.

**Comment by msbemba** [comment]
@rprechel Thank you for your feedback. You are correct, I have made changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/609 to reflect the same.


Thanks
Sri

**Comment by mypil** [comment]
@rprechel - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
