### ISSUE TITLE
autentifican

### ISSUE THREAD

**Issue by yamilic008** [MicrosoftDocs/OfficeDocs-O365ITPro#607]
al momento de poner mi coidigo OTP, siempre me dice que "Error al comprobar OTP: Parece que has indicado una OTP no válida. Vuelve a intentarlo."

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 0c35b6c9-aef0-9190-3c70-f1f7d4638b6c
* Version Independent ID: 5405815c-220a-1c69-5552-60e3d71ebde4
* Content: [Portal de administración de Kaizala](https://docs.microsoft.com/es-es/office365/kaizala/kaizala-management-portal?redirectSourcePath=%252farticle%252fAbout-Kaizala-Management-Portal-2046ddba-06fb-49c9-b6d6-a4777e8a556f#feedback)
* Content Source: [Office365-Kaizala/kaizala-management-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Kaizala/kaizala-management-portal.md)
* Service: **kaizala**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@yamilic008 - Gracias por enviar sus comentarios.

Creo que la mejor manera de avanzar es si puede abrir un ticket de servicio en su inquilino para que esto se pueda resolver lo antes posible. Basado en el resultado, hágame saber si es algo que puede mencionarse en los documentos.

Siga este enlace para ponerse en contacto con el soporte para productos negocio: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

Si no le importa, manténganos informados aquí sobre la resolución y realmente deseo obtener esta información que está descubriendo en los documentos.

**Comment by mypil** [comment]
@officedocsbot close
