### ISSUE TITLE
Contact Support number for Vietnam is not working

### ISSUE THREAD

**Issue by huuphat** [MicrosoftDocs/OfficeDocs-O365ITPro#611]
Hello, Support number for Vietnam 120852137 cannot reach to your support service.
Please help to update the phone number.
We really need to call you for your support.

Thank you so much,

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@huuphat - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. 

Alternatively, if you need to contact support you can open a service ticket in your tenant so this can get resolved immediately. Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**


Thank you.

**Comment by mypil** [comment]
@officedocsbot close
