### ISSUE TITLE
GDPR assessment dead link

### ISSUE THREAD

**Issue by AlexJPawlak** [MicrosoftDocs/OfficeDocs-O365ITPro#612]
Hey!

I've tried to look up  Microsoft GDPR Assessment Tool that's mentioned in the "Next steps" - however the link looks dead. Can it be updated? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62ae9fcd-d270-e040-2a50-c1bff38df45c
* Version Independent ID: 4635cf33-c585-e6e6-3c7b-f9aa427448d7
* Content: [GDPR simplified A guide for your small business](https://docs.microsoft.com/en-gb/office365/admin/security-and-compliance/gdpr-compliance?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/gdpr-compliance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/gdpr-compliance.md)
* Service: **o365-administration**
* GitHub Login: @SuPotter
* Microsoft Alias: **supotter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AlexJPawlak - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@SuPotter - There's an error: "This site can’t be reached assessment.microsoft.com’s server IP address could not be found." when trying to access the link for the Microsoft GDPR Assessment Tool within the document.

Do you happen to know the correct URL for this? Or should the hyperlink for the Microsoft GDPR Assessment Tool be removed from the document content?

Please advise on how to proceed so we can create a PR if needed to get this fixed. Thank you.

**Comment by kennykennington** [comment]
Same problem, when will this dead link be fixed?

**Comment by mypil** [comment]
@kennykennington - we are still working with the localization team to get this issue fixed. Please standby for further updates. Thank you for your patience.

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@AlexJPawlak @kennykennington - The URL for the Microsoft GDPR Assessment Tool is [](https://discover.microsoft.com/gdpr-readiness-assessment/) 

We are still working with the localization team to ensure that this link is accessible to everyone. However, the doc has been updated with some other GDPR related information which we hope would be helpful. 

Thank you for your contribution to make the docs better! Much appreciated!
