### ISSUE TITLE
Convert to cloud-only shared mailbox

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-O365ITPro#614]
Please add details on how to convert object to a cloud-only shared mailbox.  This is needed when local AD objects are moved to a non-synced OU or are deleted but the shared mailbox content is still needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6024c6e-1373-58de-ca8b-819a11693968
* Version Independent ID: 5d02bdc8-6e20-8b9b-942e-cca0e312cc5e
* Content: [Remove a former employee from Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide#delete-a-former-employees-user-account)
* Content Source: [Office365-Admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@danmyhre - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @danmyhre ,
in the described scenario convert to  to a cloud-only shared mailbox is impossible.
if user is moved from synced OU, the mailbox will be removed from Office 365 -  you need move user back to the original OU, and after the next sync the data will be restored.
if user object was removed - proceed recovery process as it described [in this article](https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Common-mailbox-recovery-scenarios-for-hybrid-environments/ba-p/604681)
Thank you

**Comment by danmyhre** [comment]
Not sure it is impossible...you can:

- Set to regular user mailbox
- Move to un-synched OU
- Restore the user in M365 admin center or AAD
- Clear the immutable ID: Set-Msoluser -UserPrincipalName user@domain.onmicrosoft.com -ImmutableID ""
- Convert to shared mailbox

**Comment by MaratMussabekov** [comment]
Dear @danmyhre ,
**Not sure it is impossible** - sorry, I was unclear, I meant it is impossible without restoring of account.
Anyways, converting removed mailbox to a cloud-only shared mailbox is more likely within the scope of the article [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/office365/admin/email/convert-user-mailbox-to-shared-mailbox) (it already has this section), than within this one.
As to clearing the immutableid while restoring in hybrid scenarios, I think it should be added to the [Restore a user in Office 365](https://docs.microsoft.com/office365/admin/add-users/restore-user).
What do you think?
Thank you

**Comment by danmyhre** [comment]
Maybe since there are a few different scenarios at play here, perhaps it would be better to just create a page on how to convert from an AD sync'd user to a cloud only user.

**Comment by mypil** [comment]
@danmyhre - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
