### ISSUE TITLE
Reference to Azure AD B2C does not make sense in this contect

### ISSUE THREAD

**Issue by fredrikhaglund** [MicrosoftDocs/OfficeDocs-O365ITPro#615]
Azure AD B2C is not used by Office 365 as far as I know and is not relevant in this context. Most people ending up here is looking for how to simplify password complexity rules in Azure AD used by Office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c354faae-625c-2b36-2a77-4ed2962feff3
* Version Independent ID: 1dd96166-8bae-fc8c-491f-99ca45f5b058
* Content: [Password policy recommendations for Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [Office365-Admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@fredrikhaglund - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@fredrikhaglund - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
