### ISSUE TITLE
The pbit file errors out with a permissions issue.

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-O365ITPro#616]
the odata feed works correctly in Excel and in custom connectors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fdd664-c2d2-7712-fd41-3745c52d1442
* Version Independent ID: 0dfdadc8-15f0-dd7e-0efc-9a2565f7b519
* Content: [Customize the reports in Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/customize-reports?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/customize-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/customize-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@TheBluLion - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TheBluLion - Thank you for engaging with the community here for the docs.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by TheBluLion** [comment]
I did some troubleshooting on my own. The pbit file no longer prompts for a login and defaults to anonymous login. The user must edit the data source settings manually and switch from anonymous logon to organizational login

[A screenshot of a social media post  Description automatically generated]

﻿ -﻿ --
Eu Nice Loh
Premier Field Engineer
Office: (314) 872 5916
EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com>
IM:euloh@microsoft.com
8AM-5PM CT
[Microsoft]
﻿
If you have any feedback about my work, please let either me or my manager Annele Richards know at Annele.Richards@microsoft.com<mailto:Annele.Richards@microsoft.com>

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue?

Thank you.

**Comment by Sirkkuw** [comment]
I am forwarding thread to the dev in corp email to see if we can get an answer.

**Comment by Sirkkuw** [comment]
@mypil - per dev this happens sometimes, and the workaround mentioned above works.

**Comment by mypil** [comment]
@TheBluLion - From our understanding, the issue has been answered by Sirkkuw. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
