### ISSUE TITLE
Viewing more details about Roles

### ISSUE THREAD

**Issue by et3rae** [MicrosoftDocs/OfficeDocs-O365ITPro#617]
This page says to view more details about roles "In the Microsoft 365 admin center, go to Roles &gt; Roles, and then select any role to open its detail pane. Select the Permissions tab to view the detailed list of what admins assigned that role have permission to do"
But I don't see Roles anywhere in the M365 admin center, and I'm a Global Admin.  Is this actually listed somewhere else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@et3rae - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by cmcatee-MSFT** [comment]
@etra Do you have the new admin center turned on? If not, that might be why you're not seeing it yet. To turn it on, go to the admin center home page, then click the **Try the new admin center** toggle switch to turn it on.

**Comment by mypil** [comment]
@et3rae - From our understanding, the issue has been answered by cmcatee-MSFT. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
