### ISSUE TITLE
send on behalf

### ISSUE THREAD

**Issue by midnight2105** [MicrosoftDocs/OfficeDocs-O365ITPro#618]
You have two different users in the 3rd paragraph about send on behalf, Alex and Donald.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784a196f-3e0e-0c0a-0b2f-af2105a774d9
* Version Independent ID: 08300f82-3b1d-b96d-bf10-e401ac6ef2c0
* Content: [Allow members to send as or send on behalf of a Group](https://docs.microsoft.com/en-us/office365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@midnight2105 - Thank you for your efforts to clarify the docs.

Pull Request #620  has been merged and the Github page is updated. It may take a few days before the change migrates to the docs.microsoft.com page, but you can consider your feedback responded to and closed. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.
