### ISSUE TITLE
Remove Office 365 Adoption Pack from AppSource

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ITPro#621]
Please have someone remove the old Office 365 Adoption Pack from the AppSource, that has been supserseded by the Microsoft 365 Adoption Pack and its continued presence just causes confusion when people try to install it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec8961e-4fc1-eb46-1e71-3147b55ac90e
* Version Independent ID: 2c66ebfb-53b5-18ab-e560-702d4cae057f
* Content: [Enable Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@DeanGross - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
[User Voice](https://office365.uservoice.com) 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
