### ISSUE TITLE
Are these steps still valid?

### ISSUE THREAD

**Issue by student-forever** [MicrosoftDocs/OfficeDocs-O365ITPro#622]
When we run the command: Get-AzureADServicePrincipal , no Application service principal name with the name "Office 365 Yammer" with the App id 00000005-00000ff1-ce00-000000000000 can be seen. In fact, there are no app service principal names associated with Yammer anymore.

When we login to https://portal.azure.com with the global admin privilege, we can no longer see the Yammer service principal name anymore.

However, when I try to login to Yammer, I do get the URL re-directing to :

https://login.microsoftonline.com/adf7a31c-ae02-4bda-97e6-0e0a9260e5bf/oauth2/authorize?client_id=00000005-0000-0ff1-ce00-000000000000

Indicating that the app is still there. So has the Yammer app service principal name been hidden? Or can they be seen only on specific tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67be3bb5-b150-e197-08fb-eaa3bf8f7a0b
* Version Independent ID: 5e2b6dc2-992c-5b76-955d-9cb57da9fbcc
* Content: [Improve Office 365 sign-in for Yammer with auto-acceleration policy](https://docs.microsoft.com/en-us/yammer/manage-yammer-users/auto-acceleration-policy-for-signing-in#feedback)
* Content Source: [yammer/manage-yammer-users/auto-acceleration-policy-for-signing-in.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-users/auto-acceleration-policy-for-signing-in.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by student-forever** [comment]
This can be closed out, we needed to use the -All switch. Too many SPNs nowadays on Azure.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@student-forever - Glad to hear that your issue has been resolved. I will proceed to close this issue then based on your last comment.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
