### ISSUE TITLE
lack of MFA administration is a glaring omission

### ISSUE THREAD

**Issue by jwf1776** [MicrosoftDocs/OfficeDocs-O365ITPro#623]
"Full administration, which has privileges equivalent to a global admin." does not seem to be accurate.

MFA doesn't seem to work with delegated administration:
https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/17429305-delegate-permissions-for-managing-mfa

Considering it's best practice to have MFA enabled on the GA or partner delegated admin accounts that administrate the tenants MFA settings, this is a crippling issue.  To work around this with tenant MFA GAs, we have to create an MFA enabled GA for each support engineer on each tenant.  Kind of defeats the purpose of delegated admin.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jwf1776 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by jwf1776** [comment]
https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#delegated-administration-for-microsoft-partners

**Comment by msbemba** [comment]
@jwf1776  Thank you for the feedback. We see the issue here and also see an active uservoice on this topic., So we should get a response soon from the engineering team since there is a uservoice opened. Hope this helps.

The document  that you requesting correction  States that a Partner can assign "Full administration, which has privileges equivalent to a global admin." which is accurate. Let me know if there is a change required on this.

Thanks
Sri

**Comment by jwf1776** [comment]
I do think a change in the doco is warranted.

Saying “Full administration, which has privileges equivalent to a global admin." gives the reader the impression that they will be able to use a delegated partner “full administration” account to do everything that can be done with a “global admin”.  And in the case of managing MFA functions this is not currently true (either by design or oversight or bug).

Saying “Full administration, which has privileges equivalent to a global admin with the notable exception of managing MFA functionality.” would be a fair improvement.

Given that managing MFA functionality is a very common and important feature for o365 admins and one that is available to global admins, one wonders if a role that lacks that MFA ability should really be termed “full administration” or “equivalent to a global admin".

Therefore saying “Full DPA administration, which is neither “full” nor has privileges equivalent to a global admin because it cannot easily manage MFA functionality.” Might be an even better articulation.

But then that really begs the question why anyone would use the “full DPA administration” role when partners are going to have to maintain separate ‘global admin’ accounts for each tenant (1 for each support tech since these accounts need to be MFA enabled).

Obviously, the other option here is for engineering to fix the “Full DPA administration” feature so that it can easily administrate MFA and leave the doco as is.

**Comment by msbemba** [comment]
@jwf1776 Thank you for your feedback. I have made the changes to the doc to reflect the same and can be tracked under PR  https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/629

Thanks
Sri

**Comment by mypil** [comment]
@jwf1776 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
