### ISSUE TITLE
Confirmation on Licensing requirements.

### ISSUE THREAD

**Issue by student-forever** [MicrosoftDocs/OfficeDocs-O365ITPro#626]
Hello,

Could you please elaborate on the licensing requirements of the external participant. Does the external participant need to have a Yammer license in order to participate in a conversation external to their network? If so and the participant doesn't have a license already, he needs to reach out to his admin to enable a Yammer enterprise license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b3a2463-a8f4-3ba7-0524-37fc75fa783d
* Version Independent ID: 14374d2a-eb47-d2e5-fbc3-be6ee56e14b5
* Content: [Add external messaging participants to your Yammer conversations](https://docs.microsoft.com/en-us/yammer/work-with-external-users/add-external-participants)
* Content Source: [yammer/work-with-external-users/add-external-participants.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/work-with-external-users/add-external-participants.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@student-forever - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@student-forever - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
