### ISSUE TITLE
This page is out of date. 

### ISSUE THREAD

**Issue by fbcarter** [MicrosoftDocs/OfficeDocs-O365ITPro#628]
Settings Settings &gt; Office 365 Settings &gt; Personal info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8f1206-71c4-76df-6843-e39a23f2350b
* Version Independent ID: 55bb4d3c-fdc4-4363-1202-89aa6e628577
* Content: [Update your admin phone number and email address in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/update-phone-number-and-email-address?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/update-phone-number-and-email-address.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/update-phone-number-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@fbcarter - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@fbcarter  Thank you for your feedback. We have made the changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/631

**Comment by mypil** [comment]
@fbcarter - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
