### ISSUE TITLE
Create Team in MS Teams

### ISSUE THREAD

**Issue by BogdanStefanManolache** [MicrosoftDocs/OfficeDocs-O365ITPro#63]
Is there any way to create a TEAM in MS Teams based on distribution list? ...and keep them in sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c8e89a-d001-eb11-d1e4-e2525561307a
* Version Independent ID: 42c5f231-7a58-4e92-2a43-eb35bcf8c410
* Content: [Create distribution lists in the Office 365 admin center](https://docs.microsoft.com/en-us/office365/admin/setup/create-distribution-lists?view=o365-worldwide)
* Content Source: [Office365-Admin/setup/create-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/create-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by AndreaBarr** [comment]
@BogdanStefanManolache Thank you for this inquiry

I am not sure about the creation of teams in Teams. Let me get this over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hello @BogdanStefanManolache, right now there is no possibility to do this, either way, it's on the MS Teams user's voice forum, [https://microsoftteams.uservoice.com/forums/599053-schools-and-universities/suggestions/35061151-sync-distribution-lists-with-teams](microsoftteams.uservoice.com/forums) as a suggestion

**Comment by mypil** [comment]
@BogdanStefanManolache - Did j0rt3g4 & tseward answer your query?

**Comment by BogdanStefanManolache** [comment]
Yes, they answered but it is not what I was hoping for. Thanks to all of you for answering.

Kind Regards!

**Comment by mypil** [comment]
@AndreaBarr -This issue can be closed. Thank you.
