### ISSUE TITLE
MDM Manage

### ISSUE THREAD

**Issue by AdvisiconIT** [MicrosoftDocs/OfficeDocs-O365ITPro#632]
M365 Asks for enterpriseenrollment = enterpriseenrollment.manage.microsoft.com CNAME
This page suggests  enterpriseenrollment = enterpriseenrollment-s.manage.microsoft.com CNAME
Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0937468-6fd2-c83a-ed60-81129a4b766a
* Version Independent ID: 010a32f0-45a3-81da-1a6c-864996a86597
* Content: [Create DNS records for Office 365 using Windows-based DNS](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-using-windows-based-dns?redirectSourcePath=%252fen-us%252farticle%252fCreate-DNS-records-for-Office-365-using-Windows-based-DNS-9eec911d-5773-422c-9593-40e1147ffbde&view=o365-worldwide#bkmk_add_cname)
* Content Source: [Office365-Admin/dns/create-dns-records-using-windows-based-dns.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-using-windows-based-dns.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AdvisiconIT - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@AdvisiconIT  Thank you for your feedback. EnterpriseEnrollment-s.manage.microsoft.com is the preferred FQDN for enrollment, but there are two other endpoints that have been used by customers in the past and are supported. EnterpriseEnrollment.manage.microsoft.com (without the -s) and manage.microsoft.com both work as the target for the auto-discovery server, but the user will have to touch OK on a confirmation message. If you point to EnterpriseEnrollment-s.manage.microsoft.com , the user won’t have to do the additional confirmation step, so this is the recommended configuration.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@AdvisiconIT - From our understanding, the issue has been answered by msbemba. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by BryanAdvisicon** [comment]
Thank you for the help.
