### ISSUE TITLE
Please correct documentation regarding licensing requirement for O365 group naming policy

### ISSUE THREAD

**Issue by Sambsamb** [MicrosoftDocs/OfficeDocs-O365ITPro#635]
This document https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy states:
"Licensing requirements
To use the Groups naming policy feature, the following people need an Azure Active Directory Premium P1 license or Azure AD Basic EDU license:

Everyone who is a member of the group.
The person who creates the group.
The admin who creates the Groups naming policy"
This appears to be incorrect since no 'group' is needed or used for O365 naming policy configuration.

the PS Code:
$AzureADDirectorySetting = Get-AzureADDirectorySetting | where { $_.Displayname -eq 'Group.Unified' } 
(Get-AzureADDirectorySetting -Id $AzureADDirectorySetting.Id).Values
Name                          Value                               
----                          -----                               
EnableMIPLabels               false                               
CustomBlockedWordsList                     #####                       
EnableMSStandardBlockedWords  false        #####                       
ClassificationDescriptions                                        
DefaultClassification                                             
PrefixSuffixNamingRequirement              #####                       
AllowGuestsToBeGroupOwner     false                               
AllowGuestsToAccessGroups     True                                
GuestUsageGuidelinesUrl                                           
GroupCreationAllowedGroupId   7xxx6
AllowToAddGuests              False                               
UsageGuidelinesUrl                                                
ClassificationList                                                
EnableGroupCreation           False   

shows the 3 used fields 
    CustomBlockedWordsList                                 
    EnableMSStandardBlockedWords 
    PrefixSuffixNamingRequirement   
have nothing to do with groups.           

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f70ad7b-5ba2-6167-1207-7496d57c6828
* Version Independent ID: 3df3ae33-83d3-e25f-3b41-070620030a08
* Content: [Office 365 Groups naming policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/groups-naming-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/groups-naming-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Sambsamb - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Sambsamb Thank you for your feedback. I might have miss understood here.

The three attributtes 

CustomBlockedWordsList
EnableMSStandardBlockedWords
PrefixSuffixNamingRequirement

are the attributtes set on -DirectorySetting . Let me know if you have any other question.

**Comment by Sambsamb** [comment]
@msbemba 
This document https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy states:
"Licensing requirements
To use the Groups naming policy feature, the following people need an Azure Active Directory Premium P1 license or Azure AD Basic EDU license:

Everyone who is a member of the group.
The person who creates the group.
The admin who creates the Groups naming policy"
This appears to be incorrect since no 'group' is needed or used for O365 naming policy configuration.

**Comment by MikePlumleyMSFT** [comment]
The license requirements are correct. The group naming policy applies to groups that are created once the policy has been configured.

**Comment by Sambsamb** [comment]
Q1. Does the 'Everyone who is a member of the group' P1 licensing requirement applies while the policy is configured? Does that mean this specific licensing requirement does NOT apply when the policy is un-configured (values of the 3 attributes  'CustomBlockedWordsList, EnableMSStandardBlockedWords, PrefixSuffixNamingRequirement' are set back to default values)?

Q2. How on God's green earth you hope to enforce or even audit this licensing requirement? Does Microsoft track customers' O365 group membership history? Does Microsoft track the history of the values of 3 attributes  'CustomBlockedWordsList, EnableMSStandardBlockedWords, PrefixSuffixNamingRequirement'?

Please help me understand. Here's an example scenario:
- Admin enables O365 group naming policy by modifying one or more of the 3 attributes  'CustomBlockedWordsList, EnableMSStandardBlockedWords, PrefixSuffixNamingRequirement' 
- 'Samatha' is a user without P1 or P2 license. She creates a Teams site which creates an underlying O365 group that conforms to the assigned O365 group naming policy. 
- Admin disables O365 group naming policy. 
- Samantha adds 65 users to her Teams site, none of whom have P1 or P2 license.
How many P1 licenses are required in this scenario, 2 or 67?

**Comment by msbemba** [comment]
@Sambsamb I was able to test it by creating the naming policy and group without a Azure p1 or p2 license. I also found another document (https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-naming-policy) which talks about similar license requirements.  We understand the confusion here, I'll reach out to  @MikePlumleyMSFT and check with the product team and get the licensing requirements clarified.

Thank you again for your feedback and making our document better.

Thanks
Sri

**Comment by MikePlumleyMSFT** [comment]
For Azure AD P1/P2 licenses, customers are required to have the correct number of licenses in the tenant for the features that they are using. These licenses can be assigned to specific users, but it's not required. (This is different from Office 365 where licenses must be assigned to specific users before they can use the features.)

**Comment by mypil** [comment]
@Sambsamb - From our understanding, the issue you raised has been answered by MikePlumleyMSFT. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
