### ISSUE TITLE
Support for GCC High?

### ISSUE THREAD

**Issue by davidSKennedy** [MicrosoftDocs/OfficeDocs-O365ITPro#638]
I think I know the answer, but is this supported in GCC High?  The directions to enable are not correct from what I can see.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@davidSKennedy - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by davidSKennedy** [comment]
I am specifically referring to the document located at https://docs.microsoft.com/en-us/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide.  It states at the top that this is supported in GCC, but does not reference GCC High.  I do not have a Usage link under Reports.  Is there another document specifically for GCC High that I did not locate?

**Comment by mypil** [comment]
@davidSKennedy - Thank you for submitting feedback.

Here are some of the documentation that may be related to the GCC High topic you're searching for:

- **[Plan for Microsoft 365 Government - GCC High deployments](https://docs.microsoft.com/en-us/microsoftteams/plan-for-government-gcc-high)**

- **[Office 365 GCC High and DoD](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)**

Hope this helps to address your issue.

**Comment by davidSKennedy** [comment]
This does not answer the question I posted.  I don’t need generic information about GCC High.  I need to know if this connector for Power BI is supported in GCC High.  

David Kennedy

Sent from my mobile device.  Please excuse the brevity and any typos.

703-508-7297

**Comment by mypil** [comment]
@davidSKennedy - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
