### ISSUE TITLE
Mobile experience

### ISSUE THREAD

**Issue by DarrellaaS** [MicrosoftDocs/OfficeDocs-O365ITPro#639]
It would be good to see an update to talk about the mobile experience. 
When admins turn off/on Focused Inbox using PowerShell, what is the expected experience in the Outlook mobile app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83abc4f6-2d5b-1187-eda8-6cf841fe420a
* Version Independent ID: 5df31a0f-5128-140d-2c13-ca9eb0b59b0a
* Content: [Configure Focused Inbox for everyone in your organization](https://docs.microsoft.com/en-us/office365/admin/setup/configure-focused-inbox?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/configure-focused-inbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DarrellaaS - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
[User Voice](https://office365.uservoice.com) 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by DarrellaaS** [comment]
I think you misunderstood. I'm not making a feature request. I'm suggesting the documentation on the page needs to include how these admin configurations change the mobile experience of Focused Inbox. A recent service disruption to Exchange Online began to deliver everything to the 'Other' Inbox view. The suggested work around was for admins to disable Focused Inbox using the steps in this article. But there is no mention of what will happen to the Focused Inbox in Outlook for mobile.

**Comment by mypil** [comment]
@DarrellaaS - Thank you for providing clarification. 

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@DarrellaaS  Thank you for your feedback. As soon as the admin configuration changes happen it affects all the devices used to access the mailbox. Which means the mobile device will also have the focused inbox feature Turned ON/OFF as the admin makes the change.

Meanwhile, regarding the issue we had faced last week, It was an outage which was resolved in 4 hours.

Hope this helps!

Regards
Sri

**Comment by mypil** [comment]
@DarrellaaS - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
