### ISSUE TITLE
Archive Information

### ISSUE THREAD

**Issue by thomps** [MicrosoftDocs/OfficeDocs-O365ITPro#64]
I'm curious if this storage includes all items stored in archive or not.  I have been looking around and there doesn't seem to be much information on whether or not the archived items are included in these canned reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c35522-704a-a490-97a1-8389c0c6261c
* Version Independent ID: 1ed63bad-90bc-7716-3c2a-f9389946aa97
* Content: [Office 365 Reports in the Admin Center - Mailbox usage](https://docs.microsoft.com/en-us/office365/admin/activity-reports/mailbox-usage?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/mailbox-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by AndreaBarr** [comment]
@thomps Thank you for this feedback

I am not sure what the canned reports include. Let me get this over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by SteveColegrove** [comment]
I am also looking for the same info.  Any update?

**Comment by GavinEke** [comment]
I am looking for similar info about this report. I would like to know if the storage includes all mailbox types (user, shared and resource) or if it is just the storage of user mailboxes?

**Comment by JeremyTBradshaw** [comment]
So.. does this mean the Graph just performs cmdlets against exchange?

**Comment by AndreaBarr** [comment]
@sonika24 could you please investigate this?

**Comment by npsptechusa** [comment]
@JeremyTBradshaw  Get-MailboxStatistics cmdlet is for on-prem and cloud based Exchange.
Please check out - https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxstatistics?view=exchange-ps

**Comment by mypil** [comment]
@thomps - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
