### ISSUE TITLE
No groups showing

### ISSUE THREAD

**Issue by boe1** [MicrosoftDocs/OfficeDocs-O365ITPro#640]
I'm confused why this article keeps on saying outlook - does it mean to say the office365 portal or is it saying to upgrade DLs created by someone in their outlook application on their desktop?

Also, I have a hybrid 2013 exchange on prem office 365 environment with azure ad sync.   I created all the DLs on my exchange server (has the latest CU).     When I go to office 365 exchange admin, groups, DLs - those groups are synced to Office 365.  However if I click on upgrade in the right hand corner - it doesn't show any groups eligible for upgrade.   I thought there might be something odd about those groups so I created 2 new groups - 1 with my name in it and a different one with a random end user in it.   While the DLs do sync, neither of them is eligible for upgrade so my upgrade list is still blank and I checked it shows that I have no DLs that are in an upgraded state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10dbb56e-1c52-8fa0-0d3d-bab6d50519d0
* Version Independent ID: ff6585cd-9d68-ed1c-ee5f-1f451457dbef
* Content: [Upgrade distribution lists to Office 365 Groups in Outlook](https://docs.microsoft.com/en-us/office365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@boe1 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
