### ISSUE TITLE
0800 Contact support number for New Zealand is not working

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/OfficeDocs-O365ITPro#642]
I called the number from New Zeland mobile phone and I got an auto-response message "The number you've called is not available from your location. Thank you."

Alternative Phone Number: 09 912 7298 is working though

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3425d88a-ef04-122b-abef-8526912c0633
* Version Independent ID: 43eb8a88-ef1f-bb9d-fa08-c77e6809d56a
* Content: [Support information for New Zealand](https://docs.microsoft.com/en-nz/office365/admin/support/new-zealand?view=o365-worldwide)
* Content Source: [Office365-Admin/support/new-zealand.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/new-zealand.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@LinnZawWin - Thank you for submitting feedback.

I will get this telephony issue over to the O365ITPro writing team for investigation.

In the meantime, if you require technical support, you can also open a service ticket in your tenant so your issue can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

**Comment by mypil** [comment]
@cmcatee-MSFT - FYI.

**Comment by cmcatee-MSFT** [comment]
Hi @LinnZawWin The telephony carrier for the 0800 number cannot guarantee that every mobile provider will be able to call that in-country number. Therefore, it's recommended that you use the alternate phone number.
