### ISSUE TITLE
It says add 6 CNAME records but only has 5 rows in the table... 

### ISSUE THREAD

**Issue by adamsonlance** [MicrosoftDocs/OfficeDocs-O365ITPro#643]
The instuctions in multiple places say to add six cname records whose values come from the table where each row represents on record. The table, however, only has five rows meaning that there is only enough information to create 5 records. One of the two must be wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d3509b-12f4-1718-c1a5-cf694cc2a159
* Version Independent ID: f2babd10-57da-fe6a-afae-366bee4e1397
* Content: [Create DNS records at Amazon Web Services (AWS) for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-aws?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-aws.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-aws.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@adamsonlance - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@adamsonlance Thank you for your feedback. We have made changes to the doc correcting the number of CName records. Same can be tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/649

**Comment by mypil** [comment]
@adamsonlance - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
