### ISSUE TITLE
Need some clarity of SharePoint and Teams activity

### ISSUE THREAD

**Issue by AlexVincent1** [MicrosoftDocs/OfficeDocs-O365ITPro#644]
In this article it says that "working on files" is tracked as activity in a Team. So, if I create or edit a file in Teams, is this tracked as both SharePoint and Teams activity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd383fdd-30de-e0a0-2c2d-6316424b56da
* Version Independent ID: 2c9cc89b-2e35-5474-ff94-16179aa1d475
* Content: [Active user in Office 365 usage reports](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/active-user-in-usage-reports?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/active-user-in-usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/active-user-in-usage-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AlexVincent1 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@AlexVincent1 thank you for your feedback. You are correct! As files in teams use sharepoint as the database the changes will be tracked on both Teams and Sharepoint.

Hope this helps!

Regards
Sri

**Comment by mypil** [comment]
@AlexVincent1 - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
