### ISSUE TITLE
A href Target should be _blank

### ISSUE THREAD

**Issue by deanmresource** [MicrosoftDocs/OfficeDocs-O365ITPro#645]
otherwise you click on a link and lose this page. :/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac5c263-b0c3-7c40-d951-0ad9207765e5
* Version Independent ID: 0c91c39d-59ee-b20b-1eff-815f34b60d07
* Content: [Create organization-wide signatures and disclaimers](https://docs.microsoft.com/en-us/office365/admin/setup/create-signatures-and-disclaimers?view=o365-worldwide)
* Content Source: [Office365-Admin/setup/create-signatures-and-disclaimers.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/create-signatures-and-disclaimers.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@deanmresource - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@deanmresource - We appreciate your efforts to clarify the docs.
Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by deanmresource** [comment]
Hi, sorry about this, i didn't realise it would be this much work :)

Basically all i suggested was ensuring that every link on the page opened in a new window, right now when you click a link it opens in the window you are viewing which is a waste of time as you then lose the page you are on and have to go back a page just to reclick the link you wanted to view but you have to do it in a new window.

Take for example the link under "Microsoft 365 admin center."

if you are reading the document and then following the how to you click the link, it opens in the page you are actually reading for instructions and you have to go back to the place you got to then reopen the link so you can continue following the help thread.

It should just open in a new window by default. :)

**Comment by mypil** [comment]
@deanmresource - We appreciate your suggestion to improve the docs.

I believe this is the standard in opening links or URLs where it opens in the same window. You do have the option of opening the link in a new tab or window depending on what web browser you're using. 

However, if you would really like to get more traction on this feedback then I suggest that you submit it via [User Voice](https://office365.uservoice.com) OR you may submit your feedback and suggestion on the [Microsoft Style Guide - URLs and web addresses](https://docs.microsoft.com/en-us/style-guide/urls-web-addresses) page. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by deanmresource** [comment]
Thank you, i won't suggest it to the styles guide, it seems a little much, however it probably is an improvement to have the links in a new window by default because it saves the end user making the mistake each time they forget :)

Thanks for looking.
