### ISSUE TITLE
What permissions are needed to run the Compatibility Checker?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-O365ITPro#646]
This article does not state what permissions are needed to run the Office 365 Centralized Deployment Compatibility Checker.  Global admin I'm assuming can, but not all of us are global admins.  What rights do other users/admins need to request to run the checker?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0659185-aece-2fa7-0e9d-fe56c771d8f9
* Version Independent ID: b5f0658e-d859-ad4d-7d1f-33a753fbd6c9
* Content: [Determine if Centralized Deployment of add-ins works for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins?redirectSourcePath=%252fen-us%252farticle%252fDetermine-if-Centralized-Deployment-of-add-ins-works-for-your-Office-365-organization-b4527d49-4073-4b43-8274-31b7a3166f92&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Canis-Lupis - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @Canis-Lupis , it's a Global admin...
I will create a PR to make the description less confusing
Thank you

**Comment by Canis-Lupis** [comment]
Much appreciated, thanks.

**Comment by mypil** [comment]
@Canis-Lupis - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
