### ISSUE TITLE
Azure AD security groups and access to a Office 365 group SharePoint

### ISSUE THREAD

**Issue by 2ndcahl** [MicrosoftDocs/OfficeDocs-O365ITPro#650]
Right now I'm trying to setup a small group of Office 365 group SharePoint sites where external people need access to. So if you are a member of OfficeGroup-A, you will also have read access to OfficeGroup-B (and vice versa). This can be done by adding "Members of OfficeGroup-A"-group to "OfficeGroup-B visitors"-group (and vice versa). This works fine. So long so good.
But if I try doing the same thing with a Azure AD security group, this does not work. I Add members (users) to AzureGroup-A and add this group to "OfficeGroup-B visitors"-group, then these users aren't given access to OfficeGroup-B SharePoint.

This page does not give any such information and I think it's vital to know, that Office 365 groups and Azure AD Security groups works in different ways.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbf6567-57c3-e359-8672-0c52cce6cc3b
* Version Independent ID: 2a0fbbad-b49d-7e6a-b5b8-3620d9fa9081
* Content: [Compare groups in Office 365](https://docs.microsoft.com/en-us/office365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by 2ndcahl** [comment]
Hmm... maybe it does work with an AD Security group. Does it take some time for Azure AD and SharePoint to synchronize group memberships? Or is there something else I need to be aware, when I try to give permissions using Azure AD security groups?

**Comment by mypil** [comment]
@2ndcahl - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by 2ndcahl** [comment]
Hi @mypil 
I haven't opened a support case, but I can confirm that it works with Azure AD security groups. I haven't looked closer into the delay and I don't have time for further investigations, so I have just accepted the delay. Maybe it was just temporary - or something I overlooked in my testing.
But thank you for replying and suggestion. I will close the case here.
