### ISSUE TITLE
Audio Conferencing in Office 365 is available in Office 365 Business Premium. 

### ISSUE THREAD

**Issue by umayrsufi** [MicrosoftDocs/OfficeDocs-O365ITPro#651]
This needs to be updated on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e643065c-fe65-e305-2c30-320b288109dc
* Version Independent ID: 413360ab-9ffb-97e2-3dd2-0e2d48f9fafa
* Content: [Buy or edit an add-on for Office 365 for business](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/buy-or-edit-an-add-on?view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/buy-or-edit-an-add-on.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/buy-or-edit-an-add-on.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@umayrsufi - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@umayrsufi - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
