### ISSUE TITLE
Incorrect page link

### ISSUE THREAD

**Issue by Imathil** [MicrosoftDocs/OfficeDocs-O365ITPro#652]
At the bottom of the article "If you need some help figuring out how to add the required DNS records and your DNS host isn't listed in Create DNS records for Office 365, first gather the information you need to create Office 365 DNS records. Then use the general steps in this topic to set up your domain's DNS records so you can use your domain with Office 365 services, like email."

The link "Create DNS records for Office 365" just loops back to the same article you are reading instead of what is purported to be an article with DNS hosts that support Office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f8d73e-364f-76dc-f826-1397f3656962
* Version Independent ID: 47fb8a7e-f062-e615-07c3-98b66e70c38e
* Content: [Create DNS records at any DNS hosting provider for Office 365](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?redirectSourcePath=%252farticle%252fb0f3fdca-8a80-4e8e-9ef3-61e8a2a9ab23.aspx&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Imathil - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Imathil - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
