### ISSUE TITLE
Is it 6 CNAME records or 5?

### ISSUE THREAD

**Issue by ilamak** [MicrosoftDocs/OfficeDocs-O365ITPro#653]
As far as the doc goes and on the portal, there are only 5 CNAME Records. What is this article referring to when it states 
"Add the six CNAME records that are required for Office 365" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958b2c19-260e-8489-6bbe-b1198bad2dab
* Version Independent ID: cefb2a92-2ba9-4c73-5d8a-e0636fc83510
* Content: [Create DNS records at Wix for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-wix?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-wix.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-wix.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by angiekam** [comment]
https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-google-domains?view=o365-worldwide#add-the-six-cname-records-that-are-required-for-office-365
This one also states Add the six cname Records... Need to verify the 6th record. 
1)
autodiscover 
 CNAME 
 1H 
 autodiscover.outlook.com. 
This value MUST end with a period (.) 
 
2)
sip 
 CNAME 
 1H 
 sipdir.online.lync.com. 
This value MUST end with a period (.) 

3) 
lyncdiscover 
 CNAME 
 1H 
 webdir.online.lync.com. 
This value MUST end with a period (.) 

4) 
enterpriseregistration 
 CNAME 
 1H 
 enterpriseregistration.windows.net. 
This value MUST end with a period (.) 

5) 
enterpriseenrollment 
 CNAME 
 1H 
 enterpriseenrollment-s.manage.microsoft.com. 
This value MUST end with a period (.)

**Comment by angiekam** [comment]
![image](https://user-images.githubusercontent.com/53496967/62170573-7c3f0480-b349-11e9-85fc-d2967098df32.png)

![image](https://user-images.githubusercontent.com/53496967/62170606-9aa50000-b349-11e9-9b40-37f252ca8fbf.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ilamak - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@ilamak - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
