### ISSUE TITLE
Microsoft Store?

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-O365ITPro#655]
Are we sure Microsoft _Store_ associates can help us with Global Admin questions? :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0974c5a1-988b-87d0-c67c-a95fc3a9a829
* Version Independent ID: 77ad3b51-e37a-c3ef-921f-171f90b07985
* Content: [Assign admin roles in Office 365 for business](https://docs.microsoft.com/en-us/office365/admin/add-users/assign-admin-roles?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/assign-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/assign-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@tseward - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@adefowler - Can you please share your insights on this issue?

Thank you.

**Comment by adefowler** [comment]
@tseward - Absolutely! We've set up a program where small businesses can get help from the Microsoft Stores. You can schedule an appointment to get help, or you can join one of the planned in-store training events. https://www.microsoft.com/en-us/store/locations/answer-desk?icid=en-us_passwords_tip_answer-desk_1152019

**Comment by adefowler** [comment]
Thanks! Replied and closed the issue.
