### ISSUE TITLE
Record Type

### ISSUE THREAD

**Issue by SerenModz21** [MicrosoftDocs/OfficeDocs-O365ITPro#656]
Freenom is missing SRV Record types. SRV Records are useful for lots of people and should be added to the site

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c001e51-b6f8-7161-cde9-27675fc0f07a
* Version Independent ID: 89e41027-7318-ff4b-f9ae-f14f327d363b
* Content: [Create DNS records at Freenom for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-freenom?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-freenom.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-freenom.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SerenModz21 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by SerenModz21** [comment]
ok thank you

**Comment by MaratMussabekov** [comment]
Hello @SerenModz21 ,
DSN management console at Freenom doesn't support SRV records, therefore SRV records are missed from this article (and there is a caution at the beginning of the article)
Thank you.

**Comment by mypil** [comment]
@SerenModz21 - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
