### ISSUE TITLE
Shared mailbox keep asking password in Outlook 2013 Standard

### ISSUE THREAD

**Issue by dinoleung68** [MicrosoftDocs/OfficeDocs-O365ITPro#657]
license@microsoft.com <- licensing mailbox
shared@microsoft.com <- shared mailbox

If granted permission to the licensing mailbox access the shared mailbox, on the Outlook 2013 Standard will show the Windows Security Alert and asking the password. Even the password is correct, the Outlook 2013  will still asking the password. 

If removed the permission, the mailbox will resume normal.
On Outlook 2016 Standard, the licensing mailbox and shared mailbox are working normally.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dinoleung68 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by dinoleung68** [comment]
Microsoft reference link:
https://docs.microsoft.com/en-us/office365/admin/email/create-a-shared-mailbox?view=o365-worldwide

This is my post:
https://techcommunity.microsoft.com/t5/Office-365/Outlook-2013-Standard-keep-asking-password-when-shared-mailbox/m-p/778381#M23703

**Comment by MaratMussabekov** [comment]
Hello @dinoleung68 ,
1. Have you tried to create new Outlook profile?
2. Is automapping enabled for this mailbox?
3. Does your Office 2013 has all the patches installed?
4. have you tried to repair Office 2013?

From my experience, most of the issues related to shared mailboxes could be solved by disabling automapping.
Thank you

**Comment by dinoleung68** [comment]
Hi @MaratMussabekov ,

1. Have you tried to create new Outlook profile?
  Dino: Yes, we had to create a new Outlook profile, and set up to another computer. Still failure.

Is automapping enabled for this mailbox?
Does your Office 2013 has all the patches installed?
have you tried to repair Office 2013?
From my experience, most of the issues related to shared mailboxes could be solved by disabling automapping.
Thank you

**Comment by MaratMussabekov** [comment]
Hi @dinoleung68 ,
Please try to disable automapping for this mailbox and add it to outlook as a separate mailbox.
i understand that it is not a solution, but as there is only single mailbox affected, it could be an acceptable workaround.
Thank you

**Comment by mypil** [comment]
@dinoleung68 - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
