### ISSUE TITLE
I go to this page from the O365 new admin portal and does not list out the admin roles.

### ISSUE THREAD

**Issue by mstehouwer** [MicrosoftDocs/OfficeDocs-O365ITPro#660]
I am trying find details on the admin roles and what each one give access to. The admin portal sent me to this page "Choose the admin role that you want to assign to this user. Learn more about administrator roles". This page does help you learn about the roles. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?redirectSourcePath=%252fen-US%252farticle%252fda585eea-f576-4f55-a1e0-87090b6aaa9d&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by adefowler** [comment]
@mstehouwer - Please stay tuned...they are getting added back by EOD today. I was hasty in removing them too soon. :-) Thank you so much for your feedback. I'll reply back when the topic is published.

**Comment by adefowler** [comment]
@mstehouwer - The topic has been updated. Thanks again much for providing this feedback. I'm sure you weren't the only person who noticed, but you are the one who let me know!

**Comment by mstehouwer** [comment]
Thank you for fixing so fast.

Matt Stehouwer
Senior Messaging and Collaboration Manager
Michigan State University
IT Services
517 355-9003 | Email: stehouw2@msu.edu<mailto:stehouw2@msu.edu>
[IT Services grapic]
