### ISSUE TITLE
i having this message on all my e-mails to yours servers

### ISSUE THREAD

**Issue by renamate** [MicrosoftDocs/OfficeDocs-O365ITPro#661]
"5.7.1 Unfortunately, messages from [104.130.122.30] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [HE1EUR04FT035.eop-eur04.prod.protection.outlook.com]"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34678809-c030-f606-d793-378ec1501efc
* Version Independent ID: 74b5b2fa-14a1-f150-f0a7-d3ae47848d0a
* Content: [Support information for Chile](https://docs.microsoft.com/en-us/office365/admin/support/chile?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/support/chile.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/chile.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@renamate - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by cmcatee-MSFT** [comment]
@renamate Please see [Fix email delivery issues for error code 550 5.7.1 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online)

**Comment by mypil** [comment]
@renamate - Please refer to the additional recommendation from cmcatee-MSFT which could help resolve your technical concern. If your issue persists, then it would be best for you to open a service ticket in your tenant.

However, if in case you find that it is a documentation error, feel free to comment back here and we'll be glad to help fix it. Thank you!

**Comment by mypil** [comment]
@officedocsbot close
