### ISSUE TITLE
Query on "Add the six CNAME records that are required for Office 365"

### ISSUE THREAD

**Issue by prsamant** [MicrosoftDocs/OfficeDocs-O365ITPro#662]
Article seems to be pointing to 6 CNAME records and we are just able to see 5. This requires more clarity as might create a confusion for the customers trying to implement the said setup. If I am missing out anything please let me know but just referencing the document I think the count should be "5" and considering Office 365 requirement it should be "7". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab521261-ae0d-9fe5-eff2-14ae0a5e3f68
* Version Independent ID: 59147889-4b01-f27e-599b-970595a7fe85
* Content: [Create DNS records at Google Domains for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-google-domains?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-google-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-google-domains.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@prsamant - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by prsamant** [comment]
@mypil - Thank you for following up. We have this migration option been opted by customers moving from G-Suite to Office 365 services. This article stands as a first impression for these customers with reference to Microsoft written instructions and we have seen 1 or 2 cases getting created referencing the same issue reported by customers. Also if there can be anything to expedite this request please get it done as I see a similar concern was reported by someone before me flagging it.

**Comment by MaratMussabekov** [comment]
Hello @prsamant ,
the information in the article is outdated, currently only 5 CNAME records are required (MSOID record is no more in use)
I created the PR, Thank you

**Comment by prsamant** [comment]
Than you @MaratMussabekov for the confirmation.

**Comment by mypil** [comment]
@prsamant - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by dotun-o** [comment]
This is still an issue, or at least so on another page: https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-bluehost?view=o365-worldwide#BKMK_add_CNAME
