### ISSUE TITLE
the checker is failing with:

### ISSUE THREAD

**Issue by Rika-Q** [MicrosoftDocs/OfficeDocs-O365ITPro#663]
Error occured during retrieval of required data. Output file will not be produced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0659185-aece-2fa7-0e9d-fe56c771d8f9
* Version Independent ID: b5f0658e-d859-ad4d-7d1f-33a753fbd6c9
* Content: [Determine if Centralized Deployment of add-ins works for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Rika-Q - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Rika-Q** [comment]
Q is the centralized deployment suppose to work for Outlook Add-in on hybrid, while user MB is hosted on prem ?

**Comment by msbemba** [comment]
@Rika-Q Thank you for your feedback. That is correct, The MB needs to be licensed and hosted in Exchange online for the Centralized deployment to work. Hope this helps!

Regards
Sri

**Comment by Rika-Q** [comment]
Thanks @msbemba
