### ISSUE TITLE
[LOC] MD notation visible at live site

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-O365ITPro#665]
**article:** create-dns-records-at-godaddy.md
**author:** pebaum
**URL:**  https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-godaddy?view=o365-worldwide

**repro steps:**
 1. navigate to URL above
 2. check _Add a TXT record for verification_ paragraph
   - point 4 : table
   - point 5 : asterisks

![image](https://user-images.githubusercontent.com/47977325/62535568-060c3780-b84c-11e9-9461-920b87fa8241.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGlobal  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
