### ISSUE TITLE
User owned apps and services option not available

### ISSUE THREAD

**Issue by rahulraj40** [MicrosoftDocs/OfficeDocs-O365ITPro#666]
I could not find 'User owned apps and services' options under Settings &gt; Services & add-ins with old Admin center UI. neither in new UI under Settings &gt; Apps. Tried with Global Admin account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d424b-6f62-e70c-9c2d-ad779ffa6c3b
* Version Independent ID: e4597136-bfe8-4230-da83-f806a1126005
* Content: [Manage deployment of Office 365 add-ins in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by rahulraj40** [comment]
This is working, I was checking in Production tenant where I don't have Global Admin.

**Comment by mypil** [comment]
@rahulraj40 - Thank you for submitting feedback.

From our understanding, you mentioned that it is already working. Does this mean that your issue has been resolved or is there anything within this doc that you suggest to be edited?

**Comment by mypil** [comment]
@rahulraj40 - Closing this issue since you indicated that it is already working. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
