### ISSUE TITLE
1&1 is being renamed to IONOS

### ISSUE THREAD

**Issue by FlorentinStafie** [MicrosoftDocs/OfficeDocs-O365ITPro#67]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60ec04cf-93af-b216-4290-c2d0ff79878d
* Version Independent ID: e7fd186e-7efd-711e-3f29-e318b2100083
* Content: [Create DNS records at 1&1 Internet for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-1-1-internet?redirectSourcePath=%252fen-us%252farticle%252fcreate-dns-records-at-1-1-internet-for-office-365-5762c3ca-1de2-4999-bfe5-4c5e25a8957e&view=o365-worldwide)
* Content Source: [Office365-Admin/dns/create-dns-records-at-1-1-internet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-1-1-internet.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndreaBarr** [comment]
@FlorentinStafie Thank you for this update

I will get this rebranding information over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@FlorentinStafie  this has been fixed
