### ISSUE TITLE
Item Count field missing from exported CSV

### ISSUE THREAD

**Issue by MDouglasBTS** [MicrosoftDocs/OfficeDocs-O365ITPro#673]
Hi,

Export the email activity usage report yesterday and the CSV contained a fiend labelled Item Count.  however, when exporting the results again today the field is missing.  Am i doing something wrong or has something changed?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@MDouglasBTS - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by MDouglasBTS** [comment]
OFFICIAL

https://docs.microsoft.com/en-us/office365/admin/activity-reports/mailbox-usage?view=o365-worldwide






Regards,


Martin Douglas
Support Technician
Dumfries & Galloway Council
Economy & Resources
Business & Technology Solutions
Monreith House | Crichton Business Park | Glencaple Road
Dumfries | DG1 4ZZ

Telephone: Internal: 60028 | External: 01387 702 628
Mobile: 07920 528 141

Email: Martin.Douglas@dumgal.gov.uk<mailto:Martin.Douglas@dumgal.gov.uk>

Any email message sent or received by the Council may require to be disclosed by the Council under the provisions of the Freedom of Information (Scotland) Act 2002.

Disclaimer:
This email, from Dumfries and Galloway Council, and any files transmitted with it, is confidential and intended solely for the use of the individual or entity to whom they are addressed.

If you are not the intended recipient of this email (and any attachment) please inform the sender by return email and destroy all copies.  If you are not the intended recipient or responsible for delivering it to the intended recipient, you are hereby notified that any use, disclosure, review, dissemination, distribution or reproduction of this email is strictly prohibited.  Please be aware that communication by internet email is not secure as messages can be intercepted and read by someone else.  Dumfries and Galloway Council do not accept liability for any loss or damage which may result from this email or any files attached.  It is your responsibility to scan this email and any attachments for computer viruses or other defects.

Any email including its content may be monitored and used by the Council for reasons of security and form monitoring internal compliance with the policy on staff use.  Email monitoring or blocking software may also be used.

Any email message sent or received by the Council may require to be disclosed by the Council under the provisions of the Freedom of Information (Scotland) Act 2002.  For further information and to view the Council's privacy statement please click  here<https://www.dumgal.gov.uk/privacy>


P  SAVE PAPER - Please do not print this e-mail unless absolutely necessary

**Comment by mypil** [comment]
@MDouglasBTS  - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
