### ISSUE TITLE
Fix this problem

### ISSUE THREAD

**Issue by Songyisunshine** [MicrosoftDocs/OfficeDocs-O365ITPro#679]
When can you fix these problems and make them work in line with the international version of Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d24ddb3-fd0d-22e7-3f0a-215ec8aa5212
* Version Independent ID: 1d7b58ce-c35a-ffcf-adba-ee5ec02f8bcf
* Content: [Office 365 operated by 21Vianet](https://docs.microsoft.com/en-us/office365/admin/services-in-china/parity-between-azure-information-protection?view=o365-21vianet#feedback)
* Content Source: [Office365-Admin/services-in-china/parity-between-azure-information-protection.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/services-in-china/parity-between-azure-information-protection.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Songyisunshine - Thank you for submitting this feedback.

Can you please share more details on the exact problems that you have? Which portion of this document are you clarifying?

Thank you.

**Comment by Songyisunshine** [comment]
My question is: Will the missing features described above be resolved one by one?
“These are the existing gaps between Azure Information Protection for Office 365 operated by 21Vianet and our commercial offerings as of July 2019”

**Comment by mypil** [comment]
@Songyisunshine - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in [User Voice](https://office365.uservoice.com) 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
