### ISSUE TITLE
Register Domain on office365

### ISSUE THREAD

**Issue by eysz7x** [MicrosoftDocs/OfficeDocs-O365ITPro#68]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4080057-b2f7-129a-ed97-450b6b571920
* Version Independent ID: 1a98aaee-42b8-dc0d-602a-07342969bdca
* Content: [Create DNS records at Register365 for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-register365?redirectSourcePath=%252fen-us%252farticle%252f004030b4-10ad-4026-96e7-011b6afc7e73&view=o365-worldwide)
* Content Source: [Office365-Admin/dns/create-dns-records-at-register365.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-register365.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndreaBarr** [comment]
@eysz7x Do you have a specific issue with this article?

**Comment by mypil** [comment]
@eysz7x - Can you please share what specific issue you have with this article?

**Comment by mypil** [comment]
@eysz7x - We appreciate any feedback you can provide to make the content in the Microsoft docs better. Since we did not get any response from you, we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
