### ISSUE TITLE
Broken go-link in section 1.

### ISSUE THREAD

**Issue by v-MarioMigliacio** [MicrosoftDocs/OfficeDocs-O365ITPro#684]
Hi, I notice that in section 1, it first says that In the admin center, with a link for the 'admin center' but it doesn't resolve to the admin center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0759f6b0-4d12-e0fa-f1cf-320f4e4ae32a
* Version Independent ID: 5b10ae00-e088-b39d-e13f-ead4081f2784
* Content: [Top 10 ways to secure Office 365 and Microsoft 365 Business plans](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @SuPotter
* Microsoft Alias: **supotter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@v-MarioMigliacio - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@v-MarioMigliacio Thank you for the feedback. We have corrected the broken link and the same can be tracked via PR https://go.microsoft.com/fwlink/p/?linkid=837890

**Comment by mypil** [comment]
@v-MarioMigliacio - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
