### ISSUE TITLE
Copy edits

### ISSUE THREAD

**Issue by pomroy** [MicrosoftDocs/OfficeDocs-O365ITPro#686]
This document needs review by a professional editor. "admin takeover" can't seriously be the official term for this. "It's an office tenant that do have an administrator account already" could use some work as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24eaf551-7e49-ee4a-2979-8515f92d4d2a
* Version Independent ID: 67e53343-d996-ce5e-4742-0c0d819fbca1
* Content: [Do an admin takeover in Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/become-the-admin?redirectSourcePath=%252fen-US%252farticle%252fb9707ec8-2247-4e25-9bad-f11ddbc686e4&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/become-the-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/become-the-admin.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@pomroy - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@nenonix - As discussed, please assist to complete this copy/edit issue. Thank you.

**Comment by nenonix** [comment]
@pomroy  I have submitted PR #746 to address the many problems you raise (subject to review). Thank you for taking time to help improve the content. Note that the term "admin takeover" is correct and is used in other content (but I did try to use it more elegantly by rewording the article title).  Apologies for taking so long - this was a challenging issue to address.
