### ISSUE TITLE
Old references

### ISSUE THREAD

**Issue by JD-aus** [MicrosoftDocs/OfficeDocs-O365ITPro#687]
Step 2. This document references incorrect information as the domains page is no longer within the setup section of admin center.

Step 4. this document also references details that i can not see. when clicking on the domain, the menu options are: "set as default", "DNS management", "check dns" & "remove". when clicking "DNS Management" i get thrown back into the the setup wizard (despite the fact that all domains were setup a few years ago).

I am "trailing" the latest GUI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a782c64-5ec7-de5c-d57f-65b8f07a8678
* Version Independent ID: dbb00763-2bae-7843-2334-cc3d077beb1a
* Content: [Add or edit custom DNS records in Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/add-or-edit-custom-dns-records?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/add-or-edit-custom-dns-records.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/add-or-edit-custom-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@JD-aus - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@JD-aus  Thank you for your feedback. The latest GUI still has the domain section under setup. Also, For  step 4 (Edit or add custom records) You need to have the NS records pointing to Microsoft so that the options show up. If your domain is setup with DNS records like MX TXT and CName, Custom records option would not show up

Hope this Helps!

Thanks
Sri

**Comment by mypil** [comment]
@JD-aus - From our understanding, the issue has been answered by msbemba. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by ElvinBadBoyBishop** [comment]
Agreed this reference is out of date and incorrect. Domains are under Setup not settings. There's no link to custom records. I get thrown into the setup Wizard when I try to Manage DNS.
