### ISSUE TITLE
Links fail to resolve due to extra character.

### ISSUE THREAD

**Issue by hst44** [MicrosoftDocs/OfficeDocs-O365ITPro#689]
Many of the links have an extra ')' at the end of them causing the FWLink to fail to resolve.

For example, the first Message Center link on the page is defined as:

< a href="https://go.microsoft.com/fwlink/p/?linkid=2070717)" target="_blank">Message center</a >

the ')' at the end of the link should be removed for it to be a valid FWLink and not redirect to the fallback (microsoft.com).  Note:  This occurs in several spots on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f10cd1-72c8-b741-cfe4-905423275e58
* Version Independent ID: 86d3bfb1-53cc-6877-0be1-e347e428ad7e
* Content: [Message center in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/message-center?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/message-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/message-center.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hst44 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@hst44 - PR #709 has been created to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!
