### ISSUE TITLE
Custom tile image URL is not recognized

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/OfficeDocs-O365ITPro#69]
Hello Microsoft Support,
I wanted to add two custom tiles to SharePoint locations within our tenant.
I uploaded two images on our corporate website (utilizing WordPress as CMS):
https://www.das-ee.com/wp-content/uploads/2018/11/teamevents-das_60px.png
https://www.das-ee.com/wp-content/uploads/2018/11/icon-aus-und-weiterbildung_60px.png

I tested another image from the web (https://www.academicgates.com/images/USA_SDB_UNOFKE.png) which worked perfectly fine. Same dimensions (60x60 px), same file type png.

What I figured out so far in my dev tenant ...
The image URL must not contain any "-" at all ?!?
I spend almost two hours on this "basic task".
Any idea? Can you reconstruct my issue?

Last but not least, to answer one question in advance:
No, anonymous sharing links are not an option for me. Thank you for your support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368890ff-2835-ca55-b1c6-29cbe47c2244
* Version Independent ID: 03bbe66d-e3cb-9fe1-c77c-4741276c43d0
* Content: [Add custom tiles to the app launcher](https://docs.microsoft.com/en-us/office365/admin/manage/customize-the-app-launcher?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by joshn-ridewta-com** [comment]
I experienced the same problem and it looks like a "-" was the problem for me too.  Thank you so much Markus-Hanisch for your troubleshooting.

**Comment by Markus-Hanisch** [comment]
> I experienced the same problem and it looks like a "-" was the problem for me too. Thank you so much Markus-Hanisch for your troubleshooting.

You are welcome. Sharing is caring.

**Comment by mwiedemeyer** [comment]
Hi,
please can you explain, why no - is allowed in the image url? That absolutely makes no sense.
I wanted to add an image from a CDN which contains a - in the domain.

**Comment by mypil** [comment]
@Markus-Hanisch - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Markus-Hanisch** [comment]
@mypil 
I opened the ticket back then already. Issue was never resolved. Ticket is closed. 
I just wanted to make other's aware of this issue.
It is not mentioned in the documentation, but took me hours to figure out the root cause, which, as agreed with @mwiedemeyer, absolutely makes no sense.
