### ISSUE TITLE
CloudFlare Admin GUI does not allow _tls SRV records

### ISSUE THREAD

**Issue by jwhite1st** [MicrosoftDocs/OfficeDocs-O365ITPro#691]
The guide says to create a _tls SRV record and Cloudflare only allows _tcp and _udp in the web gui. If you use the API you can create whatever records per [this](https://github.com/ansible/ansible/pull/36709)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaff890-3858-eacb-ed21-a7c0dc4d3d36
* Version Independent ID: 087f92d5-6ace-4a32-4252-c94b843de607
* Content: [Create DNS records at Cloudflare for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide)
* Content Source: [Office365-Admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jwhite1st  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@jwhite1st This option was available when the article was written. I'm surprised to see that it's not there anymore (in the GUI at least). There are a few topics around this withing the Cloudflare community - check https://community.cloudflare.com/t/no-srv-tls-option/108899.

I think this will get fixed/addressed sometime in the future, so i would not change the article but add a note stating that at the moment this cannot be done using the GUI.

There are workarounds, as you also mentioned. One is exporting the DNS zone config from O365, editing it and importing it in Cloudflare, as described [here](https://www.urtech.ca/2019/08/solved-cannot-create-_tls-srv-record-in-cloudflare/)

**Comment by jwhite1st** [comment]
@VLG17 Cloudflare rolled out a GUI update which broke creating records for certain types. I made a script that uses the API for people as a workaround.
I just figured that the more people knew the better it would be.

**Comment by VLG17** [comment]
@jwhite1st Good to know that. Could you share a link to this script?

**Comment by jwhite1st** [comment]
@VLG17 
https://github.com/jwhite1st/Scripts/tree/master/CloudFlare/DNS_Record

**Comment by mypil** [comment]
@jwhite1st - From our understanding, the issue has been resolved based on the merged commit [[682c57c](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/682c57c39c7f8a2bb9447516d6c99906f4a2bb1f)] but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
