### ISSUE TITLE
"Add the six CNAME records that are required for Office 365" section error

### ISSUE THREAD

**Issue by WhatWouldChuckDo** [MicrosoftDocs/OfficeDocs-O365ITPro#693]
In the "Add the six CNAME records that are required for Office 365" section,

The section should be renamed to "Add the five CNAME records that are required for Office 365".
step 4 states add the first of six when only five are listed.
step 6 state add each of the other five when the other listed are four.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d30a72-4274-982c-4737-7c87a35febb9
* Version Independent ID: dea907ab-1da1-dcbd-8db7-5120c2c41a8f
* Content: [Create DNS records at DNSMadeEasy for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-dnsmadeeasy?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-dnsmadeeasy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-dnsmadeeasy.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@WhatWouldChuckDo  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @WhatWouldChuckDo 
Thanks for your feedback, I created a pull request to correct the article.
Thank you

**Comment by mypil** [comment]
@WhatWouldChuckDo - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
