### ISSUE TITLE
Read email in another user's mailbox

### ISSUE THREAD

**Issue by ValerianHeints** [MicrosoftDocs/OfficeDocs-O365ITPro#696]
setting the permission "Read and manage" is actually full access setting.
Why not to communicate cleary? Why using euphemism "Read email in another user's mailbox" instead of "granting full-access"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d976996c-10a9-c1a2-7f25-3f6ba90ad9db
* Version Independent ID: 2e9c738f-2a48-8c83-4505-a3ffaf2646ed
* Content: [Give mailbox permissions to another user in Office 365 - Admin Help](https://docs.microsoft.com/en-us/office365/admin/add-users/give-mailbox-permissions-to-another-user?redirectSourcePath=%252farticle%252fRead-email-from-another-user-s-mailbox-in-Office-365-cb3b6a8a-c6e8-4342-803c-3e54b6428cc2&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ValerianHeints - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@ValerianHeints Thank you for sahring your feedback. Please note that Read and Manage is not a full access with read and manage permissions you can create email drafts, Send calendar invites, create events, delete emails, read emails, but cannot send emails.

Thanks.

**Comment by mypil** [comment]
@ValerianHeints - From our understanding, the issue has been answered by joinimran. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by ValerianHeints** [comment]
Hello,

I cannot confirm that it is not "full access". Setting to "Read and Manage"
via microsoft 365 admin center / users / active users / mail / mailbox
permissions results in setting the corresponding "mailbox delegation" Full
Access setting in Exchange admin center / mailboxes.

Best regards
Valerian

Am Do., 29. Aug. 2019 um 08:52 Uhr schrieb ImranHabib <
notifications@github.com>:

**Comment by joinimran** [comment]
Hello @ValerianHeints ,

I have checked and found that its with Read and Manage permission you will not get full access to the mailbox. As you will not be able to send the emails. Please see this test screenshot.

![image](https://user-images.githubusercontent.com/47118050/64550248-52351680-d2e7-11e9-9236-a8837314401c.png)

Although in Exchange online it shows it in the list of Full Access but its actually not. I have checked and verified this on my test environment. 

Regards.
Imran.
