### ISSUE TITLE
Best Practice - IT Support

### ISSUE THREAD

**Issue by laughey** [MicrosoftDocs/OfficeDocs-O365ITPro#698]
I wholeheartedly agree with modern auth, MFA, etc., but it's next to impossible to troubleshoot, manage and deploy systems (i.e., Windows 10) using Office 365 when "confirmation" is needed to complete steps involving (MA/MFA) authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc64ec1-ba7d-bcd3-51a6-a99a5d060e2c
* Version Independent ID: 2e6ca190-14c5-5ae5-780a-00ca99ccc9fd
* Content: [Plan for multi-factor authentication for Office 365 Deployments](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/multi-factor-authentication-plan?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/multi-factor-authentication-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/multi-factor-authentication-plan.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@laughey - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
**[User Voice](https://office365.uservoice.com)** .
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by laughey** [comment]
Idea submitted!

Modern Authentication Pause

Thanks for the direction/advice.

J. Lance Aughey | IT Manager

Direct 603.766.5887 | Main 603.422.8833 | Cell 603.781.5837

Communication assembled using two thumbs; please excuse brevity and typ0s.

________________________________

**Comment by mypil** [comment]
@officedocsbot close
