### ISSUE TITLE
How to change deny alert or send a message to users that try to create a new group

### ISSUE THREAD

**Issue by 2704lnx** [MicrosoftDocs/OfficeDocs-O365ITPro#70]
This procedure is useful and easy to implement.
We recently block the group creation after two years. 
The users don't know what is the new procedure to create their groups.

To make a good change management, I'm looking to change the system message "Your organization's global admin has turned off the ability to create new Plans ans Office 365 Groups." 
or get an activity alerts from Graph.  It is seem not possible to do that. 

With FORMs, we created a new self-service process to create office groups that include many validations.
How can I redirect my users to the new procedure that I created? 
I have to inform users when they try to create groups by mails, with a pop-up message or any other way...

Thanks
Marc
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@2704lnx Thank you for this inquiry

I am not sure how to get the users redirected to your process with a pop up or other option. Let me get this over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@2704lnx - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by 2704lnx** [comment]
I have already do that! no results.  I am in list in uservoice portal... no solutions at this time
https://office365.uservoice.com/forums/286611-office-365-groups/suggestions/36147103-after-block-office-group-creation-in-tenant-we-ar
