### ISSUE TITLE
Invalid phone number

### ISSUE THREAD

**Issue by boffsky** [MicrosoftDocs/OfficeDocs-O365ITPro#700]
Please tell how can I call to 8 10 800 2548 1044? My phone answers "invalid phone number", my skype answers "no answer". If I call 499 922 86 23, the answer is "Please call 8 10 800 2548 1044, we can't help you here"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c05c72-db81-b012-f871-9243de45567d
* Version Independent ID: ad5fab8b-bc24-900a-85df-f69bcfa050c5
* Content: [Support information for Russia](https://docs.microsoft.com/en-us/office365/admin/support/russia?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/support/russia.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/russia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@boffsky  - Thank you for submitting feedback.

I will get this telephony issue over to the O365ITPro writing team for investigation.

In the meantime, if you require technical support, you can open a **[service ticket](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online)** in your tenant so this can get resolved ASAP.  Based on outcome, let me know if it is something that can be called out in the docs.

**Comment by mypil** [comment]
@cmcatee-MSFT - FYI.

**Comment by cmcatee-MSFT** [comment]
@boffsky It would help us troubleshoot this if you can provide us some additional information. We'd like you to test the # again, and make 2 attempts from 2 different caller phone numbers. Please contact me directly (click my profile image to get my email address) and provide the following information for each test call:

1.   Country and Number being called:
2.   Country and City of person calling to test: 
3.   Number tester is calling from:
4.   Landline or Mobile Phone?
5.   What Carrier does this number belong to?  
6.   Date and time of test call:
7.   Exact details of errors or experience when calling:

Also – Please insure that these callers have International service enabled on their mobile service (this could cause the issue).

Thanks,
Cern

**Comment by mypil** [comment]
@boffsky  - We will close this issue now. If you still have problems calling our support hotline and need help to troubleshoot your telephony issue, please contact cmcatee@microsoft.com. 

Thank you.
