### ISSUE TITLE
I Don't Have a Send As Option

### ISSUE THREAD

**Issue by mramiller** [MicrosoftDocs/OfficeDocs-O365ITPro#701]
I'm trying to follow the instructions in this article, however I only have a Send on Behalf option in my distribution list's group delegation settings, I don't have the Send As option. Any ideas why I'm not seeing the Send As option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784a196f-3e0e-0c0a-0b2f-af2105a774d9
* Version Independent ID: 08300f82-3b1d-b96d-bf10-e401ac6ef2c0
* Content: [Allow members to send as or send on behalf of a Group](https://docs.microsoft.com/en-us/office365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@mramiller - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
