### ISSUE TITLE
Which account gets debited if you have more than one set up ?

### ISSUE THREAD

**Issue by marc-be** [MicrosoftDocs/OfficeDocs-O365ITPro#702]
Hi,

We only have one subscription giving A3 licences to everyone but some departments would like to be able to buy A5 licences instead of the A3 already provided. If I had the different departments bank accounts will I be able to choose from which bank account (department) the additional A5 licences bought should be debited or how does it work ?

Thanks in advance,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bdbb534-fd78-a4d0-dac4-b9a3ce1179fe
* Version Independent ID: 134d6149-7c7d-3cd8-4842-47287bdd158f
* Content: [Add, update, or remove a credit card or bank account](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/add-update-or-remove-credit-card-or-bank-account?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/add-update-or-remove-credit-card-or-bank-account.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/add-update-or-remove-credit-card-or-bank-account.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@marc-be - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
