### ISSUE TITLE
As a SharePoint Admin it's not possible to manage Office 365 group from Admin Center. 

### ISSUE THREAD

**Issue by markgort86** [MicrosoftDocs/OfficeDocs-O365ITPro#703]
Please change the documentation, to something like Manage Office 365 / SharePoint Online group sites. The same issue exists for the Teams admin.

SharePoint admin	Full access to SharePoint Online, manages Office 365 groups, manages service requests, and monitors service health.
Teams admin	Full access to Teams & Skype admin center, manages Office 365 groups and service requests, and monitors service health.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [Admin functies in het Microsoft 365 admin center](https://docs.microsoft.com/nl-nl/office365/admin/add-users/about-admin-roles?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@markgort86  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @markgort86, I think it would be better just to remove the part "Office 365 groups" without replacing it with "Manage Office 365 / SharePoint Online group sites", because this role has "Full access to SharePoint Online", which already means that it can administrate any SharePoint site.
What do you think?
Thank you

**Comment by markgort86** [comment]
Yeah, i think it's better to replace that part! In the admin portal of Office 365 this text must als removed because the information over there is also incorrect.

**Comment by mypil** [comment]
@markgort86 - From our understanding, the issue you raised has been answered by MaratMussabekov and by the doc owner - adefowler based on this [comment](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/706#issuecomment-528936091).  If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by markgort86** [comment]
@mypil thanks for you're response on this issue, how can i reopen that pull request?

**Comment by mypil** [comment]
@markgort86 - are the changes you're suggesting similar to what is in PR #706 or is there something more that you would like to add? 

Please take note that it was the doc owner @adefowler who Closed PR #706. So, if we reopen it then it might be Closed again.

If it is something new then a new PR needs to be created for that. Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? 
If you could suggest what the appropriate text and where it should be placed, I could assign MaratMussabekov to create a Pull Request to get it added or you also have the option to create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. 

Thank you.

**Comment by mypil** [comment]
@markgort86  - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by adefowler** [comment]
Hi! @markgort86 - I checked with the product team and this is actually a bug that you found! So thank you very much for reporting it. I'll reply back when the bug has been fixed. Thanks so much again for reporting it.

**Comment by markgort86** [comment]
Hi @adefowler, thanks for getting back to me! I’m happy to see that someone from Microsoft is responding to this issue. I was also thinking that i found a bug. Is is possible to reopen this issue on Github?

**Comment by adefowler** [comment]
Actually there is. Issue reopened!

**Comment by mypil** [comment]
@adefowler - Do you have any updates on this issue?

**Comment by adefowler** [comment]
@markgort86 - We've got a fix in place and we're testing it now. Should be rolled out in October. Thanks for that feedback -- and keep it coming.

**Comment by mypil** [comment]
@markgort86 - From our understanding, the issue you raised has been answered by adefowler where she mentioned that they found a fix which should be rolled out this month - October. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by markgort86** [comment]
@mypil yes, but until now the issue isn't resolved globally. It's better to have this case open until it's rolled out, or am i wrong?

**Comment by mypil** [comment]
@markgort86 - Reopening issue as requested.

@adefowler - Please assist to give updates and close issue once roll out is successful.

Thank you.

cc: @kenwith

**Comment by adefowler** [comment]
@markgort86 - Sorry taking so long to get back to you, Mark! But the fix has been rolled out. Please test it - and if it works for you, close the comment.

Thanks again for reporting this bug!

**Comment by markgort86** [comment]
@adefowler thanks for this update! I tried to update a group in the Office 365 admin center and that is now possible without limitations. Is there a way to see what has been changed by Microsoft? Instead of what is already visible on the roadmap.

**Comment by adefowler** [comment]
@markgort86 - The roadmap is still the best way.
