### ISSUE TITLE
Still requires app password for Office 2013?

### ISSUE THREAD

**Issue by rejohnson76** [MicrosoftDocs/OfficeDocs-O365ITPro#704]
I added the reg keys but I can't set up a new Outlook 2013 account with O365 without creating an app password.  Once Outlook config is created, I can delete the app password for that device and use my AD credentials with MFA enabled.  Perhaps there is another registry entry to modify that is missing until the very first time one successfully creates an Outlook profile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db5aea7-bb2e-f349-7518-fc4fd396b3da
* Version Independent ID: b4112301-d38e-4a77-847b-f41bd7bca0f1
* Content: [Enable Modern Authentication for Office 2013 on Windows devices](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by rejohnson76** [comment]
This is now fixed.  Not sure why it wouldn't work but I deleted everything under Identity and restarted.  Then added the two DWords as stated and now Outlook is checking MFA and using my AD credentials.  No more app p/w!  Thanks!

**Comment by mypil** [comment]
@rejohnson76 - Glad to know that your issue has been fixed! I will proceed to close this issue then.

Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.
