### ISSUE TITLE
Preview?

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-O365ITPro#705]
How is this still in preview?  It has been long over a year - previews should never last that long.  This needs to get into the production AzureAD module - as well as the AAD UI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@danmyhre  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@MikePlumleyMSFT - Can you please share your insights on this issue?

Thank you.

**Comment by MikePlumleyMSFT** [comment]
The documentation is correct. I don't have a date for when this will be available in the production Azure AD module.

**Comment by mypil** [comment]
@danmyhre - The doc owner has shared his insights and answered your query.

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. 

Thank you for engaging with the community here for the docs.
