### ISSUE TITLE
Description of Privileged role admin

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-O365ITPro#707]
The description of the `Privileged role admin` reads

    Manages role assignments in manages all access control features of Privileged Identity Management.

Syntactically that is not a valid sentence.
Should that be "Manages role assignments **and** all access control features of Privileged Identity Management."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@Weishaupt - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by adefowler** [comment]
@Weishaupt - Thanks for finding my bad copy/paste error. The sentence should read: 
Manages role assignments and all access control features of Privileged Identity Management.

**Comment by mypil** [comment]
@Weishaupt - PR #713 has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
