### ISSUE TITLE
Add functionality to show different apps in app launcher to different groups of users

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-O365ITPro#71]
Many of my clients have a need to add apps to the app launcher for specific user groups only, not just globally. This is a common requirement for multinational organisations which may for example have separate IT support functions per country, separate HR applications per country etc.
Pleas add the functionality to show different apps to different users based on AD group membership or user profile properties (country, department, role, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368890ff-2835-ca55-b1c6-29cbe47c2244
* Version Independent ID: 03bbe66d-e3cb-9fe1-c77c-4741276c43d0
* Content: [Add custom tiles to the app launcher](https://docs.microsoft.com/en-us/office365/admin/manage/customize-the-app-launcher?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by pettersh** [comment]
You can achieve what you want by registering your apps in Azure AD and only assign access to specific users or groups

**Comment by pettersh** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users

**Comment by angoo-atea** [comment]
> 
> 
> https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users

Hi Petter - I've looked further at this and tried to test with a standard O365 application (Yammer) but the instructions in that article don't seem to match the navigation/settings options in the Azure interface. 
For example, 

_"**Assign users and groups to the app**
Once you've configured your app to enable user assignment, you can go ahead and assign users and groups to the app.

    Select the Users and groups pane in the application’s left-hand navigation menu."_

There is no Users and groups pane in the Yammer applications left-nav.
Does this mean that this configuration is only available for custom apps?

**Comment by mypil** [comment]
@angoo-atea -  Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the  Office 365 better. They keep a close tab on User Voice **https://office365.uservoice.com/** and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!
