### ISSUE TITLE
System Serial Number issue

### ISSUE THREAD

**Issue by Naxterra** [MicrosoftDocs/OfficeDocs-O365ITPro#710]
Hello

I am trying enroll my devices to Intune Autopilot but CSV file format is wrong.

Get-WindowsAutoPilotInfo.ps1 -OutputFile C:\Temp\ShaPC.csv that is my command.

![image](https://user-images.githubusercontent.com/41871948/64195130-00bcff80-ce81-11e9-8fef-93d5c2124556.png)

I also tried with computer name

Get-WindowsAutoPilotInfo.ps1 -ComputerName "Shade-PC-001" -OutputFile C:\Temp\ShaPC-2.csv

![image](https://user-images.githubusercontent.com/41871948/64195362-96f12580-ce81-11e9-81c7-15ae45d63683.png)

What can I do?

**Comment by mypil** [comment]
@Naxterra - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Naxterra** [comment]
Hello

I talked with MS Support yesterday they said that serial number is giving by OEM. I told them no one would put 'System Serial Number' as a serial number but they kept insisting it is by OEM.

I am not sure what is wrong. I am expecting something with numbers and letters like in Vmware VM.

**Comment by mypil** [comment]
@Naxterra - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via **[User Voice](https://office365.uservoice.com/)**. I know the product teams are always looking for user feedback on how to make Windows 10 better. You might find others have made a similar request that you can add to, or you can open a new one.

For technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a **[support ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)**.

I hope this gets you pointed in the right direction. Thank you.

**Comment by Naxterra** [comment]
Sorry, I thought this was for Get-WindowsAutoPilotInfo PS script.
