### ISSUE TITLE
Allow Owners but not members

### ISSUE THREAD

**Issue by andyleese** [MicrosoftDocs/OfficeDocs-O365ITPro#711]
We use to be able to Create a Group &gt; add an owner without being a member.
 
Then the owner could manage members though Groups on Outlook Web/front end and would not receive the group emails. Which was good for delegation of admin without dashboard access.

In this later version, this seems to have been removed, although you can still apply it in the Admin dashboard.

I see in the later version they've split Members & Owners under People &gt; Groups but the Group doesn't appear if you are only a Owner, You have to be a Member or Member & Owner for the group to appear.
I don't know whether this is a bug or by design. 

Either way its very annoying. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96891122-3c0b-1335-35be-556b5681b0ca
* Version Independent ID: 7c567123-f4c0-497c-7d52-21f8bef66040
* Content: [Add or remove members from Office 365 groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/add-or-remove-members-from-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/add-or-remove-members-from-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/add-or-remove-members-from-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@andyleese - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
