### ISSUE TITLE
Typo in last section

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/OfficeDocs-O365ITPro#714]
The section reads "Ask users to OneDrive for Business content to their computer, and then add it back to their new subscription."  It should say "Ask users to Copy/Sync OneDrive for Business content to their computer, and then add it back to their new subscription."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43efaa70-69c2-01b1-e2d7-85f8b1f5e84e
* Version Independent ID: ce7bd43d-818d-d7d3-a66e-14b19e8d85fb
* Content: [Transfer data manually between two Office 365 accounts](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/transfer-data-manually?view=o365-worldwide#transfer-administrative-settings-between-subscriptions)
* Content Source: [Office365-Admin/get-help-with-domains/transfer-data-manually.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/transfer-data-manually.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@WillMartin58  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@WillMartin58  Thank you for your feedback. We have fixed the typo via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/723

**Comment by mypil** [comment]
@WillMartin58 - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by WillMartin58** [comment]
Have added the text I suggested, but now it says “Ask users to Copy/SyncOneDrive for Business content to their computer<https://support.office.com/article/59b1de2b-519e-4d3a-8f45-51647cf291cd.aspx>, and then add it back to their new subscription.”  Notice the lack of a space between the new text and OneDrive for Business.  Not as crucial, obviously, just a nuisance.

**Comment by mypil** [comment]
@WillMartin58 - I believe the content has been updated to add the changes that you requested for. We value your contribution towards the improvement of our docs.

Please feel free to open a new issue if there is a specific area in the docs that we can make better. Thank you!
