### ISSUE TITLE
Missing line feed

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/OfficeDocs-O365ITPro#715]
In the Add SRV records section, for the first record, it says:
In the New Resource Record dialog box, make sure that the fields are set to precisely the following values: 
Service: _sip
Protocol: _tls
Priority: 100
Weight: 1
Port: 443Target (Hostname): sipdir.online.lync.com

Note the last line I copied - it should be broken into the following two lines:
Port: 443
Target (Hostname): sipdir.online.lync.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0937468-6fd2-c83a-ed60-81129a4b766a
* Version Independent ID: 010a32f0-45a3-81da-1a6c-864996a86597
* Content: [Create DNS records for Office 365 using Windows-based DNS](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-using-windows-based-dns?view=o365-worldwide#add-srv-records)
* Content Source: [Office365-Admin/dns/create-dns-records-using-windows-based-dns.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-using-windows-based-dns.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@WillMartin58 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@WillMartin58 Thank you for your feedback. We have corrected the changes via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/724

**Comment by mypil** [comment]
@WillMartin58  - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
