### ISSUE TITLE
"THE admin" center

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-O365ITPro#716]
You say: go to The Admin center. Please specify exactly which admin center you refer to (Azure, O365, other?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27249e0c-e601-b849-8404-ce0bb8155fce
* Version Independent ID: a308f156-998b-8ea9-5668-7a59e549cd10
* Content: [Gather the information you need to create Office 365 DNS records](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide)
* Content Source: [Office365-Admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/information-for-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@blouwagie - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@blouwagie  Thank you for your feedback. It should be the MIcrosoft 365 admin center. We have raised a PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/725 to correct the changes in the document.

**Comment by mypil** [comment]
@blouwagie - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
