### ISSUE TITLE
lack of correct documentation for the missing features in the delete user facility

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/OfficeDocs-O365ITPro#717]
I am appalled @adefowler that you have closed my previous feedback on this issue with out updating the documentation or replying to the feedback I gave through the give feedback link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c772841-0d77-98e6-3e0e-af6f5c9d06a1
* Version Independent ID: 9e61ed55-3037-c7f2-4149-ca72ba789c9d
* Content: [What's new in the Microsoft 365 admin center?](https://docs.microsoft.com/en-us/office365/admin/whats-new-in-preview?view=o365-worldwide)
* Content Source: [Office365-Admin/whats-new-in-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/whats-new-in-preview.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@technonath - Thank you for the follow up. This is related to issue #668. 

Let me send this feedback over to @adefowler so she can respond accordingly.

**Comment by adefowler** [comment]
I'm sorry @technonath, I should've responded more clearly. That's not the purpose of this document. This document's purpose is to quickly let you know what is new - What it is and how to find the new feature in the UI. This document is an historic record and we don't go back and update previous months. Especially at the time of your comment, we were still in "Preview". 

And you're actually asking for feature requests in your comment:

"What I wanted to know is do you plan to re-instate the features available in the old interface, if so when and if not why not? That was the information I was seeking."

In fact, I asked you to please provide product feedback as the product group will get back to you very quickly with the information you are seeking. Did you not have success doing that? If not, let me know which day you provided feature feedback in-product and I will find it and make sure it gets answered ASAP.

**Comment by technonath** [comment]
I did follow the feedback route as you suggested and I did not receive a reply. i left my feedback on the 13th of August.

As for "And you're actually asking for feature requests in your comment:" - let me get this right, what you are saying is that we now have to raise a feature request to get the same functionality that the previous portal had before?  
Surely it should have all the functionality of the old portal and then improve on that? 

Perhaps you should focus on existing functionality first before worrying about a dark mode that only works on one page!

**Comment by adefowler** [comment]
@technonath I found your Feedback comment and replied to you via email. I'm sorry no one responded to you. I'm looking into how that happened. Any how, you should get a reply very soon. If you don't just email me back and let me know. I will make it happen.

**Comment by mypil** [comment]
@technonath - From our understanding, the issue has been answered by adefowler. If you feel it hasn't been addressed, please re-open this issue.

Thank you for engaging with the community here for the docs.
