### ISSUE TITLE
International Domains

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/OfficeDocs-O365ITPro#718]
Can you have a domain from a different country registered to a US (or other) tenant? 

Example: A customer has a US tenant but own a .com.ve domain from Venezuela.  Can they register this domain with the US tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc99803-4432-cd7c-4747-0953276298d9
* Version Independent ID: 1d7554f1-8b1c-dd3a-18e6-1106ad2b3bcb
* Content: [Domains FAQ](https://docs.microsoft.com/en-us/office365/admin/setup/domains-faq?redirectSourcePath=%252farticle%252fDomains-FAQ-1272bad0-4bd4-4796-8005-67d6fb3afc5a&view=o365-worldwide)
* Content Source: [Office365-Admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@AndySanchezVM - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by AndySanchezVM** [comment]
@mypil - I submitted an advisory ticket with Microsoft with our Partner Benefits and received confirmation that you can add any domain to your Office 365 account as long as you validate ownership through TXT and MX records.  You can keep  this closed. Thank you!
