### ISSUE TITLE
Existing groups

### ISSUE THREAD

**Issue by Dutchman1993** [MicrosoftDocs/OfficeDocs-O365ITPro#720]
What happens to existing groups when you enable this policy and the groups already have expired? Will they instantly be soft-deleted? 

For example: I created a group on 1 January 2017 and I have an expiration policy set for 365 days. I activate this policy today. What happens? Will they be instantly soft-deleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4773fc-df89-4d7c-6819-9ed94c66e1a3
* Version Independent ID: 9a0ce458-fd6b-5f12-0b6e-98f9b38ad13c
* Content: [Office 365 Group Expiration Policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/office-365-groups-expiration-policy?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/office-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/office-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@Dutchman1993 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Dutchman1993** [comment]
Seems there is more information in this link: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-lifecycle

"When you first set up expiration, any groups that are older than the expiration interval are set to 30 days until expiration unless the owner renews it. The first renewal notification email is sent out within a day."

**Comment by mypil** [comment]
@Dutchman1993 - We're glad to know that you found the information you were looking for. 

Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.
