### ISSUE TITLE
Please fix the app on iOS

### ISSUE THREAD

**Issue by scottyjn** [MicrosoftDocs/OfficeDocs-O365ITPro#721]
The Microsoft 365 Admin app on iOS has not worked in 2-3 months.  Please fix...or remove the app from the store 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 676bca67-7468-3eae-878e-5b56260a9abf
* Version Independent ID: 47ab73fd-14f6-f5cc-2983-44979c2fc8ef
* Content: [About the Microsoft 365 Admin mobile app](https://docs.microsoft.com/en-ca/office365/admin/admin-overview/admin-mobile-app?redirectSourcePath=%252farticle%252fe16f6421-2a1a-4142-bf9d-9846600a060a&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/admin-overview/admin-mobile-app.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/admin-overview/admin-mobile-app.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@scottyjn - Thank you for submitting feedback.

As indicated in the doc, if you're having trouble using the Admin mobile app on iOS or Android, please send an email at **feedback365@microsoft.com**. Alternatively, you can also open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP.

**Comment by chrimorgNG** [comment]
That email address is kicking back a delivery failure notice. It’s saying “the group only accepts messages from people in its organization or on its allowed senders list.”

Please update the email or update the group settings so we can reach out to it

**Comment by adefowler** [comment]
@chrimorgNG - Can you try again? I've checked the settings on the distribution list and it allows external senders and the feedback dev says that they've gotten 2 delivered feedbacks this morning. 

Thank you! 

> That email address is kicking back a delivery failure notice. It’s saying “the group only accepts messages from people in its organization or on its allowed senders list.”
> 
> Please update the email or update the group settings so we can reach out to it

**Comment by adefowler** [comment]
Hi, @chrimorgNG - We figured out the issue. Within that distribution list is a nested distribution list that didn't have external senders enabled. So, we were getting your email, but the nested DL was sending the NDR. Sorry about that. We've fixed the issue.
