### ISSUE TITLE
Prevent users from creating Microsoft Teams

### ISSUE THREAD

**Issue by tmarinoIN2L** [MicrosoftDocs/OfficeDocs-O365ITPro#726]
All I want to do is prevent users from creating their own Microsoft Teams. It shouldn't be this difficult to do. I mean, I'm a global admin. I can disable end users from creating SharePoint sites. Why can't I do this in Teams? Is it really a licensing issue? Do I need a different o365 license to do this?

**Comment by tmarinoIN2L** [comment]
Everything I read points to this article: https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

I execute the Powershell script and I only get so far... I called support and they told me I need an elevated license to do this. Doesn't this seem silly?

**Comment by tmarinoIN2L** [comment]
Any insight would be very appreciated. Thanks!

**Comment by mypil** [comment]
@tmarinoIN2L - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by tmarinoIN2L** [comment]
Thank you!

**Comment by mypil** [comment]
@tmarinoIN2L - I believe the content has been updated to add the changes that you requested for. We value your contribution towards the improvement of our docs. 

Please feel free to open a new issue if there is a specific area in the docs that we can make better. Thank you!

**Comment by mypil** [comment]
Reopening issue since it was prematurely closed.

**Comment by msbemba** [comment]
@tmarinoIN2L Thank you for your feedback. It is by design that you need an Azure AD premium License to be able to manage who creates Groups.

Regards
Sri

**Comment by mypil** [comment]
@tmarinoIN2L  - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

We appreciate your contribution to make the docs better!
