### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by moticohen** [MicrosoftDocs/OfficeDocs-O365ITPro#727]
Is this true for all versions of Office 365 or just Business version? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a3bd9d-0022-b742-08c8-8717ae31be8c
* Version Independent ID: 802bca8e-ebff-2a9c-86d9-884ec909469e
* Content: [Change your email address to use your custom domain](https://docs.microsoft.com/en-us/office365/admin/email/change-email-address?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/change-email-address.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/change-email-address.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@moticohen  Thank you for the question. This is applicable for all versions of Office 365 except for the Home/personal version. If you are using Home/personal version you can follow the below link
https://support.office.com/en-us/article/get-a-personalized-email-address-in-office-365-75416a58-b225-4c02-8c07-8979403b427b


Hope this Helps!

Thanks
Sri

**Comment by mypil** [comment]
@moticohen - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
