### ISSUE TITLE
Need info/clarifiction on deprecation of Power BI Content Packs

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-O365ITPro#728]
Microsoft has since a year announced the deprecation of Power BI **Content Packs** being replaced with **Apps**. What does this mean for Microsoft 365 Usage Analytics? Will it be completely removed or do we need to update the documentation to reflect how to configure it differently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@JonesMikael - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue?

Thank you.

**Comment by Sirkkuw** [comment]
@mypil I sent a question to the dev.

**Comment by Sirkkuw** [comment]
OK - I will update the docs as soon as the new apps are ready. I am not entirely sure on the timeline, but the product team has already contacted me, and I will be working with them on this shortly.
