### ISSUE TITLE
Multiple Groups Possible?

### ISSUE THREAD

**Issue by ocico** [MicrosoftDocs/OfficeDocs-O365ITPro#729]
can I also create more groups and run this script for each group?
https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

**Comment by mypil** [comment]
@ocico - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@ocico Thank you for the question. Only one security group in your organization can be used to control who is able to create Groups.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@ocico - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in [User Voice](https://office365.uservoice.com) 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

We appreciate your contribution to make the docs better!

**Comment by mypil** [comment]
@ocico - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
