### ISSUE TITLE
Trying to view PowerBI Pro licenses

### ISSUE THREAD

**Issue by ChrisNeedsHelp** [MicrosoftDocs/OfficeDocs-O365ITPro#730]
The user data tables behind the Microsoft 365 Usage Analytics PowerBI report don't seem to track what specific users have a PowerBI Pro license assigned.  I can use the TenantOfficeLicenses table to see the total number of PowerBI Pro licenses assigned, but I can't join this to the UserState table (or UserActivity table) to see the names of the users.  The only licenses that seem to be tracked there are Exchange Online, OneDrive for Business, SharePoint Online, Yammer,  Skype For Business, and Teams.  Am I missing something?  If not, when will PowerBI (and other apps like Dynamics, Project, and Visio) be added to the UserState table?  This issue is making app and user administration very difficult. 
 Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f00316bc-99c9-35d7-6f92-ca3b3cfab1f1
* Version Independent ID: 2a9e9e14-43b7-5c18-4f6b-2e3cf56fde5e
* Content: [Microsoft 365 usage analytics data model](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics-data-model?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics-data-model.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics-data-model.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@ChrisNeedsHelp - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@ChrisNeedsHelp - I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
