### ISSUE TITLE
Example PS to check current app and owner

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/OfficeDocs-O365ITPro#731]
Here a quick hack PS to check apps and owner

```powershell
Get-AzureADApplication | Foreach-Object{

    $AppObjectId = $_ 
    $AppOwner = Get-AzureADApplicationOwner -ObjectId $AppObjectId.ObjectId

    New-Object -TypeName PSObject -Property @{
        AppDisplayName = $AppObjectId.DisplayName
        AppObjectId = $AppObjectId.ObjectId
		AppAppId = $AppObjectId.AppId
		AppReplyUrls = $AppObjectId.ReplyUrls
        OwUPN = $AppOwner.UserPrincipalName
        OwType = $AppOwner.UserType
    }
} | select AppDisplayName,AppObjectId,AppAppId,@{ n='AppReplyUrls'; e={ $_.AppReplyUrls -join ' ' } },@{ n='OwUPN'; e={ $_.OwUPN -join ' ' } } | Export-Csv -Path .\AppsO365.csv -NoTypeInformation
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279bb5c8-222e-5ee9-dcd7-8c06bd4d3a3e
* Version Independent ID: 4b1d6664-91b3-8bd6-f26e-d46005891294
* Content: [Turning Integrated Apps on or off](https://docs.microsoft.com/en-us/office365/admin/misc/integrated-apps?view=o365-worldwide)
* Content Source: [Office365-Admin/misc/integrated-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/integrated-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@TiloGit - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc? 

We would really appreciate if you are able to help by providing more details as to what should be edited and/or included.

**Comment by TiloGit** [comment]
suggest to add this script to check before use the toggle.
Should give you current app and the current app owner.

**Comment by mypil** [comment]
@TiloGit - Thank you for your suggestion.

I will get this issue over to the O365ITPro writing team for their consideration.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@kwekuako - FYI. Please share your insights on this.

Thank you.

**Comment by mypil** [comment]
@TiloGit - We have forwarded this request to the product team who manages this topic for their consideration. 

Thank you for engaging with the community here and for your contribution to help improve the docs.
