### ISSUE TITLE
Using the REST API to query Microsoft 365 usage data

### ISSUE THREAD

**Issue by StevieBleeds** [MicrosoftDocs/OfficeDocs-O365ITPro#732]
I've been trying (unsuccessfully) to query the data stored in https://reports.office.com/pbi/v1.0/$tenantId/TenantProductUsage directly using the REST API and PowerShell and then storing the output in a raw JSON file.

I'm hitting an issue where it's simply not streaming the data, but instead, giving an output where it simply streams the html from an error page. The error page is noting that cookies are disabled (they aren't).

Is it possible to achieve this outcome or does the API used for generating the Adoption Pack data not support this?

**Comment by mypil** [comment]
@StevieBleeds - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by StevieBleeds** [comment]
Sure, I've been looking at these documents and trying to write a PowerShell script which then dumps the data into a raw JSON file.

https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics-data-model?view=o365-worldwide

https://docs.microsoft.com/en-us/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide

I've tried both registering apps using the Graph API and the Power BI Service API - both give the same outcome.

```
[Net.ServicePointManager]:Smiley FrustratedecurityProtocol = [Net.SecurityProtocolType]::Tls12

# Token credentials
$tenant="<tenant>.onmicrosoft.com" 
$clientID="" 
$clientSecret=''
$token=$null
       
# Create access token
$Token = Invoke-RestMethod -Uri https://login.microsoftonline.com/$tenant/oauth2/token?api-version=1.0 -Method Post -Body @{"grant_type" = "client_credentials"; "resource" = "https://graph.microsoft.com/"; "client_id" = $ClientID; "client_secret" = $ClientSecret}

$Headers = @{
    'authorization'="Bearer $($Token.access_token)"
}

#SPECIFY WHICH ENDPOINT TO QUERY
$uri = 'https://reports.office.com/pbi/v1.0/<tenant>/TenantProductUsage'

#CONNECT TO THE GRAPH API USING REST METHOD
$result = Invoke-WebRequest -Headers $headers -Uri $uri -Method Get

```

**Comment by mypil** [comment]
@StevieBleeds -  Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by brunoslam** [comment]
@StevieBleeds you could get the data from the url?

**Comment by cpunella** [comment]
Hi @StevieBleeds were you able to find the right way? I was looking on it as well .. thanks
