### ISSUE TITLE
number of Groups a user can be member of

### ISSUE THREAD

**Issue by dwienie** [MicrosoftDocs/OfficeDocs-O365ITPro#733]
Is this limit also valid for dynamic groups ?  
And are there plans to increase this limit?
If later security groups are allowed to be member of a Group will the limit of 1000 still be valid ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b2aa17-cc9e-7fe4-f2fc-a5dd24e6936e
* Version Independent ID: 7c63cc46-1d04-27a8-7e71-c1b93642b5ab
* Content: [Overview of Office 365 Groups for administrators](https://docs.microsoft.com/en-us/office365/admin/create-groups/office-365-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@dwienie - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@MikePlumleyMSFT - Can you please share your insights on this issue?

Thank you.

**Comment by MaratMussabekov** [comment]
Dear @dwienie ,
**Is this limit also valid for dynamic groups ?** - yes, it is
**And are there plans to increase this limit? If later security groups are allowed to be member of a Group will the limit of 1000 still be valid ?** - I think that plans like this are out of the scope of the Microsoft Docs portal, so you need to check resources that announce Office 365 updates.
Thank you

**Comment by dwienie** [comment]
Thx for the fast answer.
