### ISSUE TITLE
Password Admin

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/OfficeDocs-O365ITPro#734]
Password Admin is no longer a role.  It was completely renamed to Helpdesk admin.

https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#things-to-consider

https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#helpdesk-administrator-permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#things-to-consider)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@poortom1004 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by adefowler** [comment]
@poortom1004 - Yes, the Password admin role was renamed Helpdesk admin. However, there is a new role being rolled out called the "Password admin" role and that role just allows you to reset passwords. If you aren't seeing the new role yet, stay tuned.

**Comment by mypil** [comment]
@poortom1004 - From our understanding, the issue you raised has been answered by the doc owner- adefowler. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
