### ISSUE TITLE
Cannot restrict the creation of groups using script in Powershell

### ISSUE THREAD

**Issue by bizzcuit2000** [MicrosoftDocs/OfficeDocs-O365ITPro#736]
I am still unable to restrict the creation of groups and have been getting the following error when entering the script in powershell..

I am an admin but its saying i dont have the proper privileges. 

PS C:\WINDOWS> .\GroupCreators.ps1

Account                  Environment TenantId                             TenantDomain     AccountType
-------                  ----------- --------                             ------------     -----------
jonessh@delmar-group.com AzureCloud  260e9b96-afc9-44c0-bc73-12ca22439801 delmar-group.com User
New-AzureADDirectorySetting : Error occurred while executing NewDirectorySetting
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
InnerError:
  RequestId: 8f9ff05a-1a51-4513-9bf5-7260c9822156
  DateTimeStamp: Wed, 18 Sep 2019 16:47:04 GMT
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed
At C:\WINDOWS\GroupCreators.ps1:11 char:5
+     New-AzureADDirectorySetting -DirectorySetting $settingsCopy
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADDirectorySetting], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.NewDirectorySetting

Get-AzureADDirectorySetting : Cannot bind argument to parameter 'Id' because it is null.
At C:\WINDOWS\GroupCreators.ps1:15 char:49
+ $settingsCopy = Get-AzureADDirectorySetting -Id $settingsObjectID
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzureADDirectorySetting], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Open.MSGraphBeta.PowerShell.GetDirectorySetting

Set-AzureADDirectorySetting : Cannot bind argument to parameter 'Id' because it is null.
At C:\WINDOWS\GroupCreators.ps1:23 char:33
+ Set-AzureADDirectorySetting -Id $settingsObjectID -DirectorySetting $ ...
+                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureADDirectorySetting], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Open.MSGraphBeta.PowerShell.SetDirectorySetting

Get-AzureADDirectorySetting : Cannot bind argument to parameter 'Id' because it is null.
At C:\WINDOWS\GroupCreators.ps1:25 char:34
+ (Get-AzureADDirectorySetting -Id $settingsObjectID).Values
+                                  ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzureADDirectorySetting], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Open.MSGraphBeta.PowerShell.GetDirectorySetting

**Comment by mypil** [comment]
@bizzcuit2000 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bizzcuit2000** [comment]
https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

**Comment by bizzcuit2000** [comment]
I was able to get to work!! I had to use a Global Admin ID when prompted by powershell for my credentials.....

However now I have a new problem..... The users who I added to the group creation admin group, are now also not able to create groups....

![image](https://user-images.githubusercontent.com/55505610/65262341-23355680-dad8-11e9-829f-bed23202d645.png)

**Comment by mypil** [comment]
@bizzcuit2000 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by bizzcuit2000** [comment]
I was able to get it to work!! However after i logged out/in again now I am unable to create groups again...
Here is the confirmation i got from Powershell:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> cd..
PS C:\Windows> Import-Module AzureADPreview
PS C:\Windows> Connect-AzureAD

Account                  Environment TenantId                             TenantDomain     AccountType
-------                  ----------- --------                             ------------     -----------
jonessh@delmar-group.com AzureCloud  260e9b96-afc9-44c0-bc73-12ca22439801 delmar-group.com User


PS C:\Windows> Get-AzureADGroup -SearchString "O365_Group_Admins"

ObjectId                             DisplayName       Description
--------                             -----------       -----------
7df05c0f-c0a9-4513-a558-2ccdceaf72b0 O365_Group_Admins Security group that can create O365 Groups


PS C:\Windows>  $Template = Get-AzureADDirectorySettingTemplate | where {$_.DisplayName -eq 'Group.Unified'}
PS C:\Windows> $Setting = $Template.CreateDirectorySetting()
PS C:\Windows> New-AzureADDirectorySetting -DirectorySetting $Setting
New-AzureADDirectorySetting : Error occurred while executing NewDirectorySetting
Code: Request_BadRequest
Message: A conflicting object with one or more of the specified property values is present in the directory.
InnerError:
  RequestId: 5b56a59b-d21a-4a5d-bdc9-5593f9648c22
  DateTimeStamp: Wed, 25 Sep 2019 18:02:59 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ New-AzureADDirectorySetting -DirectorySetting $Setting
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADDirectorySetting], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.New
   DirectorySetting

PS C:\Windows>  $Setting = Get-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where -Property DisplayName -Value "Group.Unified" -EQ).id
PS C:\Windows> $Setting["EnableGroupCreation"] = $False
PS C:\Windows> $Setting["GroupCreationAllowedGroupId"] = (Get-AzureADGroup -SearchString "O365_Group_admins").objectid
PS C:\Windows> Set-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where -Property DisplayName -Value "Group.Unified" -EQ).id -DirectorySetting $Setting
PS C:\Windows>  (Get-AzureADDirectorySetting).Values

Name                          Value
----                          -----
EnableMIPLabels               False
CustomBlockedWordsList
EnableMSStandardBlockedWords  False
ClassificationDescriptions
DefaultClassification
PrefixSuffixNamingRequirement
AllowGuestsToBeGroupOwner     False
AllowGuestsToAccessGroups     True
GuestUsageGuidelinesUrl
GroupCreationAllowedGroupId   7df05c0f-c0a9-4513-a558-2ccdceaf72b0
AllowToAddGuests              True
UsageGuidelinesUrl
ClassificationList
EnableGroupCreation           False


PS C:\Windows>

**Comment by get-itips** [comment]
Hello @bizzcuit2000 I will take a look at the script/article to see if it needs any adjustment. Thanks

**Comment by get-itips** [comment]
Hello @bizzcuit2000 
I could successfully test the published Ps script and it works as the article says, only who is member of the Allowed Group can create, so I don't identify anything to be corrected in the article.

![image](https://user-images.githubusercontent.com/36666927/65974806-fb34e400-e443-11e9-9538-a8d1689c0410.png)

Hope I understand well your scenario.

If still does not work for you, I recommend creating a service ticket directly on your tenant.

Thank you

**Comment by bizzcuit2000** [comment]
Thanks Everyone for their help.... I was able to finally get it working. I had to execute each line in the script individually, hitting enter after every line, as opposed to just launching the script.

**Comment by get-itips** [comment]
@bizzcuit2000  Glad to hear you make it work on your own tenant.
@mypil we can close this now.
Thanks
