### ISSUE TITLE
Refresh Power BI data set  - Microsoft 365 usage report using Azure AD App Registration

### ISSUE THREAD

**Issue by harshdamaniahd** [MicrosoftDocs/OfficeDocs-O365ITPro#737]
I want to refresh my dataset using Azure AD App Registration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e8dbad-cf6b-2523-c58d-9cd8e41bbda5
* Version Independent ID: 290ee9e7-1155-cdd5-cd02-94ef8d355a02
* Content: [Troubleshooting Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics-errors?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics-errors.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@harshdamaniahd - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
