### ISSUE TITLE
Group Admin

### ISSUE THREAD

**Issue by JvdMaat** [MicrosoftDocs/OfficeDocs-O365ITPro#739]
Can the Group Admin permissions be improved?
Our Helpdesk has been given Helpdesk, Exchange and User admin, but is seemingly unable to change user group permissions.
We don't necessarily want to give them SharePoint or Teams permissions to manage group membership.
Additionally, even once we added Teams Admin, they can edit membership from the group level, but when editing a user, it gives them the warning:
You can only remove members from groups you have access to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@JvdMaat - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@JvdMaat - Are you requesting for a new feature in the permissions?

**Comment by mypil** [comment]
@JvdMaat - We would like to follow up. Can you please respond to the query of joinimran?

Thank you.

**Comment by mypil** [comment]
@JvdMaat - We value any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you!
