### ISSUE TITLE
right nav pain

### ISSUE THREAD

**Issue by Eric-ITaaS** [MicrosoftDocs/OfficeDocs-O365ITPro#740]
Where is this exactly?
In the right navigation pane, select Setup.
I have no right navigation pane.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@Eric-ITaaS - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Borkason** [comment]
There is a left navigation pane and there is a **Setup** link. However, there is no **Turn on multi-factor authentication (MFA)** card.

![image](https://user-images.githubusercontent.com/2971735/65497888-43d82480-debb-11e9-9f83-cbd388e58954.png)

**Comment by mypil** [comment]
@Eric-ITaaS - I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Borkason** [comment]
Let's say -- hypothetically -- the customer doesn't want to add any more time on this matter after he resolved this with a ticket. Will the docs just stay wrong until another customer decides to correct the documentation that should be corrected by Microsoft in the first place?

**Comment by Eric-ITaaS** [comment]
If I understand Borkason's sentiment I agree. I don't have time to open up a ticket. I figured out how to accomplish the task on my own, I just wanted to point out the error in documentation. I feel like I did my part, I won't be opening up a ticket, seems like you (mypil) would/could/should do that.

**Comment by mypil** [comment]
@Eric-ITaaS @Borkason  - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via **[User Voice](https://office365.uservoice.com/)**. I know the product teams are always looking for user feedback on how to make Office 365 better. You might find others have made a similar request that you can add to, or you can open a new one.

For technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a **[support ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)**.

I hope this gets you pointed in the right direction. If you do find that it is a documentation error though, feel free to comment back and we'll gladly look into fixing it.

Thank you.

**Comment by Borkason** [comment]
Please ask the product owner to review and fix the documentation and do not rely on the customer to correct documentation.

**Comment by mypil** [comment]
@Borkason - We greatly encourage collaboration from the readers and get constructive criticism, containing suggestions of what would improve the documentation. Let me just loop in the doc owner to get her insights on how we can incorporate your feedback.

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue.

Thank you.

cc: @kenwith

**Comment by Sirkkuw** [comment]
@Borkason  and @mypil What you see on the Setup page depends on your subscription, and if MFA is turned on for your tenant. Please first enable tenant for MFA if you are not seeing this option (turnign  it on steps are in the doc). Note also that the admin center is being worked on to improve it, and changes are rolled out in waves. In the latest I see this: 
![image](https://user-images.githubusercontent.com/31521796/65784647-6199c980-e107-11e9-8412-2b951a592c22.png)

**Comment by Borkason** [comment]
@Sirkkuw That doesn't explain where the "right nav pane" is.

Where in the admin center did you take this screenshot?

**Comment by webstaff** [comment]
Is this going to be updated then or are you waiting for some kind soul to write this for you?
Then keep it current for you?

I have a nicely written article about it, maybe we can discuss how much your going to pay me for access to a current and correct article as its cost our business a lot of time to get a working how to 2FA / MFA including all the hoops, loops and bugs that we are likely / expecting to see when we enable MFA..

Better still if someone at MS could implement some QA / testing before they roll out these products and related documentation then maybe we could all stop having to do MS's job for them?

For a start maybe the article should state that as there is no testing done at MS, so this document is likely to now be out of date for current info please raise a ticket and speak to support as the internal documentation / memo contains far more useful info than any internet published documents contain.

For example Modern Authentication inc 2FA in outlook 2016 and 2013 works but there are that many work arounds that support advise an app password in preference to MA which in my mind defeats the purpose of MFA / 2FA in relation to increased security.

**Comment by Sirkkuw** [comment]
@Borkason the page is the Setup page in the Microsoft admin center.
@webstaff  The admin center is rolling out changes and you will likely see the ability to turn on MFA on the Active users page.

**Comment by jadesolis** [comment]
Does this mean the new Admin Center now requires Conditional Access Policies just to enable MFA?

**Comment by mypil** [comment]
@Sirkkuw - Can you please assist with this addtional query from @jadesolis?

Thank you.

**Comment by Sirkkuw** [comment]
@jadesolis the MFA currently provided uses Azure CA - it will be changing, however, in the UI you can see this: Multi-factor authentication is changing in early 2020. New default security settings in ‎Azure Active Directory‎ will replace baseline policies as the place to manage multi-factor authentication. Go to Message center to learn about these new default security settings

**Comment by jadesolis** [comment]
@Sirkkuw do we have a Message center Message ID I can reference about Multi-factor authentication changing in early 2020, or the New default security settings in ‎Azure Active Directory‎ will replace baseline policies? 
The 'new' Microsoft 365 admin center which uses Azure CA would now require us to use Azure AD Premium to access the CA Policies. Shouldn't this new requirement (hidden cost) be noted? In contrast, the 'old' Microsoft 365 admin center which doesn't use CA allows MFA use for free.

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your inputs on this additional query?

Thank you.

**Comment by Sirkkuw** [comment]
It is an additional cost depending on your subscription. With Microsoft 365 Business, for example, you continue to get CA.

**Comment by mypil** [comment]
@Eric-ITaaS @Borkason @webstaff @jadesolis - Please refer to the answers provided in the coment thread by the doc owner-Sirkkuw regarding this topic and please see this comment for additional context - https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/744#issuecomment-540719181. We hope this helps to address your issues.

We appreciate your efforts to clarify the docs. Thank you for your contribution to make the docs better!
