### ISSUE TITLE
No Graph endpoints available

### ISSUE THREAD

**Issue by ivanfioravanti** [MicrosoftDocs/OfficeDocs-O365ITPro#741]
For more information, see Working with Office 365 usage reports in Microsoft Graph, but when you click there you don't find any references. This API is still using Username/password for login, instead of Graph  API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f00316bc-99c9-35d7-6f92-ca3b3cfab1f1
* Version Independent ID: 2a9e9e14-43b7-5c18-4f6b-2e3cf56fde5e
* Content: [Microsoft 365 usage analytics data model](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics-data-model?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-adoption-content-pack-data-model-08c5307c-4a6b-4761-8410-a6c96725760f&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics-data-model.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics-data-model.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@ivanfioravanti - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@ivanfioravanti As far as i understand, the API is still in preview, meaning you should not use it in Production and is not "fully functional" yet.


"Is it possible to integrate the data from the content pack into existing solutions?

The data in the content pack can be retrieved through the Office 365 APIs **(in preview**). When they ship to production they will be merged within the Microsoft Graph reporting APIs."

From: https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide

**Comment by mypil** [comment]
@ivanfioravanti  - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
