### ISSUE TITLE
Missing words?

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/OfficeDocs-O365ITPro#742]
The sentence "The data model that powers the content pack includes user attributes that from Active Directory, enabling the ability to pivot in certain reports." seems be lacking a few words? Or maybe simply the word "that" should be deleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@baardhermansen - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@baardhermansen  - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
