### ISSUE TITLE
Please include PowerShell options

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/OfficeDocs-O365ITPro#743]
Please include the PowerShell equivalent for each of these GUI steps to help with automating these.  For instance for moving users to a different subscription, I would like to see the official MS recommended approach for this since.

I have seen some people recommend changing a subscription by removing the subscription, waiting for 5 minutes and then adding the new subscription, and I have seen others recommend immediately adding the new subscription after the old subscription is removed.  If there is a single command that can remove the old ones and add the news ones in the same transaction that would be helpful too.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8703e584-d768-1d04-643c-069b50d69b79
* Version Independent ID: 13c9c0da-4551-6ff3-1cee-e489c8fed0c3
* Content: [Assign licenses to users](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/assign-licenses-to-users?view=o365-worldwide#move-users-to-a-different-subscription)
* Content Source: [Office365-Admin/subscriptions-and-billing/assign-licenses-to-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/assign-licenses-to-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@aakash-shah  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by cmcatee-MSFT** [comment]
@aakash-shah The section [What you need to know about assigning licenses to users](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/assign-licenses-to-users?view=o365-worldwide#what-you-need-to-know-about-assigning-licenses-to-users) contains a link to the PowerShell documentation for assigning licenses. Does that help?

**Comment by aakash-shah** [comment]
> @aakash-shah The section [What you need to know about assigning licenses to users](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/assign-licenses-to-users?view=o365-worldwide#what-you-need-to-know-about-assigning-licenses-to-users) contains a link to the PowerShell documentation for assigning licenses. Does that help?

Hello @cmcatee-MSFT!  Unfortunately this page does not state how to "Move users to a different subscription" - I am looking to do this in the same step/transaction and would like to see how MS recommends doing what is listed in the GUI process at https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/assign-licenses-to-users?view=o365-worldwide#move-users-to-a-different-subscription to do this same thing via PowerShell.

Thanks!

**Comment by cmcatee-MSFT** [comment]
@aakash-shah Thanks for the clarification. I'll look into this and let you know what I find.

**Comment by cmcatee-MSFT** [comment]
@aakash-shah The information you're looking for has been added to the article [here](https://docs.microsoft.com/en-us/office365/enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell#move-a-user-to-a-different-subscription-license-plan-with-the-azure-active-directory-powershell-for-graph-module). Please let me know if this answers your question. Thanks!

**Comment by aakash-shah** [comment]
Hello @cmcatee-MSFT!  Thanks for that information.  In your example, you have separate lines/commands that first perform the addition of the new license, and then in a separate step, perform the removal of the old license.  However in some cases, you cannot simply add a new license to the existing license since the new license may conflict with the old one.  

In the GUI, for a single user, I am able to de-select the old license AND select the new license in the same step/transaction and then commit those changes.  In the GUI, for multiple users, MS documents the GUI steps at [Replace existing product license assignments](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/assign-licenses-to-users?view=o365-worldwide#move-users-to-a-different-subscription) section.  However, it does not list how to perform this replacement step via PowerShell (the example you updated recently is first adding and then removing as 2 separate steps, and not doing a replace operation in a single step as shown in the GUI).

Based on your script, it appears that Set-AzureADUserLicense accepts as a parameter AssignedLicenses, and AssignedLicenses accepts BOTH the attributes AddLicenses and RemoveLicenses.  So if this is the case, can we populate BOTH AddLicenses with the new license and RemoveLicenses with the old license and then run "Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $licenses" to perform _both_ the addition and removal in the same step to replicate the functionality seen in the GUI at [Replace existing product license assignments](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/assign-licenses-to-users?view=o365-worldwide#move-users-to-a-different-subscription)?  If so, is this supported and the recommended route?  Or is there some better way to perform this replace operaiton?

Thanks!

**Comment by JoeDavies-MSFT** [comment]
@aakash-shah The new PowerShell section first removes the user from a license and then adds them to a different license. This moves the user from one subscription (license) to another. And yes, it is possible to do this in a single command, but I cannot spend the time required to rework this to duplicate the GUI functionality. Thanks.

**Comment by aakash-shah** [comment]
To clarify, does this mean that MS supports removing a license where a user has an Exchange mailbox, and then adding it back as a next step?  I've read about people reporting problems with this since this causes the mailbox to not have an Exchange license for a moment which can cause disruption.  This is the reason I am trying to find out how to do this in a single operation, or to get guidance as to how to avoid user disruption when a license is changed.

Thanks.

**Comment by cmcatee-MSFT** [comment]
@JoeDavies-MSFT Can you respond to this?
