### ISSUE TITLE
Step missing "Go to the classic settings page"

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/OfficeDocs-O365ITPro#748]
After selecting "Settings" in the left nav, you must then select "Go to the classic settings page" which opens a new page with the required settings.

Same issue as reported on another doc page, https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/749.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e22c980-262e-292b-0f52-72fccae038f9
* Version Independent ID: cbaf3f8e-4dff-4cea-10fa-5718a6eb7813
* Content: [SharePoint enterprise social experience - Yammer and Newsfeed](https://docs.microsoft.com/en-us/yammer/integrate-yammer-with-other-apps/yammer-and-newsfeed)
* Content Source: [yammer/integrate-yammer-with-other-apps/yammer-and-newsfeed.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/integrate-yammer-with-other-apps/yammer-and-newsfeed.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@softwarecraft - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@softwarecraft - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
