### ISSUE TITLE
Step missing "Go to the classic settings page"

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/OfficeDocs-O365ITPro#749]
In section https://docs.microsoft.com/en-us/yammer/manage-yammer-users/office-365-sign-in#make-yammer-the-default-enterprise-social-network-in-sharepoint...

After selecting "Settings" in the left nav, you must then select "Go to the classic settings page" which opens a new page with the required settings.

Same issue as reported on another doc page, https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/748.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c754d867-1763-5664-3386-b4e726bc0608
* Version Independent ID: 42bb998e-9f46-7d48-675c-8aa449419e80
* Content: [Office 365 sign-in for Yammer](https://docs.microsoft.com/en-us/yammer/manage-yammer-users/office-365-sign-in)
* Content Source: [yammer/manage-yammer-users/office-365-sign-in.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/manage-yammer-users/office-365-sign-in.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@softwarecraft - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@softwarecraft - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
