### ISSUE TITLE
MSOnline

### ISSUE THREAD

**Issue by ShyangTan** [MicrosoftDocs/OfficeDocs-O365ITPro#75]
Thanks for the great article!  However, Azure Active Directory Connection page doesn't have the link to download AdministrationConfig-V1.1.166.0-GA.msi.  

It seems like it has been replaced by Install-Module MSOnline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8299b0d8-25e4-af45-a9f8-724f61ed4f4a
* Version Independent ID: 4ab5dc30-7f11-758b-9b58-e5254e25774e
* Content: [Set an individual user's password to never expire](https://docs.microsoft.com/en-us/office365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@ShyangTan Thank you for this feedback

I'll get this information about the link over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
Ok will do.

[image: Picture]

**Comment by lindspea** [comment]
@ShyangTan, thank you for pointing this out.  I will investigate further.

**Comment by lindspea** [comment]
@AndreaBarr  @mypil This issue can be closed thank you.
