### ISSUE TITLE
Please review first chapter

### ISSUE THREAD

**Issue by mwe-microsoft** [MicrosoftDocs/OfficeDocs-O365ITPro#750]
It is stated that a yammer enterprise license is needed for an external user who belongs to an Office 365 Tenant. 
The OSTs say on page 27 Yammer
For Office 365 Services that include Yammer, External Users invited to Yammer via external network functionality do not need User SLs
Further it is stated that users that do not not (two nots) belong to an Office 365 tenant need a school and work account. Can you please explain what a school and work account is that is not an Office 365 account? 
The only way I know is an Azure oder Intune Account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b3a2463-a8f4-3ba7-0524-37fc75fa783d
* Version Independent ID: 14374d2a-eb47-d2e5-fbc3-be6ee56e14b5
* Content: [Add external messaging participants to your Yammer conversations](https://docs.microsoft.com/en-us/yammer/work-with-external-users/add-external-participants#feedback)
* Content Source: [yammer/work-with-external-users/add-external-participants.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/work-with-external-users/add-external-participants.md)
* Service: **yammer**
* GitHub Login: @IrenePasternack
* Microsoft Alias: **v-irpast**

**Comment by mypil** [comment]
@mwe-microsoft  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TeresaFG-writer - Can you please share your insights on this issue?

Thank you.

**Comment by TeresaFG-writer** [comment]
Thank you for forwarding. I made some changes and they are pending.

**Comment by mypil** [comment]
@mwe-microsoft - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/3aa303300867dfd9a2a44a6f9a607641df7aa4a9. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
