### ISSUE TITLE
'Set Up 2-step verification' page for users is actually the same as the app password instructions, with a different title

### ISSUE THREAD

**Issue by lefrinj** [MicrosoftDocs/OfficeDocs-O365ITPro#755]
The 2 links above promise to be very useful for sending to users, but it turns out that the first page is actually app password instructions again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@lefrinj  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by lefrinj** [comment]
Thanks. On further examination the pages are not the same, but it is still confusing that there is so much on app passwords when that’s not the focus of the page and another page exists for that purpose. Thanks for all you’re doing to make it easier for us to find the info we need 😊

Dev


________________________________

**Comment by mypil** [comment]
@lefrinj - We appreciate your efforts to clarify the docs. Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. 

Thank you.

**Comment by mypil** [comment]
@lefrinj - We value any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to open a new issue if you find any documentation error or if there is a particular area of the docs that we can improve on and we will be glad to help fix it. Thank you.
