### ISSUE TITLE
Video is inaccurate

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/OfficeDocs-O365ITPro#756]
The video on this page https://www.microsoft.com/en-us/videoplayer/embed/7d4c20ee-f96f-4336-b79d-d955507583d1?autoplay=false still advises users to use Office 365 Adoption Content Pack which was a preview. Users should now be advised to use Microsoft 365 Usage Analytics App which is the GA version by going to Apps -> Get Apps -> Microsoft 365 Usage Analytics

**Comment by mypil** [comment]
@noobcoder7412 - May we know which Microsoft document link you used that contains this video?

Please share it with us so we can investigate further. Thank you.

**Comment by noobcoder7412** [comment]
Here it is

https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide

Thanks
Haider

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mypil** [comment]
@noobcoder7412  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@haider392 - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/52affb455b2b438309a24825fed48f4068d88344. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
