### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by benrwb** [MicrosoftDocs/OfficeDocs-O365ITPro#757]
The documentation suggests that this is a three-page wizard but on my version of the Office 365 admin center, and in the video, all of these settings are on a single page.

For example step 3 "On the Choose a group type page, choose Distribution, and then choose Next."
There is no such thing as the "Choose a group type page", and there is no "Next" button.
The group type is actually chosen from a drop-down list called "Type".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c8e89a-d001-eb11-d1e4-e2525561307a
* Version Independent ID: 42c5f231-7a58-4e92-2a43-eb35bcf8c410
* Content: [Create distribution groups in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/setup/create-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/create-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/create-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@benrwb  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@benrwb -  From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/827e2b291df1e968aa989193aec36c93ffa52754 but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
