### ISSUE TITLE
What about disabling users from creating groups?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-O365ITPro#759]
I have a comment and a question.  First, Stream is another application that allows users to create groups, so you can add that to the list at the top of the article. 

As for my question, what if you don't want any users to be able to create groups, except for the global and other admins listed?  How do you turn off group creation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@Canis-Lupis  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by veronicageek** [comment]
@Canis-Lupis 
About your question on restricting group creation, hope this article should help:
https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

**Comment by Canis-Lupis** [comment]
This just links back to the article I'm posting the question on.  I'm not looking to create a group to allow Group creation, I'm looking to disable group creation for all (except the admins listed in the article).

Is disabling Group creation part of the PowerShell script listed?  While I am familiar with PowerShell, the script appears over my head.  What is the command that does that without adding the "Group Creators?"
________________________________

**Comment by veronicageek** [comment]
This is what the script does. Prevents users from creating groups **except** the members (i.e.: your admins) of the Security Group you define.
You can copy/paste the PowerShell script & change the $GroupName value with your own.

**Comment by Canis-Lupis** [comment]
Thanks, I'll give it a try but I don't want to have anything for $GroupName as we don't won't any regular users to have the ability to  create groups.  I will try to modify the script without that and give it a try.

________________________________

**Comment by veronicageek** [comment]
@Canis-Lupis if you create a Security Group and put yourself only as a member, running the script with this Security Group name in $GroupName will make you the **only person** able to create groups.

**Comment by Canis-Lupis** [comment]
Well, I'm a global admin, so I should be able to create groups anyway, correct?

I did try running the script with a dummy (empty)  security group and it didn't work.  I did install AzureADPreview first, per instructions.  But running the script gives errors,
The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet, function, script file, or operable program.
The term 'Get-AzureADDirectorySettingTemplate' is not recognized as the name of a cmdlet, function, script file, or operable program.
The term 'New-AzureADDirectorySetting' is not recognized as the name of a cmdlet, function, script file, or operable program.

Etc... you get the idea.
________________________________

**Comment by veronicageek** [comment]
:triumph: Argh I hear ya, those AzureAD modules are very frustrating, and despite people submitting pull requests, seems nobody is taking care of them :thumbsdown:

**Comment by Canis-Lupis** [comment]
Well, the good news is that I found my problem:  I ran Uninstall-Module AzureADPreview but hadn't run Uninstall-Module AzureAD.  Once I did that, I reinstalled the AzureADPreview and the script ran successfully.

I guess I owe everyone an apology for opening this issue as the ability to disable Group creation was in the article all along--I just hadn't run the PowerShell script originally because I thought it was only for creating the group to allow members to create Groups.
________________________________

**Comment by veronicageek** [comment]
@Canis-Lupis - Glad you got it resolved 👍

**Comment by mypil** [comment]
@Canis-Lupis - From our understanding, the issue has been answered by <veronicageek. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.
