### ISSUE TITLE
How to implement this?

### ISSUE THREAD

**Issue by Haribo112** [MicrosoftDocs/OfficeDocs-O365ITPro#760]
Great that you give us all these considerations, but how do I actually apply these settings in Office 365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c354faae-625c-2b36-2a77-4ed2962feff3
* Version Independent ID: 1dd96166-8bae-fc8c-491f-99ca45f5b058
* Content: [Password policy recommendations for Office 365](https://docs.microsoft.com/en-us/office365/admin/misc/password-policy-recommendations?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@Haribo112 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
