### ISSUE TITLE
Number of concurrently devices: 5 or 15?

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-O365ITPro#764]
Does this page correctly reflect current Office 365 limit on device install. As I understand it, in the year the terms were (dis)"improved" to max any 5 devices, as stated on this current sales page:
https://products.office.com/en-ca/compare-all-microsoft-office-products?&activetab=tab%3aprimaryr2 
and specifically for Business Users MS has automated moving license count around, moving from least recently used device to this new device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f28ec79-1d61-21ae-a11e-b429d32a3346
* Version Independent ID: 2f068dd8-b9c9-7266-159a-09b90501c100
* Content: [Understand subscriptions and licenses in Office 365 for business](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/subscriptions-and-licenses?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/subscriptions-and-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/subscriptions-and-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@mypil Already investigating this issue.

**Comment by cmcatee-MSFT** [comment]
@Ronsss The article is correct as written. If you look at the products page, the part about 5 PCs or Macs applies to desktop version, while the very next section applies to web and mobile versions, and says you can install on up to 5 phones and 5 tablets. So it's both. Hope that helps.
