### ISSUE TITLE
There's one process missing here

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-O365ITPro#769]
Pretty through article, but the one part about removing a former employee that's missing here is how to remove the "belongs to" setting in desktop applications (perhaps mobile applications as well but I haven't checked that).  We are noticing that when one employee leaves and a new employee uses the same workstation, even though the new employee can log on with her account just fine, the "belongs to" for the desktop apps still shows the previous employee's name.  

So far, this hasn't caused any issues with new employees being able to use the apps, but we're worried about possible unforeseen repercussions.  One area we have noticed a problem is with reports.  Since 'belongs to' is not showing for the new employee, activation reports don't list any for the new employee.  What this means is that the new employee gets an 'extra' activation of 6 instead of the standard 5.  And since former employees' accounts have been deleted, no activations even show up for them.

In case anyone is wondering, yes, I have contacted support about this and so far their answers have been unacceptable in an enterprise environment.  They have suggested:
A) Log in to the portal as the former employee and deactivate her installs.
B) Reinstall Office on the workstation after an employee leaves.
C) Run a vbs script on the workstation after an employee leaves.

Option A is just all kinds of silly that I won't even comment on.  And B&C are unacceptable in an enterprise environment as they involve IT personal having to run around to individual workstations every time a new employee is hired.  We're a fairly good-sized company and have a few departments with high turn-over rates and I can't ask IT to spend all their time doing this.  Is this how Microsoft does it with their tens of thousands of employees?

In short, what's missing is how to change/remove the 'belongs to' for desktop apps of former employees from the O365 Admin Center, a policy, or with a PowerShell command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6024c6e-1373-58de-ca8b-819a11693968
* Version Independent ID: 5d02bdc8-6e20-8b9b-942e-cca0e312cc5e
* Content: [Remove a former employee from Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@Canis-Lupis -  - Thank you for engaging with the community here for the docs.

Currently, there's no PowerShell command for what you are requesting for but I know the product teams are always looking for user feedback and feature requests on how to make Office 365/Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[User Voice](https://office365.uservoice.com)** 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Canis-Lupis** [comment]
Thanks, Joyce, I will do that.
________________________________
