### ISSUE TITLE
In German translation the SRV record ist called _sip instead of _sip._tls

### ISSUE THREAD

**Issue by arichter83** [MicrosoftDocs/OfficeDocs-O365ITPro#77]
In German translation the SRV record ist called _sip instead of _sip._tls

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 58d30a72-4274-982c-4737-7c87a35febb9
* Version Independent ID: dea907ab-1da1-dcbd-8db7-5120c2c41a8f
* Content: [Erstellen von DNS-Einträgen für Office 365 bei DNSMadeEasy](https://docs.microsoft.com/de-de/office365/admin/dns/create-dns-records-at-dnsmadeeasy?redirectSourcePath=%252fArticle%252fe158b079-b054-4b7e-8e01-e55169ce18d7&view=o365-worldwide)
* Content Source: [Office365-Admin/dns/create-dns-records-at-dnsmadeeasy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-dnsmadeeasy.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndreaBarr** [comment]
@arichter83 Thank you for pointing this out. 

I'll get this tralsation name issue over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@samanthaw

**Comment by mypil** [comment]
@samanthaw @MollyMalone

**Comment by MollyMalone** [comment]
@arichter83 thank you for reporting it.  I passed on to the localizers to fix it.

**Comment by arichter83** [comment]
Yes, thank you for fixing!
