### ISSUE TITLE
Should resource mailboxes have sign in blocked as well

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/OfficeDocs-O365ITPro#770]
I note under 'Block sign-in for the shared mailbox account' that it is recommended to block sign-in for the account that's associated with a shared mailbox to prevent hacking.

I notice that 'Resource' mailboxes (Rooms and Equipment) also have an account associated with them - are these also vulnerable and so should we block sign in for these too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a258b08-9f84-d11d-a5c5-8c758dfd5d18
* Version Independent ID: 1b9620e1-c056-cb1d-72cd-623703365e79
* Content: [Create a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/create-a-shared-mailbox?view=o365-worldwide#block-sign-in-for-the-shared-mailbox-account)
* Content Source: [Office365-Admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@ChrisAtMAF - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello, @ChrisAtMAF Thank you for your query and this applies to all shared mailboxes including rooms and equipment. The best practice would be to block those accounts to sign in. 

Thanks.

**Comment by ChrisAtMAF** [comment]
Thank you - please can this best practice be added to the Room and Equipment Mailboxes documentation so people are aware?
https://docs.microsoft.com/en-gb/exchange/recipients-in-exchange-online/manage-room-mailboxes?redirectedfrom=MSDN

https://docs.microsoft.com/en-gb/exchange/recipients-in-exchange-online/manage-equipment-mailboxes?redirectedfrom=MSDN

https://docs.microsoft.com/en-gb/office365/admin/manage/room-and-equipment-mailboxes?view=o365-worldwide#set-up-room-and-equipment-mailboxes

**Comment by mypil** [comment]
@ChrisAtMAF - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/9774aec47f895f0595ad0de83c06f563bdd69ab7. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
