### ISSUE TITLE
Microsoft 365 Usage Analytics needs a Power BI Pro License

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/OfficeDocs-O365ITPro#771]
In the documentation, it is mentioned that this app is free and user only need to sign up for free Power BI Service. This is incorrect. To install Microsoft 365 Usage Analytics app, a Power BI Pro (paid license) is required.

Link where this is mentioned: https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#is-this-content-pack-going-to-be-available-through-purchase-or-will-it-be-free

**Comment by mypil** [comment]
@haider392 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @haider392 , Can you please share your whole scenario where you are facing this issue. The usage  analytics is free for Office365 usage analysis. Please see https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide for more details. This https://docs.microsoft.com/en-us/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide can help you enable Prower BI for usage analytics for free. 

Thanks.

**Comment by mypil** [comment]
@haider392 - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
