### ISSUE TITLE
Yammer with code snippets?

### ISSUE THREAD

**Issue by timskovjacobsen** [MicrosoftDocs/OfficeDocs-O365ITPro#773]
My company will be using Yammer from Jan 2020. We really need our technical networks on the site to support code snippets in posts. Any chance this will be implemented in the future? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107f1ed0-b257-639b-112f-1c8f26095297
* Version Independent ID: 572dc2d1-773e-46ef-c5ca-61dd46e0c4af
* Content: [Rich text formatting for Yammer messages](https://docs.microsoft.com/en-us/yammer/get-started-with-yammer/rich-text-formatting#feedback)
* Content Source: [yammer/get-started-with-yammer/rich-text-formatting.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/yammer/get-started-with-yammer/rich-text-formatting.md)
* Service: **yammer**
* GitHub Login: @TeresaFG-writer
* Microsoft Alias: **v-teflor**

**Comment by mypil** [comment]
@timskovjacobsen - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Yammer better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[User Voice](https://yammer.uservoice.com/)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by timskovjacobsen** [comment]
@mypil - Thanks for the reply. I have made a post about it in UserVoice and upvoted some related suggestions.

**Comment by zivsha** [comment]
@timskovjacobsen have you ended up using Yammer for technical Q&A ? if you did can you say how? if not, what did you use?

**Comment by timskovjacobsen** [comment]
> @timskovjacobsen have you ended up using Yammer for technical Q&A ? if you did can you say how? if not, what did you use?

In the company I worked for previously they use it for technical Q&A. I'm not using Yammer anymore myself.
