### ISSUE TITLE
"Invalid nameserver" error message when editing nameservers.

### ISSUE THREAD

**Issue by Outright-Graham** [MicrosoftDocs/OfficeDocs-O365ITPro#775]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e339f0-e8f8-a30f-1b27-af58235f1b0d
* Version Independent ID: 6928fa1f-7f67-71ee-c839-9688b96da754
* Content: [Change nameservers to set up Office 365 with Bluehost](https://docs.microsoft.com/en-us/office365/admin/dns/change-nameservers-at-bluehost?view=o365-worldwide#if-there-are-nameservers-already-listed)
* Content Source: [Office365-Admin/dns/change-nameservers-at-bluehost.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/change-nameservers-at-bluehost.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@Outright-Graham - Can you please share what specific issue you have with this doc? Or are you having some technical issues which requires technical support?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by Outright-Graham** [comment]
Hello Joyce!
I'm very sorry to relay I was unable to figure out the problem. However my
coworker was able to submit name (alternative) server records (in Bluehost)
successfully.

Long story: we are trying to direct a domain on Bluehost to Microsoft. I
attempted twice and was unsuccessful. I'm sure I typed it in properly and
even double checked my work. My colleague, working off site, replicated my
effort and was successful. I have no idea what to differentiator was.

Thank you for your fast response. You can consider this closed on my end.

**Comment by mypil** [comment]
@Outright-Graham - We're glad to know that your issue has been resolved. We will close this issue now.

Please feel free to open a new issue if there is a specific area in the docs that we can make better. 

Thank you!
