### ISSUE TITLE
Read Actions definition

### ISSUE THREAD

**Issue by redamaleki** [MicrosoftDocs/OfficeDocs-O365ITPro#778]
Is there a page that explains what a read action is? Is it just a message changing from unread to read?  Not necessarily someone reading a message that has already been read?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0edd827-38a3-12d1-7836-a2eacc97ed1c
* Version Independent ID: b0765177-6d47-49f4-47a5-2456107652c3
* Content: [Office 365 Reports in the admin center - Email activity](https://docs.microsoft.com/en-us/office365/admin/activity-reports/email-activity?redirectSourcePath=%252fen-US%252farticle%252f1cbe2c00-ca65-4fb9-9663-1bbfa58ebe44&view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/email-activity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/email-activity.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@redamaleki  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
hello @redamaleki ,
read action counts when user clicks on email message or opens it. It is not the change of status from "unread" to "read", it is the fact that the message was displayed.
**Is there a page that explains what a read action is** - unfortunately, I didn't find article with the definition of this action.
Thank you

**Comment by mypil** [comment]
@redamaleki - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
