### ISSUE TITLE
Kaizala Management Portal

### ISSUE THREAD

**Issue by Sepiks-Perfected** [MicrosoftDocs/OfficeDocs-O365ITPro#779]
NOTE: This pertains to the EmployeeHelpdesk-SolutionsPackage by Kaizala
I keep running into this issue even though I've followed all instructions for the file...

![Annotation 2019-10-16 150629](https://user-images.githubusercontent.com/56653094/66950857-34b24580-f027-11e9-830b-be0448e2e5ae.png)

**Comment by mypil** [comment]
@Sepiks-Perfected - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@Sepiks-Perfected - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
