### ISSUE TITLE
Giving folder access to groups in Sharepoint online

### ISSUE THREAD

**Issue by hooperman** [MicrosoftDocs/OfficeDocs-O365ITPro#78]
I really don't believe that you could make this topic more confusing if you went out and out to do so :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 812da0c1-b351-62bb-bf61-a30ff65b8987
* Version Independent ID: cdf8e0e7-a61f-651b-eb92-eb8bd5b16a9f
* Content: [Create, edit, or delete a security group in the Office 365 admin center](https://docs.microsoft.com/en-us/office365/admin/email/create-edit-or-delete-a-security-group?view=o365-worldwide)
* Content Source: [Office365-Admin/email/create-edit-or-delete-a-security-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/create-edit-or-delete-a-security-group.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@hooperman Thank you for this feedback

Is there a specific part that you need clarification on?

**Comment by mypil** [comment]
Hi @hooperman, we would like to follow up and get more details from you. Can you please share what specific issue you have with this article?

**Comment by mypil** [comment]
@hooperman - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make the SharePoint better. They keep a close tab on User Voice https://sharepoint.uservoice.com and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by hooperman** [comment]
Neither of the links in this email worked

Kind Regards​

[cid:image010.png@01D4BD6B.69D564D0]

Paul Hooper

Director

,

Route22 Limited


[cid:image011.png@01D4BD6B.69D564D0]

+441883370692<tel:+441883370692>

 |

[cid:image012.png@01D4BD6B.69D564D0]

+447903938616<tel:+447903938616>



[cid:image013.png@01D4BD6B.69D564D0]

paul.hooper@route22.co.uk<mailto:paul.hooper@route22.co.uk>

 |

[cid:image014.png@01D4BD6B.69D564D0]

www.route22.co.uk<http://www.route22.co.uk/>


[cid:image015.png@01D4BD6B.69D564D0]

76 Campbell Road

,

Caterham on the Hill

,

CR3 5JN



[Twitter]<https://twitter.com/>


[Facebook]<https://www.facebook.com/>


[LinkedIn]<https://www.linkedin.com/in/hooperman/>




Please join our mailing list
<http://eepurl.com/duq1kb>


All prices exclude VAT unless it is specifically stated otherwise.
Please see our website: www.route22.co.uk<http://www.route22.co.uk/> for terms and conditions of service.

Route22 Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.



Route22 Ltd is a company registered in England and Wales under number 3986440.
Registered office: 76 Campbell Road, Caterham, Surrey, CR3 5JN
