### ISSUE TITLE
Global reader - shortcomings

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-O365ITPro#780]
Couple of things that I've noticed is that Get-InboxRules fails.  Example:  
Get-InboxRule -Mailbox user@company.com
The operation on mailbox "User" failed because it's out of the current user's read scope. You may need elevated permissions. 'User' isn't within your current write scopes. Can't perform save operation.

Also, signing into SharePoint online fails.
Connect-SPOService : Current user is not a tenant admin.
I'm able to connect to Skype Online & Exchange Online PowerShell sessions fine.

It is promising and much needed role, but seems to have a few kinks still.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by mypil** [comment]
@J-Fedor  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@J-Fedor Thank you for your feedback. I was able to repro the issue, I'll check with the team internally and update you shortly on the next steps.

Thanks
Sri

**Comment by msbemba** [comment]
@J-Fedor Thanks for catching and reporting the problem. We have done some investigation, the conclusion is: it’s not a bug of Global Reader, but a by-design behavior of the CMDLet “Get-InboxRule” which is a confusing one requiring to write permission but with a “Get-*” format. See below code snippet for more information:

            // We need to verify the recipient is in write scope of the current user, because we essentially are changing its mailbox;

            if (this.BypassScopeCheck)

            {

                this.VerifyIsWithinScopes(this.TenantGlobalCatalogSession, adUser, true, Strings.ErrorCannotChangeMailboxOutOfReadScope);

            }

Meanwhile, The issue with SPO is a known issue and Our team is working to fix that. Hope this helps!


Thanks
Sri

**Comment by J-Fedor** [comment]
Well, the 'by-design' should still be able to function for all get-* commands since it is read operation.  I created a new role to handle doing the get-inboxrule so it can be manually added to the account as necessary

New-ManagementRole -Name "Read Inbox Rules" -Description "because of shortcomings with globalreader"  -EnabledCmdlets Get-InboxRule -Parent "Mail Recipients"

**Comment by adefowler** [comment]
@J-Fedor I forwarded your comment about the global reader role to the product group and they are investigating. Thank you!
