### ISSUE TITLE
As a USER (not admin), how to update your own recovery info  after I did complete step 5 (filled the form on my first login)?

### ISSUE THREAD

**Issue by ttpro1995** [MicrosoftDocs/OfficeDocs-O365ITPro#781]
[Enter feedback here]
First time I log on, it shown a form for me to give recovery information (including email and phone number). 

Now I want to change recovery information (by myself, without contacting human in IT support) but I can't find a link. How can I update recovery information ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90059adc-9f5f-bc6c-caab-695e7ca1933a
* Version Independent ID: d71bf1c7-ee9d-4c7c-5b65-a8765366b064
* Content: [Let users reset their own passwords in Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/let-users-reset-passwords?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/let-users-reset-passwords.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/let-users-reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by ttpro1995** [comment]
related question on stackexchange https://superuser.com/questions/1493108/how-to-update-recovery-information-of-myself-in-self-service-password-reset-tool

**Comment by mypil** [comment]
@ttpro1995 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by ttpro1995** [comment]
hi, but you have not directly answer my question. The issue is not resolved yet. 

I am USER, not ADMIN.
