### ISSUE TITLE
Link for Removing a reseller relationship with partner not working

### ISSUE THREAD

**Issue by dalmendinger** [MicrosoftDocs/OfficeDocs-O365ITPro#782]
The link provided: https://go.microsoft.com/fwlink/p/?linkid=870519 does not work. This is found at the bottom for Remove a reseller relationship with partner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57d391d-6fb4-8449-e816-6ae040781416
* Version Independent ID: bbfd14f9-8b89-5391-1963-ccfb19a3f4b6
* Content: [Add, change, or delete a subscription advisor partner](https://docs.microsoft.com/en-us/office365/admin/misc/add-partner?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/add-partner.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/add-partner.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@dalmendinger - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/a29bc6a12ba94dca91291a92e3094e13e8e064bd. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
