### ISSUE TITLE
Powershell capability

### ISSUE THREAD

**Issue by Kav7** [MicrosoftDocs/OfficeDocs-O365ITPro#784]
Can any of this be achieved or queried via powershell? We want to be able audit our clients tenant to check who they have as partner of records, or who they have allocated as delegated admins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57d391d-6fb4-8449-e816-6ae040781416
* Version Independent ID: bbfd14f9-8b89-5391-1963-ccfb19a3f4b6
* Content: [Add, change, or delete a subscription advisor partner](https://docs.microsoft.com/en-us/office365/admin/misc/add-partner?redirectSourcePath=%252farticle%252fAdd-change-or-delete-a-subscription-advisor-partner-f86e8177-936e-491e-9024-44dea2b296ff&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/add-partner.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/add-partner.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@kavehs7  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@Kav7 You could leverage the [Partner Center Powershell module](https://docs.microsoft.com/en-us/powershell/partnercenter/get-started?view=partnercenterps-2.0) 

If you need help with the actual Powershell script in order to get that info, i suggest opening a ticket directly in Partner Center.

**Comment by mypil** [comment]
@Kav7  - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Kav7** [comment]
Thanks, had a look at all the Get* commands from the PartnerCenter module, but none of them provide the information I was requesting. It only tells me about my relationship with the clients, not all the relationships they have created in their tenant (like CSP reseller etc.).

**Comment by VLG17** [comment]
@Kav7 I understand. I'm sorry the PartnerCenter module did not help. To be honest, i don't have any other ideea. It could also be possible that this option is not available because it could lead to data privacy issues.

I would also advise to open a case with Partner Center just to be sure there is no other way.
