### ISSUE TITLE
Is Azure AD Basic EDU still a thing?

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/OfficeDocs-O365ITPro#785]
In this section, there is a mentioning of the Azure AD Basic EDU License: https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy?view=o365-worldwide#licensing-requirements

Where can I find additional Information about Azure AD Basic and how can I enable this within an EDU tenant?

This issue is related to this question: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3252

Hope to get some clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f70ad7b-5ba2-6167-1207-7496d57c6828
* Version Independent ID: 3df3ae33-83d3-e25f-3b41-070620030a08
* Content: [Office 365 Groups naming policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/groups-naming-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/groups-naming-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@andikrueger  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
hello @andikrueger ,
unfortunately Basic versions of Azure AD is not available for new customers (https://github.com/MicrosoftDocs/azure-docs/issues/36471)
It still mentioned in the documentation as existing customers can continue use it (at least for now).
Thank you

**Comment by mypil** [comment]
@andikrueger - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by andikrueger** [comment]
@MikePlumleyMSFT I am workings with an EDU customer at the moment. Is AAD Basic EDU still available?

**Comment by MikePlumleyMSFT** [comment]
@andikrueger I'm not sure. Support should be able to get you some info though.

**Comment by mypil** [comment]
@andikrueger - As recommended by the author, it would be best if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP.

However, if in case you find that it is a documentation error, feel free to comment back here and we'll be glad to help fix it. Thank you!
