### ISSUE TITLE
Using [CountryOrRegion] in eaxmple rather then [Country]

### ISSUE THREAD

**Issue by MohitGargMSFT** [MicrosoftDocs/OfficeDocs-O365ITPro#79]
As per discussion on this document feedback - https://github.com/MicrosoftDocs/azure-docs/issues/18991 please change the example to use Using [CountryOrRegion] in example rather then [Country] else it is causing confusion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f70ad7b-5ba2-6167-1207-7496d57c6828
* Version Independent ID: 3df3ae33-83d3-e25f-3b41-070620030a08
* Content: [Office 365 Groups naming policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/groups-naming-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/groups-naming-policy.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@MohitGargMSFT Thank you for this feedback

I'll get this change of wording request over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dianef77** [comment]
Hi Mohit, I updated the article for this issue.
