### ISSUE TITLE
Clarification of the WARNING text at the end of the document

### ISSUE THREAD

**Issue by jpalo** [MicrosoftDocs/OfficeDocs-O365ITPro#790]
Can you please clarify the WARNING at the end of the article as to why the passwords expire after 90+ days even if you set passwords to never expire: "Passwords set to -PasswordPolicies DisablePasswordExpiration still age based on the pwdLastSet attribute. If you set the user passwords to never expire and then 90+ days go by, the passwords expire."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8299b0d8-25e4-af45-a9f8-724f61ed4f4a
* Version Independent ID: 4ab5dc30-7f11-758b-9b58-e5254e25774e
* Content: [Set an individual user's password to never expire](https://docs.microsoft.com/en-us/office365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@jpalo  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@jpalo Thank you for your feedback. 

1)When the policy goes live(new policy applies), passwords last changed before the number of days set in the policy will automatically expire. For example, if a user had last changed their password 6 months ago and the new policy was set for passwords to never expire, they will need to change the password else it would expire in 6 months.

2) Regarding the second line, if you change the expiration to -PasswordPolicies None, all passwords that have a pwdLastSet older than 90 days require the user to change them the next time they sign in.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@jpalo  - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by rdupplaw** [comment]
This still doesn't make much sense. Why, if I disable password expiration for a user, would their password then expire following the 6 months policy? What is the point of disabling password expiration if the password still expires?
