### ISSUE TITLE
Disabling Automapping

### ISSUE THREAD

**Issue by sn131678** [MicrosoftDocs/OfficeDocs-O365ITPro#791]
How to disable the automatic Automapping feature of shared accounts would be good to share on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a258b08-9f84-d11d-a5c5-8c758dfd5d18
* Version Independent ID: 1b9620e1-c056-cb1d-72cd-623703365e79
* Content: [Create a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/create-a-shared-mailbox?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@sn131678 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@sn131678 Thank you for your feedback. We have added steps to disable Automapping on the document. This can be tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/797

Thanks
Sri

**Comment by mypil** [comment]
@sn131678 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/da41c446a17c6ee7ac5512ebfd815b72b6f0d6fa. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
