### ISSUE TITLE
Export-PlannerUserContent never finishes

### ISSUE THREAD

**Issue by mevaibhav83** [MicrosoftDocs/OfficeDocs-O365ITPro#795]
Issue
Export-PlannerUserContent command never finishes in following 3 condition and its getting stuck.

1. when upn has office 365 license (including planner) and user has never accessed planner so far
2. when upn has office 365 license (including planner) and user has not created any planner
3. when upn has office 365 license (including planner) but user never logged into office 365 yet

Following it looks like and it keep receiving 2-bytes and never finishes which is forcing me to abort execution after some time:

Export-PlannerUserContent -UserAadIdOrPrincipalName user@domain.com -ExportDirectory $path -Authentication $auth -Verbose
VERBOSE: POST https://tasks.office.com/taskApi/UserContentExport/UserContentExport with -1-byte payload
VERBOSE: received 0-byte response of content type 
VERBOSE: GET https://tasks.office.com/taskapi/UserContentExport/UserContentExport/yxxp6vg with 0-byte payload
VERBOSE: received 2-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://tasks.office.com/taskapi/UserContentExport/UserContentExport/yxxp6vg with 0-byte payload
VERBOSE: received 2-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://tasks.office.com/taskapi/UserContentExport/UserContentExport/yxxp6vg with 0-byte payload
VERBOSE: received 2-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://tasks.office.com/taskapi/UserContentExport/UserContentExport/yxxp6vg with 0-byte payload
VERBOSE: received 2-byte response of content type application/json; charset=utf-8

**Comment by mypil** [comment]
@mevaibhav83 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mevaibhav83** [comment]
Sure, this is the link : https://docs.microsoft.com/en-us/office365/planner/export-user-data

**Comment by mypil** [comment]
@mevaibhav83 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
