### ISSUE TITLE
Sub-domains information seems to contradict itself

### ISSUE THREAD

**Issue by jeking3** [MicrosoftDocs/OfficeDocs-O365ITPro#796]
[Enter feedback here]

The section "Can I add custom subdomains or multiple domains to Office 365?" first says that to have sub-domains you "must" use an external DNS provider.

Then it goes on to say that "Typically, you can add up to 900 domains to your Office 365 subscription".  Which one is correct?

Let's say I have foo.com in Office 365.  I wanted to add `eng.foo.com` as a sub-domain and then have some A records for each engineer.  I tried adding `eng.foo.com` as a domain and it complains:

```
You can't add eng.foo.com because the DNS for foo.com is managed by Office 365. 
If you want to add eng.foo.com, you have to make a change so that you manage DNS 
records for foo.com at your registrar or other DNS hosting provider instead.
```

Is this part of the documentation talking about behavior of other DNS providers or of Office 365?  It is confusing:

> Typically, you can add up to 900 domains to your Office 365 subscription.
> 
> For example, you could add the domains contoso.com and contosomarketing.com, and then add the subdomains www.contoso.com, www.partners.contoso.com, www.partners.marketing.contoso.com, and so on.
> 
> When you add a subdomain, it is automatically verified based on the parent domain that is being verified.

That seems to describe what I was trying to do with `eng.foo.com` but it does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc99803-4432-cd7c-4747-0953276298d9
* Version Independent ID: 1d7554f1-8b1c-dd3a-18e6-1106ad2b3bcb
* Content: [Domains FAQ](https://docs.microsoft.com/en-us/office365/admin/setup/domains-faq?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@jeking3 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @jeking3 - Thank you for your query, Please note that if you own DNS then you can add subdomains but if you are letting Microsoft manage your DNS or you bought your domain from Microsoft then you can not add subdomains. This is mentioned in the document. 

![image](https://user-images.githubusercontent.com/47118050/68209133-8cbfe480-fff4-11e9-8dcb-6ffa1f0d709d.png)


Thanks.

**Comment by mypil** [comment]
@jeking3 - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
