### ISSUE TITLE
Can you add a note to say this doesn't work from a tenanted admin

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/OfficeDocs-O365ITPro#798]
Or in other words we don't care about partners!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90059adc-9f5f-bc6c-caab-695e7ca1933a
* Version Independent ID: d71bf1c7-ee9d-4c7c-5b65-a8765366b064
* Content: [Let users reset their own passwords in Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/let-users-reset-passwords?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/let-users-reset-passwords.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/let-users-reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@webstaff - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc? Or are you having some technical issues which requires technical support?

Please assist to provide more details so we can investigate further.

**Comment by mypil** [comment]
@webstaff - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it.  

Thank you!
