### ISSUE TITLE
I think the process here assumes too about much about how companies handle former employees.

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-O365ITPro#799]
I've worked at 4 different companies now that utilize O365 and not one of them removes former employee accounts as depicted here; that is, by resetting the password.  They all do one of two things (hybrid environments):
1) Delete AD account
2) Disable AD account and move it to an OU that doesn't sync to O365
Given this, some of the items listed here just don't work as listed.  For example, the employee's mailbox no longer shows up in Exchange--after all, its been deleted.  So how do you wipe data or disable features from a phone they received email on if you  can't view their mailbox in EAC? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6024c6e-1373-58de-ca8b-819a11693968
* Version Independent ID: 5d02bdc8-6e20-8b9b-942e-cca0e312cc5e
* Content: [Remove a former employee from Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@Canis-Lupis - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Canis-Lupis Thank you for your feedback.  The document talks about Office365 tenancy in the cloud and Not Hybrid deployments.

What you have mentioned is correct w.r.t Hybrid as you cannot make changes on cloud and you will make changes on-premise AD. 

Hope this Helps!

Thanks
Sri

**Comment by mypil** [comment]
@Canis-Lupis - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
