### ISSUE TITLE
Migrating from Exchange: license assigment

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/OfficeDocs-O365ITPro#80]
Better specify clearly that the Office365 user licenses has to be assigned AFTER migration. We are doing license assignment before migration from several users, discovering after months (thanks to support) that migration reset the user license and assign a "30 days grace" license. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0744dc5-5459-dc0e-6afa-48a1e1bd9c99
* Version Independent ID: f57a5812-e95d-b85d-b5f2-2969e7fb4ea2
* Content: [Add users individually or in bulk to Office 365 - Admin Help](https://docs.microsoft.com/en-us/office365/admin/add-users/add-users?redirectSourcePath=%252fit-it%252farticle%252fAggiungere-utenti-singolarmente-o-in-blocco-a-Office-365-Guida-per-l-amministratore-1970f7d6-03b5-442f-b385-5880b9c256ec&view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/add-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/add-users.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@carloreggiani Thank you for this feedback

I will get this information about the licences and migration over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@jamesrhea Could you please investigate this issue?

**Comment by mypil** [comment]
@nenonix - reassigning this issue to you. Thanks.

**Comment by nenonix** [comment]
@carloreggiani Thanks for your feedback, and your patience. I am going to do some research, consult with the team and try to resolve this as speedily as possible.

**Comment by carloreggiani** [comment]
Thank you @nenonix , hope to solve some headhache to other sysadmins with this issue :)

**Comment by nenonix** [comment]
@carloreggiani Could you help me edit the article by giving me some more detail or your suggestions of how we could edit the content to make that clear?  Do you think that adding a note would do the trick?

**Comment by carloreggiani** [comment]
@nenonix I think a box note could be fine. I suggest (sorry for my english grammar): "Office365 user licenses has to be assigned after migration otherwise the migration activity will reset the user license and assign a "30 days grace" license".

**Comment by nenonix** [comment]
@carloreggiani  Thank you for helping improve the content. I hope the note I added makes it clearer.

**Comment by mypil** [comment]
@carloreggiani - From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
