### ISSUE TITLE
Overriding tenant settings

### ISSUE THREAD

**Issue by awdhaan** [MicrosoftDocs/OfficeDocs-O365ITPro#801]
Suggested improvement to this page is to clearify that if tenant Guest Access settings are set to False, individual groups cannot be set to True, where it does work the other way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b191c8b0-5673-efce-de2a-ba219aa82f37
* Version Independent ID: d5f71172-e733-af54-e938-19b738a026b3
* Content: [Manage guest access in Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@awdhaan - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@awdhaan Thank you for your feedback. I have added a note to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/814

Thanks
Sri

**Comment by mypil** [comment]
@awdhaan - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/e336efbfbd424b7cdb7ddef9624315c7572727c1. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
