### ISSUE TITLE
Access OneDrive File Share link not correct

### ISSUE THREAD

**Issue by JohnMoor** [MicrosoftDocs/OfficeDocs-O365ITPro#802]
Under "Access a former user's OneDrive documents" bullet 4 (of both new and old MS365 admin) states:

Select the link to open the file location and download and copy the files to your own OneDrive for Business, or a common location. You can also share the link with another user to download the files.

This last sentence seems incorrect. When clicking the link it only allows the global admin to access the files. When sharing the link with another user it will give access denied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@JohnMoor  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@JohnMoor  Thank you for your feedback. I have created a PR# https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/813  to remove the last sentence.

**Comment by mypil** [comment]
@JohnMoor - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/bca9057114538a18483fbf53e7290c83636aa27e. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
