### ISSUE TITLE
Another requirement

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/OfficeDocs-O365ITPro#803]
It appears not only must the distribution list have an owner but that owner must have a mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10dbb56e-1c52-8fa0-0d3d-bab6d50519d0
* Version Independent ID: ff6585cd-9d68-ed1c-ee5f-1f451457dbef
* Content: [Upgrade distribution lists to Office 365 Groups in Outlook](https://docs.microsoft.com/en-us/office365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@mprentice22153 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@mprentice22153 Thank you for the feedback. You are correct about the statement, however, to be a distribution list owner one must have a mailbox. So I think the addition is not required to this doc.

Hope this helps!

Thanks
Sri

**Comment by mprentice22153** [comment]
I was able to setup a distribution list with an owner that did not have a mailbox.  It doesn't hurt to add the the statement to ensure the detail is known.

**Comment by msbemba** [comment]
@mprentice22153 I hear you! I have added a note to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/815 if the author thinks it is required this will be merged to live.

Thanks
Sri

**Comment by mypil** [comment]
@mprentice22153 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/98b012c33b8c9fe494ea212e899e93c6dce64141. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
