### ISSUE TITLE
No option to create custom A record

### ISSUE THREAD

**Issue by Pinakin2404** [MicrosoftDocs/OfficeDocs-O365ITPro#804]
my DNS are pointing to microsoft and I used to be able to add A records. I don't get this option any more. 

Please help.

**Comment by mypil** [comment]
@Pinakin2404 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
