### ISSUE TITLE
There is no "Start setup" on domains page

### ISSUE THREAD

**Issue by b27lu** [MicrosoftDocs/OfficeDocs-O365ITPro#806]
Step 1 point 2 "On the Domains page, select your domain, then select Start setup. You'll go back to the domains setup wizard to see the specific value you need to add." I don't have "Start setup" on domains page. I only have "New custom record" and clicking it won't give me any pre-filled text value, it's just empty. I have have the default domain (XXX.onmicrosoft.com) in the domains page 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27249e0c-e601-b849-8404-ce0bb8155fce
* Version Independent ID: a308f156-998b-8ea9-5668-7a59e549cd10
* Content: [Gather the information you need to create Office 365 DNS records](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/information-for-dns-records?redirectSourcePath=%252fen-us%252farticle%252fgather-the-information-you-need-to-create-office-365-dns-records-77f90d4a-dc7f-4f09-8972-c1b03ea85a67&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/information-for-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@b27lu - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
