### ISSUE TITLE
How to change alternate Email 

### ISSUE THREAD

**Issue by manjunathp008** [MicrosoftDocs/OfficeDocs-O365ITPro#807]
Helped. Thumbs up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8f1206-71c4-76df-6843-e39a23f2350b
* Version Independent ID: 55bb4d3c-fdc4-4363-1202-89aa6e628577
* Content: [Update your admin phone number and email address in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/update-phone-number-and-email-address?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/update-phone-number-and-email-address.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/update-phone-number-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@manjunathp008 - Can you please share what specific issue you have with this doc? Or are you giving commendation that this doc was able to help you?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by mypil** [comment]
@manjunathp008 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you
