### ISSUE TITLE
Incomplete Information

### ISSUE THREAD

**Issue by obviousbadger** [MicrosoftDocs/OfficeDocs-O365ITPro#809]
Office 365 Business Premium is required, this should be mentioned to stop users purchasing an incompatable product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a3bd9d-0022-b742-08c8-8717ae31be8c
* Version Independent ID: 802bca8e-ebff-2a9c-86d9-884ec909469e
* Content: [Change your email address to use your custom domain](https://docs.microsoft.com/en-us/office365/admin/email/change-email-address?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/change-email-address.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/change-email-address.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@obviousbadger  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@obviousbadger Thank you for your feedback. To add a Custom domain all you need is a tenant with any  office365 license. There is no requirement to have an office365 Business premium License. It works with even the basic exchange online plan 1.

Hope this Helps!

Thanks
Sri

**Comment by obviousbadger** [comment]
You need any office 365 licence that includes *exchange*. Others come with
email and you can add your own domain but you can not use that domain for
email unless you have exchange. Which means choosing the premium license.

Coming from Gapps I just assumed that since I have email and I am able to
add a personal domain that I would be able to link the two things.

So I feel the documentation should specifically say that you require a
licence with exchange. That way I wouldn't have wasted my time and cancel
my office365 account.

**Comment by msbemba** [comment]
@obviousbadger  I have added a note to explain this in the doc and the same can be tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/836

Thank you for the feedback.

Thanks
Sri

**Comment by mypil** [comment]
@obviousbadger - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/6718e736bdd1d63f409107f49cdc64d3de25784e.


Thank you for your contribution to make the docs better! Much appreciated!
