### ISSUE TITLE
Phone Number is not working

### ISSUE THREAD

**Issue by jerikkofrancisco** [MicrosoftDocs/OfficeDocs-O365ITPro#81]
Already tried to use India (Both Primary and Alternate)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2b385a-9cb4-9110-94bb-7d63f7e591f0
* Version Independent ID: 07d6eed9-0f79-5c7e-6c7b-0391d0190c57
* Content: [Support information for India](https://docs.microsoft.com/en-us/office365/admin/support/india?view=o365-worldwide)
* Content Source: [Office365-Admin/support/india.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/india.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
I'm working on verifying that the #s are correct & working. Will update when I know more.

**Comment by tumud** [comment]
Tried connection to those two phone numbers over one hour in the mentioned time... but in vain

**Comment by mypil** [comment]
@jerikkofrancisco & @tumud  - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by mypil** [comment]
@jerikkofrancisco & @tumud - We have confirmed that the phone numbers stated in the MS Article are correct. However, there is a technical issue in the backend that is being resolved. Rest assured that this is being worked on.

Thank you for submitting this feedback. We appreciate your contribution to make the docs better.
