### ISSUE TITLE
In the new admin, there's no Turn on multi-factor authentication choice under Setup.

### ISSUE THREAD

**Issue by bc-109** [MicrosoftDocs/OfficeDocs-O365ITPro#811]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@bc-109  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Ghawblin** [comment]
Same issue. Instructions says "setup -> Turn on multi factor authentication" but even though I enabled modern authentication and am in the new admin center, it isn't there.

Typical microsoft.

**Comment by mypil** [comment]
@bc-109 @Ghawblin @chi-ltd - Thank you for submitting feedback.

Please refer to the response by the doc owner- @Sirkkuw regarding this topic found in this issue comment- https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/740#issuecomment-540708378 and this additional update- https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/744#issuecomment-540719181. We hope this helps to address your concerns.

Thank you for your contribution to make the docs better!
