### ISSUE TITLE
PowerShell

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-O365ITPro#817]
Hello,
Is it possible to query this data using PowerShell, please? 
Really interested in count of "Files shared externally"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb3459c-e032-f893-63e3-c3c94748e62c
* Version Independent ID: 52deeb2c-fe25-a211-1a5e-a3fd565dd81b
* Content: [Office 365 Reports in the admin center - SharePoint activity](https://docs.microsoft.com/en-us/office365/admin/activity-reports/sharepoint-activity?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/sharepoint-activity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/sharepoint-activity.md)
* Service: **o365-administration**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by mypil** [comment]
@lightupdifire  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. While this document pertains to Office 365 Reports in the admin center - SharePoint activity we will not be able to add steps to get reports or collection information via Powershell. However, You can use the Office 365 Auditing Report Tool  from https://gallery.technet.microsoft.com/office/Office-365-Auditing-Tool-01747cd4 which can provide over 300 reports.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@lightupdifire - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
