### ISSUE TITLE
Adjustment for Unlocking Teams

### ISSUE THREAD

**Issue by bmcdade00** [MicrosoftDocs/OfficeDocs-O365ITPro#818]
When unlocking Teams, it says to run the script and set $GroupName = ""

This will not remove the group ObjectId from the GroupCreationAllowedGroupID field.  On a GCC High tenant, it caused issues with being not able to create teams after it was unlocked.

To fix, change the "if ($GroupName)..." section to this:

if($GroupName)
{
	$settingsCopy["GroupCreationAllowedGroupId"] = (Get-AzureADGroup -SearchString $GroupName).objectid
} else {
        $settingsCopy["GroupCreationAllowedGroupId"] = $GroupName
}

That will clear the field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@bmcdade00  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by bmcdade00** [comment]
Thank you.  I appreciate it.

Thank you,

Brian McDade
Sr. Cloud Engineer
855-21-CLOUD ext. 719<tel:8552125683,719> (O) | 724-561-6531<tel:7245616531> (M)
BMcDade@AppliedCloud.io<mailto:BMcDade@AppliedCloud.io> | LinkedIn<https://www.linkedin.com/in/bmcdade318>

[Horizontal 150x40]<https://www.appliedcloud.io/>  [LinkedIn-Email Signature] <https://www.linkedin.com/company/applied-cloud-systems>   [Twitter - Email Signature] <https://twitter.com/AppliedCloudSys>   [Facebook] <https://www.facebook.com/appliedcloudsystems/>
Your Trusted Advisor for the Microsoft Cloud.   Azure  |  Office365  |  Dynamics365  |  PowerBI

**Comment by msbemba** [comment]
@bmcdade00 Thank you for your feedback. We have made few changes to the doc reflecting your suggestion. This can be tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/831

Thanks
Sri

**Comment by mypil** [comment]
@bmcdade00 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/f6ae52fcaf66097a87818c59302f02c96c5a4fdf. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
