### ISSUE TITLE
Remove account from iOS admin app if I can't sign in?

### ISSUE THREAD

**Issue by solmssen** [MicrosoftDocs/OfficeDocs-O365ITPro#819]
Sign out is only available from menu if I can sign in - I want to remove an account I no longer have access to.

**Comment by mypil** [comment]
@solmssen - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by solmssen** [comment]
I came here from https://docs.microsoft.com/en-us/office365/admin/admin-overview/admin-mobile-app?view=o365-worldwide. My concern is that I'm no longer able to sign into an admin account that was added to the app, I want to remove it, but there doesn't seem to be a way to edit accounts or sign out of a specific account without signing in first.

**Comment by mypil** [comment]
@solmssen - Thank you for submitting feedback.

As indicated in the doc, please try the suggested troubleshooting steps below found in the doc or send an email to feedback365@microsoft.com to report any issues in using Admin mobile app. 

![image](https://user-images.githubusercontent.com/47188252/68577316-c9835400-04aa-11ea-9fa9-9928f880eacf.png)
![image](https://user-images.githubusercontent.com/47188252/68577747-a73e0600-04ab-11ea-91f9-cfab35cf5759.png)

Alternatively, you may also follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We hope this will help to resolve your issue.
