### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/OfficeDocs-O365ITPro#82]
The new admin center is cool, but I feel its missing the most important thing of it all. Dark mode theme ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a046b07e-0b18-facf-8990-ad37d673e8bb
* Version Independent ID: f28529dc-4ae4-a52d-5ae9-11bc787660af
* Content: [About Microsoft 365 admin center preview](https://docs.microsoft.com/en-us/office365/admin/microsoft-365-admin-center-preview?view=o365-worldwide)
* Content Source: [Office365-Admin/microsoft-365-admin-center-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/microsoft-365-admin-center-preview.md)
* Service: **o365-administration**
* GitHub Login: @anfowler
* Microsoft Alias: **anfowler**

**Comment by AndreaBarr** [comment]
@xNiklasJern Thank you for this suggestion.

I know the product teams are always looking for user feedback and how to make the o365 admin center better. They keep a close tab on User Voice [https://office365.uservoice.com/](https://office365.uservoice.com/) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!
