### ISSUE TITLE
This number doesn't exists.

### ISSUE THREAD

**Issue by omairkhan** [MicrosoftDocs/OfficeDocs-O365ITPro#820]
This number is not working. No support for commercial products at all. I tried various ways to handle my issue but nothing is working. I am totally exhausted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 857771a7-6be1-5630-2aa9-539a12390781
* Version Independent ID: 3cb9162f-d140-75c9-1071-d147bf97d19a
* Content: [Support information for Pakistan](https://docs.microsoft.com/en-us/office365/admin/support/pakistan?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/support/pakistan.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/pakistan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@omairkhan - Thank you for submitting feedback and sorry to hear that you're having issues.

I will get this telephony issue over to the O365ITPro writing team for investigation.

In the meantime, if you require technical support, you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

**Comment by mypil** [comment]
@cmcatee-MSFT - Can you please assist to get the telephony team to investigate on this issue?


Thank you.

cc: @kenwith

**Comment by cmcatee-MSFT** [comment]
@omairkhan Would you please send me the following information directly in email (do not post this information here):

1. Country and Number being called:
2. Country and City of person calling to test: 
3. Number tester is calling from:
4. Landline or Mobile Phone?
5. What Carrier does this number belong to?  
6. Date and time of test call:
7. Exact details of errors or experience when calling:

My email address is in my profile. Thanks.

**Comment by mrqasimali** [comment]
This number is not working, very poor telephonic support for commercial products at all. I tried various ways to handle my issue but nothing is working. I am also trying to +92(21)35839934 and used this email id mspkinfo@microsoft.com but their are no response at all.

**Comment by cmcatee-MSFT** [comment]
@mrqasimali Please send me the following information directly in email (do not post this information here):

1. Country and Number being called:
2. Country and City of person calling to test:
3. Number tester is calling from:
4. Landline or Mobile Phone?
5. What Carrier does this number belong to?
6. Date and time of test call:
7. Exact details of errors or experience when calling:

My email address is in my profile. Thanks.

**Comment by mypil** [comment]
@omairkhan @mrqasimali - We will close this issue now. If your phone issue is not resolved, please send an email directly to **cmcatee@microsoft.com** with the required details that he is asking for.

 Thank you.
