### ISSUE TITLE
Powershell options

### ISSUE THREAD

**Issue by Retne** [MicrosoftDocs/OfficeDocs-O365ITPro#821]
I was sent here via a different MS page (for Exchange Online I think, although that's in the breadcrumb not in an "applies to" section so not as obvious as it might be).
On the page I was looking at Powershell commands and that's what I'm after. Please could the appropiate link be placed here or if I can't use PowerShell to gather this information, that be highlighted. Thanks.

(Edit - pages -> page, that -> the, added a few words for clarity)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50963b73-8563-f99a-72f7-bf4037965cde
* Version Independent ID: 5daa29ed-8092-3a79-c011-8bcbe0225b2c
* Content: [Add another email alias for a user](https://docs.microsoft.com/en-gb/office365/admin/email/add-another-email-alias-for-a-user?redirectSourcePath=%252farticle%252f0b0bd900-68b1-4bf5-808b-5d240a7739f4&view=o365-worldwide)
* Content Source: [Office365-Admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@Retne  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Retne Thank you for your feedback. Are you looking for Powershell cmdlets to add an email alias to the user?

Thanks
Sri

**Comment by Retne** [comment]
Hi msbemba. I was, but have now found what I was after, thank you. I am also not sure if my original comment makes as much sense out of context, so I'll edit it a bit to help there.

**Comment by mypil** [comment]
@Retne - Is your issue already resolved? Or Is there anything in particular within this doc that you suggest to be added or edited? If there is, please assist to provide more details.

Thank you.

**Comment by Retne** [comment]
Hi mypil. I did resolve my issue via, I _think_, another MS Docs page. So personally, I have what I need.

The suggestion I would make is to add a link in the See Also section that links to the documentation that shows users how to do this same thing via a command line, as opposed to the UI. It may not matter - I may the only one to come here via a general Internet search. But if I'm not the only person who came here looking for command line arguments a link to other relevant information would be useful.

I'll have a quick look and post back here if I still have my browsing history and can just send you the link I found useful.

**Comment by Retne** [comment]
Okay, so I've had a quick look and think I used a few sources to find that info I needed, but this page is the key command:
https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps
It doesn't have an example for an alias - perhaps that page itself could be altered with example 7 that covers the command: Set-Mailbox "mainEmailAddress" -EmailAddresses @{add="aliasToAdd@yourDomain.com"}? I've leave this with you though!

(I did like how the page I linked to has Applies To right at the top. This is something all pages should have - I find it very very useful).
Thanks!

**Comment by msbemba** [comment]
@Retne I agree with you. I have added an example to the doc which has this covered. This can be tracked via PR # https://github.com/MicrosoftDocs/office-docs-powershell/pull/4470

Thanks
Sri

**Comment by mypil** [comment]
@Retne - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/office-docs-powershell/commit/8ba01b361a0c49a3db84cbbd6045fc72af3e00bb. 

Thank you for your contribution to make the docs better! Much appreciated!
