### ISSUE TITLE
Does this apply to Office 365 Home?

### ISSUE THREAD

**Issue by ghanjiboy** [MicrosoftDocs/OfficeDocs-O365ITPro#823]
Hi,I have Outlook.com Premium and looking to transition to Office 365 Home. My Domain registration is with Google, will I be able to setup my personalized email address with Google domains as opposed to Godaddy?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab521261-ae0d-9fe5-eff2-14ae0a5e3f68
* Version Independent ID: 59147889-4b01-f27e-599b-970595a7fe85
* Content: [Create DNS records at Google Domains for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-google-domains?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/dns/create-dns-records-at-google-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-google-domains.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@ghanjiboy  - Thank you for submitting feedback.

Please click on the below links with suggestions that may help address your issue:

1) https://office365.uservoice.com/forums/264636-general/suggestions/8987830-office-365-home-personal-email-domain-availabili

2) https://support.office.com/article/what-account-do-i-use-with-office-and-why-do-i-need-one-914e6610-2763-47ac-ab36-602a81068235#bkmk_gmailyahooaccts

If you have additional technical queries or concerns, then it would be best for you to **[contact technical support](https://docs.microsoft.com/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone)** and open a support ticket to get immediate resolution. 

However, if in case you find that it is a documentation error, feel free to comment back here and we'll be glad to help fix it. Thank you!
