### ISSUE TITLE
GroupCreationAllowedGroupId output stays blank after running script

### ISSUE THREAD

**Issue by bsofd** [MicrosoftDocs/OfficeDocs-O365ITPro#824]
GroupCreationAllowedGroupId stays blank after running the script and security group does not allow group creation

I have tried running 
$GroupName = ""
$AllowGroupCreation = "True"

and then running the script with the security group name again, but the GroupCreationAllowedGroupId output remains blank and the specified group is not able to create groups.

I have also tried creating a new security group, running the script with new security group name, but getting the same result

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@bsofd - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
