### ISSUE TITLE
No groups showing up when clicking on the upgrade icon

### ISSUE THREAD

**Issue by boe1** [MicrosoftDocs/OfficeDocs-O365ITPro#825]
All my DG show up in 365 exchange management, not a single group showed up as available for migration/upgrade.  I created a test DL to see if it was anything unique about my others.  There is only one user as a member, owner, and they are on 365 (not on prem), there is no nested dl, there are no special characters, there are no shared mailboxes, there are no sender restrictions, no security groups, nothing dynamic, join memebership and restrictions are not closed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10dbb56e-1c52-8fa0-0d3d-bab6d50519d0
* Version Independent ID: ff6585cd-9d68-ed1c-ee5f-1f451457dbef
* Content: [Upgrade distribution lists to Office 365 Groups in Outlook](https://docs.microsoft.com/en-us/office365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@boe1 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by boe1** [comment]
I opened a case with MS.  Basically it was there best guess is the upgrade icon only works on distribution lists that were created in the cloud to begin with so I'm not sure what it upgrades if the DL is already there.   It is like saying if you buy this house we'll move everything to it free of charge - so you'll move everything to my new house from my old house - no, we'll take all your stuff out of your new house after you move it there and then put it back where it was in the new house.

**Comment by boe1** [comment]
Sorry about the typo - I meant to say THEIR best guess.    Also I should mention the engineer created a test lab environment of a on prem server to 365 and found the same problem.   His guess is they never finished developing the feature.

**Comment by msbemba** [comment]
@boe1 Thank you for the feedback. The upgrade option is only available if the group was created directly in exchange online. The upgrade option lets the user upgrade the group from a DL to an O365 group (Which can be used for teams/streams planner etc).

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@boe1  - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
