### ISSUE TITLE
How do you actually manage add-ins?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-O365ITPro#826]
Did I miss something here or is there no instructions on how to actually manage the add-ins?  I see a section on deploying add-ins, but what if I need to remove an add-in or change who gets the add-in?  I don't see that anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d424b-6f62-e70c-9c2d-ad779ffa6c3b
* Version Independent ID: e4597136-bfe8-4230-da83-f806a1126005
* Content: [Manage deployment of Office 365 add-ins in the admin center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@Canis-Lupis  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Canis-Lupis  Thank you for your feedback. We have added the missing information on the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/833

Thanks
Sri

**Comment by Canis-Lupis** [comment]
Thanks, guys.

**Comment by mypil** [comment]
@Canis-Lupis - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/cb9128a52d87781ef8e6f6ec70faa71284b3170d. 


Thank you for your contribution to make the docs better! Much appreciated!
