### ISSUE TITLE
Admin role clarification

### ISSUE THREAD

**Issue by MidSpeck** [MicrosoftDocs/OfficeDocs-O365ITPro#827]
This page states, "You must have admin permissions to do this."  Can you clarify the minimum permissions role needed for adding an alias?  Surely they don't have to be a global admin.  Do they have to be an Exchange admin?  Is it possible to add an alias with less?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50963b73-8563-f99a-72f7-bf4037965cde
* Version Independent ID: 5daa29ed-8092-3a79-c011-8bcbe0225b2c
* Content: [Add another email alias for a user](https://docs.microsoft.com/en-us/office365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@MidSpeck  - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@MidSpeck  Thank you for your feedback. You are correct, There are more than one role which you could use to add an alias. I have made the change to the doc via PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/832 

Thanks
Sri

**Comment by mypil** [comment]
@MidSpeck  - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/18b2b3432fbf1c65320977256db8ab7f62f6cdec but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
