### ISSUE TITLE
What is "Roadmap" and is "Microsoft Stream" missing

### ISSUE THREAD

**Issue by tomka75** [MicrosoftDocs/OfficeDocs-O365ITPro#828]
Hi,

reading the documentation I saw a service called "Roadmap". Is this correct? And I think Microsoft Stream is missing.

BR
Tomislav

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide&source=docs)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tomka75** [comment]
OK, found that Roadmap is from Project for web. Microsoft Stream is missing.

**Comment by msbemba** [comment]
@tomka75  Thank you for your feedback. I have added Microsoft Stream to this list via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/835

Thanks
Sri

**Comment by mypil** [comment]
@tomka75 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/8f68e309fe91d3e0c10abae253e24ea3471e29a6. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
