### ISSUE TITLE
Powershell compatibility AzureADPreview + GCC High

### ISSUE THREAD

**Issue by rbahne** [MicrosoftDocs/OfficeDocs-O365ITPro#837]
The instructions here seem to work like a charm in a commercial tenant, but I am not sure if there is an incompatibility with GCC High clients... 

https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#step-3-run-powershell-commands 

When run in GCC High we are getting a token error any light you can shed would be greatly appreciated. 

Ryan

**Comment by mypil** [comment]
@rbahne  - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
