### ISSUE TITLE
Is there any way I can read shared mail box programmatically in java? 

### ISSUE THREAD

**Issue by ulasalasreenath** [MicrosoftDocs/OfficeDocs-O365ITPro#838]
Hi, is there any way I can read emails from shared mailbox programmatically with java programming language?

**Comment by mypil** [comment]
@ulasalasreenath - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by ulasalasreenath** [comment]
Hi @mypil, It's not an issue. I was going through shared mailbox details like what is shared mailbox etc, at https://docs.microsoft.com/en-us/office365/admin/email/create-a-shared-mailbox?view=o365-worldwide

In our organization, we are using shared mailbox. We would like to know is there any way I can access the mails from shared mailbox programmatically in java. 

I have been searching for solution from so many days, could not find. Hence I thought of asking for a solution here. 

If you have any supporting documents, can you please share??

**Comment by mypil** [comment]
@ulasalasreenath - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
