### ISSUE TITLE
Isn't auto renew public preview only?

### ISSUE THREAD

**Issue by Cheekynandos456** [MicrosoftDocs/OfficeDocs-O365ITPro#840]
I believe auto renew is currently on public preview? The wording above seems to state its already available to all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4773fc-df89-4d7c-6819-9ed94c66e1a3
* Version Independent ID: 9a0ce458-fd6b-5f12-0b6e-98f9b38ad13c
* Content: [Office 365 Group Expiration Policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/office-365-groups-expiration-policy?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/office-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/office-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by danprill** [comment]
It is now generally available:  https://techcommunity.microsoft.com/t5/Office-365-Blog/User-Activity-based-Expiration-Policy-for-Office-365-groups-is/ba-p/942877

**Comment by mypil** [comment]
@Cheekynandos456 - From our understanding, the issue has been answered by danprill so we will close this issue.

Thank you for engaging with the community here for the docs.
