### ISSUE TITLE
Block / Unblock User Option for Help Desk Admins

### ISSUE THREAD

**Issue by RafaelGtze** [MicrosoftDocs/OfficeDocs-O365ITPro#841]
Hello, 
I need my help desk to be able to block /unblock users in the O365 admin center, however, this option is not available in the help desk role. They need to have this option as part of their day to day activities but I don't want them to user admin role as that is too much access.

Either adding block / unblock users to the help desk role or create a new role would be great help.

Thank you,

**Comment by mypil** [comment]
@RafaelGtze - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by RafaelGtze** [comment]
Hi Mypil, I used this as reference:
https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide

This is the text that indicates what the help desk role can do:

Helpdesk admin | Assign the Helpdesk admin role to users who need to do the following:- Reset passwords- Force users to sign out- Manage service requests- Monitor service healthNote: The Helpdesk admin can only help non-admin users and users assigned these roles: Directory reader, Guest inviter, Helpdesk admin, Message center reader, and Reports reader.
-- | --

**

**Just a remark, I am not saying that that the description of the text doesn't match the actual role. All I am saying is that usually help desk users have access to block and unblock users in organizations so this addition would be greatly appreciated. Otherwise, another Admin Role with block and unblock access would be a great addition.**

**Comment by mypil** [comment]
@RafaelGtze - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback [[and feature requests]] on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
