### ISSUE TITLE
File size limit way too small and inaccurate

### ISSUE THREAD

**Issue by sietec** [MicrosoftDocs/OfficeDocs-O365ITPro#842]
This page says the limit for uploading a logo is 15kb, when it is actually 10kb.  Why such a small limit?  I could understand 100kb or (maybe) even 25-50kb.  But 10!?  It is nearly impossible to get a decent looking image that is 200x30px into 10kb.  Think about it... ignoring compression for now, if we were talking about a 256 COLOR (8 bit == 1 byte) image , that is an uncompressed size of 6000 bytes (200px * 30px * 1byte/px).  Now, make it 16 bit (crappy, remember the early 90's dithering??) color o it and the raw bitmap size has gone up to 12000 bytes - over the limit (200 * 30 * 2bytes/px).

If we go to 24 bit, it becomes 18000 bytes and 32 bits is 24000 bytes.  Add another byte for transparency (48bit) and you've got a 36,000 byte file (uncompressed).  Unfortunately, at such small dimensions, it is tough to get a file to compress much without losing a lot of the integrity of the image.  This is due to the nature of lossy compression (e.g. JPEG, PNG, etc).  Unfortunately, we have tried every trick in the book to get our 32bit logo below 10,000 bytes and it simply cannot be done without making it essentially unreadable.  

Please update the file limit - or permit UPLOADING of files (not just URLs) larger than 10kb and in some other formats would be nice also.

Thanks a lot for listening to my long-winded post!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f660bc0-58da-cc42-2a8a-f931a9037316
* Version Independent ID: be26fcbe-01ba-fe94-969d-ae0e771a0b77
* Content: [Customize the Office 365 theme for your organization](https://docs.microsoft.com/en-US/office365/admin/setup/customize-your-organization-theme?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/customize-your-organization-theme.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/customize-your-organization-theme.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by mypil** [comment]
@sietec - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by sietec** [comment]
Thank you for the response, it is nice that Microsoft is actively monitoring customer feedback. I went ahead and did submit a request on user voice, one already existed so I just upvoted that one.
