### ISSUE TITLE
New version available when?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-O365ITPro#844]
Announced at Microsoft Ignite 2019, there will be a new version of this coming. You can also see in this page was edited a few days ago by @Sirkkuw, a new screenshot of it is shown (Executive Summary screenshot). When will it be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue?

Thank you.

**Comment by Sirkkuw** [comment]
@mypil - I have reached out to the product team and will answer once I hear from them on the release cadence.

**Comment by Sirkkuw** [comment]
@JonesMikael  - you can get the downloadable here:
 https://download.microsoft.com/download/7/8/2/782ba8a7-8d89-4958-a315-dab04c3b620c/Microsoft%20365%20Usage%20Analytics.pbit

I will also update this doc https://docs.microsoft.com/office365/admin/usage-analytics/usage-analytics with the proper download link.
