### ISSUE TITLE
Global reader is not able to access SharePoint

### ISSUE THREAD

**Issue by deepikatyagi** [MicrosoftDocs/OfficeDocs-O365ITPro#847]
when we assign a global reader role, sharepoint admin center is not visible in the o365 admin center. In another document at this url: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles; it says the same. Could you clarify?

"
Global reader role has a few limitations right now -

    SharePoint admin center - SharePoint admin center does not support the Global reader role. You won't see 'SharePoint' in left pane under Admin Centers in Microsoft 365 admin center.
    OneDrive admin center - OneDrive admin center does not support the Global reader role.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@deepikatyagi -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/d93bffadac9534ff000f161652edf7f82fb40d89. 


Thank you for your contribution to make the docs better! Much appreciated!
