### ISSUE TITLE
Unclear who gets permission to what

### ISSUE THREAD

**Issue by reklov79** [MicrosoftDocs/OfficeDocs-O365ITPro#848]
This document, especially "Send email from another user's mailbox" as well as the admin itself is unclear on who gets permission to what. Does the account where you "add permission" give permission to the user added, or do you add mailboxes that user has permission to to that account? 

Also in the admin itself it should be clearly statet what happens. Which account gives permission to which one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d976996c-10a9-c1a2-7f25-3f6ba90ad9db
* Version Independent ID: 2e9c738f-2a48-8c83-4505-a3ffaf2646ed
* Content: [Give mailbox permissions to another user in Office 365 - Admin Help](https://docs.microsoft.com/en-us/office365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by tmires** [comment]
This video should help clarify things. I just had this question myself.

https://www.youtube.com/watch?v=f4QSZiZiG-E

**Comment by MaratMussabekov** [comment]
Hello @reklov79 ,
on the step 2 you are choosing the mailbox which you are going to send as.
on step 5 you are choosing user WHO will have the permission

**Comment by mypil** [comment]
@reklov79 -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/99f523cb5c2e1c2f95025a2582c47f008a083823. 


Thank you for your contribution to make the docs better! Much appreciated!
