### ISSUE TITLE
The given brand color, changes to a different shade after applying the branding colors.

### ISSUE THREAD

**Issue by sijojlouis** [MicrosoftDocs/OfficeDocs-O365ITPro#849]
I really like the idea of able to customise the colors as per brand, but I do not understand what is the purpose of O365 changing the given branding color to another shade. As it is definitely doesn't look like the brand page anymore. 

Please, do not have the color change once the brand colors are applied. It just doesn't make sense to apply it at all.

**Comment by mypil** [comment]
@sijojlouis - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@sijojlouis - We appreciate any feedback that improves the content in the Microsoft docs but we haven't received any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.

**Comment by sijojlouis** [comment]
Hi @mypil, sorry I missed sharing it earlier and for the late response.
I created the issue, because the feature wasn't working the way expected.

It was not due to an issue with the [MS doc](https://docs.microsoft.com/en-IN/office365/admin/setup/customize-your-organization-theme?WT.mc_id=365AdminCSH&view=o365-worldwide) but more on the feature on working in the [MS app](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/companyprofile).
