### ISSUE TITLE
Why does this page only apply to Office "for business"

### ISSUE THREAD

**Issue by jamietshaw** [MicrosoftDocs/OfficeDocs-O365ITPro#850]
What about the personal version? There is nothing on the whole web page that suggests that I'm only in some business section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0721ffec-3115-1479-a73f-e74706d41410
* Version Independent ID: d34d5bdf-4380-e2e0-fa47-10057f7ef0ea
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/what-if-my-subscription-expires?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jamietshaw  Thank you for your feedback. While the table details remain the same For Paid Home, Personal,  and Business subscriptions. This document pertains only to Paid Office 365 Business subscriptions and thus no information about the Home or personal version.

I understand that this page doesn't suggest that you are in the business section, however from the overview you can see these documents refer only to the Office 365 business plans.

Hope this helps! Sorry about the confusion.

Thanks
Sri

**Comment by mypil** [comment]
@jamietshaw - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
