### ISSUE TITLE
Need to add the differentiation of cancelling the renewal and cancelling the subscription

### ISSUE THREAD

**Issue by artekartian** [MicrosoftDocs/OfficeDocs-O365ITPro#851]
The first sentence on this page is misleading: “If your subscription ends—either because it expires, or because you decide to CANCEL […] go through multiple states before the subscription is fully turned off, or deprovisioned.” If you CANCEL SUBSCRIPTION users will lose access immediately. It’s not enough to mention at the end of this page that one phase will be skipped if I cancel! The key issue is, there are two ways of cancelling: 1. Cancelling the renewal (and what happens after that event) 2. Cancelling the subscription (and what are the consequences). I suggest to re-phrase the instructions to make them more clear and more precise for both cancelling options. It has a deep impact on direct to CSP conversion experience. Happy to work with you on the resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0721ffec-3115-1479-a73f-e74706d41410
* Version Independent ID: d34d5bdf-4380-e2e0-fa47-10057f7ef0ea
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/what-if-my-subscription-expires?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by joinimran** [comment]
@artekartian Thank you for your feedback. Can you please share in detail what should be added so that I can see and help to make document to reflect the accurate information.

**Comment by mypil** [comment]
@artekartian - We would like to follow up. Can you please respond to the query of joinimran?

Thank you.

**Comment by artekartian** [comment]
Thanks for reminder. I will be back to you tomorrow. Just holidays.


Pozdrawiam,
Sebastian
________________________________

**Comment by artekartian** [comment]
Hi All,
I’m referring the first sentence in the docs article:
https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/what-if-my-subscription-expires?view=o365-worldwide

If your subscription ends—either because it expires, or because you decide to cancel—your access to Office 365 services, applications […]

This is misleading and customers expect a different behavior if they cancel a monthly direct subscription.

I propose to make a better distinction of cancelling a monthly and an annual direct subscription. AND you need to explain WHEN the first stage STARTS in each scenario.

You need to describe all 3 scenarios:

  1.  If your subscription expires -> Then it goes thru following stages: Expired / Disabled / Deprovisioned. The stage “Expired” starts directly after the subscription reach to its end date.
  2.  If you cancel the renewal of you annual subscription (direct subscription from Microsoft) > Then it goes thru the same stages as expired subscription and the first stage starts at the anniversary of the annual subscription (not at the date of cancelling the subscription renewal) > Expired / Disabled / Deprovisioned
  3.  But if you cancel the monthly subscription (direct subscription from Microsoft) > then is will be disabled immediately (at the date of cancellation) – which means your users will lost the access the Office 365 assets immediately and only admins will get access to the data for next 90 days and described in the subscription cancellation and expiration table.
Hope, it helps a bit.

Regards,
Sebastian

**Comment by cmcatee-MSFT** [comment]
@artekartian Thanks for your feedback. The article has been updated.

**Comment by artekartian** [comment]
Thanks a lot! Nice to see the docs updated. 👍👍👍


Pozdrawiam,
Sebastian
________________________________
