### ISSUE TITLE
Available add-ons

### ISSUE THREAD

**Issue by jstpldev** [MicrosoftDocs/OfficeDocs-O365ITPro#852]
Can the list of mentioned add-ons, be bifurcated by traditional and standalone add-ons for better understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e643065c-fe65-e305-2c30-320b288109dc
* Version Independent ID: 413360ab-9ffb-97e2-3dd2-0e2d48f9fafa
* Content: [Buy or edit an add-on for Office 365 for business](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/buy-or-edit-an-add-on?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/buy-or-edit-an-add-on.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/buy-or-edit-an-add-on.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by jstpldev** [comment]
We dont see any document to bifurcate Add-ons by traditional and standalone for better understanding. This is impacting our development as we need to understand this concept.

**Comment by jstpldev** [comment]
@mypil Can you provide us contact person details for our question to bifurcate Add-ons by traditional and standalone for better understanding. This is impacting our development as we need to understand this concept.

**Comment by mypil** [comment]
@cmcatee-MSFT - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by cmcatee-MSFT** [comment]
@jstpldev - We will pass this feature request back to the Partner Center team for consideration. Thanks.
