### ISSUE TITLE
Unable to see Microsoft 365 Usage Executive Summary

### ISSUE THREAD

**Issue by RascoPK** [MicrosoftDocs/OfficeDocs-O365ITPro#853]
I was hoping that after importing template file, one of the tabs will have a look as its presented in documentation.
Its not and I am not able to find this "Microsoft 365 Usage Executive Summary" tab.

Where is it located or where can I download template with that tab?

**Comment by mypil** [comment]
@RascoPK - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by RascoPK** [comment]
https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide

In that link its possibel to download PowerBi Template. I was expecting Executive Summary in that template but it's not there.

**Comment by RascoPK** [comment]
https://download.microsoft.com/download/7/8/2/782ba8a7-8d89-4958-a315-dab04c3b620c/Microsoft%20365%20Usage%20Analytics.pbit

**Comment by mypil** [comment]
@RascoPK - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
