### ISSUE TITLE
Admins unable to create group

### ISSUE THREAD

**Issue by cragazzo** [MicrosoftDocs/OfficeDocs-O365ITPro#854]
I following the ps1 to create a security group to stop end users from creating groups to prevent such mess. Even though I have added certain users in that security group, those users are unable to create groups. Further, Administrators are not permitted to create groups either. Any thoughts?

This is the article / script I followed (which was successful): https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

**Comment by mypil** [comment]
@cragazzo  - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by cragazzo** [comment]
Update:  I ran the script as documented, which generated the security group. Despite having a member in that security group, they were unable to create a new teams group. I re-ran the script with the <> so line 2 now looks like $GroupName = "AllowGroupCreation". Now any member in this group can create a new teams group. Although global admins still are not able to, I can easily add as members in this security group.
