### ISSUE TITLE
The link found in Step 1 of "Team members can store their own files in OneDrive"

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/OfficeDocs-O365ITPro#855]
The link found in Step 1 of "Team members can store their own files in OneDrive" points to a location which only administrators have access to. Should it instead point to https://portal.office.com/ ?

https://docs.microsoft.com/en-us/office365/admin/setup/set-up-file-storage-and-sharing?view=o365-worldwide#team-members-can-store-their-own-files-in-onedrive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c454f78-7336-f872-c945-23c2997856af
* Version Independent ID: 4d7e4a09-122e-d291-769b-93a4dffb0942
* Content: [Set up Office 365 file storage and sharing](https://docs.microsoft.com/en-us/office365/admin/setup/set-up-file-storage-and-sharing?view=o365-worldwide#start-using-onedrive-and-your-team-site)
* Content Source: [Office365-Admin/setup/set-up-file-storage-and-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/set-up-file-storage-and-sharing.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@treestryder Thank you for your feedback. We have made the change in document via PR #879 

Thanks
Sri

**Comment by mypil** [comment]
@treestryder - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/66f58b74c4990bc9ed05a61734a30730f174a8c6. 


Thank you for your contribution to make the docs better! Much appreciated!
