### ISSUE TITLE
Cannot find 

### ISSUE THREAD

**Issue by jcrowland** [MicrosoftDocs/OfficeDocs-O365ITPro#856]
The header of this article states:  "You can also see the version information of Outlook apps that users are using, which will allow you to follow up with those who are using unsupported versions [...]"

Reviewing the document, I can find the report that shows the total for users using Office 2010 or 2013, but there is no way to find who the users are.  If there is a way, the documentation doesn't clearly show, and I haven't found it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 535888ea-6011-1467-bf9a-1de66cb8c402
* Version Independent ID: d72f6ddc-15a0-5398-251e-92496afdf309
* Content: [Office 365 Reports in the admin center - Email apps usage](https://docs.microsoft.com/en-us/office365/admin/activity-reports/email-apps-usage?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/activity-reports/email-apps-usage.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/email-apps-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jcrowland Thank you for your feedback. You may not be able to see the username section unless you add it. You can do that using the steps provided in Step8 https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/879

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@jcrowland  - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
