### ISSUE TITLE
quarantine administrator is not listed in the article

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/OfficeDocs-O365ITPro#857]
quarantine admin is not listed nor is the details on what it allows when granted.

**Comment by mypil** [comment]
@scottsa-msft - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by scottsa-msft** [comment]
This is the URL that is missing any reference to the new quarantine admin role
https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles

Scott Sanders | Office 365 Service Delivery Manager
scottsa@microsoft.com<mailto:scottsa@microsoft.com> ' 678 629-5746 È 404 538-5105  7 O365 Support 1-800-936-3100
[cid:image001.png@01D5AE71.FDCF0CC0]

**Comment by mypil** [comment]
@scottsa-msft - Thank you for sharing the doc link. This repository is intended for feedback on docs specific to Office 365 ITPro topics and the link you shared is for the Azure repo.  Please submit your feedback and open a new issue by clicking on the Feedback section on the specific Microsoft doc (https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles) which is found at the bottom of the page.
