### ISSUE TITLE
quarantine administrator role is not listed

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/OfficeDocs-O365ITPro#858]
quarantine admin role is missing as well as what it gives access to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by scottsa-msft** [comment]
This role is listed in the security and compliance center

**Comment by msbemba** [comment]
@scottsa-msft Thank you for your feedback. The quarantine role is not available on the Microsoft 365 admin center yet. So I have update the doc for Security and Compliance center roles via PR # https://github.com/MicrosoftDocs/microsoft-365-docs/pull/942

**Comment by msbemba** [comment]
@scottsa-msft Thank you for the feedback. We found that the role was exposed prematurely. You will see more in the documents once this is publically live for all tenants.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@scottsa-msft - From our understanding, the issue you raised has been answered by msbemba and please refer to this additional https://github.com/MicrosoftDocs/microsoft-365-docs/pull/942#issuecomment-566189249 from the author so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
