### ISSUE TITLE
What if I need to do this for another Azure AD

### ISSUE THREAD

**Issue by pmdci** [MicrosoftDocs/OfficeDocs-O365ITPro#86]
What if I need to set a user's password to never expire, but this user exists in another Azure AD which I am invited to and I am a full admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8299b0d8-25e4-af45-a9f8-724f61ed4f4a
* Version Independent ID: 4ab5dc30-7f11-758b-9b58-e5254e25774e
* Content: [Set an individual user's password to never expire](https://docs.microsoft.com/en-us/office365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@pmdci Thank you for this inquiry

I am not sure if the same exact steps will work for another Azure AD. Let me get this over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@pmdci - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by pmdci** [comment]
Uh?

I don't need to open a ticket. I asked a question for a scenario that is common -- not a specific issue I need help with.

**Comment by ethanbayliss** [comment]
Gonna necro this - if you need to connect to another tenant then specify their tenant ID in the connect-azuread parameters:

connect-azuread -tenantid xxxx-xxx-xxxx-xxx
#Enter YOUR email address, and if you are a partner/invited it will authenticate properly.
#Then you can perform the checks and changes as needed
Get-AzureADUser -All $true | Select-Object UserprincipalName,@{N="PasswordNeverExpires";E={$_.PasswordPolicies -contains "DisablePasswordExpiration"}}
