### ISSUE TITLE
Step 1 needs a Step 1a added

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-O365ITPro#862]
If this is a step-by-step process, then you actually need to click 'Add a group' button before selecting the Type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?redirectSourcePath=%252fen-us%252farticle%252fManage-who-can-create-Office-365-Groups-4c46c8cb-17d0-44b5-9776-005fced8e618&view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@jantoney Thank you for your feedback. We have added the extra step to the document via PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/878

Thanks
Sri

**Comment by mypil** [comment]
@jantoney - From our understanding, the issue has been resolved based on this merged commit 
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/3a9df79a42d178fa0be531eeeb58a5bd5f4188fd. 

Thank you for your contribution to make the docs better! Much appreciated!
