### ISSUE TITLE
"Make sign-in more secure" does not exist as an option

### ISSUE THREAD

**Issue by OzmeisterO** [MicrosoftDocs/OfficeDocs-O365ITPro#863]
When setting up MFA, "Make sign-in more secure" is not an option on my screen.  I'm therefore unable to follow these instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@OzmeisterO - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
