### ISSUE TITLE
Support is not 24/7

### ISSUE THREAD

**Issue by MurtazK** [MicrosoftDocs/OfficeDocs-O365ITPro#864]
Technical Support Number is not 24/7 as mentioned. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4e69c4-7a73-4860-8296-0f658c012bad
* Version Independent ID: 12f53517-e53d-e53e-a230-7bf8c2b758e9
* Content: [Support information for Singapore](https://docs.microsoft.com/en-us/Office365/Admin/support/singapore?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/support/singapore.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/singapore.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@MurtazK - Thank you for submitting feedback.

To help investigate this issue, please send an email to **cmcatee@microsoft.com** and provide the below information directly in email (do not post this information here):

Country and Number being called:
Country and City of person calling to test:
Number tester is calling from:
Landline or Mobile Phone?
What Carrier does this number belong to?
Date and time of test call:
Exact details of errors or experience when calling:


cc: @cmcatee-MSFT
