### ISSUE TITLE
Not only third-party apps and access to Office 365 information

### ISSUE THREAD

**Issue by jnxxx** [MicrosoftDocs/OfficeDocs-O365ITPro#865]
This settings appears not only to affect third-party apps to access their Office 365 information. It prevents users from consenting to any permission, even to own developed apps (hardly considered third party).

Please allow us to configure which permissions users can consent to themselves. Like basic login (User.Read) etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279bb5c8-222e-5ee9-dcd7-8c06bd4d3a3e
* Version Independent ID: 4b1d6664-91b3-8bd6-f26e-d46005891294
* Content: [Turning Integrated Apps on or off](https://docs.microsoft.com/en-us/office365/admin/misc/integrated-apps?WT.mc_id=365AdminCSH&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/integrated-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/integrated-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@jnxxx - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
