### ISSUE TITLE
Error in the Template

### ISSUE THREAD

**Issue by dobby10** [MicrosoftDocs/OfficeDocs-O365ITPro#867]
There is an error in the template, The Teams User number for the executive summary is filtering on the Teams Product from the "TenantProductActivity" table, where it should be using the "TenantProductUsage" table. I discovered this because the number was 3x the number of users in the whole company.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@dobby10 - Can you please share what specific issue you have with this doc? Or are you having some technical issues which requires technical support?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by mypil** [comment]
@dobby10 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't received any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
