### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by DFLiddle** [MicrosoftDocs/OfficeDocs-O365ITPro#87]
Above, it reads, “Group naming policy requires Azure Active Directory Premium P1 license for unique users that are members of Office 365 groups.”

Does that mean that a license is required for each user who will implement the policy, or that one is required for each person who will be affected by the policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f70ad7b-5ba2-6167-1207-7496d57c6828
* Version Independent ID: 3df3ae33-83d3-e25f-3b41-070620030a08
* Content: [Office 365 Groups naming policy](https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/groups-naming-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/groups-naming-policy.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@DFLiddle Thank you for this inquiry

I am not sure if that means you need a P1 licence for the creater of the group or everyone in the group. Let me get this over to the O365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by oberjc** [comment]
Any response to this question?  I am also looking for this info as the document is not 100% clear.

**Comment by AndreaBarr** [comment]
@sonika24 Can you please investigate this?

**Comment by dianef77** [comment]
Hi, I updated this article to clarify the licensing requirements.

**Comment by DFLiddle** [comment]
Thank you for the update! It is nice and clear now.

(Some readers might take note that, at this time, the Azure Active Directory Premium P1 license mentioned is also part of the Enterprise Mobility + Security suite.)

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
