### ISSUE TITLE
looks like this can be done via GUI as well

### ISSUE THREAD

**Issue by ragupt** [MicrosoftDocs/OfficeDocs-O365ITPro#870]
I had suggested couple of changes to this This can also be done through the new option that is available in Azure AD
Go to Portal.Azure.com.
Go to Azure Active directory.
Go to User settings.
Click on "Manage external collaboration settings".
under Collaboration restrictions" select Allow invitations only to the specified domains (most restrictive).
Enter the target domain names to be allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b191c8b0-5673-efce-de2a-ba219aa82f37
* Version Independent ID: d5f71172-e733-af54-e938-19b738a026b3
* Content: [Manage guest access in Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by ragupt** [comment]
This can also be done through the new option that is available in Azure AD
Go to Portal.Azure.com.
Go to Azure Active directory.
Go to User settings.
Click on "Manage external collaboration settings".
under Collaboration restrictions" select Allow invitations only to the specified domains (most restrictive).
Enter the target domain names to be allowed.
![70410742-15a7c100-1a76-11ea-918a-2d6269c49873](https://user-images.githubusercontent.com/58678787/70768371-cff73b00-1d8a-11ea-8a85-f3fe3490bc49.jpg)

**Comment by msbemba** [comment]
@ragupt Thank you for your feedback. We have added a section for this named Allow or block guest access based on their domain and a link is posted within this section which talks about the new option that is available in Azure AD

https://docs.microsoft.com/en-us/azure/active-directory/b2b/allow-deny-list

Thanks again for making our docs look better.

Thanks
Sri

**Comment by mypil** [comment]
@ragupt  - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
