### ISSUE TITLE
Message provided doesn't reflect the reality of today's threats.

### ISSUE THREAD

**Issue by nottalada** [MicrosoftDocs/OfficeDocs-O365ITPro#873]
"Do not open these type of files from people you do not know because they might contain macros with malicious code." isn't good advice because these days, it's easy enough for malicious attachments to come from people you know.

It should read:
"Do not open these type of files unless you were expecting it because the file may contain malicious code and knowing the sender isn't a guarantee of safety."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0759f6b0-4d12-e0fa-f1cf-320f4e4ae32a
* Version Independent ID: 5b10ae00-e088-b39d-e13f-ead4081f2784
* Content: [Top 10 ways to secure Office 365 and Microsoft 365 Business plans](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @SuPotter
* Microsoft Alias: **supotter**

**Comment by msbemba** [comment]
@nottalada Thank you for your feedback. I have made changes to the doc to reflect your concern. THis can be tracked via PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/889

Thank you for making our docs better.

Thanks
Sri

**Comment by mypil** [comment]
@nottalada -From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/5e974e0e7a389ccafaa9af3c19a9b35463d9a0b2. 


Thank you for your contribution to make the docs better! Much appreciated!
