### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/OfficeDocs-O365ITPro#874]
Article is outdated. Many of the options here have moved or are renamed in the admin center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@RobvanB Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/890 to reflect the correct steps.

Thanks
Sri

**Comment by mypil** [comment]
@RobvanB - Please refer to the author's https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/890#issuecomment-570688767 in response to this issue. We hope this helps to give clarity so will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
