### ISSUE TITLE
No Domains in Settings, Domains' Moved to Setup

### ISSUE THREAD

**Issue by Wang-W-e-i** [MicrosoftDocs/OfficeDocs-O365ITPro#875]
Instead of 'go to the Settings', Step 1.1 should read 'In the Microsoft 365 admin center, go to Setup'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27249e0c-e601-b849-8404-ce0bb8155fce
* Version Independent ID: a308f156-998b-8ea9-5668-7a59e549cd10
* Content: [Gather the information you need to create Office 365 DNS records](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/information-for-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@Wang-W-e-i Thank you for the feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/891

Thanks
Sri

**Comment by mypil** [comment]
@Wang-W-e-i - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/b49ef27bbe2ce013dc90ce36cbfc42195453bbc3. 


Thank you for your contribution to make the docs better! Much appreciated!
