### ISSUE TITLE
21Vianet EXO large message trace downlaoding issue

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-O365ITPro#876]
Customer often cannot download large message trace. If size of trace is small downloading, then we are able to download it. However, there is no preview of query in portal. Can we compose and publish any official docs guide customer how to download message trace in EAC portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35c839a1-9440-3e07-1cd9-99f8664d1a6e
* Version Independent ID: d87fa57b-b806-febd-7c0f-7a074dcbf7cc
* Content: [Office 365 operated by 21Vianet](https://docs.microsoft.com/en-us/office365/admin/services-in-china/services-in-china?view=o365-21vianet#feedback)
* Content Source: [Office365-Admin/services-in-china/services-in-china.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/services-in-china/services-in-china.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by XixiHuang333** [comment]
hi Team,
Any update on this?

**Comment by XixiHuang333** [comment]
Our Gallatin customers mentioned they rely on email trace report a lot for email platform/audit operation. They feel very inconvenient for trace downloading because most of time they encountered error when downloading trace. They also feel it is troublesome and difficult for them to filter less information many time to reduce size of trace to less than limitation size as there is no preview size information. Customer expect one of the following options is available:

Preview size information is available in portal.
Change size limitation of trace downloading.
If both two options is impossible, at least we have official document to state the size limitation information, and customer guidance on how to get mass data of message trace.

**Comment by VLG17** [comment]
@XixiHuang333 Have you tried running the Message Trace from the Security & Compliance Center instead of EAC? 

https://techcommunity.microsoft.com/t5/exchange-team-blog/new-message-trace-in-office-365-security-038-compliance-center/ba-p/607893

> **Message Trace in the Exchange Admin Center (EAC) is a useful tool for tracing messages, but it's visually cluttered and confusing, and it lacks a number of more sophisticated capabilities.** To make Message Trace more effective and easier for both professional and part-time email admins, we've redesigned Message Trace and placed it in the Office 365 Security & Compliance Center. **The new Message Trace sports a streamlined, modern interface, and adds a number of new features that will help you get your job done more quickly and with greater effectiveness.**

Regarding the options that the customer wants, i recomment opening thread on [UserVoice for Office 365](https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338) and requesting these changes: 

Preview size information is available in portal.
Change size limitation of trace downloading.

**Comment by mypil** [comment]
@XixiHuang333 -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
