### ISSUE TITLE
12175139

### ISSUE THREAD

**Issue by foldcode** [MicrosoftDocs/OfficeDocs-O365ITPro#88]
We are not getting instant response on ticket 12175139. Have been routed to many people and asking for wait.

I would like to get this case fix ASAP. This is affecting business, as we could not get emails in office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2b385a-9cb4-9110-94bb-7d63f7e591f0
* Version Independent ID: 07d6eed9-0f79-5c7e-6c7b-0391d0190c57
* Content: [Support information for India](https://docs.microsoft.com/en-us/office365/admin/support/india?view=o365-worldwide)
* Content Source: [Office365-Admin/support/india.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/support/india.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by AndreaBarr** [comment]
@foldcode Thank you for this feedback

If this is an immediate issue that is affecting your business then I want to get you over to Support. They have more resources to dig in and find a resolution. They will also be able to find a resolution quicker than we are able to here in the docs. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
