### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by born-slippy** [MicrosoftDocs/OfficeDocs-O365ITPro#881]
Troubleshoot: User not seeing add-ins
https://docs.microsoft.com/office365/troubleshoot/troubleshooting/user-not-seeing-add-ins

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d424b-6f62-e70c-9c2d-ad779ffa6c3b
* Version Independent ID: e4597136-bfe8-4230-da83-f806a1126005
* Content: [Manage deployment of Office 365 add-ins in the admin center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@born-slippy -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/d8d048beef834ffcc72de85c85c96efb9b9fcc70. 


Thank you for your contribution to make the docs better! Much appreciated!
