### ISSUE TITLE
Executive summary dashboard image above is outdated

### ISSUE THREAD

**Issue by saigrsundaram** [MicrosoftDocs/OfficeDocs-O365ITPro#882]
The current version of "Microsoft Office365 usage analytics" app dashboard layout is different than the dashboard above. Request you to update the image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by MaratMussabekov** [comment]
Dear @mypil, @Sirkkuw,
Could you please have a look, I created a Usage report in my tenant and I see following:
![image](https://user-images.githubusercontent.com/48041687/71643244-4a0f4580-2ce1-11ea-87ff-74df377e7076.png)
it seems that this article contains the description of sections of Microsoft 365 usage analytics that do not exist.
Does article need to be rewritten or am I doing something wrong?
Thank you

**Comment by abhitalks** [comment]
Yes. The executive summary section is not available. Also, the UI of the executive summary section is different than the rest of the reports?

**Comment by JohanssonMarkus** [comment]
Seems that Power BI on the Web and Desktop is using different templates. I did download and running on desktop version and looks better. Try this
https://download.microsoft.com/download/7/8/2/782ba8a7-8d89-4958-a315-dab04c3b620c/Microsoft%20365%20Usage%20Analytics.pbit

**Comment by MaratMussabekov** [comment]
yes, but even in desktop version it looks much differ, not as it is described in the article.

**Comment by Sirkkuw** [comment]
Where are you located @MaratMussabekov  ? In the FAQ section there is a link to the pbit file you can download. That was just updated to the new file, and the topic itself was updated with the new look just recently.

**Comment by Sirkkuw** [comment]
However, I will follow up with the product team to make sure I have included the appropriate figure.

**Comment by MaratMussabekov** [comment]
Hello @Sirkkuw ,
**In the FAQ section there is a link to the pbit file you can download** - yes, I tried this file, but still dashboard is not the same as in the article.
Thank you

**Comment by mypil** [comment]
@saigrsundaram @abhitalks @MaratMussabekov - We have verified and confirmed with the Product team that the figure is the current version. 

We value your feedback. Thank you for engaging the community here for the docs!
