### ISSUE TITLE
Link broken: Settings > Services & add-ins page

### ISSUE THREAD

**Issue by mscaitlina** [MicrosoftDocs/OfficeDocs-O365ITPro#883]
Deploy an Office add-in using the admin center
...
In the admin center, go to the Settings > Services & add-ins page.

Link: https://go.microsoft.com/fwlink/p/?linkid=2053743

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d424b-6f62-e70c-9c2d-ad779ffa6c3b
* Version Independent ID: e4597136-bfe8-4230-da83-f806a1126005
* Content: [Manage deployment of Office 365 add-ins in the admin center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [Office365-Admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@mscaitlina Thank you for the feedback. The link is working now and you should be able to access the services and add-in page from the link mentioned in the doc.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@mscaitlina - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
