### ISSUE TITLE
Microsoft 365 Usage Analytics App cannot be created

### ISSUE THREAD

**Issue by esther-tan-IT** [MicrosoftDocs/OfficeDocs-O365ITPro#884]
I tried to follow the 'Initiate the content pack' steps on this page: https://docs.microsoft.com/en-US/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide. 

On step 3, after clicking 'Get in now', it displays a "Please hold on while we load a few things..." message, and continues spinning.

**Comment by mypil** [comment]
@esther-tan-IT - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get this information you are discovering back into the docs.
