### ISSUE TITLE
Problem with Downloading Office 2013 Language Packs (Italian)

### ISSUE THREAD

**Issue by leonid17242** [MicrosoftDocs/OfficeDocs-O365ITPro#887]
Hello everyone ! 

When i'm trying to download the Office 2013 Language Packs (Italian), the downloading run and all it's good i follow the instructions and it's finish. 

but when i'm going to per example Outlook or World in the settings -> Options -> Choose Editing Languages, the Italian Editing Language are Enabled but Not Installed while i have installed this now 5 times with different package and the Proofing still "Not Installed"

Do you have solution please to resolve this problem ? 

Thank you !

**Comment by mypil** [comment]
@leonid17242 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by leonid17242** [comment]
https://support.office.com/fr-fr/article/module-linguistique-language-accessory-pack-pour-office-82ee1236-0f9a-45ee-9c72-05b026ee809f#ID0EAADAAA=Office%C2%A02013

**Comment by mypil** [comment]
@leonid17242 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
