### ISSUE TITLE
Generate and send reports

### ISSUE THREAD

**Issue by towernick** [MicrosoftDocs/OfficeDocs-O365ITPro#892]
Hello,

I am wondering if it's currently possible to have these reports sent to an email address automatically at a set date?

I am the administrator over multiple O365 accounts, and would like to find out if there's a way to have info the client requested sent to me to avoid having to sign into multiple O365 accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2900ade-43fe-5f21-fc18-d1db33762787
* Version Independent ID: 574a1284-ace4-68ba-8811-4e305386c7de
* Content: [Activity Reports in the Microsoft 365 admin center](https://docs.microsoft.com/en-US/office365/admin/activity-reports/activity-reports?WT.mc_id=365AdminCSH&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/activity-reports/activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/activity-reports.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@towernick - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
