### ISSUE TITLE
Remove [Microsoft Dynamics 365 for Operations] 

### ISSUE THREAD

**Issue by YujiImaoka** [MicrosoftDocs/OfficeDocs-O365ITPro#894]
Could you please remove [Microsoft Dynamics 365 for Operations] from Available self-service programs?
Because the link for [Website for self-service sign up] does not work.
https://www.microsoft.com/ja-jp/dynamics365/operations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27380ae-e2d6-7d32-b573-5c9a08592164
* Version Independent ID: b17e2ed4-9b79-0fd3-efa9-e62f73dc5cb4
* Content: [Using self-service sign up in your organization](https://docs.microsoft.com/en-us/office365/admin/misc/self-service-sign-up?view=o365-worldwide)
* Content Source: [Office365-Admin/misc/self-service-sign-up.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/self-service-sign-up.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@YujiImaoka - Thank you for submitting feedback.

I just checked and confirmed that the link for the Website for self-service sign up for the Microsoft Dynamics 365 for Operations actually works. This is the source link - https://dynamics.microsoft.com/en-us/finance-and-operations-to-finance-and-scm/ and the Japanese version is this link - **https://dynamics.microsoft.com/ja-jp/finance-and-operations-to-finance-and-scm/**

I hope this helps to resolve your issue.
