### ISSUE TITLE
Please change [Website for self-service sign up] for Microsoft Dynamics 365 for Operations

### ISSUE THREAD

**Issue by YujiImaoka** [MicrosoftDocs/OfficeDocs-O365ITPro#895]
Please change [Website for self-service sign up] for Microsoft Dynamics 365 for Operations to
https://dynamics.microsoft.com/en-us/finance-and-operations-to-finance-and-scm/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27380ae-e2d6-7d32-b573-5c9a08592164
* Version Independent ID: b17e2ed4-9b79-0fd3-efa9-e62f73dc5cb4
* Content: [Using self-service sign up in your organization](https://docs.microsoft.com/en-us/office365/admin/misc/self-service-sign-up?view=o365-worldwide)
* Content Source: [Office365-Admin/misc/self-service-sign-up.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/self-service-sign-up.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@YujiImaoka - This is related to the closed issue #894.  
 
Are you having issues accessing the link within the doc for the  [Website for self-service sign up] for Microsoft Dynamics 365 for Operations? If yes, can you please share the error message or a screenshot of the error that you're getting? This will help us investigate if there's really a need to make changes on this doc.

As mentioned in this https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/894#issuecomment-569151590, the link is working when we tested it.

**Comment by YujiImaoka** [comment]
As I mention in other request, correct URL is
https://dynamics.microsoft.com/en-us/finance-and-operations-to-finance-and-scm/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdynamics.microsoft.com%2Fen-us%2Ffinance-and-operations-to-finance-and-scm%2F&data=02%7C01%7Cyuji.imaoka%40microsoft.com%7C3e7ab1d42b4b400c14c608d78a604c01%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637130019255786556&sdata=FwxIqyEzVNrtuGGhE4zod5Wo9HSX1IzhvUsH%2FbFg%2BII%3D&reserved=0>

Old URL is this one. https://www.microsoft.com/ja-jp/dynamics365/operations
You will see this error message when opening this URL.
<Error>
We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.
[cid:image001.jpg@01D5BCAA.222ACC30]

**Comment by mypil** [comment]
@YujiImaoka - Thank you for your response and for sharing the error message. 

I created PR #896 to help fix the broken link issue and tagged the author to review/merge the PR.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cmcatee-MSFT** [comment]
@YujiImaoka - The link should be working correctly now.
