### ISSUE TITLE
Adding additional licences from other source

### ISSUE THREAD

**Issue by mosaiqrs** [MicrosoftDocs/OfficeDocs-O365ITPro#897]
Hello Team,

can you, please, help us to add an additional licence from the box? We are a small company and we bought 2 licences for 2 users directly on Microsoft.com. We bought another licence from a reseller (box with key). How to add this licence to existing domain and subscription? Is enough just to go to office.com/setupkey and activate it here? Does this will just increase the number of users in my admin center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bd79f9-7cff-9b2a-707d-38e87adeabc9
* Version Independent ID: 4bd53ddf-c412-90f4-56c0-a99fffbf0376
* Content: [Buy licenses for your Office 365 for business subscription](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/buy-licenses?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/buy-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/buy-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@mosaiqrs - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
