### ISSUE TITLE
How to determine if Group creation IS restricted to a group?

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/OfficeDocs-O365ITPro#899]
This explains how to restrict the ability to create groups to members of a specific group.  How can we determine if this has already been configured? would we have to examine every group in our tenant for that "EnableGroupCreation" property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?redirectSourcePath=%252fen-us%252farticle%252fControl-who-can-create-Office-365-Groups-4c46c8cb-17d0-44b5-9776-005fced8e618&view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by SteveColegrove** [comment]
run the PS stuff listed in the article but comment out the 3 lines listed below.  In the output, just look at GroupCreationAllowedGroupId and EnableGroupCreation

$GroupName = "<SecurityGroupName>"
$AllowGroupCreation = "False"
Set-AzureADDirectorySetting -Id $settingsObjectID -DirectorySetting $settingsCopy

**Comment by mypil** [comment]
@jjinatlanta - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by SteveColegrove so we will close this issue.

@SteveColegrove  - Thank you for sharing your insights to address this issue.


Thank you for your contribution to make the docs better! Much appreciated!
