### ISSUE TITLE
Feature Request : Good to Have : Schedule Send Emails on Outlook Web

### ISSUE THREAD

**Issue by bhoisuman** [MicrosoftDocs/OfficeDocs-O365ITPro#900]
It shall be a **great privacy preserving** feature to be able to **schedule send** emails on future date/time.

**Comment by mypil** [comment]
@bhoisuman - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
