### ISSUE TITLE
Some Other Suggestions to Add to this article

### ISSUE THREAD

**Issue by lmarianko** [MicrosoftDocs/OfficeDocs-O365ITPro#901]
1) How unread marks work in shared mailboxes
2) Send as and send on behalf of permissions  (or links to these documents), using security groups in shared mailbox permissions
3) on-prem vs. online and cross prem permissioning (links to this perhaps)  https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes
3) Can lock down access to it if you give permissions at the folder level
4) How to use and access a shared mailbox in the different clients - only a link to mobile here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f9dfa1-bfc2-ca15-0490-b16ebb1fbae2
* Version Independent ID: 236dc766-2f09-a5ec-f826-a1381560e106
* Content: [About shared mailboxes](https://docs.microsoft.com/en-us/office365/admin/email/about-shared-mailboxes?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/about-shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/about-shared-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@lmarianko Thank you for your suggestions. The content publishing team will consider them for future updates to this article. @Sirkkuw
