### ISSUE TITLE
Templates Nowhere to be Found...

### ISSUE THREAD

**Issue by Jamie-StarFyre** [MicrosoftDocs/OfficeDocs-O365ITPro#902]
We were anxiously awaiting this feature to arrive.  The announcement for this, in message MC188687, indicated that worldwide rollout would be complete by the end of November 2019.  

Wondering...  To date, this feature is not available in our instance.  Has there been a delay in full implementation?  It's now 2020 and we still don't have the option for user templates in the Admin Center...

Is it just us, or are there other Tenants/Organizations with the same issue?  Am I missing something??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e70b74-edd4-33cd-1d04-fb36fe235052
* Version Independent ID: 1e0cc26a-27c8-a046-5fb1-bbd2dcd8d7c6
* Content: [Create and use a template to add users](https://docs.microsoft.com/en-us/office365/admin/add-users/create-and-use-a-template-to-add-users?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/create-and-use-a-template-to-add-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/create-and-use-a-template-to-add-users.md)
* Service: **o365-administration**
* GitHub Login: @SharS
* Microsoft Alias: **v-sharos**

**Comment by mypil** [comment]
@Jamie-StarFyre - Thank you for this inquiry.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@SharS - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by Jamie-StarFyre** [comment]
@mypil 

Thanks!  I can actually report that that Templates option finally showed up on my Admin panel earlier this week!

**Comment by mypil** [comment]
@Jamie-StarFyre - Thanks for your confirmation that the issue has been resolved. We will close this issue now.

Please feel free to open a new issue if there is a specific area in the docs that we can make improve on.
