### ISSUE TITLE
AAD Security Groups

### ISSUE THREAD

**Issue by SteveColegrove** [MicrosoftDocs/OfficeDocs-O365ITPro#903]
Does a similar process exist for preventing regular users from creating Azure AD security groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb2953d4-8abc-5e9c-e30d-43b059b57b9a
* Version Independent ID: 467981d4-20b5-8b70-2d42-d3e38b918281
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@SteveColegrove  Thank you for your feedback. Only global and user management administrators have permissions to create, edit, or delete Azure AD security groups; for more information about administrator roles, see Assigning Admin roles here(https://docs.microsoft.com/en-us/office365/admin/add-users/assign-admin-roles?view=o365-worldwide)

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@SteveColegrove  - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
