### ISSUE TITLE
Groups admin

### ISSUE THREAD

**Issue by martinagrom** [MicrosoftDocs/OfficeDocs-O365ITPro#904]
The description that a groups admin can access:
"Assign the groups admin role to users who need to manage all groups settings across admin centers, including the Microsoft 365 Admin Center, Azure Active Directory portal, Teams admin center, and SharePoint admin center." is not correct as a user in that role can only access the Microsoft 365 admin center and the Azure admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About admin roles in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by VLG17** [comment]
@martinagrom thank you for this valid feedback. I have created a PR with the changes.

**Comment by mypil** [comment]
@martinagrom - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/6bfdbc774ce660ab40e2a171a61cdd50c0882d79 but it may take a few days for the merged content to appear in the doc. 


Thank you for your contribution to make the docs better! Much appreciated!
