### ISSUE TITLE
Created group from MS Teams - rule doesn´t work

### ISSUE THREAD

**Issue by ondraandy** [MicrosoftDocs/OfficeDocs-O365ITPro#906]
Hi. 
I have set rules and it works when I create group from OWA. But from MS Tems doesn´t work - domain for group is default in tenant. Have you any idea why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96002890-7e35-a0ab-a849-d94fef254fa8
* Version Independent ID: 2c4105db-b713-4829-393e-de355c5c60d4
* Content: [Choose the domain to use when creating Office 365 Groups](https://docs.microsoft.com/en-us/office365/admin/create-groups/choose-domain-to-create-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/choose-domain-to-create-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/choose-domain-to-create-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@ondraandy - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
