### ISSUE TITLE
Incorrect 

### ISSUE THREAD

**Issue by andrewflatt** [MicrosoftDocs/OfficeDocs-O365ITPro#907]
The below doesn't exist anymore
----------------

Manage MFA settings
In the admin center, select Setup.

Next to Sign-in and security, under Make sign-in more secure, select View.

Under Make sign-in more secure, select Manage.

The Azure portal Conditional Access - Policies page will appear. To turn multi-factor authentication on or off:

Select Baseline policy: End user protection (Preview), and turn the Enable toggle on or off.

Select Baseline policy: Require MFA for admins (Preview), and turn the Enable toggle on or off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@andrewflatt Thank you for your feedback. As per the Author, this is how the new settings will be looking like and there are chances that some tenants are still seeing it the old way.

https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/890#issuecomment-570688767

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@andrewflatt - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
