### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-O365ITPro#91]
Can you please clarify the permissions needed to add/manage domain, either here or in the Domains FAQ article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf4bb58c-d6e6-2cd8-2e0a-13b7eabfebc7
* Version Independent ID: fa15ca5c-66f9-62ec-1d2b-0f8020b0827a
* Content: [Add a domain to Office 365](https://docs.microsoft.com/en-us/office365/admin/setup/add-domain?redirectSourcePath=%252farticle%252f6383f56d-3d09-4dcb-9b41-b5f5a5efd611&view=o365-worldwide)
* Content Source: [Office365-Admin/setup/add-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/add-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndreaBarr** [comment]
@michevnew Thank you for this inquiry

I will get this request over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hi there @michevnew The required permissions to do the add/modifications of the domains are being done on a TENANT level, that's the reason why it requires the permissions of "Global Administrator".

Since Customized Administrator is required to do specific management of the office365, in another hand the domain that you can add or remove has a global effect on the tenant.

**Comment by michevnew** [comment]
Jose, what I meant was can you please update this in the article, as it doesnt explicitly mention it now :) I see that you added a note on top now, so all is good.

**Comment by j0rt3g4** [comment]
Will do

**Comment by j0rt3g4** [comment]
@michevnew  is done on the pull: https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/compare/public...j0rt3g4:public

**Comment by j0rt3g4** [comment]
Vasil!!!
Now I've found you here as well hahaha.

I know you from experts exchange :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
