### ISSUE TITLE
Baseline policies are being depreciated

### ISSUE THREAD

**Issue by b-col** [MicrosoftDocs/OfficeDocs-O365ITPro#910]
As per "What's new in Azure Active Directory?", baseline policies are being depreciated. This should be mentioned in this article.
https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new#replacement-of-baseline-policies-with-security-defaults

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@b-col Thank you for your feedback. We have added a note in the doc via PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/923

Thanks
Sri

**Comment by mypil** [comment]
@b-col - According to the doc owner, the topic in question has been updated and has gone through an edit cycle to update it to the Security defaults. Please see this https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/923#issuecomment-579373013 as reference.

We will close this issue now. Thank you for your valuable feedback to help us improve the quality of the docs!
