### ISSUE TITLE
Administrative Assistance Association

### ISSUE THREAD

**Issue by jarrott616** [MicrosoftDocs/OfficeDocs-O365ITPro#912]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a48cf8a-f5cb-ca05-c8ca-f9b29c458cf3
* Version Independent ID: d926f9d3-a659-f81c-af11-868094683733
* Content: [Switch to a different Office 365 for business plan](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/switch-to-a-different-plan?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/switch-to-a-different-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/switch-to-a-different-plan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@jarrott616 - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc? We would really appreciate it if you are able to help by providing more details as to what should be edited and/or included.

**Comment by mypil** [comment]
@jarrott616 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
