### ISSUE TITLE
What is the powershell command for turning off (or on) permissions for integrated apps?

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/OfficeDocs-O365ITPro#916]
Would be nice to have the powershell equivalent of the gui documented for mass configuration of multiple tenants 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279bb5c8-222e-5ee9-dcd7-8c06bd4d3a3e
* Version Independent ID: 4b1d6664-91b3-8bd6-f26e-d46005891294
* Content: [Turning Integrated Apps on or off](https://docs.microsoft.com/en-us/office365/admin/misc/integrated-apps?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/misc/integrated-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/misc/integrated-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Absoblogginlutely  Thank you for the feedback. unfortunately, we don't have a way currently to use Powershell cmdlets to exercise this. The document will be updated once the PS cmdlets are ready.

Thanks
Sri

**Comment by mypil** [comment]
@Absoblogginlutely - From our understanding, the issue you raised has been answered by msbemba  so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
