### ISSUE TITLE
Set up multi-factor authentication

### ISSUE THREAD

**Issue by ragupt** [MicrosoftDocs/OfficeDocs-O365ITPro#918]
below section is incorrect

Set up multi-factor authentication

In the admin center, select Setup.
Next to Sign-in and security, under Make sign-in more secure, select View.
On the Make sign-in more secure page, select Get started.
Select the Require multi-factor authentication and Require users to register for multi-factor authentication and block access if risk is detected check boxes.
Under Do you want to exclude anyone from these policies, select any users that you want to exclude from the drop-down list box.
Select Create policy. You will return to the Make sign-in more secure page, which will now say Completed.

it should be :-

In the admin center, select Multi factor authentication
Select the user to enable / disable the MFA 
Under Quick steps &gt; Select Enable or Disable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by ragupt** [comment]
Below section is incorrect and doesn't exist : -

Set up multi-factor authentication

- In the admin center, select Setup.
- Next to Sign-in and security, under Make sign-in more secure, select View.
- On the Make sign-in more secure page, select Get started.
- Select the Require multi-factor authentication and Require users to register for multi-factor authentication and block access if risk is detected check boxes.
- Under Do you want to exclude anyone from these policies, select any users that you want to exclude from the drop-down list box.
- Select Create policy. You will return to the Make sign-in more secure page, which will now say Completed.

It should be :-

1. In the admin center, select Multi factor authentication

![image](https://user-images.githubusercontent.com/58678787/72241027-bbb59080-360b-11ea-9fa8-491064b24055.png)

2. Select the user to enable / disable the MFA
![image](https://user-images.githubusercontent.com/58678787/72241148-1818b000-360c-11ea-8e8f-6a375cc3d3ce.png)

3. Under Quick steps > Select Enable or Disable
![image](https://user-images.githubusercontent.com/58678787/72241195-341c5180-360c-11ea-98ff-ebad696bd6d0.png)

**Comment by JamesHeathcote** [comment]
We have 10k users, on the MFA page for azure you can only select users in batches of 20, and there is no logical sort, we have all our invited customers in the list which results in over 10k individuals we have to go through. This is not scalable. As per ragupt's post, the section does not exist to "make sign-in more secure"

**Comment by msbemba** [comment]
@ragupt  and @JamesHeathcote  Thank you for your feedback. As per the Author, this is how the new settings will be looking like and there are chances that some tenants are still seeing it the old way.

https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/890#issuecomment-570688767

Hope this helps!

Thanks
Sri

**Comment by ragupt** [comment]
@msbemba  - Thanks for your message may I know where has this been role out as it is documented at this moment? I purchased 2 new American tenants yesterday and didn't see new behavior as mentioned .. comments please

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this additional feedback?

Thank you.

cc: @kenwith

**Comment by Sirkkuw** [comment]
If you bought a new tenant you should have security defaults turned on automatically, as described in the topic. You can still go to the Azure admin center and turn on MFA on per user basis, but it should not be available from the list of users in the Microsoft admin center. However, it is possible that the changes haven';t rolled out quite to everyone. Please take a look at the set up MFA topic again, it was recently updated for the new UI.

**Comment by mypil** [comment]
@ragupt - From our understanding, the issue you raised has been answered by Sirkkuw & msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
