### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ekamkar** [MicrosoftDocs/OfficeDocs-O365ITPro#919]
There is a typo issue in the first sentence of the "Save you data" segment.
Lose access to your "dat" should be "data".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad7fc1eb-7083-a9b0-b4aa-3eaa5e364fbc
* Version Independent ID: b27630b4-77e6-5493-b5b7-27dc6e143531
* Content: [Cancel your subscription](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/cancel-your-subscription?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/cancel-your-subscription.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/cancel-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@ekamkar - Thank you for pointing this out.

PR #920  has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
