### ISSUE TITLE
Don't close this without fixing the issue like you did with the other guy

### ISSUE THREAD

**Issue by tttomdemaria** [MicrosoftDocs/OfficeDocs-O365ITPro#92]
Step 3 is wrong.  The button does not appear whether the user has a license or not.

The way it can be done is by going to the exchange admin center, clicking "recipients", finding the user, then clicking "Convert" under "Convert to Shared Mailbox"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by dianef77** [comment]
Hey, I just double-checked Step 3 and it's correct.  There must be another reason you aren't seeing the option to convert the user's mailbox to a shared mailbox in the Office admin center, but you can access the functionality in the Exchange admin center.  (Only licensed users appear in the recipients page of Exchange admin center.) Perhaps it's your permissions?  I recommend opening a support ticket to figure out the issue.

**Comment by AndreaBarr** [comment]
@tttomdemaria Based on Diane's response please open a Support ticket. I am going to close this ticket for now but please reopen it once you have an update from Support. Replying to this comment will re-open the ticket.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by dianef77** [comment]
Are you a delegated admin, with full admin rights?  (As opposed to a global admin.)

**Comment by tttomdemaria** [comment]
I'm going to take the hard L on this one.  Can you explain why it's setup
that way?  Wouldn't it make sense for "global" admin to have access to
everything?

**Comment by dianef77** [comment]
Think we had a miscommunication.  I was thinking the reason you're not seeing the option to convert the user mailboxes to shared is because you might be (I was guessing) a delegated full admin, not a global admin.  I've noticed that delegated full admins don't have all the same permissions as the global admin.  The fact that you're experiencing this behavior and you're a global admin is odd.  If you can, shoot me a mail at dianef@microsoft.com with the name of your tenant, and when I meet with the dev later this week we'll look into it.

**Comment by tttomdemaria** [comment]
Yea it's basically the opposite in all the tenants.  Within my company, and 3 others, at the time of sending this reply, where global admin has less access than if I take the admin account and grant it everything with "custom administrator".  I will follow up via email.
