### ISSUE TITLE
Is the link to Microsoft 365 Usage Analytics.pbit still actual

### ISSUE THREAD

**Issue by Kreism** [MicrosoftDocs/OfficeDocs-O365ITPro#924]
We have problems with the actual Microsoft 365 Usage Analytics.pbit file, loading the TenantOfficeLiceses, we always getting the error "the access to the resource is forbidden"
Could you please check if the file is working fine?
Thanks
Martin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f1b4f-6101-2741-32d9-77df46602591
* Version Independent ID: 64c576f5-200a-a702-7662-d66892596c7f
* Content: [Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@Kreism - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
