### ISSUE TITLE
How would one *force* Focused Inbox off for an account?

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/OfficeDocs-O365ITPro#925]
For example, we have shared accounts like conference rooms that must be kept consistent. How would we turn it off and prevent it from being enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83abc4f6-2d5b-1187-eda8-6cf841fe420a
* Version Independent ID: 5df31a0f-5128-140d-2c13-ca9eb0b59b0a
* Content: [Configure Focused Inbox for everyone in your organization](https://docs.microsoft.com/en-us/office365/admin/setup/configure-focused-inbox?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/configure-focused-inbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@ryanhelmer - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
