### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by sth2258** [MicrosoftDocs/OfficeDocs-O365ITPro#927]
This information is extremely outdated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784a196f-3e0e-0c0a-0b2f-af2105a774d9
* Version Independent ID: 08300f82-3b1d-b96d-bf10-e401ac6ef2c0
* Content: [Allow members to send as or send on behalf of a Group](https://docs.microsoft.com/en-us/office365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@sth2258 Thank you for the feedback. This document talks about modifying the permissions via the Exchange admin center. So the instructions are current.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@sth2258 - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
