### ISSUE TITLE
The "Tip" is misinforming the users

### ISSUE THREAD

**Issue by Bogdan-Paun** [MicrosoftDocs/OfficeDocs-O365ITPro#928]
The default password policy for newly created accounts is for the passwords to expire at 90 days with a 14 day notification period.
tested just a few minutes ago by creating a new tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ae0f7d-90b6-8647-8ea5-0a3b15cd1d53
* Version Independent ID: b8c089e1-689e-96a3-f67d-c6031f0fb725
* Content: [Set the password expiration policy for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/set-password-expiration-policy?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Bogdan-Paun Thank you for the feedback. We have made changes to the doc via PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/951

Thanks
Sri

**Comment by mypil** [comment]
@Bogdan-Paun - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/19867c4b33c214986da0157159b7054505c06eed. 


Thank you for your contribution to make the docs better! Much appreciated!
