### ISSUE TITLE
Section: Add the six CNAME records that are required for Office 365

### ISSUE THREAD

**Issue by lewatson** [MicrosoftDocs/OfficeDocs-O365ITPro#929]
As of 2020-01-19, 

a) The instructions indicate there are 6 CNAME records required for Office 365 and only 5 are listed: autodiscover, sip, lyncdiscover, enterpriseregistration, and enterpriseenrollment. What is the sixth CNAME record?

b) For step "5) Select the DNS Traffic icon (orange cloud) to bypass the Cloudflare servers" the desired outcome is unclear. Should the cloud be orange (on) or grey (off)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaff890-3858-eacb-ed21-a7c0dc4d3d36
* Version Independent ID: 087f92d5-6ace-4a32-4252-c94b843de607
* Content: [Create DNS records at Cloudflare for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#add-the-six-cname-records-that-are-required-for-office-365)
* Content Source: [Office365-Admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@lewatson Thank you for the feedback. The Cloud Icon should be grey after you select to bypass.
I have made the correction the number of Cname records required via PR https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/952

Thanks
Sri

**Comment by mypil** [comment]
@lewatson - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/36e59dc2a319fa242bcc49d41effc6f1f1de9276. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by lewatson** [comment]
I believe 6 CNAMES are required. Adding the 5 specified above didn't work for me. I had to add a sixth - 

CNAME msoid clientconfig.microsoftonline-p.net 30 min

**Comment by msbemba** [comment]
@lewatson Thank you for the feedback. This CNmae record is used for direct authentication to the correct identity platform and Makes the auth process faster. If you don't add this record, it should still work as it will use the default authentication endpoint. I Agree with you that this should be added to this list as well. Created PR #https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/978  to add the CName record msoid.

Thanks
Sri
