### ISSUE TITLE
can I use for office 2016x

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-O365ITPro#93]
thanks for the information about Modern authentication setup 

Can I enable second verification setup on windows 10 with office 2016 pro plus 
with above registry keys.
I will replace 15.0 by 16.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db5aea7-bb2e-f349-7518-fc4fd396b3da
* Version Independent ID: b4112301-d38e-4a77-847b-f41bd7bca0f1
* Content: [Enable Modern Authentication for Office 2013 on Windows devices](https://docs.microsoft.com/en-in/office365/admin/security-and-compliance/enable-modern-authentication?redirectSourcePath=%252fen-us%252farticle%252fenable-modern-authentication-for-office-2013-on-windows-devices-7dc1c01a-090f-4971-9677-f1b192d6c910&view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@RAJU2529 Thank you for this inquiry

I am not sure if the above registry keys are good for the 2016 version. Let me get this over to the o365ITPro writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mikenri** [comment]
Office 2016 supports modern authentication by default, no changes are needed to enable it.

**Comment by RAJU2529** [comment]
thanks

**Comment by AndreaBarr** [comment]
@RAJU2529 It looks like Mike answered your question. I am going to close this issue at this time. If your issue is not resolved please re-open this issue.

**Comment by ajhstn** [comment]
@mikenri you say and MS says and the doco says Office2016 is modern auth compliant by default..  I have a fresh Windows 10 1809, installed Office 365 (2016) x64, and it simply will not let me auth.

I have an authentication policy set to block basic auth protocols (new-authenticationpolicy), and i cannot connect..

**Comment by RAJU2529** [comment]
hello mikeni , I think at initial office 365 while installing on windows 10, so that updated office 365 might be update to office365 (2019 )version 
Other users might give good solutions

**Comment by RAJU2529** [comment]
hello mikeni , I think at initial office 365 while installing on windows 10, so that updated office 365 might be update to office365 (2019 )version 
Other users might give good solutions

**Comment by sravankumar1107** [comment]
Hi @Mikenri, I have same issue office 365 office suite got installed on windows 10. Modern authentication is not working . Unable to authenticate with user!!!. Any Directions for this issue resolution is much Appreciable.
