### ISSUE TITLE
Section: Add an MX record so email for your domain will come to Office 365

### ISSUE THREAD

**Issue by lewatson** [MicrosoftDocs/OfficeDocs-O365ITPro#930]
As of 2020-01-19, the MX record values shown on the MX tab on the "Verify your domain" page in my account are different than indicated here:

Points to: msXXXXXXXX.msv1.invalid instead of &lt;domain-key&gt; .mail.protection.outlook.com indicated in the instructions above
Priority: 32767 instead of 1 indicated in the instructions above
TTL: 3600 instead of 30 minutes indicated in the instructions above

What values should I follow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaff890-3858-eacb-ed21-a7c0dc4d3d36
* Version Independent ID: 087f92d5-6ace-4a32-4252-c94b843de607
* Content: [Create DNS records at Cloudflare for Office 365](https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#add-the-six-cname-records-that-are-required-for-office-365)
* Content Source: [Office365-Admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@lewatson Thank you for the feedback. The steps mentioned in the document should be followed after the domain is verified using the TXT record as they are used for email routing and not domain verifying.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@lewatson - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
