### ISSUE TITLE
[LOC] Broken link in several articles

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-O365ITPro#931]
Hello, we found 1 broken link in several articles, could you please check it and update or remove from the articles?

**Broken link:** https://support.office.com/article/a8178510-501d-4bd8-9921-b04f2e9517a5.aspx
**Link Text:** Use a public website with Office 365

**Affected articles:**
 - create-dns-records-at-1-1-internet.md
 - create-dns-records-at-123-reg-co-uk.md
 - create-dns-records-at-aws.md
 - create-dns-records-at-bluehost.md
 - create-dns-records-at-crazy-domains.md
 - create-dns-records-at-dnsmadeeasy.md
 - create-dns-records-at-dyn-com.md
 - create-dns-records-at-enomcentral.md
 - create-dns-records-at-godaddy.md
 - create-dns-records-at-google-domains.md
 - create-dns-records-at-hostgator.md
 - create-dns-records-at-hover.md
 - create-dns-records-at-mydomain.md
 - create-dns-records-at-name-com.md
 - create-dns-records-at-names-co-uk.md
 - create-dns-records-at-network-solutions.md
 - create-dns-records-at-register365.md
 - create-dns-records-at-register-com.md

e.g.
https://docs.microsoft.com/en-us/office365/admin/dns/create-dns-records-at-enomcentral?view=o365-worldwide
![image](https://user-images.githubusercontent.com/47977325/72715177-4b10f580-3b70-11ea-8296-52186afa3e9f.png)

**Comment by mypil** [comment]
@OfficeGlobal - Thank you for pointing this out.

PR #933 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
