### ISSUE TITLE
Manage security defaults section - set Yes or No

### ISSUE THREAD

**Issue by peterwake** [MicrosoftDocs/OfficeDocs-O365ITPro#932]
I think you are missing a step in these docs
Point 3 says On the bottom of the page, choose Manage Security defaults.
But then.. a screen pops up .. do you want to turn this to Yes or No ?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@peterwake at that point, on the page that pops up, turn it to Yes if you want security defaults turned on (in most cases you do).
@mypil  please ask a freelancer add a clarifying step.

**Comment by mypil** [comment]
@msbemba - As discussed, please assist with this issue. Thank you.

**Comment by msbemba** [comment]
@peterwake Thank you for the feedback. We have made changes to the document via PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/957

Thanks
Sri

**Comment by mypil** [comment]
@peterwake - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/a14c019423b0a35a2dbd6e8983dae31f86596515. 


Thank you for your contribution to make the docs better! Much appreciated!
