### ISSUE TITLE
[LOC] Type in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-O365ITPro#935]
Hello there is a typo in an article.

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide
2. Search for "conditonal"

**Actual results:**
conditional is writen as conditonal
**Expected results:**
conditonal should be changed to conditional

**GH article:**
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md
![image](https://user-images.githubusercontent.com/47977325/72789538-40b82f80-3c34-11ea-9ab6-a356a0d5635b.png)

**Comment by mypil** [comment]
@OfficeGlobal -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/1ac8f92029149ab719b0f4b444ffb70e21184f4e#diff-2012347ee26db8e4a848e8d0ef923d17. 


Thank you for your contribution to make the docs better! Much appreciated!
