### ISSUE TITLE
stolen vewiws

### ISSUE THREAD

**Issue by milkyway1** [MicrosoftDocs/OfficeDocs-O365ITPro#936]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db5aea7-bb2e-f349-7518-fc4fd396b3da
* Version Independent ID: b4112301-d38e-4a77-847b-f41bd7bca0f1
* Content: [Enable Modern Authentication for Office 2013 on Windows devices](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by milkyway1** [comment]
prea must turn back to retrospective their is know bailout prea is the door of a lie wharer the meeting is to be split as for currecy now cr criminal guess who almost got robbed for their country well they stole first and I say get a ejecation

**Comment by mypil** [comment]
@milkyway1 - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc? 

We would really appreciate it if you are able to help by providing more details as to what should be edited and/or included.

**Comment by mypil** [comment]
@milkyway1 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page.
