### ISSUE TITLE
you need to provide the link

### ISSUE THREAD

**Issue by jansenbro** [MicrosoftDocs/OfficeDocs-O365ITPro#937]
There is a link .. somthing like aka.etcetc for setting up the MFA  it needs to be posted here for admins to quickly find so they can send to end users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@mypil  please have a freelancer add a section for users - something like "Tell your users how to set up the Authenticator app" and this link
https://support.office.com/article/use-microsoft-authenticator-with-office-365-1412611f-ad8d-43ab-807c-7965e5155411#ID0EAADAAA=_Step_1

**Comment by mypil** [comment]
@msbemba - As discussed, please assist with this issue. Thank you.

**Comment by Darrell-P** [comment]
Direct users to follow the instructions in THIS Microsoft document - https://answers.microsoft.com/en-us/msoffice/forum/all/regenerate-qr-code-for-my-microsoft-authenticator/c9c975da-f8f5-48f5-b403-193fa3d66554

**Comment by msbemba** [comment]
@Darrell-P Thank you for your feedback. This link is about regenerating a code when you have lost access to the existing app. We appreciate your time to help us.

Thanks
Sri

**Comment by Darrell-P** [comment]
You are looking for a link for end-users as to how to download, install, and then scan the QR code?

**Comment by msbemba** [comment]
@Darrell-P  Thank you for the feedback. The addition will reflect steps that a user can take to install the Authenticator App. Once the PR is approved, You will see the changes in doc.

Thanks
Sri

**Comment by mypil** [comment]
@jansenbro  - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/a14c019423b0a35a2dbd6e8983dae31f86596515. 


Thank you for your contribution to make the docs better! Much appreciated!
