### ISSUE TITLE
User management administrator can adds, removes, and updates license assignments for users, groups as same as License administrator.

### ISSUE THREAD

**Issue by M365SupportJapan** [MicrosoftDocs/OfficeDocs-O365ITPro#94]
The User management administrator can adds, removes, and updates license assignments for users, groups as same as the License administrator in addition to resets passwords, monitors service health, adds and deletes user accounts, manages support tickets, adds and removes members from Office 365 groups. Please consider to add this behavior on this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e45a4-3d00-c650-c40f-3a10b457cf46
* Version Independent ID: fefa373f-f380-8988-e58a-73e9255134bb
* Content: [About Office 365 admin roles](https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?redirectSourcePath=%252fja-jp%252farticle%252fda585eea-f576-4f55-a1e0-87090b6aaa9d%2525E2%252580%25258B&view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@M365SupportJapan Thank you for this feedback

I will get this suggestion and information over to the o365ITPro team for investigation.

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@sonika24 Could you please investigate this issue?

**Comment by mypil** [comment]
@M365SupportJapan - From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by M365SupportJapan** [comment]
Thanks Andrea.
What I wanted to ask to add a description was User management admin have the ability to add, remove, update license assignments for users and groups which is for license admin or GA/CA. Would you please review this again?

**Comment by mypil** [comment]
@Jcoetsee - Please assist to review and make the necessary changes on this. Thank you.

**Comment by mypil** [comment]
@dianef77 - we need your insights on the request to add more information specific to the description of the User management admin as indicated on the above comment. Can we add this description to the article?

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this and get your insights on the request to add more information specific to the description of the User management admin as indicated on the above comment. Can we add this description to the article?

**Comment by dianef77** [comment]
Yes, that's fine.  Just please ensure it's in grammatically correct English.  Thanks.

**Comment by mypil** [comment]
@dianef77 - thanks for your response. @Jcoetsee - Please create a PR for the change and please ensure it's in grammatically correct English. Thank you.

**Comment by mypil** [comment]
@M365SupportJapan - the content has been updated to add the description that you requested for. Kindly check and let us know if your issue has been resolved. Thanks.

**Comment by M365SupportJapan** [comment]
Hi Team,

Confirmed that my requested information was added on the article.
Thank you all for taking care of my feedback!

Thank you!
