### ISSUE TITLE
Very misleading regarding PBI licensing

### ISSUE THREAD

**Issue by crshovrd41** [MicrosoftDocs/OfficeDocs-O365ITPro#940]
You don't state anywhere on this page that to actually view the data you must upgrade your license to pro or you can "try free for 60 days." Please fix the article so other people don't make the same mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec8961e-4fc1-eb46-1e71-3147b55ac90e
* Version Independent ID: 2c66ebfb-53b5-18ab-e560-702d4cae057f
* Content: [Enable Microsoft 365 usage analytics](https://docs.microsoft.com/en-us/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by raymondlittle100** [comment]
I found this very confusing as well. On the page linked below it says you can use the free licence

https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide

"The content pack is available to all customers free of charge. You need to sign up for the free Power BI service to connect to the content pack. You can also customize the dashboards and reports with the free Power BI service.

To share the dashboards with others, both the user who is sharing and the user the dashboard is shared with must have Power BI Pro or Power BI Premium."

**Comment by haider392** [comment]
Yes, the app is free of charge but the user still needs to have a paid Power BI pro license. The current wordings lead the customers to believe that the app is entirely free of charge and can be installed if users have Power BI free license.

**Comment by pgans-les** [comment]
This makes no sense. From a licensing side, Power BI Pro is all about the ability to share data within organizations. This artificial need for a Pro license is ridiculous for this dashboard.

**Comment by haider392** [comment]
Im from support. No point telling that to me. Please pass this feedback to the folks who made this requirement into the design.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by crshovrd41** [comment]
Thanks. So, does that mean someone will adjust the wording to make it clear you need PBI Pro to make this useful? That's all that really matters here. Microsoft can arbitrarily make any changes they want with licensing, as long as it's clearly outlined.

Thanks!

**Comment by Sirkkuw** [comment]
I am following up with PG.

**Comment by Sirkkuw** [comment]
I have updated the docs to specify that Power BI Pro license is needed
