### ISSUE TITLE
Why must every customer have to google for the licensing requirements himself?

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/OfficeDocs-O365ITPro#941]
I'm sorry, but it's really a shame that the Important licensing requirements Block does not offer a Link to the Licensing details.

Are you afraid that this Microsoft could get invalid after some weeks? Then a free tip: simply define logical, static links. Here it is: 
www.M$.com/licencing/O365/Office-365-Groups
This link could stay forever and always display the latest content, maybe with links to the older releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b2aa17-cc9e-7fe4-f2fc-a5dd24e6936e
* Version Independent ID: 7c63cc46-1d04-27a8-7e71-c1b93642b5ab
* Content: [Overview of Office 365 Groups for administrators](https://docs.microsoft.com/en-us/office365/admin/create-groups/office-365-groups?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **v-teflor**

**Comment by mypil** [comment]
@schittli - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/48e9d24d116dc4230f14d0ddfd09cbeb173bab00. 


Thank you for your contribution to make the docs better! Much appreciated!
