### ISSUE TITLE
Which admin permissions?

### ISSUE THREAD

**Issue by ChrispyBites** [MicrosoftDocs/OfficeDocs-O365ITPro#943]
Please be specific about the admin privileges that are needed to perform this action on the M365 Admin Center.  You just say "You must have admin permissions in Office 365 to do these steps," but not every administrator role has the rights to perform this action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8183c4-8fef-2e30-b84d-ad48d7a5278b
* Version Independent ID: f29c45cf-0d0c-a30b-c8c7-58abd4e7e3d4
* Content: [Configure email forwarding in Office 365](https://docs.microsoft.com/en-us/office365/admin/email/configure-email-forwarding?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by robertgreeneahp** [comment]
I second this.  We are facing this issue now where our help desk doesn't have the proper permission to perform this option.  So what user role is needed to do this?

**Comment by msbemba** [comment]
@ChrispyBites Thank you for the feedback. You need to be a Global Admin or an exchange admin to perform this action. We have made changes to the doc via PR #
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/953

Thanks
Sri

**Comment by mypil** [comment]
@ChrispyBites - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/8b27ebe9e665f616e1f84b0a4b85608810ff2763. 


Thank you for your contribution to make the docs better! Much appreciated!
