### ISSUE TITLE
Information is wrong, maybe?

### ISSUE THREAD

**Issue by brakim** [MicrosoftDocs/OfficeDocs-O365ITPro#944]
I have a couple of Microsoft 365 Business subscriptions and i don't have access to company branding,  is says i need to upgrade my AAD to premium. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1e37fbb-0bb1-7c14-fda3-376ed667834a
* Version Independent ID: 44237e1d-1792-2073-9d9a-0905a9e2c555
* Content: [Add your company branding to Office 365 Sign In page](https://docs.microsoft.com/en-us/office365/admin/setup/customize-sign-in-page?view=o365-worldwide)
* Content Source: [Office365-Admin/setup/customize-sign-in-page.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/customize-sign-in-page.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@brakim - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
