### ISSUE TITLE
Recycle bin

### ISSUE THREAD

**Issue by RichardFransen** [MicrosoftDocs/OfficeDocs-O365ITPro#946]
Are the number of files (and the related amount of storage) in the RECYCLE BIN taken into account when calculating the number of FILES and STORAGE USED in the ODB Usage Report?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59b9dada-0658-e34b-fba2-568d1322b947
* Version Independent ID: 4561d278-79c0-517f-fb7e-de94474cc3f3
* Content: [Office 365 Reports in the admin center - OneDrive for Business usage](https://docs.microsoft.com/en-us/office365/admin/activity-reports/onedrive-for-business-usage?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/onedrive-for-business-usage.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/onedrive-for-business-usage.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@RichardFransen Thank you for the feedback. The one drive storage size shown on the report includes the data deleted/in the recycle bin.

Hope this helps!
Thanks
Sri

**Comment by mypil** [comment]
@RichardFransen  - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
