### ISSUE TITLE
Requesting for elaboration on some terms

### ISSUE THREAD

**Issue by isaacgandalf** [MicrosoftDocs/OfficeDocs-O365ITPro#949]
"Billing Period is the time period since the last invoice date. Service Period is the time period during which you are charged to use the service."

Most of the time, we here are support get asked why the billing period is almost always behind (in dates) for the service period.
For instance, in annual invoices, one sees a Billing Period of Jan 2019 to Jan 2020, with an invoice date somewhere in Jan 2020.
The invoice would show a service date of Jan 2020 to Jan 2021.

It's a bit confusing because, why would a Billing cycle of 2019 to 2020 be showing on an invoice that's for 2020 to 2021 (annual payment)

Please help clarify this confusing concept, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07447e32-a5e3-c1ab-4b2e-9d9f22c6347e
* Version Independent ID: fb661e27-a1df-1c37-7e30-1f765633fa7c
* Content: [Understand your invoice for Office 365 for business](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/understand-your-invoice?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/subscriptions-and-billing/understand-your-invoice.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/understand-your-invoice.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@isaacgandalf Thank you for the feedback. The annual payment in your case is paid upfront and the service period is the time during which you are charged to use the service. The billing period is the time since the last invoice date. 
So for example, if the invoice date is Jan 21 2020  It will show a service period of Jan2020 to Jan2021 (Customer is paying upfront) and the billing period would be 2019-2020 as the last invoice was in 2019.

Hope this helps!

Thanks
Sri

**Comment by isaacgandalf** [comment]
@msbemba Thanks Sri,
So, in the screenshots shown on the article, the billing period shows as 02/24/2016 - 02/24/2016. Does this mean that there was no invoice-paid subscription prior to that one (this is a new subscription)? It's still a bit confusing, but at least I know now. Thanks!

**Comment by msbemba** [comment]
@isaacgandalf  That is correct. it is a New subscription and paid monthly. 

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@isaacgandalf - From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
