### ISSUE TITLE
Clarity on data retention in OneDrive for Business needed

### ISSUE THREAD

**Issue by AnatolN** [MicrosoftDocs/OfficeDocs-O365ITPro#954]
In this article we have this part referring to ODB data retention:
"When a license is removed from a user, data that is associated with that account is held for 30 days. After the 30-day grace period, the data is deleted and can't be recovered. Files that are saved in OneDrive or SharePoint Online aren't deleted."
It gives incomplete information as it does tell the files will not be deleted but does not state for how long. Maybe adding the reference to another article for details (like this one: https://docs.microsoft.com/en-us/onedrive/retention-and-deletion), could avoid the confusion.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fc9456-b067-ef65-4bd9-983672322871
* Version Independent ID: 12567ff7-4d96-9152-77b6-ff8f53c21f1d
* Content: [Unassign licenses from users](https://docs.microsoft.com/en-gb/office365/admin/manage/remove-licenses-from-users?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/remove-licenses-from-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/remove-licenses-from-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@AnatolN Thank you for the feedback. The reference of 30 days is w.r.t to the mailbox. I have added clarity to the doc via PR #https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/966

Thank you for bringing this up.

Thanks
Sri

**Comment by mypil** [comment]
@AnatolN - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/56b38ac8bbb37ec099bbf621b5733029c21a9c1f. 


Thank you for your contribution to make the docs better! Much appreciated!
