### ISSUE TITLE
"Optional Connected Experiences" is mandatory for this in Windows Outlook

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/OfficeDocs-O365ITPro#958]
Hello,
I don't see this documented anywhere, maybe you can provide an article. We had a user that could not load any Office Windows Outlook add-ins. After days of troubleshooting we determined that they have disabled "Enable Optional Connections" then Windows Outlook Add-ins will not work.

What's weird about this is that the Add-ins still loaded in Mac Outlook and OWA without any issue. This is a bang your head against the wall type issue. Be consistent with the permissions and document it properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d424b-6f62-e70c-9c2d-ad779ffa6c3b
* Version Independent ID: e4597136-bfe8-4230-da83-f806a1126005
* Content: [Manage deployment of Office 365 add-ins in the admin center](https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by afield1235** [comment]
![image001](https://user-images.githubusercontent.com/18271134/73380691-556e7600-4279-11ea-9cad-ab9f8b1fe57e.png)

**Comment by MaratMussabekov** [comment]
Hello,
**I don't see this documented anywhere, maybe you can provide an article. We had a user that could not load any Office Windows Outlook add-ins. After days of troubleshooting we determined that they have disabled "Enable Optional Connections" then Windows Outlook Add-ins will not work.** - "optional connected experiences" feature is described in [this article](https://docs.microsoft.com/deployoffice/privacy/optional-connected-experiences)

**What's weird about this is that the Add-ins still loaded in Mac Outlook and OWA without any issue** - Are you sure that optional connected experiences feature was disabled in Outlook for Mac? (for example, as described [here](https://docs.microsoft.com/deployoffice/privacy/mac-privacy-preferences#preference-setting-for-optional-connected-experiences)). If it was properly disabled and add-ins were still available for client, please contact [support](https://support.office.com/).
As for problem with OWA, optional connected experiences feature is not applicable for any web-based product, it is applicable for Office 365 ProPlus applications only.

Thank you

**Comment by mypil** [comment]
@afield1235 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
