### ISSUE TITLE
Microsoft 365 Usage Analytics App needs a Power BI Pro license and is not entirely free to use

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/OfficeDocs-O365ITPro#959]
Microsoft 365 Usage Analytics App needs a user to have a Power BI Pro license to install it. In the doc, it is incorrectly mentioned that this app is free of charge and user only needs to sign up for the free Power BI service which is misleading and not accurate. 

Yes, it is free of charge but only if the user has a Power BI pro license which is a paid license.

The wordings in the documentation leads to customer believing that they don't even have to pay for a Power BI Pro license (paid) and they can use the app with a Power BI free license.

Places where this needs to be corrected
1. https://docs.microsoft.com/en-us/office365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide#get-power-bi
2. https://docs.microsoft.com/en-us/office365/admin/usage-analytics/usage-analytics?view=o365-worldwide#is-this-content-pack-going-to-be-available-through-purchase-or-will-it-be-free

**Comment by msbemba** [comment]
@haider392  Thank you for your feedback. I'm checking this with the author and will update you ASAP.

Thanks
Sri

**Comment by Sirkkuw** [comment]
@haider392  I am checking with the product group.

**Comment by Sirkkuw** [comment]
@haider392 pinged PG again. Hope to hear by tomorrow.

**Comment by Sirkkuw** [comment]
@haider392 I have made this change, In the master branch now but should be live by tonight.

**Comment by haider392** [comment]
Sure, thanks!

-Haider
