### ISSUE TITLE
Credit Card Updates

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/OfficeDocs-O365ITPro#96]
This article does not mention anything about how a credit card must match the tenant's origin. For instance, you cannot use a UK credit card to pay on a US tenant. We do have a lot of customers that ask us about this because when updating a credit card, if the bank is not in the same country as the origin country of the tenant, they cannot update payment details. Please add this information on this document and on Change Payment Method document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bdbb534-fd78-a4d0-dac4-b9a3ce1179fe
* Version Independent ID: 134d6149-7c7d-3cd8-4842-47287bdd158f
* Content: [Add, update, or remove a credit card or bank account](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/add-update-or-remove-credit-card-or-bank-account?view=o365-worldwide)
* Content Source: [Office365-Admin/subscriptions-and-billing/add-update-or-remove-credit-card-or-bank-account.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/subscriptions-and-billing/add-update-or-remove-credit-card-or-bank-account.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by AndreaBarr** [comment]
@sonika24 Could you please look into this issue?

**Comment by Barbara232** [comment]
Microsoft needs to address this issue immediately. There is no reason why global companies, like mine, need to pay for the account with a credit card issued from the same country. Surely MS knows about tax transfers and the banks already know how to adjust payment to allow for currency conversions. No business -- *no business* -- demands payment with a credit card that is issued in the same country where the account is set up.  Let me put it to you this way MS, is it better to have a staffer pay for the account simply because it adheres to your rules, or wouldn't you prefer someone who has a bit stronger ties to the company?

**Comment by labanex** [comment]
> Microsoft needs to address this issue immediately. There is no reason why global companies, like mine, need to pay for the account with a credit card issued from the same country. Surely MS knows about tax transfers and the banks already know how to adjust payment to allow for currency conversions. No business -- _no business_ -- demands payment with a credit card that is issued in the same country where the account is set up. Let me put it to you this way MS, is it better to have a staffer pay for the account simply because it adheres to your rules, or wouldn't you prefer someone who has a bit stronger ties to the company?

Here is the reason. There are strong regulations and rules that govern each country. Tax, compliances, etc. Germany, Australia, and China are good examples. They have the most different rules than most countries. To circumvent the different tax laws, you would want the headquarters of an international company to begin the account and pay with that country's credit card. Therefore, the tax is relied on that country. There are other rules and compliances to be considered which is the reason it is locked down to that country. If I pay for US account with a UK credit card, that US tax cannot go to the US because it is banked in the UK. Even if I was a US corporation. There more to it than you think and Microsoft is only following the rules set forth. Not all rules are the same for each country. To keep it safe, they laid out the rules the same for each country.

**Comment by Barbara232** [comment]
That is exactly the point of tax transfers -- companies have tax experts
look at where items (or goods or services) are manufactured or used and
make tax-based comparisons across the company to arrive at the most
favorable tax situation for the company. MS is simply taking the most
ultra-conservative position on this issue, and as a consequence exposing
the fact that they aren't really interested in a startup or small
business.  Further, should I choose to move my HQ, and want to have my MS
account match the HQ country -- I can't do that.  There's no mechanism in
place for MS to move all the emails, Sharepoint files, Teams, etc.* even
though it's the same company and all that's changed is the billing. *

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
