### ISSUE TITLE
... install the Authenticator app on their mobile device.

### ISSUE THREAD

**Issue by UNLIMTD** [MicrosoftDocs/OfficeDocs-O365ITPro#960]
Is this referring to the Microsoft Authenticator App, or does O365 have its own?

https://www.microsoft.com/en-us/account/authenticator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed95865-eddb-4ad1-d2e2-5bd618151c1b
* Version Independent ID: ef32bb26-e78a-caad-5b41-d7e49f6ef9b4
* Content: [Set up multi-factor authentication for Office 365 users](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@UNLIMTD Thank you for the feedback. You are correct, The reference to the authenticator app in this document is the Microsoft authenticator App available via https://www.microsoft.com/en-us/account/authenticator.

Thanks
Sri

**Comment by mypil** [comment]
@UNLIMTD - Thank you for submitting feedback.

From our understanding, the issue has been answered by msbemba so we will close this issue.

Thank you for engaging with the community here for the docs.
