### ISSUE TITLE
Step 1

### ISSUE THREAD

**Issue by Weychris** [MicrosoftDocs/OfficeDocs-O365ITPro#961]
The steps in step 1 are no longer valid. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0759f6b0-4d12-e0fa-f1cf-320f4e4ae32a
* Version Independent ID: 5b10ae00-e088-b39d-e13f-ead4081f2784
* Content: [Top 10 ways to secure Office 365 and Microsoft 365 Business plans](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#setup)
* Content Source: [Office365-Admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@Weychris  Thank you for your feedback. We have updated the document via PR #https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/987 and PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/988

Thanks
Sri

**Comment by mypil** [comment]
@Weychris - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/8e38c89b71b9f7f340f53b99c9ec650ffb682776. 


Thank you for your contribution to make the docs better! Much appreciated!
