### ISSUE TITLE
Please Update the "Can I add custom subdomains or multiple domains to Office 365?" section

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-O365ITPro#962]
It appears possible to add sub domains of a parent domain to a separate O365 tenant when an org is managing their own DNS. 

Example: 
Tenant 1 owns contoso.com
Tenant 2 can have abc.contoso.com as an accepted domain

Can you please confirm and update this documentation as a authoritative reference? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc99803-4432-cd7c-4747-0953276298d9
* Version Independent ID: 1d7554f1-8b1c-dd3a-18e6-1106ad2b3bcb
* Content: [Domains FAQ](https://docs.microsoft.com/en-us/office365/admin/setup/domains-faq?redirectSourcePath=%252fen-us%252farticle%252fCan-I-add-custom-subdomains-or-multiple-domains-to-Office-365-5481401f-7771-490e-b728-b3a81305a32e&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@jebalert Thank you for your feedback. We have added a note to the document via PR # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/967

Thanks
Sri

**Comment by jebalert** [comment]
Please add comments to the section around adding sub domains to other office 365 subscriptions, commonly referred to as tenants

**Comment by msbemba** [comment]
@jebalert  That is where the note is added. Thank you.

**Comment by mypil** [comment]
@jebalert - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/cc694dc753736701dcdfeab9318a56cec1d48b84. 


Thank you for your contribution to make the docs better! Much appreciated!
