### ISSUE TITLE
6: Stop auto-forwarding for email

### ISSUE THREAD

**Issue by dougbrewer501** [MicrosoftDocs/OfficeDocs-O365ITPro#964]
Instructions located at https://support.office.com/en-us/article/stop-auto-forwarding-emails-in-microsoft-365-f9d693ba-5c78-47c0-b156-8e461e062aa7#ID0EAABAAA=Try_it!

This does not work for when users set Auto Forwarding in OWA which sets the ForwardingSmtpAddress attribute on their mailbox as described at https://support.office.com/en-us/article/forward-email-from-office-365-to-another-email-account-1ed4ee1e-74f8-4f53-a174-86b748ff6a0e

I have tested this and emails are still being forwarded. Apparently this only works for when a user creates a inbox rule to Forward email. After doing some research it appears that when Forwarding is set as described in https://support.office.com/en-us/article/forward-email-from-office-365-to-another-email-account-1ed4ee1e-74f8-4f53-a174-86b748ff6a0e this is actually considered a ReDirect not an Auto-Forward so the mail flow rule does not fire thus allowing the email to be forwarded.

**Comment by mypil** [comment]
@dougbrewer501 - There are several MS docs that you mentioned in your comment. May we know which specific Microsoft document link you used in reference to this issue? 

We would really appreciate it if you are able to help by providing more details as to what should be edited and/or included on the doc. Thank you.

**Comment by dougbrewer501** [comment]
@mypil - The problem is this article is 'mis-leading' 

**The below MS Doc shows how to set forwarding in OWA**
https://support.office.com/en-us/article/forward-email-from-office-365-to-another-email-account-1ed4ee1e-74f8-4f53-a174-86b748ff6a0e

**MS Doc below shows how to block above said forwarding**
https://support.office.com/en-us/article/stop-auto-forwarding-emails-in-microsoft-365-f9d693ba-5c78-47c0-b156-8e461e062aa7#ID0EAABAAA=Try_it!

If a hacker gets control of a users mailbox account and sets the forwarding address to an external address such as yahoo.com the instructions in the 2nd article above doesn't stop it. 

From what I have been able to find out when a person sets the auto-forwarding (as described in the 1st article above) this is considered a redirect so the Mail Flow rule described in the 2nd article doesn't catch it. 

It's really confusing and I wish I had more information to share but I don't at this time. An O365 engineer could probably explain it better.

**Comment by mypil** [comment]
@dougbrewer501 - Thank you for submitting feedback.

The two articles that you mentioned in this issue are for different topics and have their own purpose. The [Forward email from Office 365 to another email account](https://support.office.com/article/forward-email-from-office-365-to-another-email-account-1ed4ee1e-74f8-4f53-a174-86b748ff6a0e) topic just gives instructions on how to forward emails from O365 to another email account.

On the other hand, the other article talks about creating a mail flow rule to [Stop auto-forwarding emails](https://support.office.com/article/stop-auto-forwarding-emails-in-microsoft-365-f9d693ba-5c78-47c0-b156-8e461e062aa7#ID0EAABAAA=Try_it) as a precautionary security measure. For more information on the best practices that Microsoft recommends, please refer to the [Top 10 ways to secure Office 365 and Microsoft 365 Business plans](https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide).

I hope this explanation will help clarify and address your issue. 


Thank you for your contribution to make the docs better! Much appreciated!
