### ISSUE TITLE
Please List Necessary Roles

### ISSUE THREAD

**Issue by xcactusx** [MicrosoftDocs/OfficeDocs-O365ITPro#965]
Please document what roles are required.  We are trying to implement PIM in our environment.  It would appear that Global Admin is necessary to in order access former employee's onedrive.  We've tried user admin, exchange admin, and sharepoint admin.  None of these roles allow access to this link.  If this is inaccurate, please tell us what level should be necessary.  If it is accurate, can someone speak to why there isn't a OneDrive Management role or why Sharepoint Manager does't allow access.  We should need to check out and have someone approve global admin role, just to give a manager access to an ex employee's onedrive.  That's a lot of permissions, for such a small task. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5756315-8321-0d88-846a-f6f31d8018cb
* Version Independent ID: 7e55c5a1-7ae8-ba3e-cd8b-eae7a4ba2113
* Content: [Get access to and back up a former user's data](https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@xcactusx Thank you for the feedback. Unfortunately, there is no one drive management role yet.
To access users (personal site) one drive one has to be a global admin or a SharePoint admin. A SharePoint admin can add the himself or the other user/manager as a site collection admin and perform the task of delegation. (Sharepoint admin center and Manage user profiles)

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@xcactusx  - Thank you for submitting feedback.

From our understanding, the issue has been answered by msbemba so we will close this issue.

Thank you for engaging with the community here for the docs.
