### ISSUE TITLE
admin permissions

### ISSUE THREAD

**Issue by HoCGeek** [MicrosoftDocs/OfficeDocs-O365ITPro#968]
The article states "The Admin tile appears only to people who have Office 365 admin permissions.".  Can you be more prescriptive about exactly which "admin permissions" are required?  The linked article about admin permissions recommends using the least privilege model, but your document doesn't detail what the least privileges are to access the page in question.  Please provide more detail.

Thanks,

Dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58cf5ff2-8d04-84b0-8458-2e869581aa21
* Version Independent ID: 3f3ea0ab-c3be-8a7d-c0c7-b4b8088209bd
* Content: [About the Microsoft 365 admin center](https://docs.microsoft.com/en-us/office365/admin/admin-overview/about-the-admin-center?view=o365-worldwide)
* Content Source: [Office365-Admin/admin-overview/about-the-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/admin-overview/about-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by HoCGeek** [comment]
Is the "Reports Reader" role sufficient to get access to the Service Health page (https://admin.microsoft.com/Adminportal/Home#/servicehealth) of teh O365 ADmin Portal?

**Comment by MaratMussabekov** [comment]
Hello @HoCGeek,
**Can you be more prescriptive about exactly which "admin permissions" are required?** - any admin permission allows to access the page. Available menus depend on the permissions that admin has.
 **your document doesn't detail what the least privileges are to access the page in question** - there is no any "least privilege" here, page is accessible for anyone with any admin permission.
**Is the "Reports Reader" role sufficient to get access to the Service Health page of teh O365 ADmin Portal?** - no, it is not, more details are [here](https://docs.microsoft.com/office365/admin/add-users/about-admin-roles). For example, if reports reader login to admin portal, they will see following menus
![image](https://user-images.githubusercontent.com/48041687/74328682-2a733e80-4db0-11ea-88fc-b5b33a5f78d0.png)

Thank you

**Comment by HoCGeek** [comment]
Thanks for the update, but I feel there is still some clarity missing.  You say that “any admin permission allows access to the page”, but there’s no consistent definition, as far as I know, of what constitutes an admin permission.  You follow that up with a statement that “Reports Reader” is not sufficient, but on the page you link to “Reports Reader” is listed under “all roles”.  I was going to ask if “admin roles” included only roles with “administrator” in their name, but “Global Reader is listed as an admin role on the same page…

Can you provide a definition or listing of what constitutes an “admin role”

Thanks again,

Dan

**Comment by MaratMussabekov** [comment]
Hello, yes, that could be confusing, as in the article there are two tables "admin roles" and "all roles".
It is incorrect, as ALL the roles (from both tables) are admin roles and they all have access to admin center.
I will create a PR to make it clearer
Thank you

**Comment by mypil** [comment]
@HoCGeek - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/3188c9f9257fac4db7e67bd41592973702084337. 


Thank you for your contribution to make the docs better! Much appreciated!
