### ISSUE TITLE
What does the setting apply to?

### ISSUE THREAD

**Issue by Brian-T8** [MicrosoftDocs/OfficeDocs-O365ITPro#969]
Hi, it is not 100% clear for me if this setting standard or targeted release will only apply to new features being released in the tenant, so office 365, exchange and SharePoint cloud apps and settings, or, also to for example new features in the office proplus desktop client? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046ce912-1f0f-81b9-1126-5558e93df52a
* Version Independent ID: 755e811c-2aa0-9dc5-6846-93a6c401b01e
* Content: [Set up the Standard or Targeted release options in Office 365](https://docs.microsoft.com/en-us/office365/admin/manage/release-options-in-office-365?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by MaratMussabekov** [comment]
Hello @Brian-T8,
Targeted release will provide new features for cloud services, not for office proplus desktop client.
To get early access to Microsoft Office  features, you need to join [Office Insider](https://insider.office.com/business) program
It also mentioned on the bottom of the article, in the "Get the Targeted release version of Office" section.
Thank you

**Comment by Brian-T8** [comment]
Thanks a lot for your confirmation!

**Comment by mypil** [comment]
@Brian-T8  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
