### ISSUE TITLE
Hybrid information is inaccurate

### ISSUE THREAD

**Issue by dcodding** [MicrosoftDocs/OfficeDocs-O365ITPro#97]
We have a hybrid deployment and migrate all email accounts to Office 365 after AD creation.  This article says to convert the user mailbox to a shared mailbox on-premises and then move to Office 365.  However, the on-premises EAC (Exchange 2013) does not have the option to convert to shared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fb81a0-5744-18b2-1636-a41c771ef0db
* Version Independent ID: fad4cd45-1a93-bfee-e82b-892752317056
* Content: [Convert a user mailbox to a shared mailbox](https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@dcodding Did JBerglundAW resolve your issue?

**Comment by mypil** [comment]
Hi @dcodding - we would like to follow up on this. Did JBerglundAW resolve your issue?

**Comment by mypil** [comment]
@dcodding - Thank you for submitting this Feedback.

From my understanding the issue has been resolved. If the issue is not resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
