### ISSUE TITLE
office 365 group primary domain

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-O365ITPro#970]
Office 365 group primary domain is not selectable via the Office 365 group wizard. This feature would be make it even better 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36ccf55-c8e6-e4a2-c99d-1feeb9e0b7ca
* Version Independent ID: 24e94600-1f0d-9d8b-abae-73690a4a633d
* Content: [Create an Office 365 group in the admin center](https://docs.microsoft.com/en-GB/office365/admin/create-groups/create-groups?WT.mc_id=365AdminCSH&view=o365-worldwide)
* Content Source: [Office365-Admin/create-groups/create-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/create-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@SvenBell - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make Office 365. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
