### ISSUE TITLE
Have intune, but this feature still lights up

### ISSUE THREAD

**Issue by rmanjoney** [MicrosoftDocs/OfficeDocs-O365ITPro#973]
The documentation states: "Your organization will have access to this setting unless you're using Microsoft Intune or you've configured mobile device management settings in the Exchange admin center."

We're using both Intune and MDM, and this feature is lit up and available as a setting in the Admin portal in spite of this. It doesn't appear to have any material impact, however, but it's resulted in confusion for admins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eef2271-943b-766e-c143-3ebcaa8e8f1f
* Version Independent ID: 3a9bf23f-b310-eb7e-6ae4-bbb55b3f325b
* Content: [Manage email app access in Microsoft 365 admin center](https://docs.microsoft.com/en-US/office365/admin/email/manage-email-app-access?WT.mc_id=365AdminCSH&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/email/manage-email-app-access.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/manage-email-app-access.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@rmanjoney - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
