### ISSUE TITLE
Assigning licenses to Guests needs clarity

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/OfficeDocs-O365ITPro#975]
Suggest clarifying particulars with  Assigning licenses to Guests users:
You cannot assign licenses on the Licenses page when not using the new Microsoft 365 admin center.
You can only assign licenses on the Licenses page when using the new Microsoft 365 admin center.
Assigning a license to a Guest user for the first time, from the Licenses page, when using the new Microsoft 365 admin center will return an error and automatically set 'Usage Location' to 'United States' (because Guest user accounts do not have a Usage Location by default!)
You cannot assign licenses to Guest Users in the Active users page, whether using the new Microsoft 365 admin center or old. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8703e584-d768-1d04-643c-069b50d69b79
* Version Independent ID: 13c9c0da-4551-6ff3-1cee-e489c8fed0c3
* Content: [Assign licenses to users](https://docs.microsoft.com/en-us/office365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-licenses-to-users-on-the-licenses-page)
* Content Source: [Office365-Admin/manage/assign-licenses-to-users.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/manage/assign-licenses-to-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jadesolis  Thank you for the feedback. We have modified the document to include steps to assign the license to guest users PR# https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/992

Thanks
Sri

**Comment by mypil** [comment]
@cmcatee-MSFT - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by cmcatee-MSFT** [comment]
@mypil - This is under investigation. I'll update it after I get a response from the product group.

**Comment by cmcatee-MSFT** [comment]
@jadesolis I was finally able to get a response from the product group about this. I have added a new section for [Assign a license to a guest user](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-a-license-to-a-guest-user). Thanks for your suggestion!
