### ISSUE TITLE
What about the first Page

### ISSUE THREAD

**Issue by timocarp** [MicrosoftDocs/OfficeDocs-O365ITPro#976]
This article is a bit deceiving. This is the Password entry page modification.. How do you modify the page where the user puts in their email address/username?

**Comment by mypil** [comment]
@timocarp - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by timocarp** [comment]
@mypil 
https://docs.microsoft.com/en-us/office365/admin/setup/customize-sign-in-page?view=o365-worldwide

**Comment by mypil** [comment]
@timocarp - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
