### ISSUE TITLE
This is article and other not working with Hybrid configuration AD and AD Azure. Every time, when I read this fake. I have problem with update user alias on Hybrid AD configuration. Why you on information on first line? It's working only for Azure AD 

### ISSUE THREAD

**Issue by OlegKP** [MicrosoftDocs/OfficeDocs-O365ITPro#977]
This is article and other not working with Hybrid configuration AD and AD Azure. Every time, when I read this fake. I have problem with update user alias on Hybrid AD configuration. Why you on information on first line? It's working only for Azure AD 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50963b73-8563-f99a-72f7-bf4037965cde
* Version Independent ID: 5daa29ed-8092-3a79-c011-8bcbe0225b2c
* Content: [Add another email alias for a user](https://docs.microsoft.com/en-us/office365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [Office365-Admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@OlegKP THank you for your feedback. This document pertains only to O365 cloud-only customers. if you are trying to change the proxy addresses on-prem, you can follow https://support.microsoft.com/en-in/help/3190357/how-the-proxyaddresses-attribute-is-populated-in-azure-ad

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@OlegKP - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
