### ISSUE TITLE
Dates are incorrect for Pending Users

### ISSUE THREAD

**Issue by Maher256** [MicrosoftDocs/OfficeDocs-O365ITPro#979]
On this page: https://docs.microsoft.com/en-us/yammer/manage-yammer-users/add-block-or-remove-users, the statement "As of August 2019, new users added into Yammer will be added into the active user state." is incorrect. This change still has not been rolled out to Standard Release tenants.

**Comment by mypil** [comment]
@Maher256 - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TeresaFG-writer - Can you please share your insights on this issue?


Thank you.

cc: @kenwith

**Comment by TeresaFG-writer** [comment]
As part of this Pull Request (https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro-pr/pull/1253), I removed the following content: "As of August 2019, new users added into Yammer will be added into the active user state. In the coming months, existing pending users will be converted into active users." This change has been merged into Master and am just waiting for the regularly scheduled publishing cycle to pick it up and make it public.

**Comment by mypil** [comment]
@Maher256 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by TeresaFG-writer so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
