### ISSUE TITLE
OneDrive - Steps to Assign To Another User

### ISSUE THREAD

**Issue by dawander** [MicrosoftDocs/OfficeDocs-O365ITPro#981]
It would be great if you could provide more detail on the process.  When an employee leaves, it's very easy to make their mailbox a shared mailbox and assign to another user for review.  It would be great to understand the steps for assigning someone's one drive to another user as well as explain how said user would access the files.  I guess this would also apply to team sites where the employee was the owner.  Thank you.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6024c6e-1373-58de-ca8b-819a11693968
* Version Independent ID: 5d02bdc8-6e20-8b9b-942e-cca0e312cc5e
* Content: [Remove a former employee from Office 365](https://docs.microsoft.com/en-gb/office365/admin/add-users/remove-former-employee?redirectSourcePath=%252fen-us%252farticle%252fRemove-a-former-employee-from-Office-365-44d96212-4d90-4027-9aa9-a95eddb367d1&view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@dawander  Thank you for your feedback. We have another document pertaining to onedrive and can be found at https://docs.microsoft.com/en-us/office365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@dawander - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
