### ISSUE TITLE
Cannot Find Set Up --> Domain

### ISSUE THREAD

**Issue by UHustle** [MicrosoftDocs/OfficeDocs-O365ITPro#983]
I'm in the admin center but all I'm seeing is a setup link under hybrid. Hybrid is not downloading but I assume that wasn't the correct set-up link to lead me to domain? If it is, why isn't my computer allowing me to configure it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27249e0c-e601-b849-8404-ce0bb8155fce
* Version Independent ID: a308f156-998b-8ea9-5668-7a59e549cd10
* Content: [Gather the information you need to create Office 365 DNS records](https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide#feedback)
* Content Source: [Office365-Admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/get-help-with-domains/information-for-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@UHustle - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
