### ISSUE TITLE
The Post to create the restricted group limiting the ability to create Office groups does not have an "undo" procedure

### ISSUE THREAD

**Issue by bigpix2000** [MicrosoftDocs/OfficeDocs-O365ITPro#991]
On the Link: https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/create-groups/manage-creation-of-groups.md , the steps follow through setting up the group but to reverse it, there is no guidance and neither is just flipping the variables (all user abilities are lost with a flip from False to True)   It is not clear if we have to create a new security group with "everyone" in it to reverse the issue.  Also contacting support on this one and will contribute documentation if I get it before someone else picks this up. thanks.

**Comment by msbemba** [comment]
@bigpix2000 Thank you for your feedback. We have updated the reversal instructions on the document.

They are "If in the future you want to change which security group is used, you can rerun the script with the name of the new security group.

If you want to turn off the group creation restriction and again allow all users to create groups, set $GroupName to "" and $AllowGroupCreation to "True" and rerun the script."

Hope this helps!

Thanks
Sri

**Comment by bigpix2000** [comment]
It helped so much that the open support ticket I had cited the change as is if was there all the time 😉  Nice Work!

To be clear, effectively this means that setting the group name to an empty string is the key versus setting it to some type of “everyone” group.

On my Dev tenant it appears to work so now just waiting to try this in the production setting where there is a mix of Azure AD and On Prem AD.

Thanks again!

Regards,

Ralph Rivas
Chicago

**Comment by mypil** [comment]
@bigpix2000 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
