### ISSUE TITLE
[LOC] Broken table formatting

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-O365ITPro#993]
Hello, could you please check topic:
 - **name:** enable-modern-authentication.md
 - **author:** sirkkuw
 - **GH:** https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/security-and-compliance/enable-modern-authentication.md

There are 2 tables with broken formatting, it cause issues for INTL translation

PrintScreen:
![image](https://user-images.githubusercontent.com/47977325/74652542-8231f100-5186-11ea-8ef6-477018a13368.png)

**Comment by mypil** [comment]
@Sirkkuw - Thank you for submitting feedback.

I will get this issue over to the author @Sirkkuw for investigation.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue?

Thank you. 

cc: @kenwith

**Comment by Sirkkuw** [comment]
I have fixed this
